// Generated by TurboPython Compiler
#pragma once

#include <tpy/tpy.hpp>
#include "tpy.hpp"
#include "typing.hpp"

namespace tpy_user::main {

inline constexpr std::string_view __name__ = "__main__";

void test_literal();
void test_param(std::string_view msg);
void test_strview_source();

void __tpy_init();
} // namespace tpy_user::main
