// Generated by TurboPython Compiler
#include "main.hpp"

namespace tpyapp::main {

int32_t MAX{};
::tpy::BigInt MIN;

// from utils import MAX, MIN
//
// # Use imported values first
// print(MAX)  # 100
// print(MIN)  # 1
//
// # Redefine MAX with same type (explicit annotation)
// MAX: int32 = int32(42)
//
// # Redefine MIN with different type (int/BigInt)
// MIN: int = 99
//
// # Use local values
// print(MAX)  # 42
// print(MIN)  # 99
void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    ::tpyapp::utils::__tpy_init();
    std::cout << ::tpyapp::utils::MAX << "\n" << ::tpy::check_signals;
    std::cout << ::tpyapp::utils::MIN << "\n" << ::tpy::check_signals;
    MAX = 42;
    MIN = ::tpy::BigInt(99);
    std::cout << MAX << "\n" << ::tpy::check_signals;
    std::cout << MIN << "\n" << ::tpy::check_signals;
}

} // namespace tpyapp::main

int __tpy_main(int argc, char* argv[]) {
    ::tpy::init_sys_argv(argc, argv);
    ::tpyapp::main::__tpy_init();
    return 0;
}

int main(int argc, char* argv[]) {
    return ::tpy::run_main(argc, argv, &__tpy_main);
}
