// Generated by TurboPython Compiler
#pragma once

#include <tpy/tpy.hpp>
#include "tpystd/tpy/_types.hpp"
#include "tpystd/typing/_typing.hpp"

namespace tpyapp::main {

template<typename T> struct Container;

inline constexpr std::string_view __name__ = "__main__";

// def main() -> None:
void main();

// class Container[T]:
template<typename T>
struct Container {
    // count: int32
    int32_t count;
    // val: T
    T val;

    // def __init__(self) -> None:
    //     self.count = int32(0)
    Container() : count(0) {}

    // def set(self, val: T) -> None:
    //     self.val = val
    //     self.count = self.count + int32(1)
    void set(::tpy::param_val_or_ref_t<T> val) {
        this->val = ::tpy::param_to_storage<T>(val);
        this->count = (::tpy::add_check<int32_t>(this->count, 1));
    }

    // def get(self) -> T:
    //     return self.val
    ::tpy::val_or_ref_t<T> get() {
        return this->val;
    }

    // def get_count(self) -> int32:
    //     return self.count
    int32_t get_count() const {
        return this->count;
    }
    static constexpr std::string_view __tpy_class_name__ = "__main__.Container";
};

template<typename T>
inline std::ostream& operator<<(std::ostream& os, const Container<T>& obj) {
    ::tpy::print_object_default(os, "Container", obj);
    return os;
}

void __tpy_init();
} // namespace tpyapp::main
