// Generated by TurboPython Compiler
#pragma once

#include <tpy/tpy.hpp>
#include "tpystd/tpy/_types.hpp"
#include "tpystd/typing/_typing.hpp"

namespace tpyapp::main {

// class Named(Protocol):
template<typename T>
concept Named = requires(T& t) {
    { t.name() } -> std::convertible_to<std::string_view>;
};

struct Dog;
struct Cat;
struct Bird;

inline constexpr std::string_view __name__ = "__main__";

// def greet(x: Named) -> None:
template<Named T_x>
void greet(T_x& x);
// def main():
void main();

// class Dog:
struct Dog {
    // _name: str
    std::string _name;

    // def __init__(self, n: str):
    Dog() = default;
    explicit Dog(std::string_view n);

    // def name(self) -> str:
    std::string name() const;
    static constexpr std::string_view __tpy_class_name__ = "__main__.Dog";
};

inline std::ostream& operator<<(std::ostream& os, const Dog& obj) {
    ::tpy::print_object_default(os, "Dog", obj);
    return os;
}

// class Cat:
struct Cat {
    // _name: str
    std::string _name;

    // def __init__(self, n: str):
    Cat() = default;
    explicit Cat(std::string_view n);

    // def name(self) -> StrView:
    std::string_view name() const;
    static constexpr std::string_view __tpy_class_name__ = "__main__.Cat";
};

inline std::ostream& operator<<(std::ostream& os, const Cat& obj) {
    ::tpy::print_object_default(os, "Cat", obj);
    return os;
}

// class Bird:
struct Bird {
    // _name: str
    std::string _name;

    // def __init__(self, n: str):
    Bird() = default;
    explicit Bird(std::string_view n);

    // def name(self) -> String:
    ::tpy::String name() const;
    static constexpr std::string_view __tpy_class_name__ = "__main__.Bird";
};

inline std::ostream& operator<<(std::ostream& os, const Bird& obj) {
    ::tpy::print_object_default(os, "Bird", obj);
    return os;
}


// def __init__(self, n: str):
//     self._name = n
inline Dog::Dog(std::string_view n) : _name(n) {}

// def name(self) -> str:
//     return self._name
inline std::string Dog::name() const {
    return this->_name;
}

// def __init__(self, n: str):
//     self._name = n
inline Cat::Cat(std::string_view n) : _name(n) {}

// def name(self) -> StrView:
//     return self._name
inline std::string_view Cat::name() const {
    return this->_name;
}

// def __init__(self, n: str):
//     self._name = n
inline Bird::Bird(std::string_view n) : _name(n) {}

// def name(self) -> String:
//     return self._name
inline ::tpy::String Bird::name() const {
    return this->_name;
}
// def greet(x: Named) -> None:
//     print(x.name())
template<Named T_x>
void greet(T_x& x) {
    std::cout << x.name() << "\n";
}

void __tpy_init();
} // namespace tpyapp::main
