// Generated by TurboPython Compiler
#pragma once

#include <tpy/tpy.hpp>
#include "tpystd/tpy/_types.hpp"
#include "tpystd/typing/_typing.hpp"

namespace tpyapp::utils {

struct Point;

extern int32_t MAX_VALUE;
inline constexpr std::string_view __name__ = "utils";

int32_t add(int32_t a, int32_t b);

// class Point:
struct Point {
    // x: Int32
    int32_t x;
    // y: Int32
    int32_t y;

    // def __init__(self, x: Int32, y: Int32):
    Point() = default;
    explicit Point(int32_t x, int32_t y) : x(x), y(y) {}
    static constexpr std::string_view __tpy_class_name__ = "utils.Point";
};

inline std::ostream& operator<<(std::ostream& os, const Point& obj) {
    ::tpy::print_object_default(os, "Point", obj);
    return os;
}

void __tpy_init();
} // namespace tpyapp::utils
