// Generated by TurboPython Compiler
#pragma once

#include <tpy/tpy.hpp>

namespace tpy_user::main {

struct Point;
template<typename T> struct Box;

inline constexpr std::string_view __name__ = "__main__";

template<typename T>
::tpy::val_or_ref_t<T> first(std::vector<T>& items);
void test_borrow_warn();
Point& get_first_concrete(std::vector<Point>& items);
template<typename T>
::tpy::val_or_ref_t<T> get_first_generic(std::vector<T>& items);
void test_return_through_local();
void test_method_ref_semantics();
template<typename T>
::tpy::val_or_ref_t<T> get_first_from_box(Box<T>& box);
void test_method_return_through_local();
void main();

// class Point:
struct Point {
    //     x: Int32
    int32_t x;
    //     y: Int32
    int32_t y;

    //     def __init__(self, x: Int32, y: Int32) -> None:
    Point() = default;
    explicit Point(int32_t x, int32_t y) : x(x), y(y) {}
};

inline std::ostream& operator<<(std::ostream& os, const Point& obj) {
    os << "Point("
       << "x=" << obj.x
       << ", "
       << "y=" << obj.y
       << ")";
    return os;
}

// # (d) Generic method: addr_taken_roots(self._items[0]) -> "self", so
// # return_borrows_from = {-1} (borrows from self).
// class Box[T]:
template<typename T>
struct Box {
    //     _items: list[T]
    std::vector<T> _items;

    //     def __init__(self, items: list[T]) -> None:
    Box() = default;
    explicit Box(const std::vector<T>& items) : _items(items) {}

    //     def first(self) -> T:
    ::tpy::val_or_ref_t<T> first() {
        //         return self._items[0]  # borrows from self
        return ::tpy::__getitem__(this->_items, 0);
    }
};

template<typename T>
inline std::ostream& operator<<(std::ostream& os, const Box<T>& obj) {
    os << "Box("
       << "_items=" << ::tpy::ListPrinter(obj._items)
       << ")";
    return os;
}

// def first[T](items: list[T]) -> T:
template<typename T>
::tpy::val_or_ref_t<T> first(std::vector<T>& items) {
    //     return items[0]
    return ::tpy::__getitem__(items, 0);
}
// # (c) Return-through-local: generic caller -- p is val_or_ref_t<T>, param-derived.
// def get_first_generic[T](items: list[T]) -> T:
template<typename T>
::tpy::val_or_ref_t<T> get_first_generic(std::vector<T>& items) {
    //     p = first(items)
    ::tpy::val_or_ref_t<T> p = first<T>(items);
    //     return p  # tpyc: ok
    return p;
}
// # (d2) Return-through-local: generic method caller (TpyMethodCall in is_param_derived_expr).
// def get_first_from_box[T](box: Box[T]) -> T:
template<typename T>
::tpy::val_or_ref_t<T> get_first_from_box(Box<T>& box) {
    //     p = box.first()
    ::tpy::val_or_ref_t<T> p = box.first();
    //     return p  # tpyc: ok
    return p;
}

void __tpy_init();
} // namespace tpy_user::main
