// Generated by TurboPython Compiler
#include "main.hpp"

// 6: def test_list_subscript_oob() -> None:
void test_list_subscript_oob() {
  // 7:     nums: list[Int32] = [1, 2, 3]
  std::vector<int32_t> nums = {1, 2, 3};
  // 10:     x: Int32 = nums[10]
  int32_t x = tpy::get_item(nums, 10);
  // 11:     print(x)
  std::cout << x << "\n";
}

void __tpy_init_main() {
  // 13: test_list_subscript_oob()
  test_list_subscript_oob();
}

int main() {
  __tpy_init_main();
  return 0;
}
