// Generated by TurboPython Compiler
#include "main.hpp"
#include "tpystd/io_inl.hpp"
#include "main_inl.hpp"
#include "tpystd/os_inl.hpp"

namespace tpyapp::main {

::tpy::ordered_map<std::string, int32_t>* TABLE{};

// # free function: a multi-line literal and an inner comment keep their shape
// def shaped(a: int32, b: int32) -> int32:
//     cfg = {
//         "x": a,
//         "y": b,
//     }
//     # inner comment stays with its statement
//     return cfg["x"] + cfg["y"]
int32_t shaped(int32_t a, int32_t b) {
    ::tpy::ordered_map<std::string, int32_t> cfg = ::tpy::ordered_map<std::string, int32_t>({{"x", a}, {"y", b}});
    return (::tpy::add_check<int32_t>(::tpy::__getitem__(cfg, "x"), ::tpy::__getitem__(cfg, "y")));
}

// # free function: a triple-quoted string keeps its inner lines verbatim
// def quoted() -> str:
//     text = """first
//     second
//         third"""
//     return text
std::string quoted() {
    std::string_view text = "first\n    second\n        third";
    return std::string(text);
}


// def upto(n: int32) -> Iterator[int32]:
__gen_upto upto(int32_t n) {
    return __gen_upto(n);
}


// def pair(n: int32) -> Iterator[int32]:
__gen_pair pair(int32_t n) {
    return __gen_pair(n);
}

// # async: the block sits above the frame's poll implementation
// async def doubled(n: int32) -> int32:
//     await asyncio.sleep(0)             # -> S_RESUME_0
//     return n * 2
::tpystd::tpy::Poll<int32_t> __coro_doubled::__poll__(::tpystd::coro::Waker waker) {
    while (true) switch (__state) {
    case S_INITIAL: {  // entry
        __state = S_DONE;  // until a yield sets where to resume
        __sub_0.emplace(std::move(::tpystd::asyncio::sleep(static_cast<double>(0))));
        __state = S_RESUME_0;
        continue;
    }
    case S_RESUME_0: {  // after: await asyncio.sleep(0)
        auto __r0 = ::tpy::poll_with_cancel(__sub_0, __cancel_pending, waker);
        if (__r0.is_pending()) return ::tpystd::tpy::Poll<int32_t>::pending();
        (void)std::move(__r0).value();
        __sub_0.reset();
        __state = S_DONE;
        int32_t __tpy_async_ret = (::tpy::mul_check<int32_t>(n, 2));
        return ::tpystd::tpy::Poll<int32_t>::ready(std::move(__tpy_async_ret));
    }
    case S_DONE: ::tpy::tpy_panic("poll after Ready");
    }
    __builtin_unreachable();
}


// async def doubled(n: int32) -> int32:
__coro_doubled doubled(int32_t n) {
    return __coro_doubled(n);
}

// # commented definition: the comment rides above the def line inside the block
// def helper(f: int32) -> int32:
//     return f + 1
int32_t helper(int32_t f) {
    return (::tpy::add_check<int32_t>(f, 1));
}

// def main() -> None:
//     print("shaped", shaped(1, 2))
//     print("quoted", quoted())
//     c = Counter(5)
//     print("method", c.bump(3))
//     print("simple-gen", list(upto(3)))
//     print("resumable-gen", list(pair(1)))
//     print("async", asyncio.run(doubled(4)))
//     print("helper", helper(1))
//     print("decorated", Reader().peek())
void main() {
    std::cout << "shaped" << " " << ::tpyapp::main::shaped(1, 2) << "\n" << ::tpy::check_signals;
    std::cout << "quoted" << " " << ::tpyapp::main::quoted() << "\n" << ::tpy::check_signals;
    Counter c = Counter(5);
    std::cout << "method" << " " << c.bump(3) << "\n" << ::tpy::check_signals;
    std::cout << "simple-gen" << " " << ::tpy::ListPrinter(::tpy::construct<std::vector<int32_t>>(::tpyapp::main::upto(3))) << "\n" << ::tpy::check_signals;
    std::cout << "resumable-gen" << " " << ::tpy::ListPrinter(::tpy::construct<std::vector<int32_t>>(::tpyapp::main::pair(1))) << "\n" << ::tpy::check_signals;
    std::cout << "async" << " " << ::tpystd::asyncio::run<int32_t>(::tpy::make_adapter<::tpystd::coro::Cancellable<int32_t>>(::tpyapp::main::doubled(4))) << "\n" << ::tpy::check_signals;
    std::cout << "helper" << " " << ::tpyapp::main::helper(1) << "\n" << ::tpy::check_signals;
    std::cout << "decorated" << " " << Reader().peek() << "\n" << ::tpy::check_signals;
}

// # Source-comment placement in generated C++: a declaration echoes its signature,
// # an implementation its whole Python definition above the C++, a resumable frame
// # with `# -> S_RESUME_n` tags on its suspending lines (the C++ is the assertion).
// import asyncio
//
// # module-level multi-line statement: the module body is the block above __tpy_init
// TABLE = {
//     "a": 1,
//     "b": 2,
// }
//
// print("module", (TABLE["a"] + TABLE["b"]) * SCALE)
// main()
void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    ::tpystd::asyncio::__tpy_init();
    static ::tpy::ordered_map<std::string, int32_t> __global_slot_1 = ::tpy::ordered_map<std::string, int32_t>({{"a", 1}, {"b", 2}});
    TABLE = &__global_slot_1;
    std::cout << "module" << " " << (::tpy::mul_check<int32_t>((::tpy::add_check<int32_t>(::tpy::__getitem__((*TABLE), "a"), ::tpy::__getitem__((*TABLE), "b"))), SCALE)) << "\n" << ::tpy::check_signals;
    ::tpyapp::main::main();
}

} // namespace tpyapp::main

int __tpy_main(int argc, char* argv[]) {
    ::tpy::init_sys_argv(argc, argv);
    ::tpyapp::main::__tpy_init();
    return 0;
}

int main(int argc, char* argv[]) {
    ::tpy::process_startup();
    return __tpy_main(argc, argv);
}
