// Generated by TurboPython Compiler
#pragma once

#include <tpy/tpy.hpp>
#include "tpystd/tpy/_types.hpp"
#include "tpystd/typing/_typing.hpp"

namespace tpyapp::main {

struct Bag;

inline constexpr std::string_view __name__ = "__main__";

// def main() -> None:
void main();

// class Bag:
struct Bag {


    // def __getattr__(self, name: str) -> str:
    std::string __getattr__(std::string_view name) const;
    static constexpr std::string_view __tpy_class_name__ = "__main__.Bag";
};

inline std::ostream& operator<<(std::ostream& os, const Bag& obj) {
    ::tpy::print_object_default(os, "Bag", obj);
    return os;
}


// def __getattr__(self, name: str) -> str:
//     if name == "host":
//         return "example.com"
//     raise AttributeError(name)
inline std::string Bag::__getattr__(std::string_view name) const {
    if ((name == "host")) {
        return "example.com";
    }
    throw ::tpy::AttributeError(name);
}
void __tpy_init();
} // namespace tpyapp::main
