// Generated by TurboPython Compiler
#include "main.hpp"

namespace tpyapp::main {

std::vector<int32_t>* xs{};

// # Own[container] param as the for-head iterable
// def drain(items: Own[list[int32]]) -> Iterator[int32]:  # tpyc: warning(/never consumed/)
//     for x in items:
//         yield x + len(items)                                                               # -> S_RESUME_0
std::expected<int32_t, ::tpy::StopIteration> __gen_drain::__next__() {
    while (true) switch (__state) {
    case S_INITIAL: {  // entry
        ::tpy::resumable_iter_init(__for_itr_0, items);
        __state = S_JOIN_0;
        continue;
    }
    case S_RESUME_0: {  // after: yield x + len(items)
        __state = S_JOIN_0;
        continue;
    }
    case S_JOIN_0: {
        __for_r_0.emplace(::tpy::resumable_iter_next(__for_itr_0, items));
        if (!(*__for_r_0).has_value()) {
            __state = S_DONE;
            return ::tpy::make_unexpected(::tpy::StopIteration{});
        }
        x = ::tpy::unwrap_ref(*(*__for_r_0));
        __state = S_RESUME_0;
        return (::tpy::add_check<int32_t>(x, ::tpy::__len__(items)));
    }
    case S_DONE: return ::tpy::make_unexpected(::tpy::StopIteration{});
    }
    __builtin_unreachable();
}


// def drain(items: Own[list[int32]]) -> Iterator[int32]:  # tpyc: warning(/never consumed/)
__gen_drain drain(std::vector<int32_t> items) {
    return __gen_drain(std::move(items));
}

// # module-global container as the iterable; an element of the global is
// # overwritten between pulls, so the frame must iterate the global itself,
// # not a copy
// def over_global() -> Iterator[int32]:  # tpyc: ok
//     for v in xs:
//         yield v                                    # -> S_RESUME_0
std::expected<int32_t, ::tpy::StopIteration> __gen_over_global::__next__() {
    while (true) switch (__state) {
    case S_INITIAL: {  // entry
        __for_it_0.emplace(((*xs)).begin());
        __for_end_0.emplace(((*xs)).end());
        __state = S_JOIN_0;
        continue;
    }
    case S_RESUME_0: {  // after: yield v
        __state = S_JOIN_0;
        continue;
    }
    case S_JOIN_0: {
        if ((*__for_it_0) == (*__for_end_0)) {
            __state = S_DONE;
            return ::tpy::make_unexpected(::tpy::StopIteration{});
        }
        v = *((*__for_it_0))++;
        __state = S_RESUME_0;
        return v;
    }
    case S_DONE: return ::tpy::make_unexpected(::tpy::StopIteration{});
    }
    __builtin_unreachable();
}


// def over_global() -> Iterator[int32]:  # tpyc: ok
__gen_over_global over_global() {
    return __gen_over_global();
}

// # generic generator method at a value-typed instantiation in a while head
// def value_instantiation_in_head() -> int32:
//     labels = Labels[int32](1)
//     n = 0
//     while len(list(labels.gen_it(2))) > 0 and n < 2:  # tpyc: ok
//         n += 1
//     return n
int32_t value_instantiation_in_head() {
    Labels<int32_t> labels = Labels<int32_t>(1);
    int32_t n = 0;
    while (((::tpy::__len__(::tpy::construct<std::vector<int32_t>>(labels.gen_it(2))) > 0) && (n < 2))) {
        n = ::tpy::add_check<int32_t>(n, 1);
    }
    return n;
}

// def main() -> None:
//     for u in drain([1, 2, 3]):
//         print("own_container", u)
//     total = 0
//     for v in over_global():
//         total = total + v
//         if v == 1:
//             xs[2] = 30
//     print("over_global", total, xs[2])
//     print("value_instantiation", value_instantiation_in_head())
void main() {
    {
        auto __src_0 = drain({1, 2, 3});
        auto&& __itr_0 = ::tpy::__iter__(__src_0);
        for (;;) {
            auto __r_1 = __itr_0.__next__();
            if (!__r_1.has_value()) break;
            int32_t u = ::tpy::unwrap_ref(*__r_1);
        std::cout << "own_container" << " " << u << "\n";
        }
    }
    int32_t total = 0;
    {
        auto __src_2 = over_global();
        auto&& __itr_2 = ::tpy::__iter__(__src_2);
        for (;;) {
            auto __r_3 = __itr_2.__next__();
            if (!__r_3.has_value()) break;
            int32_t v = ::tpy::unwrap_ref(*__r_3);
        total = (::tpy::add_check<int32_t>(total, v));
        if ((v == 1)) {
            ::tpy::__setitem__((*xs), 2, 30);
        }
        }
    }
    std::cout << "over_global" << " " << total << " " << ::tpy::__getitem__((*xs), 2) << "\n";
    std::cout << "value_instantiation" << " " << value_instantiation_in_head() << "\n";
}

// xs = [1, 2, 3]
//
// main()
void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    static std::vector<int32_t> __global_slot_1 = {1, 2, 3};
    xs = &__global_slot_1;
    main();
}

} // namespace tpyapp::main

int __tpy_main(int argc, char* argv[]) {
    ::tpy::init_sys_argv(argc, argv);
    ::tpyapp::main::__tpy_init();
    return 0;
}

int main(int argc, char* argv[]) {
    ::tpy::process_startup();
    return __tpy_main(argc, argv);
}
