// Generated by TurboPython Compiler
#include "main.hpp"
#include "tpystd/io_inl.hpp"
#include "tpystd/os_inl.hpp"

namespace tpyapp::main {


// def main() -> None:
//     try:
//         asyncio.get_running_loop()
//         print("no error")
//     except RuntimeError:
//         print("RuntimeError")
void main() {
    {
        try {
            ::tpystd::asyncio::get_running_loop();
            std::cout << "no error" << "\n" << ::tpy::check_signals;
        } catch (const ::tpy::RuntimeError&) {
            std::cout << "RuntimeError" << "\n" << ::tpy::check_signals;
        }
    }
}

// # Regression guard: get_running_loop() called with no loop running raises
// # RuntimeError (CPython parity). Exercised here from a plain sync context.
// import asyncio
//
// main()
void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    ::tpystd::asyncio::__tpy_init();
    ::tpyapp::main::main();
}

} // namespace tpyapp::main

int __tpy_main(int argc, char* argv[]) {
    ::tpy::init_sys_argv(argc, argv);
    ::tpyapp::main::__tpy_init();
    return 0;
}

int main(int argc, char* argv[]) {
    return ::tpy::run_main(argc, argv, &__tpy_main);
}
