// Generated by TurboPython Compiler
#include "main.hpp"

namespace tpyapp::main {


// def make_pair() -> Own[tuple[int32, int32]]:
//     return (int32(10), int32(20))
std::tuple<int32_t, int32_t> make_pair() {
    return std::tuple<int32_t, int32_t>{10, 20};
}

// def main() -> None:
//     pair = make_pair()
//     print(pair[0])
//     print(pair[1])
void main() {
    std::tuple<int32_t, int32_t> pair = make_pair();
    std::cout << std::get<0>(pair) << "\n";
    std::cout << std::get<1>(pair) << "\n";
}

// main()
void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    main();
}

} // namespace tpyapp::main

int __tpy_main(int argc, char* argv[]) {
    ::tpy::init_sys_argv(argc, argv);
    ::tpyapp::main::__tpy_init();
    return 0;
}

int main(int argc, char* argv[]) {
    ::tpy::process_startup();
    return __tpy_main(argc, argv);
}
