// Generated by TurboPython Compiler
#pragma once

#include <tpy/tpy.hpp>
#include "tpystd/tpy/_types.hpp"
#include "tpystd/typing/_typing.hpp"
#include "outer.hpp"
#include "outer/inner.hpp"
#include "outer/inner/mod.hpp"

namespace tpyapp::main {

using ::tpyapp::outer::inner::mod::func;

inline constexpr std::string_view __name__ = "__main__";

int32_t main();

void __tpy_init();
} // namespace tpyapp::main
