// Generated by TurboPython Compiler
#pragma once

#include <tpy/tpy.hpp>
#include "tpystd/tpy/_types.hpp"
#include "tpystd/typing/_typing.hpp"

namespace tpyapp::main {

struct Box;

inline constexpr std::string_view __name__ = "__main__";

std::tuple<Box, Box*> make_mixed(Box& b);
std::tuple<Box, Box*> make_none();
int32_t write_through(Box& b);
int32_t read_direct(Box& b);
int32_t none_element();
void main();

// class Box:
struct Box {
    // val: Int32
    int32_t val;

    // def __init__(self, val: Int32) -> None:
    Box() = default;
    explicit Box(int32_t val);
    static constexpr std::string_view __tpy_class_name__ = "__main__.Box";
};

inline std::ostream& operator<<(std::ostream& os, const Box& obj) {
    ::tpy::print_object_default(os, "Box", obj);
    return os;
}


// def __init__(self, val: Int32) -> None:
inline Box::Box(int32_t val) : val(val) {}
void __tpy_init();
} // namespace tpyapp::main
