// Generated by TurboPython Compiler
#pragma once

#include <tpy/tpy.hpp>
#include "tpystd/builtins.hpp"
#include "tpystd/tpy.hpp"
#include "tpystd/typing.hpp"

namespace tpyapp::main {

extern char a;
extern char b;
extern std::optional<char> none_char;
extern std::optional<char> some_a;
inline constexpr std::string_view __name__ = "__main__";

bool eq_left(std::optional<char> o, char c);
bool eq_right(char c, std::optional<char> o);
bool ne_left(std::optional<char> o, char c);
bool ne_right(char c, std::optional<char> o);

void __tpy_init();
} // namespace tpyapp::main
