// Generated by TurboPython Compiler
#include "main.hpp"

namespace tpyapp::main {


// def add_one(n: int) -> int:
::tpy::BigInt add_one(const ::tpy::BigInt& n) {
    // return n + 1
    return ((n) + (::tpy::BigInt(1)));
}

// def main() -> None:
void main() {
    // a: Any = 5
    ::tpy::Any a = ::tpy::make_any(::tpy::BigInt(5));
    // print(add_one(a))
    std::cout << add_one(::tpy::any_cast_or_panic<::tpy::BigInt>(a)) << "\n";
}

void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    // main()
    main();
}

} // namespace tpyapp::main

int __tpy_main(int argc, char* argv[]) {
    ::tpy::init_sys_argv(argc, argv);
    tpyapp::main::__tpy_init();
    return 0;
}

int main(int argc, char* argv[]) {
    std::set_terminate(&::tpy::tpy_terminate_handler);
    return __tpy_main(argc, argv);
}
