// Generated by TurboPython Compiler
#include "main.hpp"

namespace tpyapp::main {



// def main() -> None:
//     s: Ptr[S] = get_s()
//     # Property access through Ptr[T] -- must emit `.config()`, not `.Config()`.
//     print(s.Config.v)
void main() {
    ::x::S* s = get_s();
    std::cout << ::tpy::deref_check(s).config().v << "\n" << ::tpy::check_signals;
}

// from tpy.extern import native, cpp_template
//
// main()
void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    ::tpyapp::main::main();
}

} // namespace tpyapp::main

int __tpy_main(int argc, char* argv[]) {
    ::tpy::init_sys_argv(argc, argv);
    ::tpyapp::main::__tpy_init();
    return 0;
}

int main(int argc, char* argv[]) {
    return ::tpy::run_main(argc, argv, &__tpy_main);
}
