// Generated by TurboPython Compiler
#include "main.hpp"

namespace tpyapp::main {

int32_t x{};
uint8_t y{};

// x: int32 = int32(300)
// y: uint8 = uint8(x)
// print(y)
void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    x = 300;
    y = ::tpy::int_cast_check<uint8_t>(x);
    std::cout << static_cast<int>(y) << "\n" << ::tpy::check_signals;
}

} // namespace tpyapp::main

int __tpy_main(int argc, char* argv[]) {
    ::tpy::init_sys_argv(argc, argv);
    ::tpyapp::main::__tpy_init();
    return 0;
}

int main(int argc, char* argv[]) {
    ::tpy::process_startup();
    return __tpy_main(argc, argv);
}
