// Generated by TurboPython Compiler
#pragma once

#include <tpy/tpy.hpp>
#include "tpystd/tpy/_types.hpp"
#include "tpystd/typing/_typing.hpp"

namespace tpyapp::main {

// class Mutable(Protocol):
template<typename T>
concept Mutable = requires(T& t) {
    { t.mutate() } -> std::convertible_to<void>;
};

struct Point;

inline constexpr std::string_view __name__ = "__main__";

// def first[T](items: list[T]) -> T:
template<typename T>
::tpy::val_or_ref_t<T> first(std::vector<T>& items);
// def process[T: Mutable](items: list[T]) -> None:
template<Mutable T>
void process(std::vector<T>& items);
// def test() -> None:
void test();

// class Point:
struct Point {
    // x: int
    ::tpy::BigInt x;

    // def __init__(self, x: int) -> None:
    Point() = default;
    explicit Point(const ::tpy::BigInt& x);

    // def mutate(self) -> None:
    void mutate();
    static constexpr std::string_view __tpy_class_name__ = "__main__.Point";
};

inline std::ostream& operator<<(std::ostream& os, const Point& obj) {
    ::tpy::print_object_default(os, "Point", obj);
    return os;
}


// def __init__(self, x: int) -> None:
//     self.x = x
inline Point::Point(const ::tpy::BigInt& x) : x(x) {}

// def mutate(self) -> None:
//     self.x += 10
inline void Point::mutate() {
    this->x = (this->x) + (::tpy::BigInt(10));
}
// def first[T](items: list[T]) -> T:
//     return items[0]
template<typename T>
::tpy::val_or_ref_t<T> first(std::vector<T>& items) {
    return ::tpy::__getitem__(items, 0);
}
// def process[T: Mutable](items: list[T]) -> None:
//     item = first(items)  # tpyc: type(T)  -- val_or_ref_t<T>: Point& for records
//     item.mutate()        # mutation through the reference
template<Mutable T>
void process(std::vector<T>& items) {
    ::tpy::val_or_ref_t<T> item = ::tpyapp::main::first<T>(items);
    item.mutate();
}

void __tpy_init();
} // namespace tpyapp::main
