// Generated by TurboPython Compiler
#include "main.hpp"

namespace tpyapp::main {


// def main() -> None:
void main() {
    // s: set[Any] = set()
    ::tpy::ordered_set<::tpy::Any> s = ::tpy::ordered_set<::tpy::Any>();
    // a: Any = 1
    ::tpy::Any a = ::tpy::make_any(::tpy::BigInt(1));
    // b: Any = "hello"
    ::tpy::Any b = ::tpy::make_any(std::string("hello"));
    // s.add(a)
    s.insert(a);
    // s.add(b)
    s.insert(b);
    // print(len(s))
    std::cout << ::tpy::__len__(s) << "\n";
}

void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    // main()
    main();
}

} // namespace tpyapp::main

int __tpy_main(int argc, char* argv[]) {
    ::tpy::init_sys_argv(argc, argv);
    tpyapp::main::__tpy_init();
    return 0;
}

int main(int argc, char* argv[]) {
    std::set_terminate(&::tpy::tpy_terminate_handler);
    return __tpy_main(argc, argv);
}
