// Generated by TurboPython Compiler
#pragma once

#include <tpy/tpy.hpp>
#include "tpystd/tpy/_types.hpp"
#include "tpystd/typing/_typing.hpp"

namespace tpyapp::main {

inline constexpr std::string_view __name__ = "__main__";

std::string owned(std::string_view s);
std::vector<uint8_t> owned_bytes(std::span<const uint8_t> b);
void main();

void __tpy_init();
} // namespace tpyapp::main
