// Generated by TurboPython Compiler
#include "main.hpp"

namespace tpyapp::main {


// async def make(n: int32) -> Own[Payload]:
::tpystd::tpy::Poll<Payload> __coro_make::__poll__(::tpystd::coro::Waker waker) {
    (void)waker;
    switch (__state) {
    case S_INITIAL: {
        // return Payload(n)
        __state = S_DONE;
        Payload __tpy_async_ret = Payload(n);
        return ::tpystd::tpy::Poll<Payload>::ready(std::move(__tpy_async_ret));
    }
    case S_DONE: ::tpy::tpy_panic("poll after Ready");
    }
    __builtin_unreachable();
}


// async def make(n: int32) -> Own[Payload]:
__coro_make make(int32_t n) {
    return __coro_make(n);
}

// def take(p: Own[Payload]) -> int32:
int32_t take(Payload&& p) {
    // return p.n
    return p.n;
}

// async def into_container() -> int32:
::tpystd::tpy::Poll<int32_t> __coro_into_container::__poll__(::tpystd::coro::Waker waker) {
    while (true) switch (__state) {
    case S_INITIAL: {
        // out: list[Payload] = []
        out.emplace(std::vector<Payload>{});
        // p = await make(1)
        __sub_0.emplace(1);
        __state = S_RESUME_0;
        continue;
    }
    case S_RESUME_0: {
        auto __r0 = ::tpy::poll_with_cancel(__sub_0, __cancel_pending, waker);
        if (__r0.is_pending()) return ::tpystd::tpy::Poll<int32_t>::pending();
        p.emplace(std::move(__r0).value());
        __sub_0.reset();
        // out.append(p)                 # last use -> moves into the element slot
        (*out).push_back(std::move((*p)));
        // return out[0].n
        __state = S_DONE;
        int32_t __tpy_async_ret = ::tpy::__getitem__((*out), 0).n;
        return ::tpystd::tpy::Poll<int32_t>::ready(std::move(__tpy_async_ret));
    }
    case S_DONE: ::tpy::tpy_panic("poll after Ready");
    }
    __builtin_unreachable();
}


// async def into_container() -> int32:
__coro_into_container into_container() {
    return __coro_into_container();
}

// async def into_call_arg() -> int32:
::tpystd::tpy::Poll<int32_t> __coro_into_call_arg::__poll__(::tpystd::coro::Waker waker) {
    while (true) switch (__state) {
    case S_INITIAL: {
        // p = await make(2)
        __sub_0.emplace(2);
        __state = S_RESUME_0;
        continue;
    }
    case S_RESUME_0: {
        auto __r0 = ::tpy::poll_with_cancel(__sub_0, __cancel_pending, waker);
        if (__r0.is_pending()) return ::tpystd::tpy::Poll<int32_t>::pending();
        p.emplace(std::move(__r0).value());
        __sub_0.reset();
        // return take(p)                # last use -> moves into the Own param
        __state = S_DONE;
        int32_t __tpy_async_ret = take(std::move((*p)));
        return ::tpystd::tpy::Poll<int32_t>::ready(std::move(__tpy_async_ret));
    }
    case S_DONE: ::tpy::tpy_panic("poll after Ready");
    }
    __builtin_unreachable();
}


// async def into_call_arg() -> int32:
__coro_into_call_arg into_call_arg() {
    return __coro_into_call_arg();
}

// async def into_field() -> int32:
::tpystd::tpy::Poll<int32_t> __coro_into_field::__poll__(::tpystd::coro::Waker waker) {
    while (true) switch (__state) {
    case S_INITIAL: {
        // p = await make(3)
        __sub_0.emplace(3);
        __state = S_RESUME_0;
        continue;
    }
    case S_RESUME_0: {
        auto __r0 = ::tpy::poll_with_cancel(__sub_0, __cancel_pending, waker);
        if (__r0.is_pending()) return ::tpystd::tpy::Poll<int32_t>::pending();
        p.emplace(std::move(__r0).value());
        __sub_0.reset();
        // h = Holder(p)                 # last use -> moves into the field
        h.emplace(Holder(std::move((*p))));
        // return h.item.n
        __state = S_DONE;
        int32_t __tpy_async_ret = (*h).item.n;
        return ::tpystd::tpy::Poll<int32_t>::ready(std::move(__tpy_async_ret));
    }
    case S_DONE: ::tpy::tpy_panic("poll after Ready");
    }
    __builtin_unreachable();
}


// async def into_field() -> int32:
__coro_into_field into_field() {
    return __coro_into_field();
}

// async def in_a_loop() -> int32:
::tpystd::tpy::Poll<int32_t> __coro_in_a_loop::__poll__(::tpystd::coro::Waker waker) {
    while (true) switch (__state) {
    case S_INITIAL: {
        // out: list[Payload] = []
        out.emplace(std::vector<Payload>{});
        // i = 0
        i = 0;
        __state = S_JOIN_0;
        continue;
    }
    case S_RESUME_0: {
        auto __r0 = ::tpy::poll_with_cancel(__sub_0, __cancel_pending, waker);
        if (__r0.is_pending()) return ::tpystd::tpy::Poll<int32_t>::pending();
        p.emplace(std::move(__r0).value());
        __sub_0.reset();
        // out.append(p)
        (*out).push_back(std::move((*p)));
        // i += 1
        i = ::tpy::add_check<int32_t>(i, 1);
        __state = S_JOIN_0;
        continue;
    }
    case S_JOIN_0: {
        if ((i < 3)) {
            // p = await make(i)
            __sub_0.emplace(i);
            __state = S_RESUME_0;
            continue;
        } else {
            // return out[0].n + out[1].n + out[2].n
            __state = S_DONE;
            int32_t __tpy_async_ret = (::tpy::add_check<int32_t>((::tpy::add_check<int32_t>(::tpy::__getitem__((*out), 0).n, ::tpy::__getitem__((*out), 1).n)), ::tpy::__getitem__((*out), 2).n));
            return ::tpystd::tpy::Poll<int32_t>::ready(std::move(__tpy_async_ret));
        }
    }
    case S_DONE: ::tpy::tpy_panic("poll after Ready");
    }
    __builtin_unreachable();
}


// async def in_a_loop() -> int32:
__coro_in_a_loop in_a_loop() {
    return __coro_in_a_loop();
}

// async def from_return() -> Own[Payload]:
::tpystd::tpy::Poll<Payload> __coro_from_return::__poll__(::tpystd::coro::Waker waker) {
    while (true) switch (__state) {
    case S_INITIAL: {
        // p = await make(4)
        __sub_0.emplace(4);
        __state = S_RESUME_0;
        continue;
    }
    case S_RESUME_0: {
        auto __r0 = ::tpy::poll_with_cancel(__sub_0, __cancel_pending, waker);
        if (__r0.is_pending()) return ::tpystd::tpy::Poll<Payload>::pending();
        p.emplace(std::move(__r0).value());
        __sub_0.reset();
        // return p                      # last use -> moves into the return slot
        __state = S_DONE;
        Payload __tpy_async_ret = std::move((*p));
        return ::tpystd::tpy::Poll<Payload>::ready(std::move(__tpy_async_ret));
    }
    case S_DONE: ::tpy::tpy_panic("poll after Ready");
    }
    __builtin_unreachable();
}


// async def from_return() -> Own[Payload]:
__coro_from_return from_return() {
    return __coro_from_return();
}

// async def main_coro() -> None:
::tpystd::tpy::Poll<::std::monostate> __coro_main_coro::__poll__(::tpystd::coro::Waker waker) {
    while (true) switch (__state) {
    case S_INITIAL: {
        // print(await into_container())
        __sub_0.emplace();
        __state = S_RESUME_0;
        continue;
    }
    case S_RESUME_0: {
        auto __r0 = ::tpy::poll_with_cancel(__sub_0, __cancel_pending, waker);
        if (__r0.is_pending()) return ::tpystd::tpy::Poll<::std::monostate>::pending();
        __await_lift_0 = std::move(__r0).value();
        __sub_0.reset();
        // print(await into_container())
        std::cout << __await_lift_0 << "\n";
        // print(await into_call_arg())
        __sub_1.emplace();
        __state = S_RESUME_1;
        continue;
    }
    case S_RESUME_1: {
        auto __r1 = ::tpy::poll_with_cancel(__sub_1, __cancel_pending, waker);
        if (__r1.is_pending()) return ::tpystd::tpy::Poll<::std::monostate>::pending();
        __await_lift_1 = std::move(__r1).value();
        __sub_1.reset();
        // print(await into_call_arg())
        std::cout << __await_lift_1 << "\n";
        // print(await into_field())
        __sub_2.emplace();
        __state = S_RESUME_2;
        continue;
    }
    case S_RESUME_2: {
        auto __r2 = ::tpy::poll_with_cancel(__sub_2, __cancel_pending, waker);
        if (__r2.is_pending()) return ::tpystd::tpy::Poll<::std::monostate>::pending();
        __await_lift_2 = std::move(__r2).value();
        __sub_2.reset();
        // print(await into_field())
        std::cout << __await_lift_2 << "\n";
        // print(await in_a_loop())
        __sub_3.emplace();
        __state = S_RESUME_3;
        continue;
    }
    case S_RESUME_3: {
        auto __r3 = ::tpy::poll_with_cancel(__sub_3, __cancel_pending, waker);
        if (__r3.is_pending()) return ::tpystd::tpy::Poll<::std::monostate>::pending();
        __await_lift_3 = std::move(__r3).value();
        __sub_3.reset();
        // print(await in_a_loop())
        std::cout << __await_lift_3 << "\n";
        // r = await from_return()
        __sub_4.emplace();
        __state = S_RESUME_4;
        continue;
    }
    case S_RESUME_4: {
        auto __r4 = ::tpy::poll_with_cancel(__sub_4, __cancel_pending, waker);
        if (__r4.is_pending()) return ::tpystd::tpy::Poll<::std::monostate>::pending();
        r.emplace(std::move(__r4).value());
        __sub_4.reset();
        // print(r.n)
        std::cout << (*r).n << "\n";
        __state = S_DONE;
        return ::tpystd::tpy::Poll<::std::monostate>::ready(::std::monostate{});
    }
    case S_DONE: ::tpy::tpy_panic("poll after Ready");
    }
    __builtin_unreachable();
}


// async def main_coro() -> None:
__coro_main_coro main_coro() {
    return __coro_main_coro();
}

// def main() -> None:
void main() {
    // asyncio.run(main_coro())
    ::tpystd::asyncio::run<std::monostate>(::tpy::make_adapter<::tpystd::coro::Cancellable<std::monostate>>(main_coro()));
}

void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    // # An await-bound local is auto-moved at its last use, like any other owned
    // # local. @nocopy forces the issue: a copy at any of these sinks is a C++
    // # build error, so a passing run proves the move happened.
    // import asyncio
    ::tpystd::asyncio::__tpy_init();
    // main()
    main();
}

} // namespace tpyapp::main

int __tpy_main(int argc, char* argv[]) {
    ::tpy::init_sys_argv(argc, argv);
    ::tpyapp::main::__tpy_init();
    return 0;
}

int main(int argc, char* argv[]) {
    ::tpy::process_startup();
    return __tpy_main(argc, argv);
}
