// Generated by TurboPython Compiler
#include "outer.hpp"

namespace tpyapp::outer {

// __all__ = ["shared_helper"]
std::vector<std::string>* __all__{};

void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    // # outer re-exports a name imported from inner. A `__all__` entry that
    // # names a re-exported import must not be flagged as phantom, even
    // # though it is not locally defined in this module.
    // from inner import shared_helper
    ::tpyapp::inner::__tpy_init();
    // __all__ = ["shared_helper"]
    static std::vector<std::string> __global_slot_1 = {"shared_helper"};
    __all__ = &__global_slot_1;
}

} // namespace tpyapp::outer
