// Generated by TurboPython Compiler
#include "outer.hpp"

namespace tpyapp::outer {


void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    // # outer re-exports a name imported from inner. A `__all__` entry that
    // # names a re-exported import must not be flagged as phantom, even
    // # though it is not locally defined in this module.
    // from inner import shared_helper
    ::tpyapp::inner::__tpy_init();
}

} // namespace tpyapp::outer
