// Generated by TurboPython Compiler
#include "main.hpp"

namespace tpyapp::main {


// def main() -> None:
void main() {
    // s = Sub(Key(5), 7)
    Sub s = Sub(::tpyapp::other::Key(5), 7);
    // print(s._k.x)
    std::cout << s._k.x << "\n";
    // print(s._v)
    std::cout << s._v << "\n";
}

void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    // from other import Key
    ::tpyapp::other::__tpy_init();
    // main()
    main();
}

} // namespace tpyapp::main

int __tpy_main(int argc, char* argv[]) {
    ::tpy::init_sys_argv(argc, argv);
    ::tpyapp::main::__tpy_init();
    return 0;
}

int main(int argc, char* argv[]) {
    ::tpy::process_startup();
    return __tpy_main(argc, argv);
}
