// Generated by TurboPython Compiler
#pragma once

#include <tpy/tpy.hpp>
#include "tpystd/tpy/_types.hpp"
#include "tpystd/typing/_typing.hpp"

namespace tpyapp::main {

inline constexpr std::string_view __name__ = "__main__";

::tpy::BytesView from_param(::tpy::BytesView b);
::tpy::BytesView from_param_sliced(::tpy::BytesView b);
::tpy::BytesView from_literal();
void main();

void __tpy_init();
} // namespace tpyapp::main
