// Generated by TurboPython Compiler
#pragma once

#include <tpy/tpy.hpp>
#include "tpystd/tpy/_types.hpp"
#include "tpystd/typing/_typing.hpp"

namespace tpyapp::main {

struct Base;
struct Child;

inline constexpr std::string_view __name__ = "__main__";

void main();

// # Tests __del__ with inheritance: parent destructor is called automatically after child
// # In C++ destructor order is child-first, then parent (opposite of __init__)
// class Base:
struct Base {
    bool __tpy_owned_ = true;

    Base() = default;
    Base(const Base&) = delete;
    Base& operator=(const Base&) = delete;
    Base(Base&& other) noexcept {
        other.__tpy_owned_ = false;
    }
    Base& operator=(Base&& other) noexcept {
        if (this != &other) {
            this->~Base();
            new (this) Base(std::move(other));
        }
        return *this;
    }
    // def __del__(self):

    ~Base() {
        if (!this->__tpy_owned_) return;
        // print("Base destroyed")
        std::cout << "Base destroyed" << "\n";
    }
};

inline std::ostream& operator<<(std::ostream& os, const Base& obj) {
    ::tpy::print_object_default(os, "Base", obj);
    return os;
}

// class Child(Base):
struct Child : Base {
    // label: str
    std::string label;

    // def __init__(self, label: str):
    Child() = default;
    explicit Child(std::string_view label) : label(label) {}
    Child(const Child&) = delete;
    Child& operator=(const Child&) = delete;
    Child(Child&& other) noexcept : Base(std::move(other)), label(std::move(other.label)) {
        other.__tpy_owned_ = false;
    }
    Child& operator=(Child&& other) noexcept {
        if (this != &other) {
            this->~Child();
            new (this) Child(std::move(other));
        }
        return *this;
    }
    // def __del__(self):

    ~Child() {
        if (!this->__tpy_owned_) return;
        // print("Child destroyed:", self.label)
        std::cout << "Child destroyed:" << " " << this->label << "\n";
    }
};

inline std::ostream& operator<<(std::ostream& os, const Child& obj) {
    ::tpy::print_object_default(os, "Child", obj);
    return os;
}

void __tpy_init();
} // namespace tpyapp::main
