// Generated by TurboPython Compiler
#include "main.hpp"

namespace tpyapp::main {


// def pick(x: A | B | C | D) -> str:
//     match x:
//         # Equivalent to `case A() | B() | C() | D():` at every depth.
//         case ((A() | B()) | C()) | D():
//             return "any"
//     return "none"
std::string pick(::tpy::Union<const A*, const B*, const C*, const D*> x) {
    auto& __match_subject_1 = x;
    switch (__match_subject_1.index()) {
    case 0:
    case 1:
    case 2:
    case 3:
    {
        return "any";
    }
    }
    ::std::unreachable();
    return "none";
}

// def value(x: A | B | C | D) -> int:
//     match x:
//         case ((A(n=v) | B(n=v)) | C(n=v)) | D(n=v):
//             return v
//     return -1
::tpy::BigInt value(::tpy::Union<const A*, const B*, const C*, const D*> x) {
    auto& __match_subject_1 = x;
    switch (__match_subject_1.index()) {
    case 0: {
        auto& __case_0_0 = *std::get<0>(__match_subject_1);
        auto& v = __case_0_0.n;
        return v;
    }
    case 1: {
        auto& __case_0_1 = *std::get<1>(__match_subject_1);
        auto& v = __case_0_1.n;
        return v;
    }
    case 2: {
        auto& __case_0_2 = *std::get<2>(__match_subject_1);
        auto& v = __case_0_2.n;
        return v;
    }
    case 3: {
        auto& __case_0_3 = *std::get<3>(__match_subject_1);
        auto& v = __case_0_3.n;
        return v;
    }
    }
    ::std::unreachable();
    return ::tpy::BigInt(-1);
}

// def main() -> None:
//     a: A | B | C | D = A(1)
//     b: A | B | C | D = B(2)
//     c: A | B | C | D = C(3)
//     d: A | B | C | D = D(4)
//     print(pick(a), value(a))
//     print(pick(b), value(b))
//     print(pick(c), value(c))
//     print(pick(d), value(d))
void main() {
    ::tpy::Union<A, B, C, D> __slot_1 = A(::tpy::BigInt(1));
    ::tpy::Union<A*, B*, C*, D*> a = ::tpy::to_ptr_variant(__slot_1);
    ::tpy::Union<A, B, C, D> __slot_2 = B(::tpy::BigInt(2));
    ::tpy::Union<A*, B*, C*, D*> b = ::tpy::to_ptr_variant(__slot_2);
    ::tpy::Union<A, B, C, D> __slot_3 = C(::tpy::BigInt(3));
    ::tpy::Union<A*, B*, C*, D*> c = ::tpy::to_ptr_variant(__slot_3);
    ::tpy::Union<A, B, C, D> __slot_4 = D(::tpy::BigInt(4));
    ::tpy::Union<A*, B*, C*, D*> d = ::tpy::to_ptr_variant(__slot_4);
    std::cout << ::tpyapp::main::pick(a.as_const()) << " " << ::tpyapp::main::value(a.as_const()) << "\n" << ::tpy::check_signals;
    std::cout << ::tpyapp::main::pick(b.as_const()) << " " << ::tpyapp::main::value(b.as_const()) << "\n" << ::tpy::check_signals;
    std::cout << ::tpyapp::main::pick(c.as_const()) << " " << ::tpyapp::main::value(c.as_const()) << "\n" << ::tpy::check_signals;
    std::cout << ::tpyapp::main::pick(d.as_const()) << " " << ::tpyapp::main::value(d.as_const()) << "\n" << ::tpy::check_signals;
}

// # Three levels of parenthesized or-pattern groups: flattening is bottom-up,
// # so arbitrary nesting depth collapses into one flat alternative list.
// from dataclasses import dataclass
//
// main()
void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    ::tpyapp::main::main();
}

} // namespace tpyapp::main

int __tpy_main(int argc, char* argv[]) {
    ::tpy::init_sys_argv(argc, argv);
    ::tpyapp::main::__tpy_init();
    return 0;
}

int main(int argc, char* argv[]) {
    return ::tpy::run_main(argc, argv, &__tpy_main);
}
