// Generated by TurboPython Compiler
#pragma once

#include <tpy/tpy.hpp>

namespace tpy_user::main {

struct Inner;
struct Outer;

inline constexpr std::string_view __name__ = "__main__";

void modify_inner(Inner* p);
int32_t read_inner(const Inner* p);
void test_field_to_ptr();
void test_field_to_const_ptr();
void test_subscript_to_ptr();

// class Inner:
struct Inner {
    // x: Int32
    int32_t x;

    // def __init__(self, x: Int32) -> None:
    Inner() = default;
    explicit Inner(int32_t x) : x(x) {}
};

inline std::ostream& operator<<(std::ostream& os, const Inner& obj) {
    os << "Inner("
       << "x=" << obj.x
       << ")";
    return os;
}

// class Outer:
struct Outer {
    // inner: Inner
    Inner inner;

    // def __init__(self, x: Int32) -> None:
    Outer() = default;
    explicit Outer(int32_t x) : inner(Inner(x)) {}
};

inline std::ostream& operator<<(std::ostream& os, const Outer& obj) {
    os << "Outer("
       << "inner=" << obj.inner
       << ")";
    return os;
}

void __tpy_init();
} // namespace tpy_user::main
