// Generated by TurboPython Compiler
#include "main.hpp"

namespace tpyapp::main {


// def main() -> None:
void main() {
    // s = Stack()
    Stack s = Stack();
    // # Both calls use borrowing (consuming dispatch is for-loop only)
    // print(s.consume())
    std::cout << s.consume() << "\n";
    // print(s.consume())
    std::cout << s.consume() << "\n";
}

void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    // from typing import Self
    // main()
    main();
}

} // namespace tpyapp::main

int main(int argc, char* argv[]) {
    ::tpy::init_sys_argv(argc, argv);
    tpyapp::main::__tpy_init();
    return 0;
}
