// Generated by TurboPython Compiler
#pragma once

#include <tpy/tpy.hpp>
#include "tpy.hpp"
#include "typing.hpp"

namespace tpy_user::main {

extern std::vector<std::optional<int32_t>>* l;
inline constexpr std::string_view __name__ = "__main__";

std::vector<std::optional<int32_t>> make_list();
void mut();
void f(const std::vector<std::optional<int32_t>>& items);

void __tpy_init();
} // namespace tpy_user::main
