// Generated by TurboPython Compiler
#pragma once

#include <tpy/tpy.hpp>
#include "tpystd/tpy/_types.hpp"
#include "tpystd/typing/_typing.hpp"

namespace tpyapp::main {

inline constexpr std::string_view __name__ = "__main__";

void discard_param(::tpy::ordered_set<std::string>& s, std::string_view k);
void discard_literal(::tpy::ordered_set<std::string>& s);
void remove_param(::tpy::ordered_set<std::string>& s, std::string_view k);
void remove_literal(::tpy::ordered_set<std::string>& s);
bool has(const ::tpy::ordered_set<std::string>& s, std::string_view k);
void empty_key(::tpy::ordered_set<std::string>& s, std::string_view k);
void main();

void __tpy_init();
} // namespace tpyapp::main
