// Generated by TurboPython Compiler
#include "main.hpp"

namespace tpyapp::main {

std::vector<int32_t>* items{};
::tpystd::tplib::array_list::ArrayList<int32_t, 10>* al{};
std::array<int32_t, 3>* arr{};

// """Test explicit dunder method calls on container types.
//
// These methods are defined in the module system and should be
// correctly resolved by codegen (not emitted as literal C++ method calls).
// """
//
// from tplib import ArrayList
//
// # Test list dunders
// items: list[int32] = []
// items.append(int32(10))
// items.append(int32(20))
// items.append(int32(30))
//
// # Explicit __len__
// print(items.__len__())  # 3
//
// # Explicit __getitem__
// print(items.__getitem__(int32(0)))  # 10
// print(items.__getitem__(int32(1)))  # 20
//
// # Explicit __setitem__
// items.__setitem__(int32(1), int32(99))
// print(items.__getitem__(int32(1)))  # 99
//
// # Test ArrayList dunders (user/library type)
// al = ArrayList[int32, 10]()
// al.append(int32(100))
// al.append(int32(200))
//
// # Explicit __len__
// print(al.__len__())  # 2
//
// # Explicit __getitem__
// print(al.__getitem__(int32(0)))  # 100
//
// # Explicit __setitem__
// al.__setitem__(int32(0), int32(111))
// print(al.__getitem__(int32(0)))  # 111
//
// # Test Array dunders
// arr: Array[int32, 3] = [int32(1), int32(2), int32(3)]
//
// # Explicit __len__
// print(arr.__len__())  # 3
//
// # Explicit __getitem__
// print(arr.__getitem__(int32(0)))  # 1
// print(arr.__getitem__(int32(2)))  # 3
void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    ::tpystd::tplib::__tpy_init();
    static std::vector<int32_t> __global_slot_1 = std::vector<int32_t>{};
    items = &__global_slot_1;
    items->push_back(10);
    items->push_back(20);
    items->push_back(30);
    std::cout << ::tpy::__len__((*items)) << "\n" << ::tpy::check_signals;
    std::cout << ::tpy::__getitem__((*items), 0) << "\n" << ::tpy::check_signals;
    std::cout << ::tpy::__getitem__((*items), 1) << "\n" << ::tpy::check_signals;
    ::tpy::__setitem__((*items), 1, 99);
    std::cout << ::tpy::__getitem__((*items), 1) << "\n" << ::tpy::check_signals;
    static ::tpystd::tplib::array_list::ArrayList<int32_t, 10> __global_slot_2 = ::tpystd::tplib::array_list::ArrayList<int32_t, 10>();
    al = &__global_slot_2;
    al->append(100);
    al->append(200);
    std::cout << al->__len__() << "\n" << ::tpy::check_signals;
    std::cout << al->__getitem__(0) << "\n" << ::tpy::check_signals;
    al->__setitem__(0, 111);
    std::cout << al->__getitem__(0) << "\n" << ::tpy::check_signals;
    static std::array<int32_t, 3> __global_slot_3 = {1, 2, 3};
    arr = &__global_slot_3;
    std::cout << ::tpy::__len__((*arr)) << "\n" << ::tpy::check_signals;
    std::cout << ::tpy::__getitem__((*arr), 0) << "\n" << ::tpy::check_signals;
    std::cout << ::tpy::__getitem__((*arr), 2) << "\n" << ::tpy::check_signals;
}

} // namespace tpyapp::main

int __tpy_main(int argc, char* argv[]) {
    ::tpy::init_sys_argv(argc, argv);
    ::tpyapp::main::__tpy_init();
    return 0;
}

int main(int argc, char* argv[]) {
    return ::tpy::run_main(argc, argv, &__tpy_main);
}
