// Generated by TurboPython Compiler
#include "main.hpp"

namespace tpyapp::main {


// def main():
void main() {
    // print(classify(Dog(1)))    # Animal + Dog = 3
    Dog __tmp_1 = Dog(1);
    std::cout << classify<Dog>(__tmp_1) << "\n";
    // print(classify(Puppy(1)))  # Animal + Dog + Puppy = 7
    Puppy __tmp_2 = Puppy(1);
    std::cout << classify<Puppy>(__tmp_2) << "\n";
}

void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    // main()
    main();
}

} // namespace tpyapp::main

int __tpy_main(int argc, char* argv[]) {
    ::tpy::init_sys_argv(argc, argv);
    ::tpyapp::main::__tpy_init();
    return 0;
}

int main(int argc, char* argv[]) {
    std::set_terminate(&::tpy::tpy_terminate_handler);
    return __tpy_main(argc, argv);
}
