// Generated by TurboPython Compiler
#include "main.hpp"

namespace tpyapp::main {


// def main() -> None:
void main() {
    // factory = DefaultPairFactory()
    DefaultPairFactory factory = DefaultPairFactory();
    // pair = create_pair(factory, 30, 10)
    SortedPair<int32_t> pair = create_pair<DefaultPairFactory>(factory, 30, 10);
    // print(pair.first)
    std::cout << pair.first << "\n";
    // print(pair.second)
    std::cout << pair.second << "\n";
}

void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    // main()
    main();
}

} // namespace tpyapp::main

int __tpy_main(int argc, char* argv[]) {
    ::tpy::init_sys_argv(argc, argv);
    ::tpyapp::main::__tpy_init();
    return 0;
}

int main(int argc, char* argv[]) {
    ::tpy::process_startup();
    return __tpy_main(argc, argv);
}
