// Generated by TurboPython Compiler
#include "main.hpp"

namespace tpyapp::main {


// def main() -> None:
void main() {
    // y: Int32 = 100
    int32_t y = 100;
    // def add_y(x: Int32) -> Int32:
    auto add_y = [&y](int32_t x) -> int32_t {
        // return x + y
        return (::tpy::add_check<int32_t>(x, y));
    };
    // print(apply(add_y, 42))
    std::cout << apply(add_y, 42) << "\n";
}

void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    // main()
    main();
}

} // namespace tpyapp::main

int main(int argc, char* argv[]) {
    ::tpy::init_sys_argv(argc, argv);
    tpyapp::main::__tpy_init();
    return 0;
}
