// Generated by TurboPython Compiler
#pragma once

#include <tpy/tpy.hpp>
#include "tpystd/tpy/_types.hpp"
#include "tpystd/typing/_typing.hpp"

namespace tpyapp::main {

struct Rec;
struct Holder;

extern std::string G;
inline constexpr std::string_view __name__ = "__main__";

// def takes(s: str) -> int:
::tpy::BigInt takes(std::string_view s);
// def view_param(s: str) -> int:  # tpyc: mir(covered)
::tpy::BigInt view_param(std::string_view s);
// def slice_local(s: str) -> int:  # tpyc: mir(covered)
::tpy::BigInt slice_local(std::string_view s);
// def slice_bounds(s: str, a: int32, b: int32) -> int:  # tpyc: mir(covered)
::tpy::BigInt slice_bounds(std::string_view s, int32_t a, int32_t b);
// def slice_of_owned(a: str, b: str) -> int:  # tpyc: mir(covered)
::tpy::BigInt slice_of_owned(std::string_view a, std::string_view b);
// def literal_view() -> int:  # tpyc: mir(covered)
::tpy::BigInt literal_view();
// def view_return(s: str) -> StrView:  # tpyc: mir(covered) mir_summary(known)
std::string_view view_return(std::string_view s);
// def view_return_caller(s: str) -> int:  # tpyc: mir(covered)
::tpy::BigInt view_return_caller(std::string_view s);
// def owned_from_view(s: str) -> str:  # tpyc: mir(covered)
std::string owned_from_view(std::string_view s);
// def explicit_view_param(v: StrView) -> StrView:  # tpyc: mir(covered) mir_summary(known)
std::string_view explicit_view_param(std::string_view v);
// def string_as_str_param(x: String) -> int:  # tpyc: mir(covered)
::tpy::BigInt string_as_str_param(const ::tpy::String& x);
// def string_as_str_sink(x: String) -> str:  # tpyc: mir(covered)
std::string string_as_str_sink(const ::tpy::String& x);
// def bytes_slice(b: bytes) -> int:  # tpyc: mir(covered)
::tpy::BigInt bytes_slice(::tpy::BytesView b);
// def stepped(s: str) -> int:  # tpyc: mir(uncovered /^stepped slice$/)
::tpy::BigInt stepped(std::string_view s);
// def span_param(xs: Span[int32]) -> int32:  # tpyc: mir(covered)
int32_t span_param(std::span<int32_t> xs);
// def reassigned_param(s: str) -> int:  # tpyc: mir(covered)
::tpy::BigInt reassigned_param(std::string_view __param_s);
// def loop_rebind(a: str, b: str, n: int32) -> int:  # tpyc: mir(covered)
::tpy::BigInt loop_rebind(std::string_view a, std::string_view b, int32_t n);
// def live_conflict(a: str) -> int:  # tpyc: mir(conflict /^replacement$/)
::tpy::BigInt live_conflict(std::string_view a);
// def last_use(a: str) -> int:  # tpyc: mir(covered)
::tpy::BigInt last_use(std::string_view a);
// def live_conflict_bytes(a: bytes) -> int:  # tpyc: mir(conflict /^replacement$/)
::tpy::BigInt live_conflict_bytes(::tpy::BytesView a);
// def bytes_tail(b: bytes) -> BytesView:  # tpyc: mir(covered) mir_summary(known)
::tpy::BytesView bytes_tail(::tpy::BytesView b);
// def bytes_twins(b: bytes) -> int:  # tpyc: mir(covered)
::tpy::BigInt bytes_twins(::tpy::BytesView b);
// def returns_global_view() -> StrView:  # tpyc: mir(covered) mir_summary(opaque /^view result origin outside the parameters$/)
std::string_view returns_global_view();
// def read_len(r: Rec) -> int:  # tpyc: mir(covered)
::tpy::BigInt read_len(const Rec& r);
// def read_copy(r: Rec) -> str:  # tpyc: mir(covered)
std::string read_copy(const Rec& r);
// def write_field(r: Rec, s: str) -> None:  # tpyc: mir(covered)
void write_field(Rec& r, std::string_view s);
// def append_field(r: Rec, s: str) -> None:  # tpyc: mir(covered)
void append_field(Rec& r, std::string_view s);
// def write_then_reuse(r: Rec, s: str) -> int:  # tpyc: mir(conflict /^replacement$/)
::tpy::BigInt write_then_reuse(Rec& r, std::string_view s);
// def field_view(r: Rec) -> int:  # tpyc: mir(covered)
::tpy::BigInt field_view(const Rec& r);
// def rename(r: Rec, s: str) -> None:  # tpyc: mir(covered) mir_summary(known)
void rename(Rec& r, std::string_view s);
// def forwarded_write(r: Rec, s: str) -> None:  # tpyc: mir(covered)
void forwarded_write(Rec& r, std::string_view s);
// def field_view_then_write(r: Rec, s: str) -> int:  # tpyc: mir(covered)
::tpy::BigInt field_view_then_write(Rec& r, std::string_view s);
// def forwarded_then_reuse(r: Rec, s: str) -> int:  # tpyc: mir(conflict /^replacement$/)
::tpy::BigInt forwarded_then_reuse(Rec& r, std::string_view s);
// def sibling(r: Rec) -> int:  # tpyc: mir(covered)
::tpy::BigInt sibling(const Rec& r);
// def local_record(s: str) -> int:  # tpyc: mir(covered)
::tpy::BigInt local_record(std::string_view s);
// def method_view(r: Rec) -> int:  # tpyc: mir(uncovered /^unsupported view source$/)
::tpy::BigInt method_view(Rec& r);
// def ctor_from_view(s: str) -> int:  # tpyc: mir(covered)
::tpy::BigInt ctor_from_view(std::string_view s);
// def ctor_from_string(x: String) -> int:  # tpyc: mir(covered)
::tpy::BigInt ctor_from_string(const ::tpy::String& x);
// def method_write(r: Rec, s: str) -> None:  # tpyc: mir(uncovered /^unsupported expression type$/)
void method_write(Rec& r, std::string_view s);
// def lit_then_write(q: Rec) -> int:  # tpyc: mir(covered)
::tpy::BigInt lit_then_write(Rec& q);
// def main() -> None:
void main();

// class Rec:
struct Rec {
    // self.name = name  # tpyc: mir_copy(self.name)
    std::string name;
    // self.n = n
    int32_t n;

    // def __init__(self, name: str, n: int32) -> None:  # tpyc: mir(covered)
    Rec() = default;
    explicit Rec(std::string_view name, int32_t n);

    // def name_len(self) -> int:  # tpyc: mir(covered)
    ::tpy::BigInt name_len() const;

    // def name_view(self) -> StrView:  # tpyc: mir(covered)
    std::string_view name_view() const;

    // def rename_m(self, s: str) -> None:  # tpyc: mir(covered)
    void rename_m(std::string_view s);
    static constexpr std::string_view __tpy_class_name__ = "__main__.Rec";
};

inline std::ostream& operator<<(std::ostream& os, const Rec& obj) {
    ::tpy::print_object_default(os, "Rec", obj);
    return os;
}

// class Holder:
struct Holder {
    // self.v = v
    std::string_view v;

    // def __init__(self, v: StrView) -> None:  # tpyc: mir(uncovered /^record holds a borrow$/)
    Holder() = default;
    explicit Holder(std::string_view v);
    static constexpr std::string_view __tpy_class_name__ = "__main__.Holder";
};

inline std::ostream& operator<<(std::ostream& os, const Holder& obj) {
    ::tpy::print_object_default(os, "Holder", obj);
    return os;
}


// # constructor: the str field is initialized by a copy of the view parameter
// def __init__(self, name: str, n: int32) -> None:  # tpyc: mir(covered)
//     self.name = name  # tpyc: mir_copy(self.name)
//     self.n = n
inline Rec::Rec(std::string_view name, int32_t n)
    : name(name),
      n(n) {}

// # method: a str field read is a borrow of the field place
// def name_len(self) -> int:  # tpyc: mir(covered)
//     return len(self.name)
inline ::tpy::BigInt Rec::name_len() const {
    return ::tpy::BigInt(::tpy::__len__(this->name));
}

// # method: a view of a field returned -- the origin is the receiver
// def name_view(self) -> StrView:  # tpyc: mir(covered)
//     return self.name
inline std::string_view Rec::name_view() const {
    return this->name;
}

// # method: a field write is a replacement event on the field place
// def rename_m(self, s: str) -> None:  # tpyc: mir(covered)
//     self.name = s  # tpyc: mir_write(self.name)
inline void Rec::rename_m(std::string_view s) {
    this->name = s;
}

// # constructor: a record holding a view is a retention effect, deferred
// def __init__(self, v: StrView) -> None:  # tpyc: mir(uncovered /^record holds a borrow$/)
//     self.v = v
inline Holder::Holder(std::string_view v) : v(v) {}
void __tpy_init();
} // namespace tpyapp::main
