// Generated by TurboPython Compiler
#include "main.hpp"

namespace tpy_user::main {


// def main() -> Int32:
int32_t main() {
    //     result: Int32 = compute()
    int32_t result = ::tpy_user::outer::inner::consumer::compute();
    //     print(result)
    std::cout << result << "\n";
    //     return Int32(0)
    return 0;
}

void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    // from outer.inner.consumer import compute
    ::tpy_user::outer::__tpy_init();
    ::tpy_user::outer::inner::__tpy_init();
    ::tpy_user::outer::inner::consumer::__tpy_init();
    // main()
    main();
}

} // namespace tpy_user::main

int main(int argc, char* argv[]) {
    tpy::init_sys_argv(argc, argv);
    tpy_user::main::__tpy_init();
    return 0;
}
