// Generated by TurboPython Compiler
#pragma once

#include <tpy/tpy.hpp>
#include "tpystd/tpy/_types.hpp"
#include "tpystd/typing/_typing.hpp"

namespace tpyapp::main {

inline constexpr std::string_view __name__ = "__main__";

struct __coro_g;

__coro_g g();
void main();

// Generator: g
struct __coro_g {
    int32_t __state;

    enum : int32_t {
        S_INITIAL = 0,
        S_RESUME_0 = 1,
        S_RESUME_1 = 2,
        S_DONE = 3,
    };

    __coro_g()
        : __state(S_INITIAL) {}

    std::expected<int32_t, ::tpy::StopIteration> __next__();
    __coro_g& __iter__() { return *this; }

    friend std::ostream& operator<<(std::ostream& os, const __coro_g&) {
        return os << "<generator g>";
    }
};

void __tpy_init();
} // namespace tpyapp::main
