// Generated by TurboPython Compiler
#include "main.hpp"

namespace tpy_user::main {


// 19: def main() -> None:
void main() {
    // 20:     b: Buffer[Int32, 3] = Buffer[Int32, 3]()
    Buffer<int32_t, 3> b = Buffer<int32_t, 3>();
    // 22:     # Set values
    // 23:     b.set(Int32(0), Int32(10))
    b.set(0, 10);
    // 24:     b.set(Int32(1), Int32(20))
    b.set(1, 20);
    // 25:     b.set(Int32(2), Int32(30))
    b.set(2, 30);
    // 27:     # Get values
    // 28:     print(b.get(Int32(0)))
    std::cout << b.get(0) << "\n";
    // 29:     print(b.get(Int32(1)))
    std::cout << b.get(1) << "\n";
    // 30:     print(b.get(Int32(2)))
    std::cout << b.get(2) << "\n";
}

void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    // 33: main()
    main();
}

} // namespace tpy_user::main

int main(int argc, char* argv[]) {
    tpy::init_sys_argv(argc, argv);
    tpy_user::main::__tpy_init();
    return 0;
}
