// Generated by TurboPython Compiler
#pragma once

#include <tpy/tpy.hpp>
#include "tpystd/tpy/_types.hpp"
#include "tpystd/typing/_typing.hpp"

namespace tpyapp::main {

inline constexpr std::string_view __name__ = "__main__";

// def take(x: bytes) -> int:
::tpy::BigInt take(::tpy::BytesView x);
// def make_greeting() -> bytes:
::tpy::Bytes make_greeting();
// def main() -> None:
void main();

void __tpy_init();
} // namespace tpyapp::main
