// Generated by TurboPython Compiler
#pragma once

#include <tpy/tpy.hpp>
#include "tpy.hpp"
#include "typing.hpp"

namespace tpy_user::main {

inline constexpr std::string_view __name__ = "__main__";

int32_t classify(int32_t x);
int32_t check_range(int32_t x);
int32_t check_bounds(int32_t x);
int32_t complex_condition(int32_t a, int32_t b);
int32_t nested_else_if(int32_t x, int32_t y);

void __tpy_init();
} // namespace tpy_user::main
