// Generated by TurboPython Compiler
#include "main.hpp"

namespace tpyapp::main {

Holder* h{};

// def test(h: Holder) -> None:
//     p: Point | None = h.value
//     print(p is None)
//
//     h.value = copy(Point(1, 2))
//     p = h.value
//     print(p is None)
//     print(p.x)
//
//     p = None
//     print(p is None)
//
//     h.value = copy(Point(3, 4))
//     p = h.value
//     print(p.y)
void test(Holder& h) {
    Point* p = ::tpy::optional_to_ptr(h.value);
    std::cout << ::tpy::print_bool((p == nullptr)) << "\n";
    h.value = Point(1, 2);
    p = ::tpy::optional_to_ptr(h.value);
    std::cout << ::tpy::print_bool((p == nullptr)) << "\n";
    std::cout << ::tpy::deref_check(p).x << "\n";
    p = nullptr;
    std::cout << ::tpy::print_bool((p == nullptr)) << "\n";
    h.value = Point(3, 4);
    p = ::tpy::optional_to_ptr(h.value);
    std::cout << ::tpy::deref_check(p).y << "\n";
}

// h = Holder()
// test(h)
void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    static Holder __global_slot_1 = Holder();
    h = &__global_slot_1;
    ::tpyapp::main::test((*h));
}

} // namespace tpyapp::main

int __tpy_main(int argc, char* argv[]) {
    ::tpy::init_sys_argv(argc, argv);
    ::tpyapp::main::__tpy_init();
    return 0;
}

int main(int argc, char* argv[]) {
    ::tpy::process_startup();
    return __tpy_main(argc, argv);
}
