// Generated by TurboPython Compiler
#include "main.hpp"

namespace tpyapp::main {

Counter* g{};

// def main() -> None:
//     with g as n1:
//         print(n1)
//     with g as n2:
//         print(n2)
//     print(g.opens)
void main() {
    auto& __ctx_1 = *(g);
    auto n1 = __ctx_1.__enter__();
    try {
        std::cout << n1 << "\n" << ::tpy::check_signals;
        goto __with_exit_1;
    } catch (::tpy::BaseException& __exc_1) {
        __ctx_1.__exit__({}, &__exc_1, {});
        throw;
    } catch (...) {
        __ctx_1.__exit__({}, nullptr, {});
        throw;
    }
    __with_exit_1:
    __ctx_1.__exit__({}, nullptr, {});
    auto& __ctx_2 = *(g);
    auto n2 = __ctx_2.__enter__();
    try {
        std::cout << n2 << "\n" << ::tpy::check_signals;
        goto __with_exit_2;
    } catch (::tpy::BaseException& __exc_2) {
        __ctx_2.__exit__({}, &__exc_2, {});
        throw;
    } catch (...) {
        __ctx_2.__exit__({}, nullptr, {});
        throw;
    }
    __with_exit_2:
    __ctx_2.__exit__({}, nullptr, {});
    std::cout << g->opens << "\n" << ::tpy::check_signals;
}

// g = Counter()
//
// main()
void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    static Counter __global_slot_1 = Counter();
    g = &__global_slot_1;
    ::tpyapp::main::main();
}

} // namespace tpyapp::main

int __tpy_main(int argc, char* argv[]) {
    ::tpy::init_sys_argv(argc, argv);
    ::tpyapp::main::__tpy_init();
    return 0;
}

int main(int argc, char* argv[]) {
    return ::tpy::run_main(argc, argv, &__tpy_main);
}
