// Generated by TurboPython Compiler
#pragma once

#include <tpy/tpy.hpp>
#include "tpystd/tpy.hpp"
#include "tpystd/typing.hpp"

namespace tpyapp::main {

struct Box;

inline constexpr std::string_view __name__ = "__main__";

template<typename T>
int32_t take_optional(std::optional<T> item, int32_t fallback);
void main();

// class Box:
struct Box {
    // value: Int32
    int32_t value;

};

inline std::ostream& operator<<(std::ostream& os, const Box& obj) {
    os << "Box("
       << "value=" << obj.value
       << ")";
    return os;
}

// def take_optional[T](item: Own[T] | None, fallback: Int32) -> Int32:
template<typename T>
int32_t take_optional(std::optional<T> item, int32_t fallback) {
    // return fallback
    return fallback;
}

void __tpy_init();
} // namespace tpyapp::main
