// Generated by TurboPython Compiler
#include "main.hpp"

namespace tpy_user::main {





// def main() -> None:
void main() {
    //     print(to_char(65))
    std::cout << static_cast<char>(65) << "\n";
    //     print(to_int("Z"))
    std::cout << static_cast<int32_t>(static_cast<unsigned char>('Z')) << "\n";
    //     print(add(10, 32))
    std::cout << 10 + 32 << "\n";
}

void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    // # @cpp_template: inline C++ expression templates in .py source
    // from tpy.extern import cpp_template
    // main()
    main();
}

} // namespace tpy_user::main

int main(int argc, char* argv[]) {
    ::tpy::init_sys_argv(argc, argv);
    tpy_user::main::__tpy_init();
    return 0;
}
