// Generated by TurboPython Compiler
#include "main.hpp"

namespace tpyapp::main {

int32_t limit{};
int32_t scale{};

// def bump() -> int32:
//     global limit
//     limit = int32(4)
//     # The subject: the filter reads the `global`-declared name, and the
//     # element expression reads a module global the function only reads.
//     return sum(i * scale for i in range(6) if i < limit)  # tpyc: ok
int32_t bump() {
    limit = 4;
    return ::tpy::builtin_sum<int32_t>(::tpy::make_generator<int32_t>(
        [__i = int32_t(0), __stop = static_cast<int32_t>(6)]() mutable -> std::optional<int32_t> {
            while (__i < __stop) {
                int32_t i = __i++;
                if ((i < limit)) {
                    return std::optional<int32_t>((::tpy::mul_check<int32_t>(i, scale)));
                }
            }
            return std::nullopt;
        }
    ));
}

// def main() -> None:
//     print(bump(), limit)
void main() {
    std::cout << bump() << " " << limit << "\n";
}

// limit: int32 = int32(3)
// scale: int32 = int32(2)
//
// main()
void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    limit = 3;
    scale = 2;
    main();
}

} // namespace tpyapp::main

int __tpy_main(int argc, char* argv[]) {
    ::tpy::init_sys_argv(argc, argv);
    ::tpyapp::main::__tpy_init();
    return 0;
}

int main(int argc, char* argv[]) {
    ::tpy::process_startup();
    return __tpy_main(argc, argv);
}
