// Generated by TurboPython Compiler
#pragma once

#include <tpy/tpy.hpp>
#include "tpystd/tpy/_types.hpp"
#include "tpystd/typing/_typing.hpp"
#include "tpystd/coro.hpp"
#include "tpystd/asyncio.hpp"

namespace tpyapp::main {

struct Counter;

inline constexpr std::string_view __name__ = "__main__";

struct __coro_make_pair;
struct __coro_main_coro;

// async def make_pair() -> tuple[Own[Counter], int32]:
__coro_make_pair make_pair();
// async def main_coro() -> None:
__coro_main_coro main_coro();
// def main() -> None:
void main();

// @nocopy
// class Counter:
struct Counter {
    // n: int32
    int32_t n;

    // def __init__(self, n: int32) -> None:
    Counter() = default;
    explicit Counter(int32_t n);
    // non-copyable (@nocopy)
    Counter(const Counter&) = delete;
    Counter& operator=(const Counter&) = delete;
    Counter(Counter&&) = default;
    Counter& operator=(Counter&&) = default;

    // def bump(self) -> None:
    void bump();
    static constexpr std::string_view __tpy_class_name__ = "__main__.Counter";
};

inline std::ostream& operator<<(std::ostream& os, const Counter& obj) {
    ::tpy::print_object_default(os, "Counter", obj);
    return os;
}

// async def make_pair() -> tuple[Own[Counter], int32]:
struct __coro_make_pair {
    int32_t __state;
    bool __cancel_pending;
    ::tpy::frame_slot<Counter> c;

    enum : int32_t {
        S_INITIAL = 0,
        S_DONE = 1,
    };

    __coro_make_pair()
        : __state(S_INITIAL), __cancel_pending(false) {}

    ::tpystd::tpy::Poll<std::tuple<Counter, int32_t>> __poll__(::tpystd::coro::Waker waker);
    void cancel() { __cancel_pending = true; }

    friend std::ostream& operator<<(std::ostream& os, const __coro_make_pair&) {
        return os << "<coroutine make_pair>";
    }
};

// async def main_coro() -> None:
struct __coro_main_coro {
    int32_t __state;
    bool __cancel_pending;
    ::tpy::frame_slot<Counter> c;
    int32_t tag;
    ::tpy::frame_slot<std::tuple<Counter, int32_t>> __await_lift_0;
    std::optional<__coro_make_pair> __sub_0;

    enum : int32_t {
        S_INITIAL = 0,
        S_RESUME_0 = 1,
        S_DONE = 2,
    };

    __coro_main_coro()
        : __state(S_INITIAL), __cancel_pending(false) {}

    ::tpystd::tpy::Poll<::std::monostate> __poll__(::tpystd::coro::Waker waker);
    void cancel() { __cancel_pending = true; }

    friend std::ostream& operator<<(std::ostream& os, const __coro_main_coro&) {
        return os << "<coroutine main_coro>";
    }
};


// def __init__(self, n: int32) -> None:
//     self.n = n
inline Counter::Counter(int32_t n) : n(n) {}

// def bump(self) -> None:
//     self.n += 1
inline void Counter::bump() {
    this->n = ::tpy::add_check<int32_t>(this->n, 1);
}
void __tpy_init();
} // namespace tpyapp::main
