// Generated by TurboPython Compiler
#pragma once

#include <tpy/tpy.hpp>

namespace tpy_user::main {

extern std::string_view __name__;
extern std::string_view s;
extern char c;
extern std::vector<tpy::BigInt>* items;
extern std::array<int32_t, 3>* arr;
extern StaticList<int32_t, 4>* sl;
extern std::optional<int32_t> x;
extern std::optional<bool> y;
extern std::optional<double> z;

void print_range();

void __tpy_init();
} // namespace tpy_user::main
