// Generated by TurboPython Compiler
#include "main.hpp"

namespace tpy_user::main {


// 13: def main() -> None:
void main() {
    // 14:     p = Point(1, 2)
    Point p = Point(1, 2);
    // 15:     print(p.x, p.y)
    std::cout << p.x << " " << p.y << "\n";
}

void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    // 17: main()
    main();
}

} // namespace tpy_user::main

int main(int argc, char* argv[]) {
    tpy::init_sys_argv(argc, argv);
    tpy_user::main::__tpy_init();
    return 0;
}
