// Generated by TurboPython Compiler
#include "main.hpp"

namespace tpyapp::main {


// def insert(d: dict[str, int32], key: str, val: int32) -> None:
//     d[key] = val
void insert(::tpy::ordered_map<std::string, int32_t>& d, std::string_view key, int32_t val) {
    ::tpy::__setitem__(d, key, val);
}

// def main() -> None:
//     d = {"a": 1}
//     insert(d, "b", 2)
//     print(d)
void main() {
    ::tpy::ordered_map<std::string, int32_t> d = ::tpy::ordered_map<std::string, int32_t>({{"a", 1}});
    ::tpyapp::main::insert(d, "b", 2);
    std::cout << ::tpy::DictPrinter(d) << "\n" << ::tpy::check_signals;
}

// main()
void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    ::tpyapp::main::main();
}

} // namespace tpyapp::main

int __tpy_main(int argc, char* argv[]) {
    ::tpy::init_sys_argv(argc, argv);
    ::tpyapp::main::__tpy_init();
    return 0;
}

int main(int argc, char* argv[]) {
    ::tpy::process_startup();
    return __tpy_main(argc, argv);
}
