// Generated by TurboPython Compiler
#include "main.hpp"

namespace tpyapp::main {


// @readonly
// def add_one(x: Int32) -> Int32:
int32_t add_one(int32_t x) {
    // return Ops.plus_one(x)  # tpyc: ok
    return Ops::plus_one(x);
}

void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    // print(add_one(3))
    std::cout << add_one(3) << "\n";
}

} // namespace tpyapp::main

int __tpy_main(int argc, char* argv[]) {
    ::tpy::init_sys_argv(argc, argv);
    ::tpyapp::main::__tpy_init();
    return 0;
}

int main(int argc, char* argv[]) {
    std::set_terminate(&::tpy::tpy_terminate_handler);
    return __tpy_main(argc, argv);
}
