// Generated by TurboPython Compiler
#include "main.hpp"

namespace tpyapp::main {


// def main() -> None:
void main() {
    // d: Cloneable = Dog()
    Dog __slot_1{Dog()};
    Cloneable* d = &__slot_1;
    // b = Box(d.replicate())
    ::tpystd::tplib::box::Box<Cloneable> b = ::tpystd::tplib::box::Box<Cloneable>(d->replicate());
    // print(b.name())
    std::cout << b.__deref__().name() << "\n";
}

void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    // from tplib import Box
    ::tpystd::tplib::__tpy_init();
    // main()
    main();
}

} // namespace tpyapp::main

int __tpy_main(int argc, char* argv[]) {
    ::tpy::init_sys_argv(argc, argv);
    ::tpyapp::main::__tpy_init();
    return 0;
}

int main(int argc, char* argv[]) {
    ::tpy::process_startup();
    return __tpy_main(argc, argv);
}
