// Generated by TurboPython Compiler
#include "main.hpp"

namespace tpyapp::main {


// def score(x: float | None) -> int32:
//     if x:  # tpyc: warning(/Truthiness check on optional value/)  # tpyc: warning(/variable 'x'/)
//         return 1
//     return 0
int32_t score(std::optional<double> x) {
    if (::tpy::is_truthy(x)) {
        return 1;
    }
    return 0;
}

// print(score(1.5))
// print(score(0.0))
// print(score(None))
void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    std::cout << ::tpyapp::main::score(1.5) << "\n" << ::tpy::check_signals;
    std::cout << ::tpyapp::main::score(0.0) << "\n" << ::tpy::check_signals;
    std::cout << ::tpyapp::main::score(std::nullopt) << "\n" << ::tpy::check_signals;
}

} // namespace tpyapp::main

int __tpy_main(int argc, char* argv[]) {
    ::tpy::init_sys_argv(argc, argv);
    ::tpyapp::main::__tpy_init();
    return 0;
}

int main(int argc, char* argv[]) {
    ::tpy::process_startup();
    return __tpy_main(argc, argv);
}
