// Generated by TurboPython Compiler
#include "main.hpp"

namespace tpyapp::main {


// def main() -> None:
//     h = HeapVal(int32(42))
//     val: int32 = h.take()
//     print("got", val)
//
//     # Temporary
//     val2: int32 = HeapVal(int32(99)).take()
//     print("got", val2)
void main() {
    HeapVal h = HeapVal(42);
    int32_t val = std::move(h).take();
    std::cout << "got" << " " << val << "\n";
    int32_t val2 = HeapVal(99).take();
    std::cout << "got" << " " << val2 << "\n";
}

// from tpy.unsafe import unsafe_alloc, unsafe_free, unsafe_init, unsafe_drop, unsafe_move_out
//
// main()
void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    ::tpyapp::main::main();
}

} // namespace tpyapp::main

int __tpy_main(int argc, char* argv[]) {
    ::tpy::init_sys_argv(argc, argv);
    ::tpyapp::main::__tpy_init();
    return 0;
}

int main(int argc, char* argv[]) {
    ::tpy::process_startup();
    return __tpy_main(argc, argv);
}
