// Generated by TurboPython Compiler
#pragma once

#include <tpy/tpy.hpp>
#include "tpystd/tpy/_types.hpp"
#include "tpystd/typing/_typing.hpp"

namespace tpyapp::main {

struct Circle;
struct Rect;

inline constexpr std::string_view __name__ = "__main__";

// def describe(s: Circle | Rect) -> None:
void describe(::tpy::Union<const Circle*, const Rect*> s);
// def main() -> None:
void main();

// class Circle:
struct Circle {
    // radius: float
    double radius;

    // def __init__(self, radius: float) -> None:
    Circle() = default;
    explicit Circle(double radius);
    static constexpr std::string_view __tpy_class_name__ = "__main__.Circle";
};

inline std::ostream& operator<<(std::ostream& os, const Circle& obj) {
    ::tpy::print_object_default(os, "Circle", obj);
    return os;
}

// class Rect:
struct Rect {
    // width: float
    double width;
    // height: float
    double height;

    // def __init__(self, width: float, height: float) -> None:
    Rect() = default;
    explicit Rect(double width, double height);
    static constexpr std::string_view __tpy_class_name__ = "__main__.Rect";
};

inline std::ostream& operator<<(std::ostream& os, const Rect& obj) {
    ::tpy::print_object_default(os, "Rect", obj);
    return os;
}


// def __init__(self, radius: float) -> None:
//     self.radius = radius
inline Circle::Circle(double radius) : radius(radius) {}

// def __init__(self, width: float, height: float) -> None:
//     self.width = width
//     self.height = height
inline Rect::Rect(double width, double height) : width(width), height(height) {}
void __tpy_init();
} // namespace tpyapp::main
