// Generated by TurboPython Compiler
#pragma once

#include <tpy/tpy.hpp>
#include "tpystd/tpy/_types.hpp"
#include "tpystd/typing/_typing.hpp"

namespace tpyapp::main {

struct Foo;

inline constexpr std::string_view __name__ = "__main__";

// def main() -> None:
void main();

// class Foo:
struct Foo {
    // x: int32
    int32_t x;
    // y: int32
    int32_t y;

    static constexpr std::string_view __tpy_class_name__ = "__main__.Foo";
};

inline std::ostream& operator<<(std::ostream& os, const Foo& obj) {
    ::tpy::print_object_default(os, "Foo", obj);
    return os;
}

void __tpy_init();
} // namespace tpyapp::main
