// Generated by TurboPython Compiler
#pragma once

#include <tpy/tpy.hpp>
#include "tpystd/tpy/_types.hpp"
#include "tpystd/typing/_typing.hpp"

namespace tpyapp::main {

inline constexpr std::string_view __name__ = "__main__";

template<typename T>
::tpy::val_or_ref_t<T> first_val(std::vector<T>&& items);
template<::tpy::ValueType T>
::tpy::val_or_ref_t<T> passthrough(::tpy::own_param_t<T> x);
void main();

// def first_val[T](items: Own[list[T]]) -> T:
template<typename T>
::tpy::val_or_ref_t<T> first_val(std::vector<T>&& items) {
    // return items[0]  # tpyc: ok
    return ::tpy::__getitem__(items, 0);
}
// def passthrough[T: ValueType](x: Own[T]) -> T:
template<::tpy::ValueType T>
::tpy::val_or_ref_t<T> passthrough(::tpy::own_param_t<T> x) {
    // return x  # tpyc: ok
    return x;
}

void __tpy_init();
} // namespace tpyapp::main
