// Generated by TurboPython Compiler
#pragma once

#include <tpy/tpy.hpp>
#include "tpystd/tpy/_types.hpp"
#include "tpystd/typing/_typing.hpp"

namespace tpyapp::main {

struct Tree;
struct Leaf;

inline constexpr std::string_view __name__ = "__main__";

int32_t head(const Tree& t);
void main();

// class Leaf:
struct Leaf {
    // v: int32
    int32_t v;

    // def __init__(self, v: int32) -> None:
    Leaf() = default;
    explicit Leaf(int32_t v);
    static constexpr std::string_view __tpy_class_name__ = "__main__.Leaf";
};

inline std::ostream& operator<<(std::ostream& os, const Leaf& obj) {
    ::tpy::print_object_default(os, "Leaf", obj);
    return os;
}


// def __init__(self, v: int32) -> None:
inline Leaf::Leaf(int32_t v) : v(v) {}
struct Tree {
    using variant_type = ::tpy::Union<Leaf, std::vector<Tree>>;
    variant_type value;

    Tree() = default;
    template<typename T>
        requires std::constructible_from<variant_type, T&&>
    Tree(T&& v) : value(std::forward<T>(v)) {}

    bool operator==(const Tree&) const = default;

    friend std::ostream& operator<<(std::ostream& os, const Tree& v) {
        ::tpy::detail::print_element(os, v.value);
        return os;
    }
};

void __tpy_init();
} // namespace tpyapp::main
