// Generated by TurboPython Compiler
#include "main.hpp"

namespace tpyapp::main {


// def describe(a: Dog | Cat) -> str:
std::string describe(const std::variant<Cat*, Dog*> a) {
    // match a:
    auto& __match_subject_1 = a;
    switch (__match_subject_1.index()) {
    case 1: {
        auto& __case_1 = *std::get<1>(__match_subject_1);
        // case Dog(legs=4):  # tpyc: ok
        {
            if (__case_1.legs == 4) {
                // return "four-legged dog"
                return "four-legged dog";
                goto __match_end_2;
            }
        }
        // case _:
        {
            // return "other"
            return "other";
            goto __match_end_2;
        }
        break;
    }
    default: {
        // case _:
        // return "other"
        return "other";
        goto __match_end_2;
        break;
    }
    }
__match_end_2:;
    ::std::unreachable();
}

// def main() -> None:
void main() {
    // print(describe(Dog(3)))
    Dog __tmp_1 = Dog(::tpy::BigInt(3));
    std::cout << describe(std::variant<Cat*, Dog*>{&__tmp_1}) << "\n";
    // print(describe(Dog(4)))
    Dog __tmp_2 = Dog(::tpy::BigInt(4));
    std::cout << describe(std::variant<Cat*, Dog*>{&__tmp_2}) << "\n";
    // print(describe(Cat("x")))
    Cat __tmp_3 = Cat("x");
    std::cout << describe(std::variant<Cat*, Dog*>{&__tmp_3}) << "\n";
}

void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    // main()
    main();
}

} // namespace tpyapp::main

int __tpy_main(int argc, char* argv[]) {
    ::tpy::init_sys_argv(argc, argv);
    ::tpyapp::main::__tpy_init();
    return 0;
}

int main(int argc, char* argv[]) {
    std::set_terminate(&::tpy::tpy_terminate_handler);
    return __tpy_main(argc, argv);
}
