// Generated by TurboPython Compiler
#pragma once

#include <tpy/tpy.hpp>
#include "pet.hpp"

namespace tpy_user::main {

// @dynamic
// 8: class NamedPet(Pet, Protocol):
template<typename T>
concept __NamedPet_Concept__ = requires(T& t) {
    { t.name() } -> std::convertible_to<std::string>;
    { t.speak() } -> std::convertible_to<std::string>;
};

struct NamedPet : ::tpy_user::pet::Pet {
    virtual std::string name() = 0;
    virtual ~NamedPet() = default;
};

} // namespace tpy_user::main

template<tpy_user::main::__NamedPet_Concept__ T>
struct tpy::Adapter<tpy_user::main::NamedPet, T> : tpy_user::main::NamedPet {
    T inner;
    template<typename... Args>
    Adapter(Args&&... args) : inner(std::forward<Args>(args)...) {}
    std::string name() override { return inner.name(); }
    std::string speak() override { return inner.speak(); }
};

template<tpy_user::main::__NamedPet_Concept__ T>
struct tpy::RefAdapter<tpy_user::main::NamedPet, T> : tpy_user::main::NamedPet {
    T& inner;
    RefAdapter(T& ref) : inner(ref) {}
    std::string name() override { return inner.name(); }
    std::string speak() override { return inner.speak(); }
};

namespace tpy_user::main {

struct Dog;
struct Parrot;

inline constexpr std::string_view __name__ = "__main__";

void greet_pet(::tpy_user::pet::Pet& pet);
void greet_named(NamedPet& pet);
void main();

// 11: class Dog(NamedPet):
struct Dog : NamedPet {


    // 12:     def speak(self) -> str:
    std::string speak() override {
        // 13:         return "Woof"
        return "Woof";
    }

    // 14:     def name(self) -> str:
    std::string name() override {
        // 15:         return "Rex"
        return "Rex";
    }
};

inline std::ostream& operator<<(std::ostream& os, const Dog& obj) {
    os << "Dog("
       << ")";
    return os;
}

// 17: class Parrot:
struct Parrot {


    // 18:     def speak(self) -> str:
    std::string speak() const {
        // 19:         return "Squawk"
        return "Squawk";
    }

    // 20:     def name(self) -> str:
    std::string name() const {
        // 21:         return "Polly"
        return "Polly";
    }
};

inline std::ostream& operator<<(std::ostream& os, const Parrot& obj) {
    os << "Parrot("
       << ")";
    return os;
}

void __tpy_init();
} // namespace tpy_user::main
