// Generated by TurboPython Compiler
#pragma once

#include <tpy/tpy.hpp>
#include "tpystd/tpy/_types.hpp"
#include "tpystd/typing/_typing.hpp"

namespace tpyapp::main {

struct P;

inline constexpr std::string_view __name__ = "__main__";

std::string describe(const P& p);
void main();

// class P:
struct P {
    // x: Optional[int]
    std::optional<::tpy::BigInt> x;
    // name: Optional[str]
    std::optional<std::string> name;

    // def __init__(self, x: Optional[int], name: Optional[str]) -> None:
    P() = default;
    explicit P(std::optional<::tpy::BigInt> x, std::optional<std::string_view> name);
    static constexpr std::string_view __tpy_class_name__ = "__main__.P";
};

inline std::ostream& operator<<(std::ostream& os, const P& obj) {
    ::tpy::print_object_default(os, "P", obj);
    return os;
}


// def __init__(self, x: Optional[int], name: Optional[str]) -> None:
inline P::P(std::optional<::tpy::BigInt> x, std::optional<std::string_view> name) : x(x), name(name ? std::make_optional(std::string(*name)) : std::nullopt) {}
void __tpy_init();
} // namespace tpyapp::main
