// Generated by TurboPython Compiler
#include "mypackage/utils.hpp"

namespace tpy_user::mypackage::utils {


// def helper() -> None:
void helper() {
    //     print("helper called")
    std::cout << "helper called" << "\n";
}

void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

}

} // namespace tpy_user::mypackage::utils
