// Generated by TurboPython Compiler
#include "main.hpp"
#include "main_inl.hpp"

namespace tpyapp::main {


// def repr_param(b: bytes) -> str:
//     # repr() of a bytes parameter, which is a view in C++.
//     return repr(b)  # tpyc: ok
std::string repr_param(::tpy::BytesView b) {
    return ::tpy::repr_of(b);
}

// def section_bytes() -> None:
//     # bytes local: printable, non-printable and quote-choosing contents.
//     b = b"a\x03"
//     print("bytes:", repr(b))  # tpyc: ok
//     print("bytes:", repr(b"it's"))  # tpyc: ok
//     print("bytes:", repr(b'say "hi"'))  # tpyc: ok
//     print("bytes:", repr(b"it's \"both\""))  # tpyc: ok
//     print("bytes:", repr(b"\t\n\\\xff"))  # tpyc: ok
//     print("bytes:", repr(bytes([0, 65, 127])))  # tpyc: ok
//     print("bytes:", repr_param(b"p"))
void section_bytes() {
    ::tpy::BytesView b = ::tpy::bytes_literal("a\x03", 2);
    std::cout << "bytes:" << " " << ::tpy::repr_of(b) << "\n" << ::tpy::check_signals;
    std::cout << "bytes:" << " " << ::tpy::repr_of(::tpy::bytes_literal_owned("it's", 4)) << "\n" << ::tpy::check_signals;
    std::cout << "bytes:" << " " << ::tpy::repr_of(::tpy::bytes_literal_owned("say \"hi\"", 8)) << "\n" << ::tpy::check_signals;
    std::cout << "bytes:" << " " << ::tpy::repr_of(::tpy::bytes_literal_owned("it's \"both\"", 11)) << "\n" << ::tpy::check_signals;
    std::cout << "bytes:" << " " << ::tpy::repr_of(::tpy::bytes_literal_owned("\t\n\\\xff", 4)) << "\n" << ::tpy::check_signals;
    std::cout << "bytes:" << " " << ::tpy::repr_of(::tpy::bytes_from_int_iterable(std::array<int32_t, 3>{0, 65, 127})) << "\n" << ::tpy::check_signals;
    std::cout << "bytes:" << " " << ::tpyapp::main::repr_param(::tpy::bytes_literal("p", 1)) << "\n" << ::tpy::check_signals;
}

// def section_bytearray() -> None:
//     # bytearray local after a mutation, and an empty one.
//     ba = bytearray(b"z")
//     ba.append(3)
//     print("bytearray:", repr(ba))  # tpyc: ok
//     print("bytearray:", repr(bytearray()))  # tpyc: ok
//     # Quote choice follows bytes, but `'` is always escaped.
//     print("bytearray:", repr(bytearray(b"it's")))  # tpyc: ok
//     print("bytearray:", repr(bytearray(b'say "hi"')))  # tpyc: ok
//     print("bytearray:", repr(bytearray(b"it's \"both\"")))  # tpyc: ok
void section_bytearray() {
    ::tpy::ByteArray ba = ::tpy::ByteArray(::tpy::bytes_literal("z", 1));
    ba.push_back(3);
    std::cout << "bytearray:" << " " << ::tpy::repr_of(ba) << "\n" << ::tpy::check_signals;
    std::cout << "bytearray:" << " " << ::tpy::repr_of(::tpy::ByteArray()) << "\n" << ::tpy::check_signals;
    std::cout << "bytearray:" << " " << ::tpy::repr_of(::tpy::ByteArray(::tpy::bytes_literal("it's", 4))) << "\n" << ::tpy::check_signals;
    std::cout << "bytearray:" << " " << ::tpy::repr_of(::tpy::ByteArray(::tpy::bytes_literal("say \"hi\"", 8))) << "\n" << ::tpy::check_signals;
    std::cout << "bytearray:" << " " << ::tpy::repr_of(::tpy::ByteArray(::tpy::bytes_literal("it's \"both\"", 11))) << "\n" << ::tpy::check_signals;
}

// def section_bytesview() -> None:
//     b = b"ab'cd"
//     # A bytes slice is a BytesView; it reprs like bytes.
//     v = b[1:4]  # tpyc: type(BytesView)
//     print("bytesview:", repr(v))  # tpyc: ok
//     print("bytesview:", v, f"{v!r}")  # tpyc: ok
void section_bytesview() {
    ::tpy::BytesView b = ::tpy::bytes_literal("ab'cd", 5);
    ::tpy::BytesView v = ::tpy::bytes_slice(b, ::tpy::BasicSlice{1, 4});
    std::cout << "bytesview:" << " " << ::tpy::repr_of(v) << "\n" << ::tpy::check_signals;
    std::cout << "bytesview:" << " " << ::tpy::BytesPrinter(v) << " " << std::format("{}", ::tpy::repr_of(v)) << "\n" << ::tpy::check_signals;
}

// def section_fstring() -> None:
//     # `!r` and the plain placeholder render the same text as repr().
//     b = b"q\x00"
//     ba = bytearray(b"w")
//     r = range(1, 4)
//     print(f"fstring: {b!r} {ba!r} {r!r}")  # tpyc: ok
//     print(f"fstring: {b} {ba} {r}")  # tpyc: ok
void section_fstring() {
    ::tpy::BytesView b = ::tpy::bytes_literal("q\000", 2);
    ::tpy::ByteArray ba = ::tpy::ByteArray(::tpy::bytes_literal("w", 1));
    ::tpy::Range<int32_t> r = ::tpy::Range<int32_t>(1, 4);
    std::cout << std::format("fstring: {} {} {}", ::tpy::repr_of(b), ::tpy::repr_of(ba), ::tpy::repr_of(r)) << "\n" << ::tpy::check_signals;
    std::cout << std::format("fstring: {} {} {}", ::tpy::__str__(b), ::tpy::__str__(ba), ::tpy::__str__(r)) << "\n" << ::tpy::check_signals;
}

// def section_container() -> None:
//     # Annotated because repr() rejects a pending list (BUGS.md#repr-pending-literal-arg).
//     xs: list[bytes] = [b"a", b"\n"]
//     # A container of bytes reprs each element as bytes.
//     print("container:", repr(xs))  # tpyc: ok
//     print("container:", xs)
void section_container() {
    std::vector<::tpy::Bytes> xs = {::tpy::bytes_literal_owned("a", 1), ::tpy::bytes_literal_owned("\n", 1)};
    std::cout << "container:" << " " << ::tpy::list_to_str(xs) << "\n" << ::tpy::check_signals;
    std::cout << "container:" << " " << ::tpy::ListPrinter(xs) << "\n" << ::tpy::check_signals;
}

// def section_range() -> None:
//     # Start kept when 0, step shown unless 1, at every element width.
//     print("range:", repr(range(3)))  # tpyc: ok
//     print("range:", repr(range(2, 5)))  # tpyc: ok
//     print("range:", repr(range(0, 10, 2)))  # tpyc: ok
//     print("range:", repr(range(10, 0, -3)))  # tpyc: ok
//     print("range:", repr(range(int64(5), int64(-1), int64(-1))))  # tpyc: ok
//     n: int = 10 ** 20
//     print("range:", repr(range(n, n + 2)))  # tpyc: ok
void section_range() {
    std::cout << "range:" << " " << ::tpy::repr_of(::tpy::Range<int32_t>(3)) << "\n" << ::tpy::check_signals;
    std::cout << "range:" << " " << ::tpy::repr_of(::tpy::Range<int32_t>(2, 5)) << "\n" << ::tpy::check_signals;
    std::cout << "range:" << " " << ::tpy::repr_of(::tpy::Range<int32_t>(0, 10, 2)) << "\n" << ::tpy::check_signals;
    std::cout << "range:" << " " << ::tpy::repr_of(::tpy::Range<int32_t>(10, 0, -3)) << "\n" << ::tpy::check_signals;
    std::cout << "range:" << " " << ::tpy::repr_of(::tpy::Range<int64_t>(5, -1, -1)) << "\n" << ::tpy::check_signals;
    ::tpy::BigInt n = ((::tpy::BigInt(10)).pow(::tpy::BigInt(20)));
    std::cout << "range:" << " " << ::tpy::repr_of(::tpy::Range<::tpy::BigInt>(n, ((n) + (::tpy::BigInt(2))))) << "\n" << ::tpy::check_signals;
}

// def section_str_range() -> None:
//     # str() of a range is its repr.
//     print("str_range:", str(range(3)))  # tpyc: ok
//     print("str_range:", str(range(1, 9, 4)))  # tpyc: ok
void section_str_range() {
    std::cout << "str_range:" << " " << std::string(::tpy::__str__(::tpy::Range<int32_t>(3))) << "\n" << ::tpy::check_signals;
    std::cout << "str_range:" << " " << std::string(::tpy::__str__(::tpy::Range<int32_t>(1, 9, 4))) << "\n" << ::tpy::check_signals;
}

// def section_small_range() -> None:
//     # int8 / uint8 ranges print their bounds as numbers, not characters.
//     print("small_range:", repr(range(int8(1), int8(3))))  # tpyc: ok
//     print("small_range:", str(range(int8(-2), int8(2))))  # tpyc: ok
//     print("small_range:", repr(range(uint8(0), uint8(9), uint8(3))))  # tpyc: ok
//     print("small_range:", str(range(uint8(200), uint8(250), uint8(25))))  # tpyc: ok
void section_small_range() {
    std::cout << "small_range:" << " " << ::tpy::repr_of(::tpy::Range<int8_t>(1, 3)) << "\n" << ::tpy::check_signals;
    std::cout << "small_range:" << " " << std::string(::tpy::__str__(::tpy::Range<int8_t>(-2, 2))) << "\n" << ::tpy::check_signals;
    std::cout << "small_range:" << " " << ::tpy::repr_of(::tpy::Range<uint8_t>(0, 9, 3)) << "\n" << ::tpy::check_signals;
    std::cout << "small_range:" << " " << std::string(::tpy::__str__(::tpy::Range<uint8_t>(200, 250, 25))) << "\n" << ::tpy::check_signals;
}

// def section_method() -> None:
//     h = Holder(b"m'")
//     print("method:", h.show(2))
void section_method() {
    Holder h = Holder(::tpy::bytes_literal("m'", 2));
    std::cout << "method:" << " " << h.show(2) << "\n" << ::tpy::check_signals;
}


// def reprs(b: bytes, n: int32) -> Iterator[str]:
__gen_reprs reprs(::tpy::BytesView b, int32_t n) {
    return __gen_reprs(b, n);
}

// def section_generator() -> None:
//     for s in reprs(b"g\x01", 3):
//         print("generator:", s)
void section_generator() {
    {
        auto __src_0 = ::tpyapp::main::reprs(::tpy::bytes_literal("g\x01", 2), 3);
        auto&& __itr_0 = ::tpy::__iter__(__src_0);
        for (;;) {
            auto __r_1 = __itr_0.__next__();
            if (!__r_1.has_value()) break;
            std::string_view s = ::tpy::unwrap_ref(*__r_1);
            std::cout << "generator:" << " " << s << "\n" << ::tpy::check_signals;
        }
    }
}

// def section_inverse() -> None:
//     # print() and str() give the same text as repr() for bytes, bytearray and range.
//     b = b"x'y"
//     print("inverse:", b)
//     print("inverse:", str(b))
//     print("inverse:", str(bytearray(b"k")))
//     print("inverse:", range(4))
void section_inverse() {
    ::tpy::BytesView b = ::tpy::bytes_literal("x'y", 3);
    std::cout << "inverse:" << " " << ::tpy::BytesPrinter(b) << "\n" << ::tpy::check_signals;
    std::cout << "inverse:" << " " << std::string(::tpy::__str__(b)) << "\n" << ::tpy::check_signals;
    std::cout << "inverse:" << " " << std::string(::tpy::__str__(::tpy::ByteArray(::tpy::bytes_literal("k", 1)))) << "\n" << ::tpy::check_signals;
    std::cout << "inverse:" << " " << ::tpy::Range<int32_t>(4) << "\n" << ::tpy::check_signals;
}

// def main() -> None:
//     section_bytes()
//     section_bytearray()
//     section_bytesview()
//     section_fstring()
//     section_container()
//     section_range()
//     section_str_range()
//     section_small_range()
//     section_method()
//     section_generator()
//     section_inverse()
void main() {
    ::tpyapp::main::section_bytes();
    ::tpyapp::main::section_bytearray();
    ::tpyapp::main::section_bytesview();
    ::tpyapp::main::section_fstring();
    ::tpyapp::main::section_container();
    ::tpyapp::main::section_range();
    ::tpyapp::main::section_str_range();
    ::tpyapp::main::section_small_range();
    ::tpyapp::main::section_method();
    ::tpyapp::main::section_generator();
    ::tpyapp::main::section_inverse();
}

// main()
void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    ::tpyapp::main::main();
}

} // namespace tpyapp::main

int __tpy_main(int argc, char* argv[]) {
    ::tpy::init_sys_argv(argc, argv);
    ::tpyapp::main::__tpy_init();
    return 0;
}

int main(int argc, char* argv[]) {
    return ::tpy::run_main(argc, argv, &__tpy_main);
}
