// Generated by TurboPython Compiler
#include "c.hpp"

namespace tpyapp::c {

// LIMIT: int32 = 99
int32_t LIMIT{};

void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    // LIMIT: int32 = 99
    LIMIT = 99;
}

} // namespace tpyapp::c
