// Generated by TurboPython Compiler
#pragma once

#include <tpy/tpy.hpp>
#include "tpystd/tpy/_types.hpp"
#include "tpystd/typing/_typing.hpp"

namespace tpyapp::main {

struct A;
struct B;
struct Holder;

inline constexpr std::string_view __name__ = "__main__";

// def main() -> None:
void main();

// # Regression: a union-typed field initialized in __init__ from a bare
// # alternative value (`A(1)`, not a pointer-variant) must NOT be wrapped
// # with `to_value_variant` -- that helper expects a `std::variant<T*...>`
// # source, and bare alternatives construct the value-variant directly.
// class A:
struct A {
    // a: int
    ::tpy::BigInt a;

    // def __init__(self, a: int) -> None:
    A() = default;
    explicit A(const ::tpy::BigInt& a);
    static constexpr std::string_view __tpy_class_name__ = "__main__.A";
};

inline std::ostream& operator<<(std::ostream& os, const A& obj) {
    ::tpy::print_object_default(os, "A", obj);
    return os;
}

// class B:
struct B {
    // b: int
    ::tpy::BigInt b;

    // def __init__(self, b: int) -> None:
    B() = default;
    explicit B(const ::tpy::BigInt& b);
    static constexpr std::string_view __tpy_class_name__ = "__main__.B";
};

inline std::ostream& operator<<(std::ostream& os, const B& obj) {
    ::tpy::print_object_default(os, "B", obj);
    return os;
}

// class Holder:
struct Holder {
    // slot: A | B | None
    ::tpy::Union<std::monostate, A, B> slot;

    // def __init__(self) -> None:
    Holder();
    static constexpr std::string_view __tpy_class_name__ = "__main__.Holder";
};

inline std::ostream& operator<<(std::ostream& os, const Holder& obj) {
    ::tpy::print_object_default(os, "Holder", obj);
    return os;
}


// def __init__(self, a: int) -> None:
//     self.a = a
inline A::A(const ::tpy::BigInt& a) : a(a) {}

// def __init__(self, b: int) -> None:
//     self.b = b
inline B::B(const ::tpy::BigInt& b) : b(b) {}

// def __init__(self) -> None:
//     self.slot = A(1)
inline Holder::Holder() : slot(A(::tpy::BigInt(1))) {}
void __tpy_init();
} // namespace tpyapp::main
