/**
 * TurboPython Runtime - Type Traits
 *
 * Compile-time type classification for value vs reference semantics.
 */

#pragma once

#include <array>
#include <cstdint>
#include <memory>
#include <optional>
#include <span>
#include <string>
#include <string_view>
#include <tuple>
#include <type_traits>
#include <utility>
#include <variant>
#include <vector>

namespace tpy {

// Forward declaration for BigInt specialization
class BigInt;

// --- Type trait for value vs reference semantics ---

/**
 * is_value_type - Type trait for determining copy vs reference semantics.
 *
 * Value types (primitives) are returned by copy when accessed from containers.
 * Object types (records, nested containers) are returned by reference.
 */
// Enums are decided by kind, not one specialization per enum: every TPy enum
// (and every @native enum binding a C/C++ one) is a value type in
// `tpyc/type_def_registry.py`, and no TPy reference type renders as a C++ enum.
template<typename T> struct is_value_type : std::bool_constant<std::is_enum_v<T>> {};

// const-qualified types share their unqualified value-ness, so a readonly
// `*args` param lowered to `varargs<const T>` selects the same specialization
// (value vs dual-mode) as the mutable `varargs<T>`.
template<typename T> struct is_value_type<const T> : is_value_type<T> {};

// The value-type rows below are the ones whose type has no defining header of
// ours: the std:: and builtin types, plus val_or_ref, defined here. A TPy
// runtime type declares its own value-ness -- and the Send / Sync overrides
// that go with it -- next to its definition: span_iter.hpp, slice.hpp,
// range.hpp, varargs.hpp, dict_ops.hpp. (The is_send / is_sync rows for
// ordered_map / ordered_set are still here behind forward declarations; they
// are reference types, so they have no value-type row to travel with.)

// Primitive value types
template<> struct is_value_type<int8_t> : std::true_type {};
template<> struct is_value_type<int16_t> : std::true_type {};
template<> struct is_value_type<int32_t> : std::true_type {};
template<> struct is_value_type<int64_t> : std::true_type {};
template<> struct is_value_type<uint8_t> : std::true_type {};
template<> struct is_value_type<uint16_t> : std::true_type {};
template<> struct is_value_type<uint32_t> : std::true_type {};
template<> struct is_value_type<uint64_t> : std::true_type {};
template<> struct is_value_type<bool> : std::true_type {};
template<> struct is_value_type<char> : std::true_type {};
template<> struct is_value_type<double> : std::true_type {};
template<> struct is_value_type<float> : std::true_type {};
template<> struct is_value_type<std::string> : std::true_type {};
template<> struct is_value_type<std::string_view> : std::true_type {};
template<> struct is_value_type<BigInt> : std::true_type {};
// std::monostate -- TPy NoneType at value-bearing positions (e.g. Future[None]).
// Pure unit type, trivially copyable; passes through containers and generics
// the same way primitives do.
template<> struct is_value_type<std::monostate> : std::true_type {};

// A borrowed view is copied, not aliased, at a generic slot. One row covers
// three TypeDefs -- Span[T], Span[readonly[T]] and BytesView
// (std::span<const uint8_t>). `tests/test_runtime_value_type_parity.py` holds
// every such row (here and in the defining headers) against the registry, with
// the two C++ types that cannot be decided at all.
template<typename T, std::size_t E> struct is_value_type<std::span<T, E>> : std::true_type {};

// Tuples are value types (immutable in Python, always copied/moved)
template<typename... Ts> struct is_value_type<std::tuple<Ts...>> : std::true_type {};

// val_or_ref<T> is a lightweight pointer/value wrapper, always passed by value
template<typename T> struct val_or_ref;
template<typename T> struct is_value_type<val_or_ref<T>> : std::true_type {};

template<typename T>
inline constexpr bool is_value_type_v = is_value_type<T>::value;

// C++ concept for the ValueType marker protocol
template<typename T>
concept ValueType = is_value_type_v<T>;

// C++ concept for the Copyable marker protocol. Maps to copy-constructibility,
// which is the operation a generic method like Box[T].clone() actually needs.
// std::copy_constructible would also require move-constructibility; we want
// just the copy step here, so check the trait directly. Two theoretical edge
// cases the trait admits but std::copy_constructible would reject: types with
// an `explicit`-only copy ctor (direct-init works, copy-init doesn't) and
// types that are copy-constructible but not destructible. Neither pattern is
// generated by TPy today; if @native ever introduces one, switch to the
// standard concept or add a static_assert in the requires-clause emit path.
template<typename T>
concept Copyable = std::is_copy_constructible_v<T>;

// --- Thread safety markers ---

/**
 * is_send - Type trait for thread-safe ownership transfer.
 *
 * Send types can be safely moved to another thread. All value types are Send
 * by default. Raw pointers and non-owning views are not Send.
 * Sema owns the authoritative per-type answer; codegen-emitted per-record
 * specializations mirroring it are deferred until hand-written C++ needs
 * to constrain on user records.
 */
template<typename T> struct is_send : is_value_type<T> {};

// Pointers are not Send (raw pointer, no ownership guarantee)
template<typename T> struct is_send<T*> : std::false_type {};
template<typename T> struct is_send<const T*> : std::false_type {};

// string_view is not Send (borrows from another string)
template<> struct is_send<std::string_view> : std::false_type {};

// span is not Send (non-owning view of another container's storage)
template<typename T, std::size_t E> struct is_send<std::span<T, E>> : std::false_type {};

// Containers: Send if elements are Send
template<typename T, typename A> struct is_send<std::vector<T, A>> : is_send<T> {};
template<typename T, std::size_t N> struct is_send<std::array<T, N>> : is_send<T> {};

// Forward declarations for container specializations
template<typename K, typename V> class ordered_map;
template<typename T> class ordered_set;

// ordered_map: Send if both key and value are Send
template<typename K, typename V>
struct is_send<ordered_map<K, V>>
    : std::bool_constant<is_send<K>::value && is_send<V>::value> {};

// ordered_set: Send if element is Send
template<typename T>
struct is_send<ordered_set<T>> : is_send<T> {};

template<typename T>
concept Send = is_send<T>::value;

/**
 * is_sync - Type trait for thread-safe shared access.
 *
 * Sync types can be safely referenced from multiple threads. Immutable types
 * are Sync. Mutable containers (vector, ordered_map) are not Sync.
 * Sema owns the authoritative per-type answer; see is_send above for the
 * per-record mirror status.
 */
template<typename T> struct is_sync : is_value_type<T> {};

// Mutable pointers are not Sync
template<typename T> struct is_sync<T*> : std::false_type {};
// Const pointers are Sync if the pointee is Sync
template<typename T> struct is_sync<const T*> : is_sync<T> {};

// Mutable containers are not Sync
template<typename T, typename A> struct is_sync<std::vector<T, A>> : std::false_type {};
template<typename K, typename V> struct is_sync<ordered_map<K, V>> : std::false_type {};
template<typename T> struct is_sync<ordered_set<T>> : std::false_type {};
template<typename T, std::size_t N> struct is_sync<std::array<T, N>> : is_sync<T> {};

// Mutable span is not Sync; a read-only span is Sync if the element is
template<typename T, std::size_t E> struct is_sync<std::span<T, E>> : std::false_type {};
template<typename T, std::size_t E> struct is_sync<std::span<const T, E>> : is_sync<T> {};

template<typename T>
concept Sync = is_sync<T>::value;

// Dispatched through impl structs so `T = void` can be specialized;
// `val_or_ref_t<void> = void` lets `def f[T] -> T` instantiate with
// T=None (the naked `std::conditional_t<..., void, void&>` form would
// substitute to ill-formed `void&`).
namespace detail {
    template<typename T> struct val_or_ref_impl       { using type = std::conditional_t<is_value_type<T>::value, T,        T&>; };
    template<typename T> struct val_or_cref_impl      { using type = std::conditional_t<is_value_type<T>::value, T,        const T&>; };
    template<typename T> struct param_val_or_ref_impl { using type = std::conditional_t<is_value_type<T>::value, const T&, T&>; };

    template<> struct val_or_ref_impl<void>       { using type = void; };
    template<> struct val_or_cref_impl<void>      { using type = void; };
    template<> struct param_val_or_ref_impl<void> { using type = void; };
}

template<typename T> using val_or_ref_t       = typename detail::val_or_ref_impl<T>::type;
template<typename T> using val_or_cref_t      = typename detail::val_or_cref_impl<T>::type;
template<typename T> using param_val_or_ref_t = typename detail::param_val_or_ref_impl<T>::type;

// Tuple-element borrow form for a generic T -- the pointer sibling of
// val_or_ref_t. A reference can't be a std::tuple member and the concrete
// tuple borrow form is std::tuple<..., T*>, so generic tuple slots use a bare
// pointer for non-value Ts (value Ts stay by value). This keeps a generic
// `tuple[T, ...]` param/return ABI-compatible with concrete pointer-form
// tuples at instantiation.
namespace detail {
    template<typename T> struct val_or_ptr_impl  { using type = std::conditional_t<is_value_type<T>::value, T, T*>; };
    template<typename T> struct val_or_cptr_impl { using type = std::conditional_t<is_value_type<T>::value, T, const T*>; };
    template<> struct val_or_ptr_impl<void>  { using type = void; };
    template<> struct val_or_cptr_impl<void> { using type = void; };
}
template<typename T> using val_or_ptr_t  = typename detail::val_or_ptr_impl<T>::type;
template<typename T> using val_or_cptr_t = typename detail::val_or_cptr_impl<T>::type;

// The `T | None` PARAMETER form for a generic T -- the nullable sibling of
// param_val_or_ref_t. A value T takes std::optional<T> by value, which is what
// the monomorphic twin (`def f(v: Int32 | None)`) already takes, so a caller
// passes the value straight through instead of materializing a temp to point
// at. A reference T stays a pointer, so a mutation inside the body is visible
// to the caller (std::optional<T> would copy it). Return position is NOT this
// form: a `T*` return can alias a field, an optional cannot.
namespace detail {
    template<typename T> struct opt_param_impl  { using type = std::conditional_t<is_value_type<T>::value, std::optional<T>, T*>; };
    template<typename T> struct opt_cparam_impl { using type = std::conditional_t<is_value_type<T>::value, std::optional<T>, const T*>; };
}
template<typename T> using opt_param_t  = typename detail::opt_param_impl<T>::type;
template<typename T> using opt_cparam_t = typename detail::opt_cparam_impl<T>::type;

// Read a generic `T | None` slot: `x is not None` is has_value() on the
// optional form and a null test on the pointer form. Spelled once here so a
// generic body's null test is form-neutral. (Dereferencing needs no helper --
// `*x` reads both forms.)
template<typename T>
constexpr bool opt_has_value(const T& x) {
    if constexpr (std::is_pointer_v<T>) {
        return x != nullptr;
    } else {
        return x.has_value();
    }
}

// Lift a generic `T | None` slot into its storage form (std::optional<T>, the
// field/container shape): the optional form already IS the storage form; the
// pointer form copies the pointee, nullptr becoming an empty optional. Dest is
// explicit for the same reason to_val_or_ptr's is -- the source alone does not
// name the slot.
template<typename Dest, typename Src>
Dest to_opt_storage(const Src& s) {
    if constexpr (std::is_pointer_v<Src>) {
        if (s != nullptr) return Dest(*s);
        return Dest{};
    } else {
        return s;
    }
}

// to_opt_storage's move sibling: the caller has given up the pointee (or the
// optional), so the payload relocates instead of being copied. No program
// reaches it yet -- every owning-move source into a generic `T | None` field
// rejects further up (an `Own[T]` parameter at `assign.field_write_shape`, a
// rebound local at `method.arg_shape`) -- but the emit picks between the two
// on the move flag, so a copy here would be silent the day one lands.
template<typename Dest, typename Src>
Dest to_opt_storage_move(Src&& s) {
    using SrcD = std::remove_cvref_t<Src>;
    if constexpr (std::is_pointer_v<SrcD>) {
        if (s != nullptr) return Dest(std::move(*s));
        return Dest{};
    } else {
        return Dest(std::forward<Src>(s));
    }
}

// Read a generic tuple slot (val_or_ptr_t<T>) as a usable value/reference:
// deref the non-value pointer case, pass value slots through. Constrained to
// lvalues (and pointers, whose deref outlives the call regardless of the
// pointer's own value category): a value-type rvalue would have its T&&
// forwarded out of the call -- a dangling reference to the dead parameter.
template<typename T>
    requires (std::is_lvalue_reference_v<T>
              || std::is_pointer_v<std::remove_cvref_t<T>>)
decltype(auto) tuple_elem_ref(T&& x) {
    using D = std::remove_cvref_t<T>;
    if constexpr (std::is_pointer_v<D>) {
        return (*x);
    } else {
        return std::forward<T>(x);
    }
}

// Build a generic slot value (tuple element or async return payload), with
// the slot type given explicitly (Dest = val_or_ptr_t<T>): borrow into a
// pointer slot by address (pass already-pointer sources through), construct/
// copy/move into a value slot. Dest must be explicit -- the source alone
// can't distinguish a `T = val_or_ref<U>` instantiation (value slot
// constructed from U&) from a plain non-value `T = U` (pointer slot taking
// &x). Forwarding reference: a source whose render is an lvalue at an
// object-typed instantiation (a borrow-returning call) may be a prvalue at a
// value-typed one, where the value slot absorbs it; sema's borrow gating
// makes a temporary at a pointer slot unreachable -- the static_assert
// documents that invariant.
template<typename Dest, typename T>
Dest to_val_or_ptr(T&& x) {
    if constexpr (std::is_pointer_v<Dest>) {
        if constexpr (std::is_pointer_v<std::remove_cvref_t<T>>) {
            return x;
        } else {
            static_assert(std::is_lvalue_reference_v<T>,
                          "borrow slot cannot take a temporary");
            return &x;
        }
    } else {
        return std::forward<T>(x);
    }
}

/**
 * is_dyn_protocol_base<T> -- true iff T is a TPy @dynamic protocol abstract
 * base. Codegen emits a specialization next to each @dynamic protocol class;
 * default-false primary tolerates incomplete T (recursive type aliases).
 */
template<typename T> struct is_dyn_protocol_base : std::false_type {};

template<typename T>
inline constexpr bool is_dyn_protocol_base_v = is_dyn_protocol_base<T>::value;

/**
 * own_param_t<T> -- C++ parameter shape for a TPy Own[T] slot, picking per T
 * at template instantiation: unique_ptr<T> for abstract @dynamic bases,
 * T&& otherwise. Lazy via alias, so one template body handles all T.
 */
template<typename T>
using own_param_t = std::conditional_t<
    is_dyn_protocol_base_v<T>,
    std::unique_ptr<T>,
    T&&
>;

/**
 * own_return_t<T> -- C++ return shape for a TPy Own[T] result.
 *
 * Companion to own_param_t. The param shape uses T&& for concrete T
 * (rvalue ref to a caller-owned object), but T&& can't be a return type
 * without dangling -- callees can't return a reference to their local.
 * own_return_t is the by-value return shape: T for concrete (move),
 * unique_ptr<T> for abstract @dynamic bases (ownership handle).
 */
template<typename T>
using own_return_t = std::conditional_t<
    is_dyn_protocol_base_v<T>,
    std::unique_ptr<T>,
    T
>;

/**
 * await_arg_capture_t<X> -- the type a forwarding-ref factory `f(T&& a)`
 * would deduce for `T` from an argument expression whose `decltype((arg))`
 * is X. Used to spell the sub-future field type of an inline await of a
 * coroutine with a static-protocol param, so the field type matches the
 * factory's deduction and the in-place `emplace(arg)` binds: an lvalue arg
 * (X = U&) is captured by reference (borrow); an rvalue (X = U or U&&) by
 * value (own the moved-in operand). Pass `decltype((arg))` -- the double
 * parens carry the value category.
 */
template<typename X>
using await_arg_capture_t = std::conditional_t<
    std::is_lvalue_reference_v<X>,
    X,
    std::remove_reference_t<X>
>;

/**
 * val_or_ref<T> - Wrapper for iterator __next__() returns.
 *
 * Stores value types (int, str, tuple, ...) by value, non-value types
 * (records, containers) by pointer. This lets __next__() return element
 * references through std::expected (which cannot hold T&).
 *
 * T may be const-qualified (e.g. from a const_iterator). val_or_ref<const T>
 * stores const T* and get() returns const T&.
 */
template<typename T>
struct val_or_ref {
    using is_val_or_ref_tag = void;
    static constexpr bool is_val = is_value_type<std::remove_const_t<T>>::value;
    using storage_t = std::conditional_t<is_val, std::remove_const_t<T>, T*>;
    storage_t data_;

    val_or_ref(const std::remove_const_t<T>& v) requires (is_val) : data_(v) {}
    val_or_ref(T& ref) requires (!is_val) : data_(&ref) {}
    // Borrow-pointer sources (tuple borrow slots are `T*`): same non-null
    // borrow contract as the T& ctor.
    val_or_ref(T* ptr) requires (!is_val) : data_(ptr) {}

    decltype(auto) get() const {
        // (data_): return a reference to the stored copy, never a prvalue --
        // callers bind views (string_view/span) to the result, which would
        // dangle at end of statement if a temporary were returned.
        if constexpr (is_val) return (data_);
        else return (*data_);
    }
};

} // namespace tpy
