// Generated by TurboPython Compiler
#include "main.hpp"

namespace tpyapp::main {


// def make_mixed(b: Box) -> tuple[Own[Box], Box]:
std::tuple<Box, Box*> make_mixed(Box& b) {
    // return (Box(1), b)
    return std::tuple<Box, Box*>{Box(1), &(b)};
}

// def realias(h: Holder, b: Box) -> None:
void realias(Holder& h, Box& b) {
    // p = make_mixed(b)
    std::tuple<Box, Box*> p = make_mixed(b);
    // p = h.pair  # tpyc: warning(/copies tuple\[Box, Box\] into owned storage/)
    p = ::tpy::tuple_to_pointer<std::tuple<Box, Box*>>(h.pair);
    // p[0].val = 55
    std::get<0>(p).val = 55;
    // p[1].val = 66
    std::get<1>(p)->val = 66;
}

// def main() -> None:
void main() {
    // b = Box(7)
    Box b = Box(7);
    // h = Holder(b)
    Holder h = Holder(b);
    // realias(h, b)
    realias(h, b);
    // # CPython prints 55 66; element 0 was copied into the local's owned slot.
    // print("elem0:", h.pair[0].val)
    std::cout << "elem0:" << " " << std::get<0>(h.pair).val << "\n";
    // print("elem1:", h.pair[1].val)
    std::cout << "elem1:" << " " << std::get<1>(h.pair).val << "\n";
}

void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    // main()
    main();
}

} // namespace tpyapp::main

int __tpy_main(int argc, char* argv[]) {
    ::tpy::init_sys_argv(argc, argv);
    ::tpyapp::main::__tpy_init();
    return 0;
}

int main(int argc, char* argv[]) {
    ::tpy::process_startup();
    return __tpy_main(argc, argv);
}
