// Generated by TurboPython Compiler
#pragma once

#include <tpy/tpy.hpp>
#include "tpystd/tpy/_types.hpp"
#include "tpystd/typing/_typing.hpp"

namespace tpyapp::main {

struct Slot;
struct Res;

inline constexpr std::string_view __name__ = "__main__";

void in_branch(bool flag);
void in_loop();
void main();

// class Slot:
struct Slot {
    // v: Int32
    int32_t v;

    // def __init__(self, v: Int32) -> None:
    Slot() = default;
    explicit Slot(int32_t v);
    static constexpr std::string_view __tpy_class_name__ = "__main__.Slot";
};

inline std::ostream& operator<<(std::ostream& os, const Slot& obj) {
    ::tpy::print_object_default(os, "Slot", obj);
    return os;
}

// class Res:
struct Res {
    // s: Slot
    Slot s;

    // def __init__(self, v: Int32) -> None:
    Res() = default;
    explicit Res(int32_t v);

    // def __enter__(self) -> Slot:
    Slot& __enter__();

    // def __exit__(self, et, ev, tb) -> None:
    void __exit__(std::monostate et, const ::tpy::BaseException* ev, std::monostate tb) const;
    static constexpr std::string_view __tpy_class_name__ = "__main__.Res";
};

inline std::ostream& operator<<(std::ostream& os, const Res& obj) {
    ::tpy::print_object_default(os, "Res", obj);
    return os;
}


// def __init__(self, v: Int32) -> None:
inline Slot::Slot(int32_t v) : v(v) {}

// def __init__(self, v: Int32) -> None:
inline Res::Res(int32_t v) : s(Slot(v)) {}

// def __enter__(self) -> Slot:
inline Slot& Res::__enter__() {
    // return self.s
    return this->s;
}

// def __exit__(self, et, ev, tb) -> None:
inline void Res::__exit__(std::monostate et, const ::tpy::BaseException* ev, std::monostate tb) const {
    // print("exit", self.s.v)
    std::cout << "exit" << " " << this->s.v << "\n";
}
void __tpy_init();
} // namespace tpyapp::main
