// Generated by TurboPython Compiler
#include "main.hpp"

namespace tpyapp::main {



// @extern_c
// def greet(name: str) -> None:
extern "C" void greet(const char* name) {
    // puts(name)
    puts(name);
}

void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    // from tpy.extern import native_c, extern_c
}

} // namespace tpyapp::main

int main(int argc, char* argv[]) {
    ::tpy::init_sys_argv(argc, argv);
    tpyapp::main::__tpy_init();
    return 0;
}
