// Generated by TurboPython Compiler
#pragma once

#include <tpy/tpy.hpp>
#include "tpystd/tpy/_types.hpp"
#include "tpystd/typing/_typing.hpp"

namespace tpyapp::main {

template<typename T> struct Container;
template<typename T, typename U> struct Pair;

inline constexpr std::string_view __name__ = "__main__";

// def consume(c: Container[int32]) -> None:
void consume(Container<int32_t>& c);
// def make_container() -> Own[Container[int64]]:
Container<int64_t> make_container();
// def setup_pair(p: Pair[int32, int64]) -> None:
void setup_pair(Pair<int32_t, int64_t>& p);
// def main() -> None:
void main();

// class Container[T]:
template<typename T>
struct Container {
    // val: T
    T val;

    // def __init__(self) -> None:
    //     pass
    Container() {
    }

    // def set(self, val: T) -> None:
    //     self.val = val
    void set(::tpy::param_val_or_ref_t<T> val) {
        this->val = ::tpy::param_to_storage<T>(val);
    }

    // def get(self) -> T:
    //     return self.val
    ::tpy::val_or_ref_t<T> get() {
        return this->val;
    }
    static constexpr std::string_view __tpy_class_name__ = "__main__.Container";
};

template<typename T>
inline std::ostream& operator<<(std::ostream& os, const Container<T>& obj) {
    ::tpy::print_object_default(os, "Container", obj);
    return os;
}

// class Pair[T, U]:
template<typename T, typename U>
struct Pair {
    // a: T
    T a;
    // b: U
    U b;

    // def __init__(self) -> None:
    //     pass
    Pair() {
    }

    // def get_a(self) -> T:
    //     return self.a
    ::tpy::val_or_ref_t<T> get_a() {
        return this->a;
    }

    // def get_b(self) -> U:
    //     return self.b
    ::tpy::val_or_ref_t<U> get_b() {
        return this->b;
    }
    static constexpr std::string_view __tpy_class_name__ = "__main__.Pair";
};

template<typename T, typename U>
inline std::ostream& operator<<(std::ostream& os, const Pair<T, U>& obj) {
    ::tpy::print_object_default(os, "Pair", obj);
    return os;
}

void __tpy_init();
} // namespace tpyapp::main
