// Generated by TurboPython Compiler
#pragma once

#include "main.hpp"

namespace tpyapp::main {

// def gen() -> Iterator[int]:
//     f: Callable[[str], int] = int  # tpyc: ok
//     yield f("7")                               # -> S_RESUME_0
inline std::expected<::tpy::BigInt, ::tpy::StopIteration> __gen_gen::__next__() {
    while (true) switch (__state) {
    case S_INITIAL: {  // entry
        __state = S_DONE;  // until a yield sets where to resume
        f = [](std::string_view __tpy_fa0) -> ::tpy::BigInt { return ::tpy::BigInt::from_str(__tpy_fa0); };
        __state = S_RESUME_0;
        return f("7");
    }
    case S_RESUME_0: {  // after: yield f("7")
        __state = S_DONE;
        return ::tpy::make_unexpected(::tpy::StopIteration{});
    }
    case S_DONE: return ::tpy::make_unexpected(::tpy::StopIteration{});
    }
    __builtin_unreachable();
}

} // namespace tpyapp::main
