# tpy: native_module
# tpy: cpp_namespace("tpystd::tpy")
from typing import overload, Protocol, Iterator, Iterable, Self, Sized
from tpy import (
    UInt64, Int32, Own, Span, Ptr, readonly, pure, nocopy,
    Float32, Int8, Int16, Int64, UInt8, UInt16, UInt32,
    Char, String, StrView,
)
from tpy.extern import native, cpp_template, builtin_type, value_ptr_coercion


# --- Structural protocols (concept generated from method signatures) ---

class Truthy(Protocol):
    @readonly
    def __bool__(self) -> bool: ...


class Stringable(Protocol):
    @readonly
    def __str__(self) -> str: ...


class Representable(Protocol):
    @readonly
    def __repr__(self) -> str: ...


class Hashable(Protocol):
    @readonly
    def __hash__(self) -> UInt64: ...


class Comparable(Protocol):
    @readonly
    def __lt__(self, other: Self) -> bool: ...


class Equatable(Protocol):
    @readonly
    def __eq__(self, other: Self) -> bool: ...


class Deref[T](Protocol):
    def __deref__(self) -> T: ...


class ReadOnlySpanLike[T](Protocol):
    @readonly
    def __span__(self) -> Span[readonly[T]]: ...


# --- Marker protocols (no methods, map to runtime C++ concepts) ---

@native("tpy::NativeIterable")
class NativeIterable[T](Protocol): ...

@native("tpy::NativeRangeConstructible")
class NativeRangeConstructible[T](Protocol): ...

@native("tpy::ValueType")
class ValueType(Protocol): ...

@native("tpy::Send")
class Send(Protocol): ...

@native("tpy::Sync")
class Sync(Protocol): ...

@native("std::default_initializable")
class Default(Protocol): ...

@native("tpy::Covariant")
class Covariant[T](Protocol): ...

# Fixed-width integer constraints (for generic functions over Int8..UInt64)
@native("tpy::AnyFixedInt")
class AnyFixedInt(Protocol): ...

@native("tpy::AnyFixedSigned")
class AnyFixedSigned(Protocol): ...

@native("tpy::AnyFixedUnsigned")
class AnyFixedUnsigned(Protocol): ...


# --- Types ---

@builtin_type("tpy.Span")
@native("std::span")
class Span[T](Iterable[T], NativeIterable[T], ReadOnlySpanLike[T]):
    @overload
    @cpp_template("{cpp}({0}, static_cast<size_t>({1}))")
    def __init__(self, ptr: Ptr[T], length: Int32) -> None: ...

    @overload
    @cpp_template("{cpp}({0})")
    def __init__(self, source: Span[T]) -> None: ...

    @native("tpy::__iter__", function=True)
    @pure
    @readonly
    def __iter__(self) -> Iterator[T]: ...

    @native("tpy::__len__", function=True)
    @pure
    @readonly
    def __len__(self) -> Int32: ...

    @cpp_template("{self}[{0}]")
    @pure
    @readonly
    def unchecked_get(self, index: Int32) -> T: ...

    @native("tpy::__getitem__", function=True)
    @pure
    @readonly
    def __getitem__(self, index: Int32) -> T: ...

    @native("tpy::__setitem__", function=True)
    def __setitem__(self, index: Int32, value: Own[T]) -> None: ...

    @native("tpy::as_span", function=True)
    @pure
    @readonly
    def __span__(self) -> Span[readonly[T]]: ...

    @cpp_template("std::stable_sort({self}.begin(), {self}.end())")
    def sort[T: Comparable](self) -> None: ...


@builtin_type("tpy.Array")
@native("std::array")
class Array[T, N: int](Iterable[T], NativeIterable[T], ReadOnlySpanLike[T]):
    @native("tpy::__iter__", function=True)
    @pure
    @readonly
    def __iter__(self) -> Iterator[T]: ...

    @native("tpy::__len__", function=True)
    @pure
    @readonly
    def __len__(self) -> Int32: ...

    @cpp_template("{self}[{0}]")
    @pure
    @readonly
    def unchecked_get(self, index: Int32) -> T: ...

    @native("tpy::__getitem__", function=True)
    @pure
    @readonly
    def __getitem__(self, index: Int32) -> T: ...

    @native("tpy::__setitem__", function=True)
    def __setitem__(self, index: Int32, value: Own[T]) -> None: ...

    @native("tpy::as_span", function=True)
    @pure
    @readonly
    def __span__(self) -> Span[readonly[T]]: ...


@builtin_type("tpy.Ptr")
@native("{T}*")
class Ptr[T](Deref[T]):
    @cpp_template("nullptr")
    def __init__(self) -> None: ...

    @cpp_template("::tpy::deref_check({self})")
    def __deref__(self) -> T: ...

    @cpp_template("std::span({self}, static_cast<size_t>({0}))")
    @readonly
    @pure
    def span(self, length: Int32) -> Span[T]: ...


@builtin_type("tpy.SpanIter")
@native("::tpy::SpanIter")
@nocopy
class SpanIter[T](NativeIterable[T], Iterable[T], Iterator[T]):
    @cpp_template("{cpp}({0})")
    def __init__(self, source: Span[T]) -> None: ...

    @cpp_template("{self}.__next__()")
    def __next__(self) -> T: ...

    @cpp_template("{self}.__iter__()")
    @readonly
    def __iter__(self) -> Self: ...


# --- Functions ---

@pure
@readonly
@native("tpy::as_span")
def span[T](x: ReadOnlySpanLike[T]) -> Span[readonly[T]]: ...

@pure
@readonly
@native("tpy::deref_check")
def deref[T](x: Deref[T]) -> T: ...

@value_ptr_coercion
@cpp_template("{0}")
def take_ptr[T](p: Ptr[T]) -> Ptr[T]: ...

@cpp_template("{T}{{}}")
def make_default[T: Default]() -> Own[T]: ...


# --- Primitive type stubs (methods for builtin types) ---

@builtin_type("tpy.Float32")
@native("float")
class Float32(Comparable, Equatable):
    # Constructors
    @overload
    @cpp_template("0.0f")
    def __init__(self) -> None: ...
    @overload
    @cpp_template("{0}")
    def __init__(self, x: Float32) -> None: ...
    @overload
    @cpp_template("static_cast<float>({0})")
    def __init__(self, x: float) -> None: ...
    @overload
    @cpp_template("static_cast<float>({0})")
    def __init__(self, x: int) -> None: ...
    @overload
    @cpp_template("static_cast<float>({0})")
    def __init__(self, x: bool) -> None: ...
    @overload
    @cpp_template("::tpy::float32_from_str({0})")
    def __init__(self, x: str) -> None: ...
    @overload
    @cpp_template("static_cast<float>({0})")
    def __init__(self, x: Int8) -> None: ...
    @overload
    @cpp_template("static_cast<float>({0})")
    def __init__(self, x: Int16) -> None: ...
    @overload
    @cpp_template("static_cast<float>({0})")
    def __init__(self, x: Int32) -> None: ...
    @overload
    @cpp_template("static_cast<float>({0})")
    def __init__(self, x: Int64) -> None: ...
    @overload
    @cpp_template("static_cast<float>({0})")
    def __init__(self, x: UInt8) -> None: ...
    @overload
    @cpp_template("static_cast<float>({0})")
    def __init__(self, x: UInt16) -> None: ...
    @overload
    @cpp_template("static_cast<float>({0})")
    def __init__(self, x: UInt32) -> None: ...
    @overload
    @cpp_template("static_cast<float>({0})")
    def __init__(self, x: UInt64) -> None: ...

    # Binary operators: Float32 op T -> result
    @overload
    @cpp_template("({self}) + ({0})")
    def __add__(self, other: Float32) -> Float32: ...
    @overload
    @cpp_template("static_cast<double>({self}) + ({0})")
    def __add__(self, other: float) -> float: ...
    @overload
    @cpp_template("({self}) + static_cast<float>({0})")
    def __add__(self, other: int) -> Float32: ...
    @overload
    @cpp_template("({self}) + static_cast<float>({0})")
    def __add__(self, other: Int32) -> Float32: ...

    @overload
    @cpp_template("({self}) - ({0})")
    def __sub__(self, other: Float32) -> Float32: ...
    @overload
    @cpp_template("static_cast<double>({self}) - ({0})")
    def __sub__(self, other: float) -> float: ...
    @overload
    @cpp_template("({self}) - static_cast<float>({0})")
    def __sub__(self, other: int) -> Float32: ...
    @overload
    @cpp_template("({self}) - static_cast<float>({0})")
    def __sub__(self, other: Int32) -> Float32: ...

    @overload
    @cpp_template("({self}) * ({0})")
    def __mul__(self, other: Float32) -> Float32: ...
    @overload
    @cpp_template("static_cast<double>({self}) * ({0})")
    def __mul__(self, other: float) -> float: ...
    @overload
    @cpp_template("({self}) * static_cast<float>({0})")
    def __mul__(self, other: int) -> Float32: ...
    @overload
    @cpp_template("({self}) * static_cast<float>({0})")
    def __mul__(self, other: Int32) -> Float32: ...

    @overload
    @cpp_template("::tpy::truediv_f32({self}, {0})")
    def __truediv__(self, other: Float32) -> Float32: ...
    @overload
    @cpp_template("::tpy::truediv(static_cast<double>({self}), {0})")
    def __truediv__(self, other: float) -> float: ...
    @overload
    @cpp_template("::tpy::truediv_f32({self}, static_cast<float>({0}))")
    def __truediv__(self, other: int) -> Float32: ...
    @overload
    @cpp_template("::tpy::truediv_f32({self}, static_cast<float>({0}))")
    def __truediv__(self, other: Int32) -> Float32: ...

    @overload
    @cpp_template("::tpy::floordiv_f32({self}, {0})")
    def __floordiv__(self, other: Float32) -> Float32: ...
    @overload
    @cpp_template("::tpy::floordiv(static_cast<double>({self}), {0})")
    def __floordiv__(self, other: float) -> float: ...
    @overload
    @cpp_template("::tpy::floordiv_f32({self}, static_cast<float>({0}))")
    def __floordiv__(self, other: int) -> Float32: ...
    @overload
    @cpp_template("::tpy::floordiv_f32({self}, static_cast<float>({0}))")
    def __floordiv__(self, other: Int32) -> Float32: ...

    @overload
    @cpp_template("::tpy::fmod_f32({self}, {0})")
    def __mod__(self, other: Float32) -> Float32: ...
    @overload
    @cpp_template("::tpy::fmod(static_cast<double>({self}), {0})")
    def __mod__(self, other: float) -> float: ...
    @overload
    @cpp_template("::tpy::fmod_f32({self}, static_cast<float>({0}))")
    def __mod__(self, other: int) -> Float32: ...
    @overload
    @cpp_template("::tpy::fmod_f32({self}, static_cast<float>({0}))")
    def __mod__(self, other: Int32) -> Float32: ...

    @overload
    @cpp_template("std::pow({self}, {0})")
    def __pow__(self, other: Float32) -> Float32: ...
    @overload
    @cpp_template("std::pow(static_cast<double>({self}), {0})")
    def __pow__(self, other: float) -> float: ...
    @overload
    @cpp_template("std::pow({self}, static_cast<float>({0}))")
    def __pow__(self, other: int) -> Float32: ...
    @overload
    @cpp_template("std::pow({self}, static_cast<float>({0}))")
    def __pow__(self, other: Int32) -> Float32: ...

    # Unary operators
    @cpp_template("+({self})")
    def __pos__(self) -> Float32: ...
    @cpp_template("-({self})")
    def __neg__(self) -> Float32: ...

    # Reverse operators: T op Float32 -> result
    @overload
    @cpp_template("({0}) + ({self})")
    def __radd__(self, other: Float32) -> Float32: ...
    @overload
    @cpp_template("({0}) + static_cast<double>({self})")
    def __radd__(self, other: float) -> float: ...
    @overload
    @cpp_template("static_cast<float>({0}) + ({self})")
    def __radd__(self, other: int) -> Float32: ...
    @overload
    @cpp_template("static_cast<float>({0}) + ({self})")
    def __radd__(self, other: Int32) -> Float32: ...

    @overload
    @cpp_template("({0}) - ({self})")
    def __rsub__(self, other: Float32) -> Float32: ...
    @overload
    @cpp_template("({0}) - static_cast<double>({self})")
    def __rsub__(self, other: float) -> float: ...
    @overload
    @cpp_template("static_cast<float>({0}) - ({self})")
    def __rsub__(self, other: int) -> Float32: ...
    @overload
    @cpp_template("static_cast<float>({0}) - ({self})")
    def __rsub__(self, other: Int32) -> Float32: ...

    @overload
    @cpp_template("({0}) * ({self})")
    def __rmul__(self, other: Float32) -> Float32: ...
    @overload
    @cpp_template("({0}) * static_cast<double>({self})")
    def __rmul__(self, other: float) -> float: ...
    @overload
    @cpp_template("static_cast<float>({0}) * ({self})")
    def __rmul__(self, other: int) -> Float32: ...
    @overload
    @cpp_template("static_cast<float>({0}) * ({self})")
    def __rmul__(self, other: Int32) -> Float32: ...

    @overload
    @cpp_template("::tpy::truediv_f32({0}, {self})")
    def __rtruediv__(self, other: Float32) -> Float32: ...
    @overload
    @cpp_template("::tpy::truediv({0}, static_cast<double>({self}))")
    def __rtruediv__(self, other: float) -> float: ...
    @overload
    @cpp_template("::tpy::truediv_f32(static_cast<float>({0}), {self})")
    def __rtruediv__(self, other: int) -> Float32: ...
    @overload
    @cpp_template("::tpy::truediv_f32(static_cast<float>({0}), {self})")
    def __rtruediv__(self, other: Int32) -> Float32: ...

    @overload
    @cpp_template("::tpy::floordiv_f32({0}, {self})")
    def __rfloordiv__(self, other: Float32) -> Float32: ...
    @overload
    @cpp_template("::tpy::floordiv({0}, static_cast<double>({self}))")
    def __rfloordiv__(self, other: float) -> float: ...
    @overload
    @cpp_template("::tpy::floordiv_f32(static_cast<float>({0}), {self})")
    def __rfloordiv__(self, other: int) -> Float32: ...
    @overload
    @cpp_template("::tpy::floordiv_f32(static_cast<float>({0}), {self})")
    def __rfloordiv__(self, other: Int32) -> Float32: ...

    @overload
    @cpp_template("::tpy::fmod_f32({0}, {self})")
    def __rmod__(self, other: Float32) -> Float32: ...
    @overload
    @cpp_template("::tpy::fmod({0}, static_cast<double>({self}))")
    def __rmod__(self, other: float) -> float: ...
    @overload
    @cpp_template("::tpy::fmod_f32(static_cast<float>({0}), {self})")
    def __rmod__(self, other: int) -> Float32: ...
    @overload
    @cpp_template("::tpy::fmod_f32(static_cast<float>({0}), {self})")
    def __rmod__(self, other: Int32) -> Float32: ...

    @overload
    @cpp_template("std::pow({0}, {self})")
    def __rpow__(self, other: Float32) -> Float32: ...
    @overload
    @cpp_template("std::pow({0}, static_cast<double>({self}))")
    def __rpow__(self, other: float) -> float: ...
    @overload
    @cpp_template("std::pow(static_cast<float>({0}), {self})")
    def __rpow__(self, other: int) -> Float32: ...
    @overload
    @cpp_template("std::pow(static_cast<float>({0}), {self})")
    def __rpow__(self, other: Int32) -> Float32: ...

    # Comparison and hashing
    @cpp_template("::tpy::__hash__({self})")
    @readonly
    @pure
    def __hash__(self) -> UInt64: ...

    @cpp_template("{self} == {0}")
    @readonly
    @pure
    def __eq__(self, other: Float32) -> bool: ...

    @cpp_template("{self} < {0}")
    @readonly
    @pure
    def __lt__(self, other: Float32) -> bool: ...


@builtin_type("tpy.Int8")
@native("int8_t")
class Int8(Comparable, Equatable, AnyFixedInt, AnyFixedSigned):
    @overload
    @cpp_template("0")
    def __init__(self) -> None: ...
    @overload
    @cpp_template("{0}")
    def __init__(self, x: Int8) -> None: ...
    @overload
    @cpp_template("::tpy::int_cast_check<{cpp}>({0})")
    def __init__[T: AnyFixedInt](self, x: T) -> None: ...
    @overload
    @cpp_template("({0}).to_fixed_check<{cpp}>()")
    def __init__(self, x: int) -> None: ...
    @overload
    @cpp_template("::tpy::from_float_check<{cpp}>({0})")
    def __init__(self, x: float) -> None: ...
    @overload
    @cpp_template("::tpy::from_float_check<{cpp}>(static_cast<double>({0}))")
    def __init__(self, x: Float32) -> None: ...
    @overload
    @cpp_template("::tpy::from_str_check<{cpp}>({0})")
    def __init__(self, x: str) -> None: ...
    @overload
    @cpp_template("static_cast<{cpp}>({0})")
    def __init__(self, x: bool) -> None: ...
    @overload
    @staticmethod
    @cpp_template("static_cast<int8_t>({0})")
    def trunc[T: AnyFixedInt](x: T) -> Int8: ...
    @overload
    @staticmethod
    @cpp_template("({0}).to_fixed_trunc<int8_t>()")
    def trunc(x: int) -> Int8: ...
    @cpp_template("::tpy::BigInt({self})")
    def __int__(self) -> int: ...
    @cpp_template("::tpy::add_check<int8_t>({self}, {0})")
    def __add__(self, other: Int8) -> Int8: ...
    @cpp_template("::tpy::sub_check<int8_t>({self}, {0})")
    def __sub__(self, other: Int8) -> Int8: ...
    @cpp_template("::tpy::mul_check<int8_t>({self}, {0})")
    def __mul__(self, other: Int8) -> Int8: ...
    @cpp_template("::tpy::truediv(static_cast<double>({self}), static_cast<double>({0}))")
    def __truediv__(self, other: Int8) -> float: ...
    @cpp_template("::tpy::div_check<int8_t>({self}, {0})")
    def __floordiv__(self, other: Int8) -> Int8: ...
    @cpp_template("::tpy::mod_check<int8_t>({self}, {0})")
    def __mod__(self, other: Int8) -> Int8: ...
    @cpp_template("::tpy::pow_check<int8_t>({self}, {0})")
    def __pow__(self, other: Int8) -> Int8: ...
    @cpp_template("::tpy::lshift_check<int8_t>({self}, {0})")
    def __lshift__(self, other: Int8) -> Int8: ...
    @cpp_template("::tpy::rshift_check<int8_t>({self}, {0})")
    def __rshift__(self, other: Int8) -> Int8: ...
    @cpp_template("static_cast<int8_t>({self} & {0})")
    def __and__(self, other: Int8) -> Int8: ...
    @cpp_template("static_cast<int8_t>({self} | {0})")
    def __or__(self, other: Int8) -> Int8: ...
    @cpp_template("static_cast<int8_t>({self} ^ {0})")
    def __xor__(self, other: Int8) -> Int8: ...
    @cpp_template("::tpy::add_check<int8_t>({0}, {self})")
    def __radd__(self, other: Int8) -> Int8: ...
    @cpp_template("::tpy::sub_check<int8_t>({0}, {self})")
    def __rsub__(self, other: Int8) -> Int8: ...
    @cpp_template("::tpy::mul_check<int8_t>({0}, {self})")
    def __rmul__(self, other: Int8) -> Int8: ...
    @cpp_template("::tpy::truediv(static_cast<double>({0}), static_cast<double>({self}))")
    def __rtruediv__(self, other: Int8) -> float: ...
    @cpp_template("::tpy::div_check<int8_t>({0}, {self})")
    def __rfloordiv__(self, other: Int8) -> Int8: ...
    @cpp_template("::tpy::mod_check<int8_t>({0}, {self})")
    def __rmod__(self, other: Int8) -> Int8: ...
    @cpp_template("::tpy::pow_check<int8_t>({0}, {self})")
    def __rpow__(self, other: Int8) -> Int8: ...
    @cpp_template("::tpy::lshift_check<int8_t>({0}, {self})")
    def __rlshift__(self, other: Int8) -> Int8: ...
    @cpp_template("::tpy::rshift_check<int8_t>({0}, {self})")
    def __rrshift__(self, other: Int8) -> Int8: ...
    @cpp_template("static_cast<int8_t>({0} & {self})")
    def __rand__(self, other: Int8) -> Int8: ...
    @cpp_template("static_cast<int8_t>({0} | {self})")
    def __ror__(self, other: Int8) -> Int8: ...
    @cpp_template("static_cast<int8_t>({0} ^ {self})")
    def __rxor__(self, other: Int8) -> Int8: ...
    @cpp_template("static_cast<int8_t>(~({self}))")
    def __invert__(self) -> Int8: ...
    @cpp_template("+{self}")
    def __pos__(self) -> Int8: ...
    @cpp_template("::tpy::neg_check<int8_t>({self})")
    def __neg__(self) -> Int8: ...
    @cpp_template("{self} == {0}")
    @readonly
    @pure
    def __eq__(self, other: Int8) -> bool: ...
    @cpp_template("::tpy::__hash__({self})")
    @readonly
    @pure
    def __hash__(self) -> UInt64: ...
    @cpp_template("{self} < {0}")
    @readonly
    @pure
    def __lt__(self, other: Int8) -> bool: ...


@builtin_type("tpy.Int16")
@native("int16_t")
class Int16(Comparable, Equatable, AnyFixedInt, AnyFixedSigned):
    @overload
    @cpp_template("0")
    def __init__(self) -> None: ...
    @overload
    @cpp_template("{0}")
    def __init__(self, x: Int16) -> None: ...
    @overload
    @cpp_template("::tpy::int_cast_check<{cpp}>({0})")
    def __init__[T: AnyFixedInt](self, x: T) -> None: ...
    @overload
    @cpp_template("({0}).to_fixed_check<{cpp}>()")
    def __init__(self, x: int) -> None: ...
    @overload
    @cpp_template("::tpy::from_float_check<{cpp}>({0})")
    def __init__(self, x: float) -> None: ...
    @overload
    @cpp_template("::tpy::from_float_check<{cpp}>(static_cast<double>({0}))")
    def __init__(self, x: Float32) -> None: ...
    @overload
    @cpp_template("::tpy::from_str_check<{cpp}>({0})")
    def __init__(self, x: str) -> None: ...
    @overload
    @cpp_template("static_cast<{cpp}>({0})")
    def __init__(self, x: bool) -> None: ...
    @overload
    @staticmethod
    @cpp_template("static_cast<int16_t>({0})")
    def trunc[T: AnyFixedInt](x: T) -> Int16: ...
    @overload
    @staticmethod
    @cpp_template("({0}).to_fixed_trunc<int16_t>()")
    def trunc(x: int) -> Int16: ...
    @cpp_template("::tpy::BigInt({self})")
    def __int__(self) -> int: ...
    @cpp_template("::tpy::add_check<int16_t>({self}, {0})")
    def __add__(self, other: Int16) -> Int16: ...
    @cpp_template("::tpy::sub_check<int16_t>({self}, {0})")
    def __sub__(self, other: Int16) -> Int16: ...
    @cpp_template("::tpy::mul_check<int16_t>({self}, {0})")
    def __mul__(self, other: Int16) -> Int16: ...
    @cpp_template("::tpy::truediv(static_cast<double>({self}), static_cast<double>({0}))")
    def __truediv__(self, other: Int16) -> float: ...
    @cpp_template("::tpy::div_check<int16_t>({self}, {0})")
    def __floordiv__(self, other: Int16) -> Int16: ...
    @cpp_template("::tpy::mod_check<int16_t>({self}, {0})")
    def __mod__(self, other: Int16) -> Int16: ...
    @cpp_template("::tpy::pow_check<int16_t>({self}, {0})")
    def __pow__(self, other: Int16) -> Int16: ...
    @cpp_template("::tpy::lshift_check<int16_t>({self}, {0})")
    def __lshift__(self, other: Int16) -> Int16: ...
    @cpp_template("::tpy::rshift_check<int16_t>({self}, {0})")
    def __rshift__(self, other: Int16) -> Int16: ...
    @cpp_template("static_cast<int16_t>({self} & {0})")
    def __and__(self, other: Int16) -> Int16: ...
    @cpp_template("static_cast<int16_t>({self} | {0})")
    def __or__(self, other: Int16) -> Int16: ...
    @cpp_template("static_cast<int16_t>({self} ^ {0})")
    def __xor__(self, other: Int16) -> Int16: ...
    @cpp_template("::tpy::add_check<int16_t>({0}, {self})")
    def __radd__(self, other: Int16) -> Int16: ...
    @cpp_template("::tpy::sub_check<int16_t>({0}, {self})")
    def __rsub__(self, other: Int16) -> Int16: ...
    @cpp_template("::tpy::mul_check<int16_t>({0}, {self})")
    def __rmul__(self, other: Int16) -> Int16: ...
    @cpp_template("::tpy::truediv(static_cast<double>({0}), static_cast<double>({self}))")
    def __rtruediv__(self, other: Int16) -> float: ...
    @cpp_template("::tpy::div_check<int16_t>({0}, {self})")
    def __rfloordiv__(self, other: Int16) -> Int16: ...
    @cpp_template("::tpy::mod_check<int16_t>({0}, {self})")
    def __rmod__(self, other: Int16) -> Int16: ...
    @cpp_template("::tpy::pow_check<int16_t>({0}, {self})")
    def __rpow__(self, other: Int16) -> Int16: ...
    @cpp_template("::tpy::lshift_check<int16_t>({0}, {self})")
    def __rlshift__(self, other: Int16) -> Int16: ...
    @cpp_template("::tpy::rshift_check<int16_t>({0}, {self})")
    def __rrshift__(self, other: Int16) -> Int16: ...
    @cpp_template("static_cast<int16_t>({0} & {self})")
    def __rand__(self, other: Int16) -> Int16: ...
    @cpp_template("static_cast<int16_t>({0} | {self})")
    def __ror__(self, other: Int16) -> Int16: ...
    @cpp_template("static_cast<int16_t>({0} ^ {self})")
    def __rxor__(self, other: Int16) -> Int16: ...
    @cpp_template("static_cast<int16_t>(~({self}))")
    def __invert__(self) -> Int16: ...
    @cpp_template("+{self}")
    def __pos__(self) -> Int16: ...
    @cpp_template("::tpy::neg_check<int16_t>({self})")
    def __neg__(self) -> Int16: ...
    @cpp_template("{self} == {0}")
    @readonly
    @pure
    def __eq__(self, other: Int16) -> bool: ...
    @cpp_template("::tpy::__hash__({self})")
    @readonly
    @pure
    def __hash__(self) -> UInt64: ...
    @cpp_template("{self} < {0}")
    @readonly
    @pure
    def __lt__(self, other: Int16) -> bool: ...


@builtin_type("tpy.Int32")
@native("int32_t")
class Int32(Comparable, Equatable, AnyFixedInt, AnyFixedSigned):
    @overload
    @cpp_template("0")
    def __init__(self) -> None: ...
    @overload
    @cpp_template("{0}")
    def __init__(self, x: Int32) -> None: ...
    @overload
    @cpp_template("::tpy::int_cast_check<{cpp}>({0})")
    def __init__[T: AnyFixedInt](self, x: T) -> None: ...
    @overload
    @cpp_template("({0}).to_fixed_check<{cpp}>()")
    def __init__(self, x: int) -> None: ...
    @overload
    @cpp_template("::tpy::from_float_check<{cpp}>({0})")
    def __init__(self, x: float) -> None: ...
    @overload
    @cpp_template("::tpy::from_float_check<{cpp}>(static_cast<double>({0}))")
    def __init__(self, x: Float32) -> None: ...
    @overload
    @cpp_template("::tpy::from_str_check<{cpp}>({0})")
    def __init__(self, x: str) -> None: ...
    @overload
    @cpp_template("static_cast<{cpp}>({0})")
    def __init__(self, x: bool) -> None: ...
    @overload
    @staticmethod
    @cpp_template("static_cast<int32_t>({0})")
    def trunc[T: AnyFixedInt](x: T) -> Int32: ...
    @overload
    @staticmethod
    @cpp_template("({0}).to_fixed_trunc<int32_t>()")
    def trunc(x: int) -> Int32: ...
    @cpp_template("::tpy::BigInt({self})")
    def __int__(self) -> int: ...
    @cpp_template("::tpy::add_check<int32_t>({self}, {0})")
    def __add__(self, other: Int32) -> Int32: ...
    @cpp_template("::tpy::sub_check<int32_t>({self}, {0})")
    def __sub__(self, other: Int32) -> Int32: ...
    @cpp_template("::tpy::mul_check<int32_t>({self}, {0})")
    def __mul__(self, other: Int32) -> Int32: ...
    @cpp_template("::tpy::truediv(static_cast<double>({self}), static_cast<double>({0}))")
    def __truediv__(self, other: Int32) -> float: ...
    @cpp_template("::tpy::div_check<int32_t>({self}, {0})")
    def __floordiv__(self, other: Int32) -> Int32: ...
    @cpp_template("::tpy::mod_check<int32_t>({self}, {0})")
    def __mod__(self, other: Int32) -> Int32: ...
    @cpp_template("::tpy::pow_check<int32_t>({self}, {0})")
    def __pow__(self, other: Int32) -> Int32: ...
    @cpp_template("::tpy::lshift_check<int32_t>({self}, {0})")
    def __lshift__(self, other: Int32) -> Int32: ...
    @cpp_template("::tpy::rshift_check<int32_t>({self}, {0})")
    def __rshift__(self, other: Int32) -> Int32: ...
    @cpp_template("static_cast<int32_t>({self} & {0})")
    def __and__(self, other: Int32) -> Int32: ...
    @cpp_template("static_cast<int32_t>({self} | {0})")
    def __or__(self, other: Int32) -> Int32: ...
    @cpp_template("static_cast<int32_t>({self} ^ {0})")
    def __xor__(self, other: Int32) -> Int32: ...
    @cpp_template("::tpy::add_check<int32_t>({0}, {self})")
    def __radd__(self, other: Int32) -> Int32: ...
    @cpp_template("::tpy::sub_check<int32_t>({0}, {self})")
    def __rsub__(self, other: Int32) -> Int32: ...
    @cpp_template("::tpy::mul_check<int32_t>({0}, {self})")
    def __rmul__(self, other: Int32) -> Int32: ...
    @cpp_template("::tpy::truediv(static_cast<double>({0}), static_cast<double>({self}))")
    def __rtruediv__(self, other: Int32) -> float: ...
    @cpp_template("::tpy::div_check<int32_t>({0}, {self})")
    def __rfloordiv__(self, other: Int32) -> Int32: ...
    @cpp_template("::tpy::mod_check<int32_t>({0}, {self})")
    def __rmod__(self, other: Int32) -> Int32: ...
    @cpp_template("::tpy::pow_check<int32_t>({0}, {self})")
    def __rpow__(self, other: Int32) -> Int32: ...
    @cpp_template("::tpy::lshift_check<int32_t>({0}, {self})")
    def __rlshift__(self, other: Int32) -> Int32: ...
    @cpp_template("::tpy::rshift_check<int32_t>({0}, {self})")
    def __rrshift__(self, other: Int32) -> Int32: ...
    @cpp_template("static_cast<int32_t>({0} & {self})")
    def __rand__(self, other: Int32) -> Int32: ...
    @cpp_template("static_cast<int32_t>({0} | {self})")
    def __ror__(self, other: Int32) -> Int32: ...
    @cpp_template("static_cast<int32_t>({0} ^ {self})")
    def __rxor__(self, other: Int32) -> Int32: ...
    @cpp_template("static_cast<int32_t>(~({self}))")
    def __invert__(self) -> Int32: ...
    @cpp_template("+{self}")
    def __pos__(self) -> Int32: ...
    @cpp_template("::tpy::neg_check<int32_t>({self})")
    def __neg__(self) -> Int32: ...
    @cpp_template("{self} == {0}")
    @readonly
    @pure
    def __eq__(self, other: Int32) -> bool: ...
    @cpp_template("::tpy::__hash__({self})")
    @readonly
    @pure
    def __hash__(self) -> UInt64: ...
    @cpp_template("{self} < {0}")
    @readonly
    @pure
    def __lt__(self, other: Int32) -> bool: ...


@builtin_type("tpy.Int64")
@native("int64_t")
class Int64(Comparable, Equatable, AnyFixedInt, AnyFixedSigned):
    @overload
    @cpp_template("0")
    def __init__(self) -> None: ...
    @overload
    @cpp_template("{0}")
    def __init__(self, x: Int64) -> None: ...
    @overload
    @cpp_template("::tpy::int_cast_check<{cpp}>({0})")
    def __init__[T: AnyFixedInt](self, x: T) -> None: ...
    @overload
    @cpp_template("({0}).to_fixed_check<{cpp}>()")
    def __init__(self, x: int) -> None: ...
    @overload
    @cpp_template("::tpy::from_float_check<{cpp}>({0})")
    def __init__(self, x: float) -> None: ...
    @overload
    @cpp_template("::tpy::from_float_check<{cpp}>(static_cast<double>({0}))")
    def __init__(self, x: Float32) -> None: ...
    @overload
    @cpp_template("::tpy::from_str_check<{cpp}>({0})")
    def __init__(self, x: str) -> None: ...
    @overload
    @cpp_template("static_cast<{cpp}>({0})")
    def __init__(self, x: bool) -> None: ...
    @overload
    @staticmethod
    @cpp_template("static_cast<int64_t>({0})")
    def trunc[T: AnyFixedInt](x: T) -> Int64: ...
    @overload
    @staticmethod
    @cpp_template("({0}).to_fixed_trunc<int64_t>()")
    def trunc(x: int) -> Int64: ...
    @cpp_template("::tpy::BigInt({self})")
    def __int__(self) -> int: ...
    @cpp_template("::tpy::add_check<int64_t>({self}, {0})")
    def __add__(self, other: Int64) -> Int64: ...
    @cpp_template("::tpy::sub_check<int64_t>({self}, {0})")
    def __sub__(self, other: Int64) -> Int64: ...
    @cpp_template("::tpy::mul_check<int64_t>({self}, {0})")
    def __mul__(self, other: Int64) -> Int64: ...
    @cpp_template("::tpy::truediv(static_cast<double>({self}), static_cast<double>({0}))")
    def __truediv__(self, other: Int64) -> float: ...
    @cpp_template("::tpy::div_check<int64_t>({self}, {0})")
    def __floordiv__(self, other: Int64) -> Int64: ...
    @cpp_template("::tpy::mod_check<int64_t>({self}, {0})")
    def __mod__(self, other: Int64) -> Int64: ...
    @cpp_template("::tpy::pow_check<int64_t>({self}, {0})")
    def __pow__(self, other: Int64) -> Int64: ...
    @cpp_template("::tpy::lshift_check<int64_t>({self}, {0})")
    def __lshift__(self, other: Int64) -> Int64: ...
    @cpp_template("::tpy::rshift_check<int64_t>({self}, {0})")
    def __rshift__(self, other: Int64) -> Int64: ...
    @cpp_template("static_cast<int64_t>({self} & {0})")
    def __and__(self, other: Int64) -> Int64: ...
    @cpp_template("static_cast<int64_t>({self} | {0})")
    def __or__(self, other: Int64) -> Int64: ...
    @cpp_template("static_cast<int64_t>({self} ^ {0})")
    def __xor__(self, other: Int64) -> Int64: ...
    @cpp_template("::tpy::add_check<int64_t>({0}, {self})")
    def __radd__(self, other: Int64) -> Int64: ...
    @cpp_template("::tpy::sub_check<int64_t>({0}, {self})")
    def __rsub__(self, other: Int64) -> Int64: ...
    @cpp_template("::tpy::mul_check<int64_t>({0}, {self})")
    def __rmul__(self, other: Int64) -> Int64: ...
    @cpp_template("::tpy::truediv(static_cast<double>({0}), static_cast<double>({self}))")
    def __rtruediv__(self, other: Int64) -> float: ...
    @cpp_template("::tpy::div_check<int64_t>({0}, {self})")
    def __rfloordiv__(self, other: Int64) -> Int64: ...
    @cpp_template("::tpy::mod_check<int64_t>({0}, {self})")
    def __rmod__(self, other: Int64) -> Int64: ...
    @cpp_template("::tpy::pow_check<int64_t>({0}, {self})")
    def __rpow__(self, other: Int64) -> Int64: ...
    @cpp_template("::tpy::lshift_check<int64_t>({0}, {self})")
    def __rlshift__(self, other: Int64) -> Int64: ...
    @cpp_template("::tpy::rshift_check<int64_t>({0}, {self})")
    def __rrshift__(self, other: Int64) -> Int64: ...
    @cpp_template("static_cast<int64_t>({0} & {self})")
    def __rand__(self, other: Int64) -> Int64: ...
    @cpp_template("static_cast<int64_t>({0} | {self})")
    def __ror__(self, other: Int64) -> Int64: ...
    @cpp_template("static_cast<int64_t>({0} ^ {self})")
    def __rxor__(self, other: Int64) -> Int64: ...
    @cpp_template("static_cast<int64_t>(~({self}))")
    def __invert__(self) -> Int64: ...
    @cpp_template("+{self}")
    def __pos__(self) -> Int64: ...
    @cpp_template("::tpy::neg_check<int64_t>({self})")
    def __neg__(self) -> Int64: ...
    @cpp_template("{self} == {0}")
    @readonly
    @pure
    def __eq__(self, other: Int64) -> bool: ...
    @cpp_template("::tpy::__hash__({self})")
    @readonly
    @pure
    def __hash__(self) -> UInt64: ...
    @cpp_template("{self} < {0}")
    @readonly
    @pure
    def __lt__(self, other: Int64) -> bool: ...


@builtin_type("tpy.UInt8")
@native("uint8_t")
class UInt8(Comparable, Equatable, AnyFixedInt, AnyFixedUnsigned):
    @overload
    @cpp_template("0")
    def __init__(self) -> None: ...
    @overload
    @cpp_template("{0}")
    def __init__(self, x: UInt8) -> None: ...
    @overload
    @cpp_template("::tpy::int_cast_check<{cpp}>({0})")
    def __init__[T: AnyFixedInt](self, x: T) -> None: ...
    @overload
    @cpp_template("({0}).to_fixed_check<{cpp}>()")
    def __init__(self, x: int) -> None: ...
    @overload
    @cpp_template("::tpy::from_float_check<{cpp}>({0})")
    def __init__(self, x: float) -> None: ...
    @overload
    @cpp_template("::tpy::from_float_check<{cpp}>(static_cast<double>({0}))")
    def __init__(self, x: Float32) -> None: ...
    @overload
    @cpp_template("::tpy::from_str_check<{cpp}>({0})")
    def __init__(self, x: str) -> None: ...
    @overload
    @cpp_template("static_cast<{cpp}>({0})")
    def __init__(self, x: bool) -> None: ...
    @overload
    @staticmethod
    @cpp_template("static_cast<uint8_t>({0})")
    def trunc[T: AnyFixedInt](x: T) -> UInt8: ...
    @overload
    @staticmethod
    @cpp_template("({0}).to_fixed_trunc<uint8_t>()")
    def trunc(x: int) -> UInt8: ...
    @cpp_template("::tpy::BigInt({self})")
    def __int__(self) -> int: ...
    @cpp_template("::tpy::add_check<uint8_t>({self}, {0})")
    def __add__(self, other: UInt8) -> UInt8: ...
    @cpp_template("::tpy::sub_check<uint8_t>({self}, {0})")
    def __sub__(self, other: UInt8) -> UInt8: ...
    @cpp_template("::tpy::mul_check<uint8_t>({self}, {0})")
    def __mul__(self, other: UInt8) -> UInt8: ...
    @cpp_template("::tpy::truediv(static_cast<double>({self}), static_cast<double>({0}))")
    def __truediv__(self, other: UInt8) -> float: ...
    @cpp_template("::tpy::div_check<uint8_t>({self}, {0})")
    def __floordiv__(self, other: UInt8) -> UInt8: ...
    @cpp_template("::tpy::mod_check<uint8_t>({self}, {0})")
    def __mod__(self, other: UInt8) -> UInt8: ...
    @cpp_template("::tpy::pow_check<uint8_t>({self}, {0})")
    def __pow__(self, other: UInt8) -> UInt8: ...
    @cpp_template("::tpy::lshift_check<uint8_t>({self}, {0})")
    def __lshift__(self, other: UInt8) -> UInt8: ...
    @cpp_template("::tpy::rshift_check<uint8_t>({self}, {0})")
    def __rshift__(self, other: UInt8) -> UInt8: ...
    @cpp_template("static_cast<uint8_t>({self} & {0})")
    def __and__(self, other: UInt8) -> UInt8: ...
    @cpp_template("static_cast<uint8_t>({self} | {0})")
    def __or__(self, other: UInt8) -> UInt8: ...
    @cpp_template("static_cast<uint8_t>({self} ^ {0})")
    def __xor__(self, other: UInt8) -> UInt8: ...
    @cpp_template("::tpy::add_check<uint8_t>({0}, {self})")
    def __radd__(self, other: UInt8) -> UInt8: ...
    @cpp_template("::tpy::sub_check<uint8_t>({0}, {self})")
    def __rsub__(self, other: UInt8) -> UInt8: ...
    @cpp_template("::tpy::mul_check<uint8_t>({0}, {self})")
    def __rmul__(self, other: UInt8) -> UInt8: ...
    @cpp_template("::tpy::truediv(static_cast<double>({0}), static_cast<double>({self}))")
    def __rtruediv__(self, other: UInt8) -> float: ...
    @cpp_template("::tpy::div_check<uint8_t>({0}, {self})")
    def __rfloordiv__(self, other: UInt8) -> UInt8: ...
    @cpp_template("::tpy::mod_check<uint8_t>({0}, {self})")
    def __rmod__(self, other: UInt8) -> UInt8: ...
    @cpp_template("::tpy::pow_check<uint8_t>({0}, {self})")
    def __rpow__(self, other: UInt8) -> UInt8: ...
    @cpp_template("::tpy::lshift_check<uint8_t>({0}, {self})")
    def __rlshift__(self, other: UInt8) -> UInt8: ...
    @cpp_template("::tpy::rshift_check<uint8_t>({0}, {self})")
    def __rrshift__(self, other: UInt8) -> UInt8: ...
    @cpp_template("static_cast<uint8_t>({0} & {self})")
    def __rand__(self, other: UInt8) -> UInt8: ...
    @cpp_template("static_cast<uint8_t>({0} | {self})")
    def __ror__(self, other: UInt8) -> UInt8: ...
    @cpp_template("static_cast<uint8_t>({0} ^ {self})")
    def __rxor__(self, other: UInt8) -> UInt8: ...
    @cpp_template("static_cast<uint8_t>(~({self}))")
    def __invert__(self) -> UInt8: ...
    @cpp_template("+{self}")
    def __pos__(self) -> UInt8: ...
    @cpp_template("{self} == {0}")
    @readonly
    @pure
    def __eq__(self, other: UInt8) -> bool: ...
    @cpp_template("::tpy::__hash__({self})")
    @readonly
    @pure
    def __hash__(self) -> UInt64: ...
    @cpp_template("{self} < {0}")
    @readonly
    @pure
    def __lt__(self, other: UInt8) -> bool: ...


@builtin_type("tpy.UInt16")
@native("uint16_t")
class UInt16(Comparable, Equatable, AnyFixedInt, AnyFixedUnsigned):
    @overload
    @cpp_template("0")
    def __init__(self) -> None: ...
    @overload
    @cpp_template("{0}")
    def __init__(self, x: UInt16) -> None: ...
    @overload
    @cpp_template("::tpy::int_cast_check<{cpp}>({0})")
    def __init__[T: AnyFixedInt](self, x: T) -> None: ...
    @overload
    @cpp_template("({0}).to_fixed_check<{cpp}>()")
    def __init__(self, x: int) -> None: ...
    @overload
    @cpp_template("::tpy::from_float_check<{cpp}>({0})")
    def __init__(self, x: float) -> None: ...
    @overload
    @cpp_template("::tpy::from_float_check<{cpp}>(static_cast<double>({0}))")
    def __init__(self, x: Float32) -> None: ...
    @overload
    @cpp_template("::tpy::from_str_check<{cpp}>({0})")
    def __init__(self, x: str) -> None: ...
    @overload
    @cpp_template("static_cast<{cpp}>({0})")
    def __init__(self, x: bool) -> None: ...
    @overload
    @staticmethod
    @cpp_template("static_cast<uint16_t>({0})")
    def trunc[T: AnyFixedInt](x: T) -> UInt16: ...
    @overload
    @staticmethod
    @cpp_template("({0}).to_fixed_trunc<uint16_t>()")
    def trunc(x: int) -> UInt16: ...
    @cpp_template("::tpy::BigInt({self})")
    def __int__(self) -> int: ...
    @cpp_template("::tpy::add_check<uint16_t>({self}, {0})")
    def __add__(self, other: UInt16) -> UInt16: ...
    @cpp_template("::tpy::sub_check<uint16_t>({self}, {0})")
    def __sub__(self, other: UInt16) -> UInt16: ...
    @cpp_template("::tpy::mul_check<uint16_t>({self}, {0})")
    def __mul__(self, other: UInt16) -> UInt16: ...
    @cpp_template("::tpy::truediv(static_cast<double>({self}), static_cast<double>({0}))")
    def __truediv__(self, other: UInt16) -> float: ...
    @cpp_template("::tpy::div_check<uint16_t>({self}, {0})")
    def __floordiv__(self, other: UInt16) -> UInt16: ...
    @cpp_template("::tpy::mod_check<uint16_t>({self}, {0})")
    def __mod__(self, other: UInt16) -> UInt16: ...
    @cpp_template("::tpy::pow_check<uint16_t>({self}, {0})")
    def __pow__(self, other: UInt16) -> UInt16: ...
    @cpp_template("::tpy::lshift_check<uint16_t>({self}, {0})")
    def __lshift__(self, other: UInt16) -> UInt16: ...
    @cpp_template("::tpy::rshift_check<uint16_t>({self}, {0})")
    def __rshift__(self, other: UInt16) -> UInt16: ...
    @cpp_template("static_cast<uint16_t>({self} & {0})")
    def __and__(self, other: UInt16) -> UInt16: ...
    @cpp_template("static_cast<uint16_t>({self} | {0})")
    def __or__(self, other: UInt16) -> UInt16: ...
    @cpp_template("static_cast<uint16_t>({self} ^ {0})")
    def __xor__(self, other: UInt16) -> UInt16: ...
    @cpp_template("::tpy::add_check<uint16_t>({0}, {self})")
    def __radd__(self, other: UInt16) -> UInt16: ...
    @cpp_template("::tpy::sub_check<uint16_t>({0}, {self})")
    def __rsub__(self, other: UInt16) -> UInt16: ...
    @cpp_template("::tpy::mul_check<uint16_t>({0}, {self})")
    def __rmul__(self, other: UInt16) -> UInt16: ...
    @cpp_template("::tpy::truediv(static_cast<double>({0}), static_cast<double>({self}))")
    def __rtruediv__(self, other: UInt16) -> float: ...
    @cpp_template("::tpy::div_check<uint16_t>({0}, {self})")
    def __rfloordiv__(self, other: UInt16) -> UInt16: ...
    @cpp_template("::tpy::mod_check<uint16_t>({0}, {self})")
    def __rmod__(self, other: UInt16) -> UInt16: ...
    @cpp_template("::tpy::pow_check<uint16_t>({0}, {self})")
    def __rpow__(self, other: UInt16) -> UInt16: ...
    @cpp_template("::tpy::lshift_check<uint16_t>({0}, {self})")
    def __rlshift__(self, other: UInt16) -> UInt16: ...
    @cpp_template("::tpy::rshift_check<uint16_t>({0}, {self})")
    def __rrshift__(self, other: UInt16) -> UInt16: ...
    @cpp_template("static_cast<uint16_t>({0} & {self})")
    def __rand__(self, other: UInt16) -> UInt16: ...
    @cpp_template("static_cast<uint16_t>({0} | {self})")
    def __ror__(self, other: UInt16) -> UInt16: ...
    @cpp_template("static_cast<uint16_t>({0} ^ {self})")
    def __rxor__(self, other: UInt16) -> UInt16: ...
    @cpp_template("static_cast<uint16_t>(~({self}))")
    def __invert__(self) -> UInt16: ...
    @cpp_template("+{self}")
    def __pos__(self) -> UInt16: ...
    @cpp_template("{self} == {0}")
    @readonly
    @pure
    def __eq__(self, other: UInt16) -> bool: ...
    @cpp_template("::tpy::__hash__({self})")
    @readonly
    @pure
    def __hash__(self) -> UInt64: ...
    @cpp_template("{self} < {0}")
    @readonly
    @pure
    def __lt__(self, other: UInt16) -> bool: ...


@builtin_type("tpy.UInt32")
@native("uint32_t")
class UInt32(Comparable, Equatable, AnyFixedInt, AnyFixedUnsigned):
    @overload
    @cpp_template("0")
    def __init__(self) -> None: ...
    @overload
    @cpp_template("{0}")
    def __init__(self, x: UInt32) -> None: ...
    @overload
    @cpp_template("::tpy::int_cast_check<{cpp}>({0})")
    def __init__[T: AnyFixedInt](self, x: T) -> None: ...
    @overload
    @cpp_template("({0}).to_fixed_check<{cpp}>()")
    def __init__(self, x: int) -> None: ...
    @overload
    @cpp_template("::tpy::from_float_check<{cpp}>({0})")
    def __init__(self, x: float) -> None: ...
    @overload
    @cpp_template("::tpy::from_float_check<{cpp}>(static_cast<double>({0}))")
    def __init__(self, x: Float32) -> None: ...
    @overload
    @cpp_template("::tpy::from_str_check<{cpp}>({0})")
    def __init__(self, x: str) -> None: ...
    @overload
    @cpp_template("static_cast<{cpp}>({0})")
    def __init__(self, x: bool) -> None: ...
    @overload
    @staticmethod
    @cpp_template("static_cast<uint32_t>({0})")
    def trunc[T: AnyFixedInt](x: T) -> UInt32: ...
    @overload
    @staticmethod
    @cpp_template("({0}).to_fixed_trunc<uint32_t>()")
    def trunc(x: int) -> UInt32: ...
    @cpp_template("::tpy::BigInt({self})")
    def __int__(self) -> int: ...
    @cpp_template("::tpy::add_check<uint32_t>({self}, {0})")
    def __add__(self, other: UInt32) -> UInt32: ...
    @cpp_template("::tpy::sub_check<uint32_t>({self}, {0})")
    def __sub__(self, other: UInt32) -> UInt32: ...
    @cpp_template("::tpy::mul_check<uint32_t>({self}, {0})")
    def __mul__(self, other: UInt32) -> UInt32: ...
    @cpp_template("::tpy::truediv(static_cast<double>({self}), static_cast<double>({0}))")
    def __truediv__(self, other: UInt32) -> float: ...
    @cpp_template("::tpy::div_check<uint32_t>({self}, {0})")
    def __floordiv__(self, other: UInt32) -> UInt32: ...
    @cpp_template("::tpy::mod_check<uint32_t>({self}, {0})")
    def __mod__(self, other: UInt32) -> UInt32: ...
    @cpp_template("::tpy::pow_check<uint32_t>({self}, {0})")
    def __pow__(self, other: UInt32) -> UInt32: ...
    @cpp_template("::tpy::lshift_check<uint32_t>({self}, {0})")
    def __lshift__(self, other: UInt32) -> UInt32: ...
    @cpp_template("::tpy::rshift_check<uint32_t>({self}, {0})")
    def __rshift__(self, other: UInt32) -> UInt32: ...
    @cpp_template("static_cast<uint32_t>({self} & {0})")
    def __and__(self, other: UInt32) -> UInt32: ...
    @cpp_template("static_cast<uint32_t>({self} | {0})")
    def __or__(self, other: UInt32) -> UInt32: ...
    @cpp_template("static_cast<uint32_t>({self} ^ {0})")
    def __xor__(self, other: UInt32) -> UInt32: ...
    @cpp_template("::tpy::add_check<uint32_t>({0}, {self})")
    def __radd__(self, other: UInt32) -> UInt32: ...
    @cpp_template("::tpy::sub_check<uint32_t>({0}, {self})")
    def __rsub__(self, other: UInt32) -> UInt32: ...
    @cpp_template("::tpy::mul_check<uint32_t>({0}, {self})")
    def __rmul__(self, other: UInt32) -> UInt32: ...
    @cpp_template("::tpy::truediv(static_cast<double>({0}), static_cast<double>({self}))")
    def __rtruediv__(self, other: UInt32) -> float: ...
    @cpp_template("::tpy::div_check<uint32_t>({0}, {self})")
    def __rfloordiv__(self, other: UInt32) -> UInt32: ...
    @cpp_template("::tpy::mod_check<uint32_t>({0}, {self})")
    def __rmod__(self, other: UInt32) -> UInt32: ...
    @cpp_template("::tpy::pow_check<uint32_t>({0}, {self})")
    def __rpow__(self, other: UInt32) -> UInt32: ...
    @cpp_template("::tpy::lshift_check<uint32_t>({0}, {self})")
    def __rlshift__(self, other: UInt32) -> UInt32: ...
    @cpp_template("::tpy::rshift_check<uint32_t>({0}, {self})")
    def __rrshift__(self, other: UInt32) -> UInt32: ...
    @cpp_template("static_cast<uint32_t>({0} & {self})")
    def __rand__(self, other: UInt32) -> UInt32: ...
    @cpp_template("static_cast<uint32_t>({0} | {self})")
    def __ror__(self, other: UInt32) -> UInt32: ...
    @cpp_template("static_cast<uint32_t>({0} ^ {self})")
    def __rxor__(self, other: UInt32) -> UInt32: ...
    @cpp_template("static_cast<uint32_t>(~({self}))")
    def __invert__(self) -> UInt32: ...
    @cpp_template("+{self}")
    def __pos__(self) -> UInt32: ...
    @cpp_template("{self} == {0}")
    @readonly
    @pure
    def __eq__(self, other: UInt32) -> bool: ...
    @cpp_template("::tpy::__hash__({self})")
    @readonly
    @pure
    def __hash__(self) -> UInt64: ...
    @cpp_template("{self} < {0}")
    @readonly
    @pure
    def __lt__(self, other: UInt32) -> bool: ...


@builtin_type("tpy.UInt64")
@native("uint64_t")
class UInt64(Comparable, Equatable, AnyFixedInt, AnyFixedUnsigned):
    @overload
    @cpp_template("0")
    def __init__(self) -> None: ...
    @overload
    @cpp_template("{0}")
    def __init__(self, x: UInt64) -> None: ...
    @overload
    @cpp_template("::tpy::int_cast_check<{cpp}>({0})")
    def __init__[T: AnyFixedInt](self, x: T) -> None: ...
    @overload
    @cpp_template("({0}).to_fixed_check<{cpp}>()")
    def __init__(self, x: int) -> None: ...
    @overload
    @cpp_template("::tpy::from_float_check<{cpp}>({0})")
    def __init__(self, x: float) -> None: ...
    @overload
    @cpp_template("::tpy::from_float_check<{cpp}>(static_cast<double>({0}))")
    def __init__(self, x: Float32) -> None: ...
    @overload
    @cpp_template("::tpy::from_str_check<{cpp}>({0})")
    def __init__(self, x: str) -> None: ...
    @overload
    @cpp_template("static_cast<{cpp}>({0})")
    def __init__(self, x: bool) -> None: ...
    @overload
    @staticmethod
    @cpp_template("static_cast<uint64_t>({0})")
    def trunc[T: AnyFixedInt](x: T) -> UInt64: ...
    @overload
    @staticmethod
    @cpp_template("({0}).to_fixed_trunc<uint64_t>()")
    def trunc(x: int) -> UInt64: ...
    @cpp_template("::tpy::BigInt({self})")
    def __int__(self) -> int: ...
    @cpp_template("::tpy::add_check<uint64_t>({self}, {0})")
    def __add__(self, other: UInt64) -> UInt64: ...
    @cpp_template("::tpy::sub_check<uint64_t>({self}, {0})")
    def __sub__(self, other: UInt64) -> UInt64: ...
    @cpp_template("::tpy::mul_check<uint64_t>({self}, {0})")
    def __mul__(self, other: UInt64) -> UInt64: ...
    @cpp_template("::tpy::truediv(static_cast<double>({self}), static_cast<double>({0}))")
    def __truediv__(self, other: UInt64) -> float: ...
    @cpp_template("::tpy::div_check<uint64_t>({self}, {0})")
    def __floordiv__(self, other: UInt64) -> UInt64: ...
    @cpp_template("::tpy::mod_check<uint64_t>({self}, {0})")
    def __mod__(self, other: UInt64) -> UInt64: ...
    @cpp_template("::tpy::pow_check<uint64_t>({self}, {0})")
    def __pow__(self, other: UInt64) -> UInt64: ...
    @cpp_template("::tpy::lshift_check<uint64_t>({self}, {0})")
    def __lshift__(self, other: UInt64) -> UInt64: ...
    @cpp_template("::tpy::rshift_check<uint64_t>({self}, {0})")
    def __rshift__(self, other: UInt64) -> UInt64: ...
    @cpp_template("static_cast<uint64_t>({self} & {0})")
    def __and__(self, other: UInt64) -> UInt64: ...
    @cpp_template("static_cast<uint64_t>({self} | {0})")
    def __or__(self, other: UInt64) -> UInt64: ...
    @cpp_template("static_cast<uint64_t>({self} ^ {0})")
    def __xor__(self, other: UInt64) -> UInt64: ...
    @cpp_template("::tpy::add_check<uint64_t>({0}, {self})")
    def __radd__(self, other: UInt64) -> UInt64: ...
    @cpp_template("::tpy::sub_check<uint64_t>({0}, {self})")
    def __rsub__(self, other: UInt64) -> UInt64: ...
    @cpp_template("::tpy::mul_check<uint64_t>({0}, {self})")
    def __rmul__(self, other: UInt64) -> UInt64: ...
    @cpp_template("::tpy::truediv(static_cast<double>({0}), static_cast<double>({self}))")
    def __rtruediv__(self, other: UInt64) -> float: ...
    @cpp_template("::tpy::div_check<uint64_t>({0}, {self})")
    def __rfloordiv__(self, other: UInt64) -> UInt64: ...
    @cpp_template("::tpy::mod_check<uint64_t>({0}, {self})")
    def __rmod__(self, other: UInt64) -> UInt64: ...
    @cpp_template("::tpy::pow_check<uint64_t>({0}, {self})")
    def __rpow__(self, other: UInt64) -> UInt64: ...
    @cpp_template("::tpy::lshift_check<uint64_t>({0}, {self})")
    def __rlshift__(self, other: UInt64) -> UInt64: ...
    @cpp_template("::tpy::rshift_check<uint64_t>({0}, {self})")
    def __rrshift__(self, other: UInt64) -> UInt64: ...
    @cpp_template("static_cast<uint64_t>({0} & {self})")
    def __rand__(self, other: UInt64) -> UInt64: ...
    @cpp_template("static_cast<uint64_t>({0} | {self})")
    def __ror__(self, other: UInt64) -> UInt64: ...
    @cpp_template("static_cast<uint64_t>({0} ^ {self})")
    def __rxor__(self, other: UInt64) -> UInt64: ...
    @cpp_template("static_cast<uint64_t>(~({self}))")
    def __invert__(self) -> UInt64: ...
    @cpp_template("+{self}")
    def __pos__(self) -> UInt64: ...
    @cpp_template("{self} == {0}")
    @readonly
    @pure
    def __eq__(self, other: UInt64) -> bool: ...
    @cpp_template("::tpy::__hash__({self})")
    @readonly
    @pure
    def __hash__(self) -> UInt64: ...
    @cpp_template("{self} < {0}")
    @readonly
    @pure
    def __lt__(self, other: UInt64) -> bool: ...


@builtin_type("tpy.Char")
@native("char")
class Char(Sized, Equatable):
    @overload
    @cpp_template("'\\0'")
    def __init__(self) -> None: ...
    @overload
    @cpp_template("static_cast<char>({0})")
    def __init__(self, x: Int32) -> None: ...
    @overload
    @cpp_template("static_cast<char>(({0}).to_fixed_check<int32_t>())")
    def __init__(self, x: int) -> None: ...
    @overload
    @cpp_template("::tpy::char_from_str({0})")
    def __init__(self, x: str) -> None: ...
    @overload
    @cpp_template("::tpy::char_from_str({0})")
    def __init__(self, x: String) -> None: ...
    @overload
    @cpp_template("::tpy::char_from_str({0})")
    def __init__(self, x: StrView) -> None: ...

    @cpp_template("::tpy::__hash__({self})")
    @readonly
    @pure
    def __hash__(self) -> UInt64: ...

    @overload
    @cpp_template("::tpy::str_concat(::tpy::char_to_str({self}), ::tpy::char_to_str({0}))")
    @readonly
    def __add__(self, other: Char) -> String: ...
    @overload
    @cpp_template("::tpy::str_concat(::tpy::char_to_str({self}), {0})")
    @readonly
    def __add__(self, other: str) -> String: ...
    @overload
    @cpp_template("::tpy::str_concat(::tpy::char_to_str({self}), {0})")
    @readonly
    def __add__(self, other: String) -> String: ...
    @overload
    @cpp_template("::tpy::str_concat(::tpy::char_to_str({self}), {0})")
    @readonly
    def __add__(self, other: StrView) -> String: ...

    @cpp_template("::tpy::str_repeat(::tpy::char_to_str({self}), {0})")
    @readonly
    @pure
    def __mul__(self, n: Int32) -> str: ...

    @cpp_template("::tpy::str_repeat(::tpy::char_to_str({self}), {0})")
    @readonly
    @pure
    def __rmul__(self, n: Int32) -> str: ...

    @cpp_template("{self} == {0}")
    @readonly
    @pure
    def __eq__(self, other: Char) -> bool: ...

    @cpp_template("1")
    @readonly
    @pure
    def __len__(self) -> Int32: ...


@builtin_type("tpy.Float64")
@native("double")
class Float64:
    @overload
    @cpp_template("0.0")
    def __init__(self) -> None: ...
    @overload
    @cpp_template("{0}")
    def __init__(self, x: float) -> None: ...
    @overload
    @cpp_template("static_cast<double>({0})")
    def __init__(self, x: Float32) -> None: ...
    @overload
    @cpp_template("static_cast<double>({0})")
    def __init__(self, x: int) -> None: ...
    @overload
    @cpp_template("static_cast<double>({0})")
    def __init__(self, x: bool) -> None: ...
    @overload
    @cpp_template("::tpy::float_from_str({0})")
    def __init__(self, x: str) -> None: ...
    @overload
    @cpp_template("static_cast<double>({0})")
    def __init__(self, x: Int8) -> None: ...
    @overload
    @cpp_template("static_cast<double>({0})")
    def __init__(self, x: Int16) -> None: ...
    @overload
    @cpp_template("static_cast<double>({0})")
    def __init__(self, x: Int32) -> None: ...
    @overload
    @cpp_template("static_cast<double>({0})")
    def __init__(self, x: Int64) -> None: ...
    @overload
    @cpp_template("static_cast<double>({0})")
    def __init__(self, x: UInt8) -> None: ...
    @overload
    @cpp_template("static_cast<double>({0})")
    def __init__(self, x: UInt16) -> None: ...
    @overload
    @cpp_template("static_cast<double>({0})")
    def __init__(self, x: UInt32) -> None: ...
    @overload
    @cpp_template("static_cast<double>({0})")
    def __init__(self, x: UInt64) -> None: ...
