# tpy: native_module
from tpy.extern import native
from tpy import Ptr, Own, UInt32, Span, nocopy, readonly

@native("tpy::UninitArrayStorage")
@nocopy
class UninitArrayStorage[T, N: int]:
    """Inline uninitialized storage for N elements of type T."""
    def __init__(self) -> None: ...
    def init(self, index: UInt32, value: Own[T]) -> None: ...
    def drop(self, index: UInt32) -> None: ...
    @readonly
    def load(self, index: UInt32) -> T: ...
    def init0(self, value: Own[T]) -> None: ...
    def drop0(self) -> None: ...
    @readonly
    def load0(self) -> T: ...
    def take(self, index: UInt32) -> Own[T]: ...
    def take0(self) -> Own[T]: ...
    @readonly
    def capacity(self) -> UInt32: ...
    def init_from_span(self, start: UInt32, src: Span[readonly[T]]) -> None: ...
    def drop_n(self, start: UInt32, count: UInt32) -> None: ...
    def shift(self, src: UInt32, dst: UInt32, count: UInt32) -> None: ...
    @readonly
    def ptr(self) -> Ptr[T]: ...

@native("tpy::UninitStorage")
@nocopy
class UninitStorage[T]:
    """Owning storage for a single optional T; tracks its own liveness and
    moves correctly element-wise (safe for non-trivially-relocatable T)."""
    def __init__(self) -> None: ...
    def construct(self, value: Own[T]) -> None: ...
    @readonly
    def has(self) -> bool: ...
    @readonly
    def get(self) -> T: ...
    def take(self) -> Own[T]: ...
    def reset(self) -> None: ...
    @readonly
    def ptr(self) -> Ptr[T]: ...

@native("tpy::UninitHeapStorage")
@nocopy
class UninitHeapStorage[T]:
    """Heap-allocated uninitialized storage with dynamic capacity."""
    def __init__(self, capacity: UInt32) -> None: ...
    def init(self, index: UInt32, value: Own[T]) -> None: ...
    def drop(self, index: UInt32) -> None: ...
    @readonly
    def load(self, index: UInt32) -> T: ...
    def init0(self, value: Own[T]) -> None: ...
    def drop0(self) -> None: ...
    @readonly
    def load0(self) -> T: ...
    def take(self, index: UInt32) -> Own[T]: ...
    def take0(self) -> Own[T]: ...
    @readonly
    def capacity(self) -> UInt32: ...
    def init_from_span(self, start: UInt32, src: Span[readonly[T]]) -> None: ...
    def drop_n(self, start: UInt32, count: UInt32) -> None: ...
    def shift(self, src: UInt32, dst: UInt32, count: UInt32) -> None: ...
    @readonly
    def ptr(self) -> Ptr[T]: ...
