# tpy: native_module
from tpy.extern import native
from tpy import Ptr, Own, uint32, Span, nocopy, nomove, readonly

@native("tpy::UninitArrayStorage")
@nocopy
@nomove
class UninitArrayStorage[T, N: int]:
    """Inline uninitialized storage for N elements of type T. Non-movable: it
    tracks no liveness, so it cannot relocate its elements on its own -- an
    owner that needs to be moved defines __move__ to relocate the live ones."""
    def __init__(self) -> None: ...
    def init(self, index: uint32, value: Own[T]) -> None: ...
    def drop(self, index: uint32) -> None: ...
    @readonly
    def load(self, index: uint32) -> T: ...
    def init0(self, value: Own[T]) -> None: ...
    def drop0(self) -> None: ...
    @readonly
    def load0(self) -> T: ...
    def take(self, index: uint32) -> Own[T]: ...
    def take0(self) -> Own[T]: ...
    # Bulk-relocate the live prefix [0, count) from `other` into this (empty)
    # storage, emptying the source. memcpy for a trivial element, element-wise
    # move otherwise.
    def relocate_from(self, other: UninitArrayStorage[T, N], count: uint32) -> None: ...
    @readonly
    def capacity(self) -> uint32: ...
    def init_from_span(self, start: uint32, src: Span[readonly[T]]) -> None: ...
    def drop_n(self, start: uint32, count: uint32) -> None: ...
    def shift(self, src: uint32, dst: uint32, count: uint32) -> None: ...
    @readonly
    def ptr(self) -> Ptr[T]: ...

@native("tpy::UninitStorage")
@nocopy
class UninitStorage[T]:
    """Owning storage for a single optional T; tracks its own liveness and
    moves correctly element-wise (safe for non-trivially-relocatable T)."""
    def __init__(self) -> None: ...
    def construct(self, value: Own[T]) -> None: ...
    @readonly
    def has(self) -> bool: ...
    @readonly
    def get(self) -> T: ...
    def take(self) -> Own[T]: ...
    def reset(self) -> None: ...
    @readonly
    def ptr(self) -> Ptr[T]: ...

@native("tpy::UninitHeapStorage")
@nocopy
class UninitHeapStorage[T]:
    """Heap-allocated uninitialized storage with dynamic capacity."""
    def __init__(self, capacity: uint32) -> None: ...
    def init(self, index: uint32, value: Own[T]) -> None: ...
    def drop(self, index: uint32) -> None: ...
    @readonly
    def load(self, index: uint32) -> T: ...
    def init0(self, value: Own[T]) -> None: ...
    def drop0(self) -> None: ...
    @readonly
    def load0(self) -> T: ...
    def take(self, index: uint32) -> Own[T]: ...
    def take0(self) -> Own[T]: ...
    @readonly
    def capacity(self) -> uint32: ...
    def init_from_span(self, start: uint32, src: Span[readonly[T]]) -> None: ...
    def drop_n(self, start: uint32, count: uint32) -> None: ...
    def shift(self, src: uint32, dst: uint32, count: uint32) -> None: ...
    @readonly
    def ptr(self) -> Ptr[T]: ...
