// Generated by TurboPython Compiler
#pragma once

#include <tpy/tpy.hpp>

namespace tpy_user::main {

template<typename T>
concept HasValue = requires(T& t) {
    { t.value } -> std::convertible_to<int32_t>;
};

template<typename T>
concept HasXY = requires(T& t) {
    { t.x } -> std::convertible_to<int32_t>;
    { t.y } -> std::convertible_to<int32_t>;
};

template<typename T>
concept Container = requires(T& t) {
    { t.is_empty() } -> std::convertible_to<bool>;
    { t.count } -> std::convertible_to<int32_t>;
};

template<typename T, typename _T0>
concept Holder = requires(T& t) {
    { t.item } -> std::convertible_to<_T0>;
};

struct Point;
struct Vec2;
struct Box;
struct IntHolder;
template<HasValue T> struct Wrapper;

extern std::string_view __name__;

struct Point {
  int32_t value;

  Point() = default;
  explicit Point(int32_t v) : value(v) {}
};

inline std::ostream& operator<<(std::ostream& os, const Point& obj) {
  os << "Point("
     << "value=" << obj.value
     << ")";
  return os;
}

struct Vec2 {
  int32_t x;
  int32_t y;

  Vec2() = default;
  explicit Vec2(int32_t x, int32_t y) : x(x), y(y) {}
};

inline std::ostream& operator<<(std::ostream& os, const Vec2& obj) {
  os << "Vec2("
     << "x=" << obj.x
     << ", "
     << "y=" << obj.y
     << ")";
  return os;
}

struct Box {
  int32_t count;

  Box() = default;
  explicit Box(int32_t c) : count(c) {}

  bool is_empty() {
    // 55:         return self.count == 0
    return (this->count == 0);
  }
};

inline std::ostream& operator<<(std::ostream& os, const Box& obj) {
  os << "Box("
     << "count=" << obj.count
     << ")";
  return os;
}

struct IntHolder {
  int32_t item;

  IntHolder() = default;
  explicit IntHolder(int32_t v) : item(v) {}
};

inline std::ostream& operator<<(std::ostream& os, const IntHolder& obj) {
  os << "IntHolder("
     << "item=" << obj.item
     << ")";
  return os;
}

template<HasValue T>
struct Wrapper {
  T inner;

  Wrapper() = default;
  explicit Wrapper(const T& val) : inner(val) {}

  int32_t get_inner_value() {
    // 74:         return self.inner.value
    return this->inner.value;
  }
};

template<typename T>
inline std::ostream& operator<<(std::ostream& os, const Wrapper<T>& obj) {
  os << "Wrapper("
     << "inner=" << tpy::ValuePrinter(obj.inner)
     << ")";
  return os;
}

template<HasValue T>
int32_t get_value(tpy::param_val_or_ref_t<T> item);
template<HasXY T>
int32_t sum_xy(tpy::param_val_or_ref_t<T> item);
template<Container T>
int32_t describe(tpy::param_val_or_ref_t<T> item);
template<Holder<int32_t> T>
int32_t get_item(tpy::param_val_or_ref_t<T> holder);
void main();

void __tpy_init();
} // namespace tpy_user::main
