// Generated by TurboPython Compiler
#include "main.hpp"

// 11: global_pt: Point = Point(1, 2)
Point global_pt = Point(1, 2);

// 13: def addr_param(p: Point) -> Ptr[Point]:
Point* addr_param(Point& p) {
  // 15:     return p
  return &p;
}

// 17: def addr_global() -> Ptr[Point]:
Point* addr_global() {
  // 19:     return global_pt
  return &global_pt;
}

// 21: def main() -> None:
int main() {
  // 22:     local: Point = Point(10, 20)
  Point local = Point(10, 20);
  // 23:     p1: Ptr[Point] = addr_param(local)
  Point* p1 = addr_param(local);
  // 24:     print(p1.x)
  std::cout << p1->x << "\n";
  // 25:     p2: Ptr[Point] = addr_global()
  Point* p2 = addr_global();
  // 26:     print(p2.y)
  std::cout << p2->y << "\n";
  return 0;
}

