// Generated by TurboPython Compiler
#include "traits.hpp"

namespace tpyapp::traits {


void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

}

} // namespace tpyapp::traits
