// Generated by TurboPython Compiler
#pragma once

#include <tpy/tpy.hpp>
#include "tpystd/tpy/_types.hpp"
#include "tpystd/typing/_typing.hpp"

namespace tpyapp::main {

struct Tagger;

inline constexpr std::string_view __name__ = "__main__";

// def str_position(s: str) -> str | None:
std::optional<std::string> str_position(std::string_view s);
// def bytes_position(b: bytes) -> bytes | None:
std::optional<::tpy::Bytes> bytes_position(::tpy::BytesView b);
// def main() -> None:
void main();

// class Tagger:
struct Tagger {
    // prefix: str
    std::string prefix;

    // def __init__(self, prefix: str) -> None:
    Tagger() = default;
    explicit Tagger(std::string_view prefix);

    // def tag(self, s: str) -> str | None:
    std::optional<std::string> tag(std::string_view s) const;
    static constexpr std::string_view __tpy_class_name__ = "__main__.Tagger";
};

inline std::ostream& operator<<(std::ostream& os, const Tagger& obj) {
    ::tpy::print_object_default(os, "Tagger", obj);
    return os;
}


// def __init__(self, prefix: str) -> None:
//     self.prefix = prefix
inline Tagger::Tagger(std::string_view prefix) : prefix(prefix) {}

// # method position
// def tag(self, s: str) -> str | None:
//     if len(s) == 0:
//         return None
//     return s  # tpyc: ok
inline std::optional<std::string> Tagger::tag(std::string_view s) const {
    if ((::tpy::__len__(s) == 0)) {
        return std::nullopt;
    }
    return std::string(s);
}
void __tpy_init();
} // namespace tpyapp::main
