// Generated by TurboPython Compiler
#pragma once

#include <tpy/tpy.hpp>
#include "tpystd/tpy/_types.hpp"
#include "tpystd/typing/_typing.hpp"
#include "tpystd/coro.hpp"
#include "tpystd/asyncio.hpp"

namespace tpyapp::main {

struct Cur;
struct Sub;
struct Deleg;
struct Rng;
struct Noisy;
struct Quiet;
struct Loud;
struct Failed;
struct Scope;
struct Holder;

extern int32_t module_count;
inline constexpr std::string_view __name__ = "__main__";

struct __gen_gen;
struct __gen_ranged;
struct __coro_acount;
struct __gen_pairs;

// def gen() -> Iterator[int32]:
__gen_gen gen();
// def ranged() -> Iterator[int32]:
__gen_ranged ranged();
// def make_list() -> Own[list[int32]]:
std::vector<int32_t> make_list();
// def make_set() -> Own[set[int32]]:
::tpy::ordered_set<int32_t> make_set();
// def add(a: int32, b: int32) -> int32:
int32_t add(int32_t a, int32_t b);
// def make_noisy(n: int32) -> Own[Noisy]:
Noisy make_noisy(int32_t n);
// def make_holder(n: int32) -> Own[Holder]:
Holder make_holder(int32_t n);
// async def acount(xs: list[int32]) -> int32:
__coro_acount acount(const std::vector<int32_t>& xs);
// @error_return(Failed)
// def checked(xs: list[int32]) -> int32:
std::expected<int32_t, Failed> checked(const std::vector<int32_t>& xs);
// def by_match(k: int32, xs: list[int32]) -> int32:
int32_t by_match(int32_t k, const std::vector<int32_t>& xs);
// def dbl(v: int32) -> int32:
int32_t dbl(int32_t v);
// def odd(v: int32) -> bool:
bool odd(int32_t v);
// def pairs(xs: list[int32]) -> Iterator[int32]:
__gen_pairs pairs(const std::vector<int32_t>& xs);
// def main() -> None:
void main();

// class Cur:
struct Cur {
    // i: int32
    int32_t i;
    // n: int32
    int32_t n;

    // def __init__(self, n: int32) -> None:
    Cur() = default;
    explicit Cur(int32_t n);

    // def __iter__(self) -> "Cur":
    Cur& __iter__();

    // def __next__(self) -> int32:
    std::expected<int32_t, ::tpy::StopIteration> __next__();
    static constexpr std::string_view __tpy_class_name__ = "__main__.Cur";
};

inline std::ostream& operator<<(std::ostream& os, const Cur& obj) {
    ::tpy::print_object_default(os, "Cur", obj);
    return os;
}

// class Rng:
struct Rng {
    // n: int32
    int32_t n;
    // i: int32
    int32_t i;

    // def __init__(self, n: int32) -> None:
    Rng() = default;
    explicit Rng(int32_t n);

    // def __iter__(self) -> Own["Rng"]:
    Rng __iter__() const;

    // def __next__(self) -> int32:
    std::expected<int32_t, ::tpy::StopIteration> __next__();
    static constexpr std::string_view __tpy_class_name__ = "__main__.Rng";
};

inline std::ostream& operator<<(std::ostream& os, const Rng& obj) {
    ::tpy::print_object_default(os, "Rng", obj);
    return os;
}

// class Noisy:
struct Noisy {
    // n: int32
    int32_t n;

    // def __init__(self, n: int32) -> None:
    Noisy() = default;
    explicit Noisy(int32_t n);

    // def __iter__(self) -> Own[Cur]:
    Cur __iter__() const;
    static constexpr std::string_view __tpy_class_name__ = "__main__.Noisy";
};

inline std::ostream& operator<<(std::ostream& os, const Noisy& obj) {
    ::tpy::print_object_default(os, "Noisy", obj);
    return os;
}

// class Quiet:
struct Quiet {
    // n: int32
    int32_t n;

    // def __init__(self, n: int32) -> None:
    Quiet() = default;
    explicit Quiet(int32_t n);

    // def __iter__(self) -> Own[Cur]:
    Cur __iter__() const;
    static constexpr std::string_view __tpy_class_name__ = "__main__.Quiet";
};

inline std::ostream& operator<<(std::ostream& os, const Quiet& obj) {
    ::tpy::print_object_default(os, "Quiet", obj);
    return os;
}

// class Loud:
struct Loud {
    // n: int32
    int32_t n;

    // def __init__(self, n: int32) -> None:
    Loud() = default;
    explicit Loud(int32_t n);

    // def __iter__(self) -> Own[Cur]:
    Cur __iter__() const;
    static constexpr std::string_view __tpy_class_name__ = "__main__.Loud";
};

inline std::ostream& operator<<(std::ostream& os, const Loud& obj) {
    ::tpy::print_object_default(os, "Loud", obj);
    return os;
}

// class Failed(Exception, ReturnException):
struct Failed : ::tpy::ReturnException {

    static constexpr std::string_view __tpy_class_name__ = "__main__.Failed";
};

inline std::ostream& operator<<(std::ostream& os, const Failed& obj) {
    ::tpy::print_object_default(os, "Failed", obj);
    return os;
}

// class Scope:
struct Scope {


    // def __enter__(self) -> int32:
    int32_t __enter__() const;

    // def __exit__(self, exc_type, exc_val, exc_tb) -> None:
    void __exit__(std::monostate exc_type, const ::tpy::BaseException* exc_val, std::monostate exc_tb) const;
    static constexpr std::string_view __tpy_class_name__ = "__main__.Scope";
};

inline std::ostream& operator<<(std::ostream& os, const Scope& obj) {
    ::tpy::print_object_default(os, "Scope", obj);
    return os;
}

// class Holder:
struct Holder {
    // n: int32
    int32_t n;
    // quiet: Quiet
    Quiet quiet;
    // count: int32
    int32_t count;

    // def __init__(self, n: int32) -> None:
    Holder() = default;
    explicit Holder(int32_t n);

    // def make(self) -> Own[Quiet]:
    Quiet make() const;

    // @staticmethod
    // def stat(n: int32) -> Own[Quiet]:
    static Quiet stat(int32_t n);

    // def total(self, xs: list[int32]) -> int32:
    int32_t total(const std::vector<int32_t>& xs) const;
    static constexpr std::string_view __tpy_class_name__ = "__main__.Holder";
};

inline std::ostream& operator<<(std::ostream& os, const Holder& obj) {
    ::tpy::print_object_default(os, "Holder", obj);
    return os;
}

// class Sub(Cur):
struct Sub : Cur {

    // def __init__(self, n: int32) -> None:
    Sub() = default;
    explicit Sub(int32_t n);
    static constexpr std::string_view __tpy_class_name__ = "__main__.Sub";
};

inline std::ostream& operator<<(std::ostream& os, const Sub& obj) {
    ::tpy::print_object_default(os, "Sub", obj);
    return os;
}

// class Deleg(Cur):  # tpyc: warning(/hides 'Cur.__iter__'/)
struct Deleg : Cur {
    // inner: Cur
    Cur inner;

    // def __init__(self, n: int32) -> None:
    Deleg() = default;
    explicit Deleg(int32_t n);

    // def __iter__(self) -> Cur:
    Cur& __iter__();
    static constexpr std::string_view __tpy_class_name__ = "__main__.Deleg";
};

inline std::ostream& operator<<(std::ostream& os, const Deleg& obj) {
    ::tpy::print_object_default(os, "Deleg", obj);
    return os;
}

// async def acount(xs: list[int32]) -> int32:
struct __coro_acount {
    ::tpy::frame_state __state;
    bool __cancel_pending;
    const std::vector<int32_t>& xs;

    enum : int32_t {
        S_INITIAL = 0,
        S_DONE = 1,
    };

    __coro_acount(const std::vector<int32_t>& xs)
        : __state(S_INITIAL),
          __cancel_pending(false),
          xs(xs) {}

    ::tpystd::tpy::Poll<int32_t> __poll__(::tpystd::coro::Waker waker);
    void cancel() { __cancel_pending = true; }

    friend std::ostream& operator<<(std::ostream& os, const __coro_acount&) {
        return os << "<coroutine acount>";
    }
};

// def gen() -> Iterator[int32]:
struct __gen_gen : public ::tpy::next_iter_mixin<__gen_gen, int32_t> {
    ::tpy::frame_state __state;

    enum : int32_t {
        S_INITIAL = 0,
        S_RESUME_0 = 1,
        S_RESUME_1 = 2,
        S_RESUME_2 = 3,
        S_DONE = 4,
    };

    __gen_gen() : __state(S_INITIAL) {}

    std::expected<int32_t, ::tpy::StopIteration> __next__();
    __gen_gen& __iter__() { return *this; }

    friend std::ostream& operator<<(std::ostream& os, const __gen_gen&) {
        return os << "<generator gen>";
    }
};

// def ranged() -> Iterator[int32]:
struct __gen_ranged : public ::tpy::next_iter_mixin<__gen_ranged, int32_t> {
    ::tpy::frame_state __state;
    int32_t i;
    ::tpy::frame_loop_slot<int32_t> __for_i_0;
    ::tpy::frame_loop_slot<int32_t> __for_stop_0;

    enum : int32_t {
        S_INITIAL = 0,
        S_RESUME_0 = 1,
        S_JOIN_0 = 2,
        S_DONE = 3,
    };

    __gen_ranged() : __state(S_INITIAL) {}

    std::expected<int32_t, ::tpy::StopIteration> __next__();
    __gen_ranged& __iter__() { return *this; }

    friend std::ostream& operator<<(std::ostream& os, const __gen_ranged&) {
        return os << "<generator ranged>";
    }
};

// def pairs(xs: list[int32]) -> Iterator[int32]:
struct __gen_pairs : public ::tpy::next_iter_mixin<__gen_pairs, int32_t> {
    ::tpy::frame_state __state;
    const std::vector<int32_t>& xs;
    int32_t t;
    std::tuple<int32_t, int32_t> __for_tup_1;
    int32_t i;
    int32_t v;
    ::tpy::frame_slot<Noisy> __coro_arg_0;
    using __for_src_0_t = ::tpy::for_source_t<decltype((::tpy::builtin_enumerate((*__coro_arg_0))))>;
    ::tpy::frame_loop_slot<__for_src_0_t> __for_src_0;

    enum : int32_t {
        S_INITIAL = 0,
        S_RESUME_0 = 1,
        S_DONE = 2,
    };

    __gen_pairs(const std::vector<int32_t>& xs)
        : __state(S_INITIAL),
          xs(xs) {}

    std::expected<int32_t, ::tpy::StopIteration> __next__();
    __gen_pairs& __iter__() { return *this; }

    friend std::ostream& operator<<(std::ostream& os, const __gen_pairs&) {
        return os << "<generator pairs>";
    }
};


// def __init__(self, n: int32) -> None:
//     self.i = 0
//     self.n = n
inline Cur::Cur(int32_t n)
    : i(0),
      n(n) {}

// def __iter__(self) -> "Cur":
//     print("  Cur.__iter__", self.n)
//     return self
inline Cur& Cur::__iter__() {
    std::cout << "  Cur.__iter__" << " " << this->n << "\n" << ::tpy::check_signals;
    return (*this);
}

// def __next__(self) -> int32:
//     if self.i >= self.n:
//         raise StopIteration
//     self.i += 1
//     return self.i
inline std::expected<int32_t, ::tpy::StopIteration> Cur::__next__() {
    if ((this->i >= this->n)) {
        return ::tpy::make_unexpected(::tpy::StopIteration{});
    }
    this->i = ::tpy::add_check<int32_t>(this->i, 1);
    return this->i;
}

// def __init__(self, n: int32) -> None:
//     self.n = n
//     self.i = 0
inline Rng::Rng(int32_t n)
    : n(n),
      i(0) {}

// def __iter__(self) -> Own["Rng"]:
//     print("  Rng.__iter__", self.n)
//     return Rng(self.n)
inline Rng Rng::__iter__() const {
    std::cout << "  Rng.__iter__" << " " << this->n << "\n" << ::tpy::check_signals;
    return Rng(this->n);
}

// def __next__(self) -> int32:
//     if self.i >= self.n:
//         raise StopIteration
//     self.i += 1
//     return self.i
inline std::expected<int32_t, ::tpy::StopIteration> Rng::__next__() {
    if ((this->i >= this->n)) {
        return ::tpy::make_unexpected(::tpy::StopIteration{});
    }
    this->i = ::tpy::add_check<int32_t>(this->i, 1);
    return this->i;
}

// def __init__(self, n: int32) -> None:
//     self.n = n
inline Noisy::Noisy(int32_t n) : n(n) {}

// def __iter__(self) -> Own[Cur]:
//     print("  Noisy.__iter__", self.n)
//     return Cur(self.n)
inline Cur Noisy::__iter__() const {
    std::cout << "  Noisy.__iter__" << " " << this->n << "\n" << ::tpy::check_signals;
    return Cur(this->n);
}

// def __init__(self, n: int32) -> None:
//     self.n = n
inline Quiet::Quiet(int32_t n) : n(n) {}

// def __iter__(self) -> Own[Cur]:
//     return Cur(self.n)
inline Cur Quiet::__iter__() const {
    return Cur(this->n);
}

// def __init__(self, n: int32) -> None:
//     print("  Loud.__init__", n)
//     self.n = n
inline Loud::Loud(int32_t n) {
    std::cout << "  Loud.__init__" << " " << n << "\n" << ::tpy::check_signals;
    this->n = n;
}

// def __iter__(self) -> Own[Cur]:
//     return Cur(self.n)
inline Cur Loud::__iter__() const {
    return Cur(this->n);
}

// def __enter__(self) -> int32:
//     return 1
inline int32_t Scope::__enter__() const {
    return 1;
}

// def __exit__(self, exc_type, exc_val, exc_tb) -> None:
//     pass
inline void Scope::__exit__(std::monostate exc_type, const ::tpy::BaseException* exc_val, std::monostate exc_tb) const {
}

// # constructor position: no statement-level slot in a member init
// def __init__(self, n: int32) -> None:
//     self.n = n
//     self.quiet = Quiet(n)
//     self.count = len(list(map(dbl, Quiet(n))))  # tpyc: ok
inline Holder::Holder(int32_t n)
    : n(n),
      quiet(Quiet(n)),
      count(::tpy::__len__(::tpy::construct<std::vector<int32_t>>(::tpy::builtin_map<int32_t>(dbl, Quiet(n))))) {}

// def make(self) -> Own[Quiet]:
//     return Quiet(self.n)
inline Quiet Holder::make() const {
    return Quiet(this->n);
}

// @staticmethod
// def stat(n: int32) -> Own[Quiet]:
//     return Quiet(n)
inline Quiet Holder::stat(int32_t n) {
    return Quiet(n);
}

// # method position
// def total(self, xs: list[int32]) -> int32:
//     t = 0
//     for a, b in zip(Noisy(self.n), xs):  # tpyc: ok
//         t += a * b
//     return t
inline int32_t Holder::total(const std::vector<int32_t>& xs) const {
    int32_t t = 0;
    {
        Noisy __tmp_1 = Noisy(this->n);
        auto __src_0 = ::tpy::builtin_zip(__tmp_1, xs);
        auto&& __itr_0 = ::tpy::__iter__(__src_0);
        for (;;) {
            auto __r_1 = __itr_0.__next__();
            if (!__r_1.has_value()) break;
            auto&& __for_tup_0 = ::tpy::unwrap_ref(*__r_1);
            const auto& __tup_1 = __for_tup_0;
            int32_t a = std::get<0>(__tup_1);
            int32_t b = std::get<1>(__tup_1);
            t = ::tpy::add_check<int32_t>(t, (::tpy::mul_check<int32_t>(a, b)));
        }
    }
    return t;
}

// def __init__(self, n: int32) -> None:
//     super().__init__(n)
inline Sub::Sub(int32_t n) : Cur(n) {}

// def __init__(self, n: int32) -> None:
//     super().__init__(0)
//     self.inner = Cur(n)
inline Deleg::Deleg(int32_t n)
    : Cur(0),
      inner(Cur(n)) {}

// def __iter__(self) -> Cur:
//     return self.inner
inline Cur& Deleg::__iter__() {
    return this->inner;
}
void __tpy_init();
} // namespace tpyapp::main
