// Generated by TurboPython Compiler
#include "main.hpp"

namespace tpyapp::main {

// a = Weight(int32(50))
Weight* a{};
// b = Weight(int32(30))
Weight* b{};

void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    // # @total_ordering with __ge__ as the anchor: synthesizes __lt__,
    // # __le__, __gt__. Covers the remaining anchor-row in the derivation
    // # table.
    // from functools import total_ordering
    ::tpystd::functools::__tpy_init();
    // a = Weight(int32(50))
    static Weight __global_slot_1 = Weight(50);
    a = &__global_slot_1;
    // b = Weight(int32(30))
    static Weight __global_slot_2 = Weight(30);
    b = &__global_slot_2;
    // print(a >= b)
    std::cout << ::tpy::print_bool((((*a)) >= ((*b)))) << "\n";
    // print(a > b)
    std::cout << ::tpy::print_bool((((*a)) > ((*b)))) << "\n";
    // print(a <= b)
    std::cout << ::tpy::print_bool((((*a)) <= ((*b)))) << "\n";
    // print(a < b)
    std::cout << ::tpy::print_bool((((*a)) < ((*b)))) << "\n";
    // print(b <= a)
    std::cout << ::tpy::print_bool((((*b)) <= ((*a)))) << "\n";
}

} // namespace tpyapp::main

int __tpy_main(int argc, char* argv[]) {
    ::tpy::init_sys_argv(argc, argv);
    ::tpyapp::main::__tpy_init();
    return 0;
}

int main(int argc, char* argv[]) {
    ::tpy::process_startup();
    return __tpy_main(argc, argv);
}
