// Generated by TurboPython Compiler
#pragma once

#include <tpy/tpy.hpp>
#include "tpystd/tpy/_types.hpp"
#include "tpystd/typing/_typing.hpp"
#include "tpystd/coro.hpp"

namespace tpyapp::main {

inline constexpr std::string_view __name__ = "__main__";

struct __coro_sub;
struct __coro_caller;

__coro_sub sub();
__coro_caller caller();
void main();

// Async coroutine: sub
struct __coro_sub {
    int32_t __state;
    bool __cancel_pending;

    enum : int32_t {
        S_INITIAL = 0,
        S_DONE = 1,
    };

    __coro_sub()
        : __state(S_INITIAL), __cancel_pending(false) {}

    ::tpy::Poll<int32_t> __poll__(::tpy::Waker waker);

    friend std::ostream& operator<<(std::ostream& os, const __coro_sub&) {
        return os << "<coroutine sub>";
    }
};

// Async coroutine: caller
struct __coro_caller {
    int32_t __state;
    bool __cancel_pending;
    int32_t x;
    int32_t y;
    int32_t z;
    std::optional<__coro_sub> __sub_0;
    std::optional<__coro_sub> __sub_1;

    enum : int32_t {
        S_INITIAL = 0,
        S_AFTER_AWAIT_0 = 1,
        S_AFTER_AWAIT_1 = 2,
        S_DONE = 3,
    };

    __coro_caller()
        : __state(S_INITIAL), __cancel_pending(false) {}

    ::tpy::Poll<int32_t> __poll__(::tpy::Waker waker);

    friend std::ostream& operator<<(std::ostream& os, const __coro_caller&) {
        return os << "<coroutine caller>";
    }
};

using ::tpystd::coro::poll_once;

void __tpy_init();
} // namespace tpyapp::main
