// Generated by TurboPython Compiler
#pragma once

#include <tpy/tpy.hpp>
#include "tpystd/tpy/_types.hpp"
#include "tpystd/typing/_typing.hpp"

namespace tpyapp::defaults {

enum class Color : int32_t {
    RED = 0,
    BLUE = 1,
};

} // namespace tpyapp::defaults

template<>
struct tpy::EnumUtil<::tpyapp::defaults::Color> {
    static constexpr std::string_view type_name = "Color";
    static std::string_view name(::tpyapp::defaults::Color e);
    static const std::array<::tpyapp::defaults::Color, 2> members;
    static ::tpyapp::defaults::Color from_value(int32_t v);
    static ::tpyapp::defaults::Color from_name(std::string_view s);
    static std::optional<::tpyapp::defaults::Color> try_parse(std::string_view s);
};

namespace tpyapp::defaults {

inline std::ostream& operator<<(std::ostream& __os, Color __e) {
    return __os << "Color." << ::tpy::EnumUtil<Color>::name(__e);
}

struct Counter;
struct Base;
struct Derived;
struct Pair;

inline constexpr std::string_view __name__ = "__main__";
inline constexpr int64_t STEP = 7;
extern const std::tuple<int32_t, int32_t> ORIGIN;

std::string greet(std::string_view name, std::string_view greeting = "Hello", bool excited = false);
int64_t advance(int64_t n, int64_t by = STEP);
double scale(double x, double factor = 0.5);
int32_t tag(::tpy::BytesView data = ::tpy::bytes_literal("ab", 2));
int32_t offset(const std::tuple<int32_t, int32_t>& at = ORIGIN);
int32_t paint(Color shade = Color::BLUE);
int64_t combine(int64_t a, int64_t b, int64_t c = 5);
int64_t blend(int64_t red, int64_t green, int64_t blue);
std::string initial(std::string_view text, int32_t idx = 0);

struct Counter {
    int64_t n;
    int64_t step;

    explicit Counter(int64_t n = 0, int64_t step = 1);

    int64_t bump(int64_t by = 1, bool twice = false);
    static constexpr std::string_view __tpy_class_name__ = "__main__.Counter";
};

inline std::ostream& operator<<(std::ostream& os, const Counter& obj) {
    ::tpy::print_object_default(os, "Counter", obj);
    return os;
}

struct Base {
    int64_t lo;
    int64_t hi;
    int64_t scale;

    Base() = default;
    explicit Base(int64_t lo, int64_t hi, int64_t scale = 2);

    int64_t span() const;
    static constexpr std::string_view __tpy_class_name__ = "__main__.Base";
};

inline std::ostream& operator<<(std::ostream& os, const Base& obj) {
    ::tpy::print_object_default(os, "Base", obj);
    return os;
}

struct Pair {
    int64_t a;
    int64_t b;

    Pair() = default;
    explicit Pair(int64_t a, int64_t b);

    int64_t weigh(int64_t factor) const;
    static constexpr std::string_view __tpy_class_name__ = "__main__.Pair";
};

inline std::ostream& operator<<(std::ostream& os, const Pair& obj) {
    ::tpy::print_object_default(os, "Pair", obj);
    return os;
}

struct Derived : Base {

    using Base::Base;
    static constexpr std::string_view __tpy_class_name__ = "__main__.Derived";
};

inline std::ostream& operator<<(std::ostream& os, const Derived& obj) {
    ::tpy::print_object_default(os, "Derived", obj);
    return os;
}


inline Counter::Counter(int64_t n, int64_t step) : n(n), step(step) {}

inline int64_t Counter::bump(int64_t by, bool twice) {
    this->n = (::tpy::add_check<int64_t>(this->n, (::tpy::mul_check<int64_t>(by, this->step))));
    if (twice) {
        this->n = (::tpy::add_check<int64_t>(this->n, (::tpy::mul_check<int64_t>(by, this->step))));
    }
    return this->n;
}

inline Base::Base(int64_t lo, int64_t hi, int64_t scale) : lo(lo), hi(hi), scale(scale) {}

inline int64_t Base::span() const {
    return (::tpy::mul_check<int64_t>((::tpy::sub_check<int64_t>(this->hi, this->lo)), this->scale));
}

inline Pair::Pair(int64_t a, int64_t b) : a(a), b(b) {}

inline int64_t Pair::weigh(int64_t factor) const {
    return (::tpy::mul_check<int64_t>((::tpy::add_check<int64_t>(this->a, this->b)), factor));
}
void __tpy_init();
} // namespace tpyapp::defaults
