// Generated by TurboPython Compiler
#include "main.hpp"

namespace tpyapp::main {


// def gen(b: Box) -> Iterator[int]:
std::expected<::tpy::BigInt, ::tpy::StopIteration> __gen_gen::__next__() {
    while (true) switch (__state) {
    case S_INITIAL: {
        auto& __match_subject_1 = b;
        // case Box(maybe=v):
        {
            v = ::tpy::optional_to_ptr(__match_subject_1.maybe);
            // yield 1
            __state = S_RESUME_0;
            return ::tpy::BigInt(1);
        }
        __state = S_JOIN_0;
        continue;
    }
    case S_RESUME_0: {
        // if v is not None:
        if ((v != nullptr)) {
            // print(v.n)
            std::cout << v->n << "\n";
        }
        // yield 2
        __state = S_RESUME_1;
        return ::tpy::BigInt(2);
    }
    case S_RESUME_1: {
        __state = S_JOIN_0;
        continue;
    }
    case S_JOIN_0: {
        __state = S_DONE;
        return ::tpy::make_unexpected(::tpy::StopIteration{});
    }
    case S_DONE: return ::tpy::make_unexpected(::tpy::StopIteration{});
    }
    __builtin_unreachable();
}


// def gen(b: Box) -> Iterator[int]:
__gen_gen gen(Box& b) {
    return __gen_gen(b);
}

// def main() -> None:
void main() {
    // for x in gen(Box(Inner(7))):
    {
        Inner __tmp_1 = Inner(::tpy::BigInt(7));
        Box __tmp_2 = Box(&(__tmp_1));
        auto __src_0 = gen(__tmp_2);
        auto&& __itr_0 = ::tpy::__iter__(__src_0);
        for (;;) {
            auto __r_1 = __itr_0.__next__();
            if (!__r_1.has_value()) break;
            const ::tpy::BigInt& x = ::tpy::unwrap_ref(*__r_1);
        // print(x)
        std::cout << x << "\n";
        }
    }
    // print("--")
    std::cout << "--" << "\n";
    // for x in gen(Box(None)):
    {
        Box __tmp_3 = Box(nullptr);
        auto __src_2 = gen(__tmp_3);
        auto&& __itr_2 = ::tpy::__iter__(__src_2);
        for (;;) {
            auto __r_3 = __itr_2.__next__();
            if (!__r_3.has_value()) break;
            const ::tpy::BigInt& x = ::tpy::unwrap_ref(*__r_3);
        // print(x)
        std::cout << x << "\n";
        }
    }
}

void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    // main()
    main();
}

} // namespace tpyapp::main

int __tpy_main(int argc, char* argv[]) {
    ::tpy::init_sys_argv(argc, argv);
    ::tpyapp::main::__tpy_init();
    return 0;
}

int main(int argc, char* argv[]) {
    std::set_terminate(&::tpy::tpy_terminate_handler);
    return __tpy_main(argc, argv);
}
