// Generated by TurboPython Compiler
#include "main.hpp"

namespace tpyapp::main {


// def log() -> None:
void log() {
    // print("log")
    std::cout << "log" << "\n";
}

// def main():
void main() {
    // p: Point | None = Point(1)
    Point __slot_1 = Point(1);
    Point* p = &__slot_1;
    // if p is None:
    if ((p == nullptr)) {
        // return
        return;
    }
    // i = 0
    int32_t i = 0;
    // while i < 2:
    while ((i < 2)) {
        // print(p.x)  # tpyc: ok
        std::cout << p->x << "\n";
        // i += 1
        i = ::tpy::add_check<int32_t>(i, 1);
    }
    // log()
    log();
    // print(p.x)  # tpyc: ok
    std::cout << p->x << "\n";
    // try:
    {
        try {
            // print("try")
            std::cout << "try" << "\n";
        } catch (...) {
            // print("fin")
            std::cout << "fin" << "\n";
            throw;
        }
        // print("fin")
        std::cout << "fin" << "\n";
    }
    // print(p.x)  # tpyc: ok
    std::cout << p->x << "\n";
}

void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    // main()
    main();
}

} // namespace tpyapp::main

int __tpy_main(int argc, char* argv[]) {
    ::tpy::init_sys_argv(argc, argv);
    ::tpyapp::main::__tpy_init();
    return 0;
}

int main(int argc, char* argv[]) {
    std::set_terminate(&::tpy::tpy_terminate_handler);
    return __tpy_main(argc, argv);
}
