// Generated by TurboPython Compiler
#include "main.hpp"

namespace tpyapp::main {


// def mk(k: int32) -> str:
//     return "x" * (4 + k)
std::string mk(int32_t k) {
    return (::tpy::str_repeat("x", (::tpy::add_check<int32_t>(4, k))));
}

// def setbuf(b: Buf, k: int32) -> None:
//     b.buf = mk(k)
void setbuf(Buf& b, int32_t k) {
    b.buf = ::tpyapp::main::mk(k);
}

// # free function: a callee reading a parameter's stored loan
// def size(t: Tok) -> int32:  # tpyc: mir(covered) mir_summary(known)
//     return len(t.s)
int32_t size(const Tok& t) {
    return ::tpy::__len__(t.s);
}

// # free function: a view read through a borrowed record parameter; the result lends it
// def first(t: Tok) -> StrView:  # tpyc: mir(covered) mir_summary(known)
//     return t.s
std::string_view first(const Tok& t) {
    return t.s;
}

// # free function: a borrowed record result reaches both arguments' objects
// def pick(a: Tok, b: Tok, flag: bool) -> Tok:  # tpyc: mir(certified) mir_summary(known)
//     if flag:
//         return a
//     return b
Tok& pick(Tok& a, Tok& b, bool flag) {
    if (flag) {
        return a;
    }
    return b;
}

// # free function: the source is replaced while the record, moved to u at its last use, lives
// def alias_replaced(k: int32, flag: bool) -> None:  # tpyc: mir(conflict /replacement/)
//     buf = mk(k)
//     t = Tok(buf, 1)  # tpyc: mir_borrows(t.s, buf)
//     u = t  # tpyc: mir_borrows(u.s, buf)
//     if flag:
//         buf = mk(k + 1)
//     print("alias_replaced", u.s)
void alias_replaced(int32_t k, bool flag) {
    std::string buf = ::tpyapp::main::mk(k);
    Tok t = Tok(buf, 1);
    Tok u = std::move(t);
    if (flag) {
        buf = ::tpyapp::main::mk((::tpy::add_check<int32_t>(k, 1)));
    }
    std::cout << "alias_replaced" << " " << u.s << "\n" << ::tpy::check_signals;
}

// # free function: an alias keeps the old object's loan when the name is reseated
// def copied_rebind(k: int32, flag: bool) -> None:  # tpyc: mir(conflict /replacement/)
//     a = mk(k)
//     b = mk(k + 1)
//     t = Tok(a, 1)
//     u = t  # tpyc: mir_borrows(u.s, a)
//     # u aliases t's object: the write shows through t
//     u.n = 7
//     print("copied_rebind", t.n)
//     t = Tok(b, 2)  # tpyc: mir_borrows(t.s, b)
//     if flag:
//         a = mk(k + 2)
//     print("copied_rebind", u.s, t.s)
void copied_rebind(int32_t k, bool flag) {
    std::optional<Tok> __slot_2;
    std::string a = ::tpyapp::main::mk(k);
    std::string b = ::tpyapp::main::mk((::tpy::add_check<int32_t>(k, 1)));
    Tok __slot_1 = Tok(a, 1);
    Tok* t = &__slot_1;
    Tok& u = (*t);
    u.n = 7;
    std::cout << "copied_rebind" << " " << t->n << "\n" << ::tpy::check_signals;
    t = &*(__slot_2 = Tok(b, 2));
    if (flag) {
        a = ::tpyapp::main::mk((::tpy::add_check<int32_t>(k, 2)));
    }
    std::cout << "copied_rebind" << " " << u.s << " " << t->s << "\n" << ::tpy::check_signals;
}

// # free function: a parameter's view member may view its sibling field
// def sibling_view(p: R, flag: bool) -> None:  # tpyc: mir(conflict /replacement/)
//     v: StrView = p.s  # tpyc: mir_borrows(v, p.s)
//     if flag:
//         p.buf = mk(2)
//     print("sibling_view", v)
void sibling_view(R& p, bool flag) {
    std::string_view v = p.s;
    if (flag) {
        p.buf = ::tpyapp::main::mk(2);
    }
    std::cout << "sibling_view" << " " << v << "\n" << ::tpy::check_signals;
}

// # free function: an owned copy of the member is no loan
// def sibling_copy(p: R) -> None:  # tpyc: mir(covered)
//     v = p.s
//     p.buf = mk(2)
//     print("sibling_copy", v)
void sibling_copy(R& p) {
    std::string v = std::string(p.s);
    p.buf = ::tpyapp::main::mk(2);
    std::cout << "sibling_copy" << " " << v << "\n" << ::tpy::check_signals;
}

// # free function: two record parameters may be one object
// def aliased_params(a: R, b: R, flag: bool) -> None:  # tpyc: mir(conflict /replacement/)
//     v: StrView = a.s  # tpyc: mir_borrows(v, a.s)
//     if flag:
//         b.buf = mk(3)
//     print("aliased_params", v)
void aliased_params(const R& a, R& b, bool flag) {
    std::string_view v = a.s;
    if (flag) {
        b.buf = ::tpyapp::main::mk(3);
    }
    std::cout << "aliased_params" << " " << v << "\n" << ::tpy::check_signals;
}

// # free function: the str argument is a temporary of the declaration
// def temporary_source(k: int32, flag: bool) -> None:  # tpyc: mir(conflict /scope_end/)
//     t = Tok(mk(k), 1)
//     if flag:
//         print("temporary_source", t.s)
//     print("temporary_source", t.n)
void temporary_source(int32_t k, bool flag) {
    Tok t = Tok(::tpyapp::main::mk(k), 1);
    if (flag) {
        std::cout << "temporary_source" << " " << t.s << "\n" << ::tpy::check_signals;
    }
    std::cout << "temporary_source" << " " << t.n << "\n" << ::tpy::check_signals;
}

// # free function: a literal's static storage outlives every replacement
// def static_source(k: int32) -> None:  # tpyc: mir(covered)
//     buf = mk(k)
//     t = Tok("lit", 1)  # tpyc: mir_borrows(t.s, static)
//     buf = mk(k + 1)
//     print("static_source", t.s, buf)
void static_source(int32_t k) {
    std::string buf = ::tpyapp::main::mk(k);
    Tok t = Tok("lit", 1);
    buf = ::tpyapp::main::mk((::tpy::add_check<int32_t>(k, 1)));
    std::cout << "static_source" << " " << t.s << " " << buf << "\n" << ::tpy::check_signals;
}

// # free function: the callees read the loan before its source is replaced
// def callee_reads(k: int32) -> int32:  # tpyc: mir(covered) mir_summary(known)
//     buf = mk(k)
//     t = Tok(buf, 1)
//     n = size(t) + len(t.text())
//     buf = mk(k + 1)
//     return n + len(buf)
int32_t callee_reads(int32_t k) {
    std::string buf = ::tpyapp::main::mk(k);
    Tok t = Tok(buf, 1);
    int32_t n = (::tpy::add_check<int32_t>(::tpyapp::main::size(t), ::tpy::__len__(t.text())));
    buf = ::tpyapp::main::mk((::tpy::add_check<int32_t>(k, 1)));
    return (::tpy::add_check<int32_t>(n, ::tpy::__len__(buf)));
}

// # free function: a callee reads the loan after its source is replaced
// def callee_reads_late(k: int32, flag: bool) -> int32:  # tpyc: mir(conflict /replacement/)
//     buf = mk(k)
//     t = Tok(buf, 1)  # tpyc: mir_borrows(t.s, buf)
//     if flag:
//         buf = mk(k + 1)
//         return size(t)
//     return t.n
int32_t callee_reads_late(int32_t k, bool flag) {
    std::string buf = ::tpyapp::main::mk(k);
    Tok t = Tok(buf, 1);
    if (flag) {
        buf = ::tpyapp::main::mk((::tpy::add_check<int32_t>(k, 1)));
        return ::tpyapp::main::size(t);
    }
    return t.n;
}

// # free function: a callee replaces the field the record views
// def callee_replaces(k: int32, flag: bool) -> None:  # tpyc: mir(conflict /replacement/)
//     b = Buf(mk(k))
//     t = Tok(b.buf, 1)  # tpyc: mir_borrows(t.s, b.buf)
//     if flag:
//         setbuf(b, k)
//     print("callee_replaces", t.s)
void callee_replaces(int32_t k, bool flag) {
    Buf b = Buf(::tpyapp::main::mk(k));
    Tok t = Tok(b.buf, 1);
    if (flag) {
        ::tpyapp::main::setbuf(b, k);
    }
    std::cout << "callee_replaces" << " " << t.s << "\n" << ::tpy::check_signals;
}

// # free function: a parameter's stored loan, seeded at entry, read after an external write
// def late_read(t: Tok, b: Buf, flag: bool) -> StrView:  # tpyc: mir(conflict /replacement/)
//     if flag:
//         b.buf = mk(2)
//     return t.s
std::string_view late_read(const Tok& t, Buf& b, bool flag) {
    if (flag) {
        b.buf = ::tpyapp::main::mk(2);
    }
    return t.s;
}

// # free function: an alias of a parameter reaches its stored loan
// def alias_late(t: Tok, b: Buf, flag: bool) -> StrView:  # tpyc: mir(conflict /replacement/)
//     u = t  # tpyc: mir_borrows(u.s, t.s)
//     if flag:
//         b.buf = mk(2)
//     return u.s
std::string_view alias_late(const Tok& t, Buf& b, bool flag) {
    const Tok& u = t;
    if (flag) {
        b.buf = ::tpyapp::main::mk(2);
    }
    return u.s;
}

// # free function: an alias reseated in a loop still reaches the parameter's stored loan
// def loop_alias(t: Tok, b: Buf, n: int32, flag: bool) -> None:  # tpyc: mir(conflict /replacement/)
//     u = t
//     for i in range(n):
//         u = t  # tpyc: mir_borrows(u.s, t.s)
//     if flag:
//         b.buf = mk(2)
//     print("loop_alias", u.s)
void loop_alias(Tok& t, Buf& b, int32_t n, bool flag) {
    Tok* u = &(t);
    int32_t __stop_0 = n;
    for (int32_t i = 0; i < __stop_0; ++i) {
        u = &(t);
    }
    if (flag) {
        b.buf = ::tpyapp::main::mk(2);
    }
    std::cout << "loop_alias" << " " << u->s << "\n" << ::tpy::check_signals;
}

// # free function: either argument's stored loan through a borrowed record result
// def pick_late(a: Tok, b: Tok, buf: Buf, flag: bool) -> StrView:  # tpyc: mir(conflict /replacement/)
//     t = pick(a, b, flag)  # tpyc: mir_borrows(t.s, a.s|b.s)
//     if flag:
//         buf.buf = mk(2)
//     return t.s
std::string_view pick_late(Tok& a, Tok& b, Buf& buf, bool flag) {
    Tok& t = ::tpyapp::main::pick(a, b, flag);
    if (flag) {
        buf.buf = ::tpyapp::main::mk(2);
    }
    return t.s;
}

// # free function: a view read off a record built in one branch
// def detached_view(k: int32, flag: bool) -> None:  # tpyc: mir(conflict /replacement/)
//     a = mk(k)
//     v: StrView = "lit"
//     if flag:
//         t = Tok(a, 1)
//         v = t.s  # tpyc: mir_borrows(v, a)
//     a = mk(k + 1)
//     print("detached_view", v)
void detached_view(int32_t k, bool flag) {
    std::string a = ::tpyapp::main::mk(k);
    std::string_view v = "lit";
    if (flag) {
        Tok t = Tok(a, 1);
        v = t.s;
    }
    a = ::tpyapp::main::mk((::tpy::add_check<int32_t>(k, 1)));
    std::cout << "detached_view" << " " << v << "\n" << ::tpy::check_signals;
}

// # free function: a literal member stores static storage
// def literal_member() -> int32:  # tpyc: mir(covered) mir_summary(known)
//     c = Lit(1)
//     return len(c.s) + c.n
int32_t literal_member() {
    Lit c = Lit(1);
    return (::tpy::add_check<int32_t>(::tpy::__len__(c.s), c.n));
}

// # free function: a view member write into the caller's record
// def retarget(t: Tok, s: str) -> None:  # tpyc: mir(covered) mir_summary(known)
//     t.s = s
void retarget(Tok& t, std::string_view s) {
    t.s = s;
}

// # free function: a record holding a view handed over
// # (only `t.n` is read, so the handed-over record is never consumed: the warning is right)
// def consume(t: Own[Tok]) -> int32:  # tpyc: mir(covered) mir_summary(known) warning(/never consumed/)
//     return t.n
int32_t consume(Tok&& t) {
    return t.n;
}

// # free function: a container element
// def in_list(name: str) -> int32:  # tpyc: mir(uncovered /^container holds a borrow$/)
//     xs = [Tok(name, 1)]
//     return len(xs)
int32_t in_list(std::string_view name) {
    std::array<Tok, 1> xs = {Tok(name, 1)};
    return ::tpy::__len__(xs);
}

// # free function: an Optional payload
// def maybe(t: Tok | None) -> int32:  # tpyc: mir(uncovered /^wrapper holds a borrow$/)
//     if t is not None:
//         return t.n
//     return 0
int32_t maybe(const Tok* t) {
    if ((t != nullptr)) {
        return t->n;
    }
    return 0;
}

// # free function: a tuple member
// def paired(t: Tok) -> int32:  # tpyc: mir(uncovered /^wrapper holds a borrow$/)
//     pair = (t, 1)
//     return pair[0].n
int32_t paired(Tok& t) {
    auto pair = std::tuple<Tok*, int32_t>{&(t), 1};
    return std::get<0>(pair)->n;
}

// # free function: a record argument built on one branch is a deferred temporary; its backing stores name's loan
// def deferred(name: str, flag: bool) -> int32:  # tpyc: mir(certified)
//     return size(Tok(name, 1)) if flag else 0
int32_t deferred(std::string_view name, bool flag) {
    std::optional<Tok> __tmp_1;
    return ((flag) ? (__tmp_1.emplace(Tok(name, 1)), ::tpyapp::main::size((*__tmp_1))) : (0));
}

// # free function: a select's conditional record storage stores a's loan where it is engaged
// def selected(owner: Tok, a: str, flag: bool) -> int32:  # tpyc: mir(certified)
//     saved = owner if flag else Tok(a, 2)
//     return saved.n
int32_t selected(Tok& owner, std::string_view a, bool flag) {
    std::optional<Tok> __select_slot_1;
    Tok& saved = ((flag) ? (owner) : (__select_slot_1.emplace(Tok(a, 2))));
    return saved.n;
}

// # free function: an in-place reseat replaces the one object's stored loan; nothing views what it replaces
// def branch(k: int32, flag: bool) -> None:  # tpyc: mir(covered)
//     a = mk(k)
//     t = Tok("lit", 1)
//     if flag:
//         t = Tok(a, 2)
//     print("branch", t.s)
void branch(int32_t k, bool flag) {
    std::string a = ::tpyapp::main::mk(k);
    Tok __slot_1 = Tok("lit", 1);
    Tok* t = &__slot_1;
    if (flag) {
        (*t) = Tok(a, 2);
    }
    std::cout << "branch" << " " << t->s << "\n" << ::tpy::check_signals;
}

// # free function: an inherited constructor reuses the base's stored loan
// def child(s: str) -> int32:  # tpyc: mir(covered) mir_summary(known)
//     c = Child(s, 1)
//     return c.n
int32_t child(std::string_view s) {
    Child c = Child(s, 1);
    return c.n;
}

// def main() -> None:
//     alias_replaced(1, False)
//     copied_rebind(1, False)
//     r = R(mk(1), "abc")
//     sibling_view(r, False)
//     sibling_copy(r)
//     aliased_params(r, r, False)
//     temporary_source(2, False)
//     static_source(3)
//     print("callee_reads", callee_reads(4))
//     print("callee_reads_late", callee_reads_late(5, False))
//     callee_replaces(6, False)
//     b = Buf(mk(7))
//     t = Tok(b.buf, 1)
//     print("late_read", late_read(t, b, False))
//     print("alias_late", alias_late(t, b, False))
//     loop_alias(t, b, 2, False)
//     print("pick_late", pick_late(t, Tok("q", 2), b, False))
//     detached_view(8, False)
//     print("first", first(Tok("zzz", 1)))
//     print("size", size(t))
//     print("literal_member", literal_member())
//     s = "rt"
//     retarget(t, s)
//     print("retarget", t.s)
//     print("consume", consume(Tok("r", 3)))
//     print("in_list", in_list("w"))
//     print("maybe", maybe(t))
//     print("paired", paired(t))
//     print("deferred", deferred("d", True), deferred("d", False))
//     print("selected", selected(t, "e", True), selected(t, "e", False))
//     print("child", child("c"))
//     branch(9, False)
void main() {
    ::tpyapp::main::alias_replaced(1, false);
    ::tpyapp::main::copied_rebind(1, false);
    R r = R(::tpyapp::main::mk(1), "abc");
    ::tpyapp::main::sibling_view(r, false);
    ::tpyapp::main::sibling_copy(r);
    ::tpyapp::main::aliased_params(r, r, false);
    ::tpyapp::main::temporary_source(2, false);
    ::tpyapp::main::static_source(3);
    std::cout << "callee_reads" << " " << ::tpyapp::main::callee_reads(4) << "\n" << ::tpy::check_signals;
    std::cout << "callee_reads_late" << " " << ::tpyapp::main::callee_reads_late(5, false) << "\n" << ::tpy::check_signals;
    ::tpyapp::main::callee_replaces(6, false);
    Buf b = Buf(::tpyapp::main::mk(7));
    Tok t = Tok(b.buf, 1);
    std::cout << "late_read" << " " << ::tpyapp::main::late_read(t, b, false) << "\n" << ::tpy::check_signals;
    std::cout << "alias_late" << " " << ::tpyapp::main::alias_late(t, b, false) << "\n" << ::tpy::check_signals;
    ::tpyapp::main::loop_alias(t, b, 2, false);
    Tok __tmp_1 = Tok("q", 2);
    std::cout << "pick_late" << " " << ::tpyapp::main::pick_late(t, __tmp_1, b, false) << "\n" << ::tpy::check_signals;
    ::tpyapp::main::detached_view(8, false);
    Tok __tmp_2 = Tok("zzz", 1);
    std::cout << "first" << " " << ::tpyapp::main::first(__tmp_2) << "\n" << ::tpy::check_signals;
    std::cout << "size" << " " << ::tpyapp::main::size(t) << "\n" << ::tpy::check_signals;
    std::cout << "literal_member" << " " << ::tpyapp::main::literal_member() << "\n" << ::tpy::check_signals;
    std::string_view s = "rt";
    ::tpyapp::main::retarget(t, s);
    std::cout << "retarget" << " " << t.s << "\n" << ::tpy::check_signals;
    std::cout << "consume" << " " << ::tpyapp::main::consume(Tok("r", 3)) << "\n" << ::tpy::check_signals;
    std::cout << "in_list" << " " << ::tpyapp::main::in_list("w") << "\n" << ::tpy::check_signals;
    std::cout << "maybe" << " " << ::tpyapp::main::maybe(&(t)) << "\n" << ::tpy::check_signals;
    std::cout << "paired" << " " << ::tpyapp::main::paired(t) << "\n" << ::tpy::check_signals;
    std::cout << "deferred" << " " << ::tpyapp::main::deferred("d", true) << " " << ::tpyapp::main::deferred("d", false) << "\n" << ::tpy::check_signals;
    std::cout << "selected" << " " << ::tpyapp::main::selected(t, "e", true) << " " << ::tpyapp::main::selected(t, "e", false) << "\n" << ::tpy::check_signals;
    std::cout << "child" << " " << ::tpyapp::main::child("c") << "\n" << ::tpy::check_signals;
    ::tpyapp::main::branch(9, false);
}

// main()
void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    ::tpyapp::main::main();
}

} // namespace tpyapp::main

int __tpy_main(int argc, char* argv[]) {
    ::tpy::init_sys_argv(argc, argv);
    ::tpyapp::main::__tpy_init();
    return 0;
}

int main(int argc, char* argv[]) {
    return ::tpy::run_main(argc, argv, &__tpy_main);
}
