// Generated by TurboPython Compiler
#include "main.hpp"

namespace tpyapp::main {


// def consume(b: Own[Box]) -> int32:
//     return b.value
int32_t consume(Box&& b) {
    return b.value;
}

// def main():
//     b = Box()
//     b.value = 42
//     print(consume(copy(b)))  # tpyc: ok (not last use -- b used below)
//     print(b.value)
void main() {
    Box b = Box();
    b.value = 42;
    std::cout << ::tpyapp::main::consume(Box(b)) << "\n";
    std::cout << b.value << "\n";
}

// main()
void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    ::tpyapp::main::main();
}

} // namespace tpyapp::main

int __tpy_main(int argc, char* argv[]) {
    ::tpy::init_sys_argv(argc, argv);
    ::tpyapp::main::__tpy_init();
    return 0;
}

int main(int argc, char* argv[]) {
    ::tpy::process_startup();
    return __tpy_main(argc, argv);
}
