// Generated by TurboPython Compiler
#pragma once

#include <tpy/tpy.hpp>
#include "tpystd/tpy/_types.hpp"
#include "tpystd/typing/_typing.hpp"

namespace tpyapp::main {

struct Key;
struct Point;
struct Edge;

inline constexpr std::string_view __name__ = "__main__";

void main();
void test_nocopy_hash();
void test_hash_delegation();

// @nocopy
// class Key:
struct Key {
    // val: Int32
    int32_t val;

    // def __init__(self, v: Int32) -> None:
    Key() = default;
    explicit Key(int32_t v) : val(v) {}
    // non-copyable (@nocopy)
    Key(const Key&) = delete;
    Key& operator=(const Key&) = delete;
    Key(Key&&) = default;
    Key& operator=(Key&&) = default;

    // def __hash__(self) -> UInt64:
    uint64_t __hash__() const;

    // def __eq__(self, other: Key) -> bool:
    bool __eq__(const Key& other) const;

    friend bool operator==(const Key& lhs, const Key& other) {
        return lhs.__eq__(other);
    }
    static constexpr std::string_view __tpy_class_name__ = "__main__.Key";
};

inline std::ostream& operator<<(std::ostream& os, const Key& obj) {
    ::tpy::print_object_default(os, "Key", obj);
    return os;
}
} // namespace tpyapp::main

template<> struct std::hash<::tpyapp::main::Key> {
    size_t operator()(const ::tpyapp::main::Key& val) const noexcept {
        return static_cast<size_t>(::tpy::__hash__(val));
    }
};

namespace tpyapp::main {


// class Point:
struct Point {
    // x: Int32
    int32_t x;
    // y: Int32
    int32_t y;

    // def __init__(self, x: Int32, y: Int32) -> None:
    Point() = default;
    explicit Point(int32_t x, int32_t y) : x(x), y(y) {}

    // def __hash__(self) -> UInt64:
    uint64_t __hash__() const;

    // def __eq__(self, other: Point) -> bool:
    bool __eq__(const Point& other) const;

    friend bool operator==(const Point& lhs, const Point& other) {
        return lhs.__eq__(other);
    }
    static constexpr std::string_view __tpy_class_name__ = "__main__.Point";
};

inline std::ostream& operator<<(std::ostream& os, const Point& obj) {
    ::tpy::print_object_default(os, "Point", obj);
    return os;
}
} // namespace tpyapp::main

template<> struct std::hash<::tpyapp::main::Point> {
    size_t operator()(const ::tpyapp::main::Point& val) const noexcept {
        return static_cast<size_t>(::tpy::__hash__(val));
    }
};

namespace tpyapp::main {


// @nocopy
// class Edge:
struct Edge {
    // a: Key
    Key a;
    // b: Key
    Key b;

    // def __init__(self, x: Int32, y: Int32) -> None:
    Edge() = default;
    explicit Edge(int32_t x, int32_t y) : a(Key(x)), b(Key(y)) {}
    // non-copyable (@nocopy)
    Edge(const Edge&) = delete;
    Edge& operator=(const Edge&) = delete;
    Edge(Edge&&) = default;
    Edge& operator=(Edge&&) = default;

    // def __hash__(self) -> UInt64:
    uint64_t __hash__() const;

    // def __eq__(self, other: Edge) -> bool:
    bool __eq__(const Edge& other) const;

    friend bool operator==(const Edge& lhs, const Edge& other) {
        return lhs.__eq__(other);
    }
    static constexpr std::string_view __tpy_class_name__ = "__main__.Edge";
};

inline std::ostream& operator<<(std::ostream& os, const Edge& obj) {
    ::tpy::print_object_default(os, "Edge", obj);
    return os;
}
} // namespace tpyapp::main

template<> struct std::hash<::tpyapp::main::Edge> {
    size_t operator()(const ::tpyapp::main::Edge& val) const noexcept {
        return static_cast<size_t>(::tpy::__hash__(val));
    }
};

namespace tpyapp::main {



// def __hash__(self) -> UInt64:
inline uint64_t Key::__hash__() const {
    // return UInt64(self.val)
    return ::tpy::int_cast_check<uint64_t>(this->val);
}

// def __eq__(self, other: Key) -> bool:
inline bool Key::__eq__(const Key& other) const {
    // return self.val == other.val
    return (this->val == other.val);
}

// def __hash__(self) -> UInt64:
inline uint64_t Point::__hash__() const {
    // return hash((self.x, self.y))
    return ::tpy::__hash__(std::tuple<int32_t, int32_t>{this->x, this->y});
}

// def __eq__(self, other: Point) -> bool:
inline bool Point::__eq__(const Point& other) const {
    // return self.x == other.x and self.y == other.y
    return ((this->x == other.x) && (this->y == other.y));
}

// def __hash__(self) -> UInt64:
inline uint64_t Edge::__hash__() const {
    // return hash((self.a, self.b))
    return ::tpy::__hash__(std::tuple<const Key&, const Key&>{this->a, this->b});
}

// def __eq__(self, other: Edge) -> bool:
inline bool Edge::__eq__(const Edge& other) const {
    // return (self.a, self.b) == (other.a, other.b)
    return (std::tuple<const Key&, const Key&>{this->a, this->b} == std::tuple<const Key&, const Key&>{other.a, other.b});
}
void __tpy_init();
} // namespace tpyapp::main
