// Generated by TurboPython Compiler
#include "main.hpp"

namespace tpyapp::main {


// def main() -> None:
//     c = Converter()
//     print(c.identity(42))
//     print(c.identity("hello"))
//     print(c.identity(True))
void main() {
    Converter c = Converter();
    std::cout << c.identity<int32_t>(42) << "\n";
    std::cout << c.identity<std::string>("hello") << "\n";
    std::cout << ::tpy::print_bool(c.identity<bool>(true)) << "\n";
}

// main()
void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    main();
}

} // namespace tpyapp::main

int __tpy_main(int argc, char* argv[]) {
    ::tpy::init_sys_argv(argc, argv);
    ::tpyapp::main::__tpy_init();
    return 0;
}

int main(int argc, char* argv[]) {
    ::tpy::process_startup();
    return __tpy_main(argc, argv);
}
