// Generated by TurboPython Compiler
#pragma once

#include <tpy/tpy.hpp>
#include "tpystd/tpy/_types.hpp"
#include "tpystd/typing/_typing.hpp"
#include "tpystd/tpy/atomic.hpp"
#include "tpystd/tpy/channel.hpp"
#include "tpystd/coro.hpp"
#include "tpystd/tpy/sync.hpp"
#include "tpystd/tpy/thread.hpp"
#include "tpystd/tpy/version.hpp"
#include <tpy/stdlib/signal_h.hpp>
#include <tpy/system.hpp>
#include <tpy/stdlib/time.hpp>

namespace tpystd::_interrupt {

inline constexpr std::string_view __name__ = "_interrupt";
// READY: Final[int32] = 1
inline constexpr int32_t READY = 1;
// WAIT_ERROR: Final[int32] = -1
inline constexpr int32_t WAIT_ERROR = -1;
// TIMED_OUT: Final[int32] = -2
inline constexpr int32_t TIMED_OUT = -2;

// def check() -> None:
void check();
// def deadline_after(timeout: float) -> float:
double deadline_after(double timeout);
// def remaining(deadline: float) -> float:
double remaining(double deadline);
// def wait_readable(fd: int32, deadline: float) -> int32:
int32_t wait_readable(int32_t fd, double deadline);
// def wait_writable(fd: int32, deadline: float) -> int32:
int32_t wait_writable(int32_t fd, double deadline);
// def deliverable() -> bool:
bool deliverable();
// def before_read(fd: int32) -> None:
void before_read(int32_t fd);
// def before_write(fd: int32) -> None:
void before_write(int32_t fd);
// def _wait(fd: int32, want_write: int32, deadline: float) -> int32:
int32_t _wait(int32_t fd, int32_t want_write, double deadline);

void __tpy_init();
} // namespace tpystd::_interrupt
