// Generated by TurboPython Compiler
#include "main.hpp"

namespace tpyapp::main {


// def test_extend_warns() -> None:
void test_extend_warns() {
    // a = ArrayList[Node, 16]()
    ::tpystd::tplib::array_list::ArrayList<Node, 16> a = ::tpystd::tplib::array_list::ArrayList<Node, 16>();
    // b: list[Node] = [Node(1)]
    std::vector<Node> b = {Node(1)};
    // a.extend(b)  # tpyc: warning(/copies Node elements/)
    a.extend(b);
    // print(a[0].val)
    std::cout << a[0].val << "\n";
    // print(len(b))
    std::cout << ::tpy::__len__(b) << "\n";
}

// def test_extend_value_type_no_warn() -> None:
void test_extend_value_type_no_warn() {
    // a = ArrayList[Int32, 16]()
    ::tpystd::tplib::array_list::ArrayList<int32_t, 16> a = ::tpystd::tplib::array_list::ArrayList<int32_t, 16>();
    // b: list[Int32] = [1, 2]
    std::vector<int32_t> b = {1, 2};
    // a.extend(b)  # tpyc: ok
    a.extend(b);
    // print(a[0])
    std::cout << a[0] << "\n";
}

// def test_ctor_warns() -> None:
void test_ctor_warns() {
    // b: list[Node] = [Node(1)]
    std::vector<Node> b = {Node(1)};
    // a = ArrayList[Node, 16](b)  # tpyc: warning(/copies Node elements/)
    ::tpystd::tplib::array_list::ArrayList<Node, 16> a = ::tpystd::tplib::array_list::ArrayList<Node, 16>(&(b));
    // print(a[0].val)
    std::cout << a[0].val << "\n";
    // print(len(b))
    std::cout << ::tpy::__len__(b) << "\n";
}

// def test_ctor_last_use_no_warn() -> None:
void test_ctor_last_use_no_warn() {
    // b: list[Node] = [Node(1)]
    std::vector<Node> b = {Node(1)};
    // a = ArrayList[Node, 16](b)  # tpyc: ok -- b's last use
    ::tpystd::tplib::array_list::ArrayList<Node, 16> a = ::tpystd::tplib::array_list::ArrayList<Node, 16>(&(b));
    // print(a[0].val)
    std::cout << a[0].val << "\n";
}

void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    // from tplib import ArrayList
    ::tpystd::tplib::__tpy_init();
    // test_extend_warns()
    test_extend_warns();
    // test_extend_value_type_no_warn()
    test_extend_value_type_no_warn();
    // test_ctor_warns()
    test_ctor_warns();
    // test_ctor_last_use_no_warn()
    test_ctor_last_use_no_warn();
}

} // namespace tpyapp::main

int __tpy_main(int argc, char* argv[]) {
    ::tpy::init_sys_argv(argc, argv);
    ::tpyapp::main::__tpy_init();
    return 0;
}

int main(int argc, char* argv[]) {
    ::tpy::process_startup();
    return __tpy_main(argc, argv);
}
