// Generated by TurboPython Compiler
#include "main.hpp"

namespace tpyapp::main {


// # Cross-variable different-size reassignment promotes both to list
// def main() -> None:
void main() {
    // a = [1, 2, 3]  # tpyc: type(/list/)
    std::vector<int32_t> __slot_1 = {1, 2, 3};
    std::vector<int32_t>* a = &__slot_1;
    // b = [4, 5]     # tpyc: type(/list/)
    std::vector<int32_t> b = {4, 5};
    // a = b
    a = &(b);
    // print(len(a))
    std::cout << ::tpy::__len__((*a)) << "\n";
}

void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    // main()
    main();
}

} // namespace tpyapp::main

int __tpy_main(int argc, char* argv[]) {
    ::tpy::init_sys_argv(argc, argv);
    tpyapp::main::__tpy_init();
    return 0;
}

int main(int argc, char* argv[]) {
    std::set_terminate(&::tpy::tpy_terminate_handler);
    return __tpy_main(argc, argv);
}
