// Generated by TurboPython Compiler
#pragma once

#include <tpy/tpy.hpp>
#include "tpystd/tpy.hpp"
#include "tpystd/typing.hpp"
#include "mod_d.hpp"

namespace tpyapp::mod_c {

inline constexpr std::string_view __name__ = "mod_c";

int32_t c_value();

void __tpy_init();
} // namespace tpyapp::mod_c
