// Generated by TurboPython Compiler
#pragma once

#include <tpy/tpy.hpp>
#include "tpystd/tpy/_types.hpp"
#include "tpystd/typing/_typing.hpp"

namespace tpyapp::main {

struct Source;

inline constexpr std::string_view __name__ = "__main__";

struct __gen_gen;
struct __gen_walk;
struct __gen_gen_range;
struct __gen_gen_ternary;
struct __gen_gen_walrus;
struct __gen_Source_gen;

// def gen() -> Iterator[list[int32]]:
__gen_gen gen();
// def walk() -> Iterator[tuple[int32, list[int32]]]:
__gen_walk walk();
// def gen_range() -> Iterator[list[int32]]:
__gen_gen_range gen_range();
// def gen_ternary(flag: bool) -> Iterator[list[int32]]:
__gen_gen_ternary gen_ternary(bool flag);
// def gen_walrus() -> Iterator[list[int32]]:
__gen_gen_walrus gen_walrus();
// def main() -> None:
void main();

// class Source:
struct Source {


    __gen_Source_gen gen() const;
    static constexpr std::string_view __tpy_class_name__ = "__main__.Source";
};

inline std::ostream& operator<<(std::ostream& os, const Source& obj) {
    ::tpy::print_object_default(os, "Source", obj);
    return os;
}

// def gen() -> Iterator[list[int32]]:
struct __gen_gen : public ::tpy::next_iter_mixin<__gen_gen, ::tpy::val_or_ref<std::vector<int32_t>>> {
    int32_t __state;
    int32_t i;
    ::tpy::frame_slot<std::vector<int32_t>> buf;

    enum : int32_t {
        S_INITIAL = 0,
        S_RESUME_0 = 1,
        S_JOIN_0 = 2,
        S_DONE = 3,
    };

    __gen_gen()
        : __state(S_INITIAL) {}

    std::expected<::tpy::val_or_ref<std::vector<int32_t>>, ::tpy::StopIteration> __next__();
    __gen_gen& __iter__() { return *this; }

    friend std::ostream& operator<<(std::ostream& os, const __gen_gen&) {
        return os << "<generator gen>";
    }
};

// def walk() -> Iterator[tuple[int32, list[int32]]]:
struct __gen_walk : public ::tpy::next_iter_mixin<__gen_walk, std::tuple<int32_t, std::vector<int32_t>*>> {
    int32_t __state;
    ::tpy::frame_slot<std::vector<int32_t>> stack;
    int32_t k;
    int32_t cur;
    ::tpy::frame_slot<std::vector<int32_t>> kids;

    enum : int32_t {
        S_INITIAL = 0,
        S_RESUME_0 = 1,
        S_JOIN_0 = 2,
        S_DONE = 3,
    };

    __gen_walk()
        : __state(S_INITIAL) {}

    std::expected<std::tuple<int32_t, std::vector<int32_t>*>, ::tpy::StopIteration> __next__();
    __gen_walk& __iter__() { return *this; }

    friend std::ostream& operator<<(std::ostream& os, const __gen_walk&) {
        return os << "<generator walk>";
    }
};

// def gen_range() -> Iterator[list[int32]]:
struct __gen_gen_range : public ::tpy::next_iter_mixin<__gen_gen_range, ::tpy::val_or_ref<std::vector<int32_t>>> {
    int32_t __state;
    int32_t _;
    ::tpy::frame_slot<std::vector<int32_t>> buf;
    ::tpy::frame_loop_slot<int32_t> __for_i_0;
    ::tpy::frame_loop_slot<int32_t> __for_stop_0;

    enum : int32_t {
        S_INITIAL = 0,
        S_RESUME_0 = 1,
        S_JOIN_0 = 2,
        S_DONE = 3,
    };

    __gen_gen_range()
        : __state(S_INITIAL) {}

    std::expected<::tpy::val_or_ref<std::vector<int32_t>>, ::tpy::StopIteration> __next__();
    __gen_gen_range& __iter__() { return *this; }

    friend std::ostream& operator<<(std::ostream& os, const __gen_gen_range&) {
        return os << "<generator gen_range>";
    }
};

// def gen_ternary(flag: bool) -> Iterator[list[int32]]:
struct __gen_gen_ternary : public ::tpy::next_iter_mixin<__gen_gen_ternary, ::tpy::val_or_ref<std::vector<int32_t>>> {
    int32_t __state;
    bool flag;
    int32_t i;
    ::tpy::frame_slot<std::vector<int32_t>> a;
    ::tpy::frame_slot<std::vector<int32_t>> b;

    enum : int32_t {
        S_INITIAL = 0,
        S_RESUME_0 = 1,
        S_JOIN_0 = 2,
        S_DONE = 3,
    };

    __gen_gen_ternary(bool flag_)
        : __state(S_INITIAL), flag(std::move(flag_)) {}

    std::expected<::tpy::val_or_ref<std::vector<int32_t>>, ::tpy::StopIteration> __next__();
    __gen_gen_ternary& __iter__() { return *this; }

    friend std::ostream& operator<<(std::ostream& os, const __gen_gen_ternary&) {
        return os << "<generator gen_ternary>";
    }
};

// def gen_walrus() -> Iterator[list[int32]]:
struct __gen_gen_walrus : public ::tpy::next_iter_mixin<__gen_gen_walrus, ::tpy::val_or_ref<std::vector<int32_t>>> {
    int32_t __state;
    int32_t i;
    ::tpy::frame_slot<std::vector<int32_t>> buf;
    std::vector<int32_t>* x = nullptr;

    enum : int32_t {
        S_INITIAL = 0,
        S_RESUME_0 = 1,
        S_JOIN_0 = 2,
        S_DONE = 3,
    };

    __gen_gen_walrus()
        : __state(S_INITIAL) {}

    std::expected<::tpy::val_or_ref<std::vector<int32_t>>, ::tpy::StopIteration> __next__();
    __gen_gen_walrus& __iter__() { return *this; }

    friend std::ostream& operator<<(std::ostream& os, const __gen_gen_walrus&) {
        return os << "<generator gen_walrus>";
    }
};

// def gen(self) -> Iterator[list[int32]]:
struct __gen_Source_gen : public ::tpy::next_iter_mixin<__gen_Source_gen, ::tpy::val_or_ref<std::vector<int32_t>>> {
    int32_t __state;
    const Source& __self;
    int32_t i;
    ::tpy::frame_slot<std::vector<int32_t>> buf;

    enum : int32_t {
        S_INITIAL = 0,
        S_RESUME_0 = 1,
        S_JOIN_0 = 2,
        S_DONE = 3,
    };

    __gen_Source_gen(const Source& __self)
        : __state(S_INITIAL), __self(__self) {}

    std::expected<::tpy::val_or_ref<std::vector<int32_t>>, ::tpy::StopIteration> __next__();
    __gen_Source_gen& __iter__() { return *this; }

    friend std::ostream& operator<<(std::ostream& os, const __gen_Source_gen&) {
        return os << "<generator Source.gen>";
    }
};

inline __gen_Source_gen Source::gen() const {
    return __gen_Source_gen(*this);
}

void __tpy_init();
} // namespace tpyapp::main
