// Generated by TurboPython Compiler
#pragma once

#include <tpy/tpy.hpp>
#include "tpystd/tpy/_types.hpp"
#include "tpystd/typing/_typing.hpp"

namespace tpyapp::main {

struct Fussy;

inline constexpr std::string_view __name__ = "__main__";

// def main():
void main();

// class Fussy:
struct Fussy {
    // _id: int32
    int32_t _id;
    bool __tpy_owned_ = true;

    // def __init__(self, id: int32):
    explicit Fussy(int32_t id);
    Fussy(const Fussy&) = delete;
    Fussy& operator=(const Fussy&) = delete;
    Fussy(Fussy&& other) noexcept;
    Fussy& operator=(Fussy&& other) noexcept;

    // def __del__(self):
    ~Fussy();
    static constexpr std::string_view __tpy_class_name__ = "__main__.Fussy";
};

inline std::ostream& operator<<(std::ostream& os, const Fussy& obj) {
    ::tpy::print_object_default(os, "Fussy", obj);
    return os;
}


// def __init__(self, id: int32):
//     self._id = id
inline Fussy::Fussy(int32_t id) : _id(id) {}

inline Fussy::Fussy(Fussy&& other) noexcept : _id(std::move(other._id)) {
    other.__tpy_owned_ = false;
}
inline Fussy& Fussy::operator=(Fussy&& other) noexcept {
    if (this != &other) {
        this->~Fussy();
        new (this) Fussy(std::move(other));
    }
    return *this;
}

// def __del__(self):
//     try:
//         print("del try", self._id)
//     except ValueError:
//         print("del handler")
//     finally:
//         print("del finally", self._id)
//         raise ValueError("cleanup failed")
inline Fussy::~Fussy() {
    if (!this->__tpy_owned_) return;
    ::tpy::DeferSignals __tpy_defer_signals;
    try {
        {
            try {
                try {
                    std::cout << "del try" << " " << this->_id << "\n" << ::tpy::check_signals;
                } catch (const ::tpy::ValueError&) {
                    std::cout << "del handler" << "\n" << ::tpy::check_signals;
                }
            } catch (...) {
                std::cout << "del finally" << " " << this->_id << "\n" << ::tpy::check_signals;
                throw ::tpy::ValueError("cleanup failed");
            }
            std::cout << "del finally" << " " << this->_id << "\n" << ::tpy::check_signals;
            throw ::tpy::ValueError("cleanup failed");
        }
    } catch (const std::exception& __del_exc) {
        ::tpy::report_del_exception(__del_exc);
    } catch (...) {
        ::tpy::report_del_exception();
    }
}
void __tpy_init();
} // namespace tpyapp::main
