// Generated by TurboPython Compiler
#include "main.hpp"

namespace tpyapp::main {


// def both(t: tuple[Rc[Node], Rc[Node]]) -> int32:
//     # Borrow form: tuple of Rc[T] borrows.
//     return t[0].get().value + t[1].get().value
int32_t both(const std::tuple<const ::tpystd::tplib::rc::Rc<Node>*, const ::tpystd::tplib::rc::Rc<Node>*>& t) {
    return (::tpy::add_check<int32_t>(std::get<0>(t)->get().value, std::get<1>(t)->get().value));
}

// def main() -> None:
//     a = Rc.new(Node(int32(10)))
//     b = Rc.new(Node(int32(20)))
//
//     pair: tuple[Rc[Node], Rc[Node]] = (a.clone(), b.clone())
//
//     print(both(pair))  # 30
//
//     # Mutate through one slot; the original handle sees it.
//     pair[0].get().value = int32(100)
//     print(a.get().value)  # 100 -- shared
//
//     # Mutate through the original; the tuple slot sees it.
//     b.get().value = int32(200)
//     print(pair[1].get().value)  # 200 -- shared
void main() {
    ::tpystd::tplib::rc::Rc<Node> a = Rc<Node>::new_<Node>(Node(10));
    ::tpystd::tplib::rc::Rc<Node> b = Rc<Node>::new_<Node>(Node(20));
    auto pair = std::tuple<::tpystd::tplib::rc::Rc<Node>, ::tpystd::tplib::rc::Rc<Node>>{a.clone(), b.clone()};
    std::cout << both(::tpy::tuple_to_pointer<std::tuple<const ::tpystd::tplib::rc::Rc<Node>*, const ::tpystd::tplib::rc::Rc<Node>*>>(pair)) << "\n";
    std::get<0>(pair).get().value = 100;
    std::cout << a.get().value << "\n";
    b.get().value = 200;
    std::cout << std::get<1>(pair).get().value << "\n";
}

// from tplib import Rc
//
// main()
void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    ::tpystd::tplib::__tpy_init();
    main();
}

} // namespace tpyapp::main

int __tpy_main(int argc, char* argv[]) {
    ::tpy::init_sys_argv(argc, argv);
    ::tpyapp::main::__tpy_init();
    return 0;
}

int main(int argc, char* argv[]) {
    ::tpy::process_startup();
    return __tpy_main(argc, argv);
}
