// Generated by TurboPython Compiler
#include "main.hpp"

namespace tpyapp::main {


// def main() -> None:
void main() {
    // h = Holder(100)
    Holder h = Holder(100);
    // c = Circle(5)
    Circle c = Circle(5);
    // print(h.method(c))  # v omitted: relies on the declaration's default
    std::cout << h.method(c) << "\n";
    // print(h.method(c, Vec(7)))
    std::cout << h.method(c, Vec(7)) << "\n";
}

void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    // main()
    main();
}

} // namespace tpyapp::main

int __tpy_main(int argc, char* argv[]) {
    ::tpy::init_sys_argv(argc, argv);
    ::tpyapp::main::__tpy_init();
    return 0;
}

int main(int argc, char* argv[]) {
    ::tpy::process_startup();
    return __tpy_main(argc, argv);
}
