// Generated by TurboPython Compiler
#include "main.hpp"

namespace tpyapp::main {


// def main() -> None:
void main() {
    // total: Int32 = 0
    int32_t total = 0;
    // def accumulate(x: Int32) -> None:
    auto accumulate = [&total](int32_t x) {
        // nonlocal total
        // total += x
        total = ::tpy::add_check<int32_t>(total, x);
    };
    // accumulate(10)
    accumulate(10);
    // accumulate(20)
    accumulate(20);
    // accumulate(30)
    accumulate(30);
    // print(total)
    std::cout << total << "\n";
}

void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    // main()
    main();
}

} // namespace tpyapp::main

int main(int argc, char* argv[]) {
    ::tpy::init_sys_argv(argc, argv);
    tpyapp::main::__tpy_init();
    return 0;
}
