// Generated by TurboPython Compiler
#pragma once

#include <tpy/tpy.hpp>
#include "tpystd/tpy/_types.hpp"
#include "tpystd/typing/_typing.hpp"
#include "tpystd/tplib.hpp"
#include "tpystd/tplib/box.hpp"
#include "tpystd/tplib/rc.hpp"

namespace tpyapp::main {

using ::tpystd::tplib::box::Box;
using ::tpystd::tplib::rc::Rc;

struct Greeter;
// @dynamic
// class Greeter(Protocol):
template<typename T>
concept __Greeter_Concept__ = requires(T& t) {
    { t.greet() } -> std::convertible_to<std::string_view>;
};

struct Greeter {
    virtual std::string greet() = 0;
    virtual ~Greeter() = default;
};

} // namespace tpyapp::main

template<> struct tpy::is_dyn_protocol_base<tpyapp::main::Greeter> : std::true_type {};

namespace tpyapp::main {

struct Frog;
struct Wrapper;

inline constexpr std::string_view __name__ = "__main__";

void main();

// class Frog:
struct Frog {
    // name: str
    std::string name;

    // def __init__(self, name: str) -> None:
    Frog() = default;
    explicit Frog(std::string_view name);

    // def greet(self) -> str:
    std::string greet() const;
    static constexpr std::string_view __tpy_class_name__ = "__main__.Frog";
};

inline std::ostream& operator<<(std::ostream& os, const Frog& obj) {
    ::tpy::print_object_default(os, "Frog", obj);
    return os;
}

// class Wrapper:
struct Wrapper {


    // def wrap[T](self, value: Own[T]) -> Own[Rc[T]]:
    template<typename T>
    ::tpystd::tplib::rc::Rc<T> wrap(::tpy::own_param_t<T> value) const {
        // return Rc.new(value)
        return Rc<T>::template new_<T>(std::move(value));
    }
    static constexpr std::string_view __tpy_class_name__ = "__main__.Wrapper";
};

inline std::ostream& operator<<(std::ostream& os, const Wrapper& obj) {
    ::tpy::print_object_default(os, "Wrapper", obj);
    return os;
}

} // namespace tpyapp::main

template<tpyapp::main::__Greeter_Concept__ T>
struct tpy::Adapter<tpyapp::main::Greeter, T> : tpyapp::main::Greeter {
    T inner;
    template<typename... Args>
    Adapter(Args&&... args) : inner(std::forward<Args>(args)...) {}
    std::string greet() override { return std::string(inner.greet()); }
};

template<tpyapp::main::__Greeter_Concept__ T>
struct tpy::RefAdapter<tpyapp::main::Greeter, T> : tpyapp::main::Greeter {
    T& inner;
    RefAdapter(T& ref) : inner(ref) {}
    std::string greet() override { return std::string(inner.greet()); }
};

namespace tpyapp::main {


// def __init__(self, name: str) -> None:
inline Frog::Frog(std::string_view name) : name(name) {}

// def greet(self) -> str:
inline std::string Frog::greet() const {
    // return self.name
    return this->name;
}
void __tpy_init();
} // namespace tpyapp::main
