// Generated by TurboPython Compiler
#pragma once

#include <tpy/tpy.hpp>
#include "tpystd/tpy/_types.hpp"
#include "tpystd/typing/_typing.hpp"

namespace tpyapp::main {

struct Cell;

inline constexpr std::string_view __name__ = "__main__";

// def main():
void main();

// class Cell:
struct Cell {
    // value: int32
    int32_t value;

    // def __init__(self, value: int32):
    Cell() = default;
    explicit Cell(int32_t value);

    // def singleton(self) -> int32:
    int32_t singleton();

    // def mixed(self) -> int32:
    int32_t mixed();

    // def inferred(self, other: Cell) -> int32:
    int32_t inferred(Cell& other) const;

    // def optional(self, other: Cell) -> int32:
    int32_t optional(Cell& other);

    // def owned_copy(self) -> int32:
    int32_t owned_copy();
    static constexpr std::string_view __tpy_class_name__ = "__main__.Cell";
};

inline std::ostream& operator<<(std::ostream& os, const Cell& obj) {
    ::tpy::print_object_default(os, "Cell", obj);
    return os;
}


// def __init__(self, value: int32):
//     self.value = value
inline Cell::Cell(int32_t value) : value(value) {}

// def singleton(self) -> int32:
//     packed = (self,)
//     # A singleton tuple holds the same receiver, not a copy.
//     packed[0].value = 12  # tpyc: ok
//     return self.value
inline int32_t Cell::singleton() {
    auto packed = std::tuple<Cell*>(this);
    std::get<0>(packed)->value = 12;
    return this->value;
}

// def mixed(self) -> int32:
//     packed = (self, self.value)
//     # The record remains shared while its captured scalar keeps the old value.
//     packed[0].value = 13  # tpyc: ok
//     return packed[1]
inline int32_t Cell::mixed() {
    auto packed = std::tuple<Cell*, int32_t>{this, this->value};
    std::get<0>(packed)->value = 13;
    return std::get<1>(packed);
}

// def inferred(self, other: Cell) -> int32:
//     saved = self
//     # Readonly self must still observe mutation through a shared mutable argument.
//     other.value = 14  # tpyc: ok
//     return saved.value
inline int32_t Cell::inferred(Cell& other) const {
    const Cell& saved = (*this);
    other.value = 14;
    return saved.value;
}

// def optional(self, other: Cell) -> int32:
//     saved: Cell | None = self
//     # Wrapping self in Optional must preserve observation through another alias.
//     other.value = 17  # tpyc: ok
//     if saved is not None:
//         return saved.value
//     return 0
inline int32_t Cell::optional(Cell& other) {
    Cell* saved = &((*this));
    other.value = 17;
    if ((saved != nullptr)) {
        return saved->value;
    }
    return 0;
}

// def owned_copy(self) -> int32:
//     saved = copy(self)
//     # This explicit copy must retain the old value after self changes.
//     self.value = 19  # tpyc: ok
//     return saved.value
inline int32_t Cell::owned_copy() {
    Cell saved = Cell((*this));
    this->value = 19;
    return saved.value;
}
void __tpy_init();
} // namespace tpyapp::main
