// Generated by TurboPython Compiler
#include "main.hpp"

namespace tpyapp::main {


// def main() -> None:
//     a: Array[int32, 3] = [int32(10), int32(20), int32(30)]
//     print(seq_at(a, int32(-1)))
//     print(seq_at(a, int32(0)))
//
//     sp: Span[int32] = a
//     print(seq_at(sp, int32(-1)))
//     print(seq_at(sp, int32(-2)))
void main() {
    std::array<int32_t, 3> a = {10, 20, 30};
    std::cout << ::tpyapp::main::seq_at(a, -1) << "\n" << ::tpy::check_signals;
    std::cout << ::tpyapp::main::seq_at(a, 0) << "\n" << ::tpy::check_signals;
    std::span<int32_t> sp = ::tpy::as_mut_span(a);
    std::cout << ::tpyapp::main::seq_at(sp, -1) << "\n" << ::tpy::check_signals;
    std::cout << ::tpyapp::main::seq_at(sp, -2) << "\n" << ::tpy::check_signals;
}

// main()
void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    ::tpyapp::main::main();
}

} // namespace tpyapp::main

int __tpy_main(int argc, char* argv[]) {
    ::tpy::init_sys_argv(argc, argv);
    ::tpyapp::main::__tpy_init();
    return 0;
}

int main(int argc, char* argv[]) {
    return ::tpy::run_main(argc, argv, &__tpy_main);
}
