// Generated by TurboPython Compiler
#include "main.hpp"

namespace tpyapp::main {


// async def get_val() -> Int32:
::tpystd::tpy::Poll<int32_t> __coro_get_val::__poll__(::tpy::Waker waker) {
    (void)waker;
    switch (__state) {
    case S_INITIAL: {
            // return Int32(7)
            __state = S_DONE;
            int32_t __tpy_async_ret = 7;
            return ::tpystd::tpy::Poll<int32_t>::ready(std::move(__tpy_async_ret));
        }
    case S_DONE: ::tpy::tpy_panic("poll after Ready");
    }
    __builtin_unreachable();
}


// async def get_val() -> Int32:
__coro_get_val get_val() {
    return __coro_get_val();
}

// async def main_coro() -> None:
::tpystd::tpy::Poll<::std::monostate> __coro_main_coro::__poll__(::tpy::Waker waker) {
    switch (__state) {
    case S_INITIAL: {
            // print(await get_val())  # await in argument position
            __sub_0.emplace();
            __state = S_AFTER_AWAIT_0;
        }
        [[fallthrough]];
    case S_AFTER_AWAIT_0: {
            if (__cancel_pending) { __cancel_pending = false; throw ::tpy::CancelledError(); }
            auto __r0 = __sub_0->__poll__(waker);
            if (__r0.is_pending()) return ::tpystd::tpy::Poll<::std::monostate>::pending();
            __await_lift_0 = std::move(__r0).value();
            __sub_0.reset();
            // print(await get_val())  # await in argument position
            std::cout << __await_lift_0 << "\n";
            // print(await get_val() + Int32(1))  # await mixed with binop
            __sub_1.emplace();
            __state = S_AFTER_AWAIT_1;
        }
        [[fallthrough]];
    case S_AFTER_AWAIT_1: {
            if (__cancel_pending) { __cancel_pending = false; throw ::tpy::CancelledError(); }
            auto __r1 = __sub_1->__poll__(waker);
            if (__r1.is_pending()) return ::tpystd::tpy::Poll<::std::monostate>::pending();
            __await_lift_1 = std::move(__r1).value();
            __sub_1.reset();
            // print(await get_val() + Int32(1))  # await mixed with binop
            std::cout << (::tpy::add_check<int32_t>(__await_lift_1, 1)) << "\n";
            __state = S_DONE;
            return ::tpystd::tpy::Poll<::std::monostate>::ready(::std::monostate{});
        }
    case S_DONE: ::tpy::tpy_panic("poll after Ready");
    }
    __builtin_unreachable();
}


// async def main_coro() -> None:
__coro_main_coro main_coro() {
    return __coro_main_coro();
}

// def main() -> None:
void main() {
    // asyncio.run(main_coro())
    ::tpystd::asyncio::run<std::monostate>(main_coro());
}

void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    // import asyncio
    ::tpystd::asyncio::__tpy_init();
    // main()
    main();
}

} // namespace tpyapp::main

int __tpy_main(int argc, char* argv[]) {
    ::tpy::init_sys_argv(argc, argv);
    ::tpyapp::main::__tpy_init();
    return 0;
}

int main(int argc, char* argv[]) {
    std::set_terminate(&::tpy::tpy_terminate_handler);
    return __tpy_main(argc, argv);
}
