// Generated by TurboPython Compiler
#include "main.hpp"

namespace tpy_user::main {


// 17: def greet(s: Speaker) -> None:
void greet(Speaker& s) {
    // 18:     print(s.speak())
    std::cout << s.speak() << "\n";
}

// 21: def main() -> None:
void main() {
    // 22:     greet(Dog())
    Dog __tmp_1{Dog()};
    greet(__tmp_1);
}

void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    // 24: main()
    main();
}

} // namespace tpy_user::main

int main(int argc, char* argv[]) {
    tpy::init_sys_argv(argc, argv);
    tpy_user::main::__tpy_init();
    return 0;
}
