// Generated by TurboPython Compiler
#include "main.hpp"

namespace tpyapp::main {

std::vector<int32_t>* zeros{};
std::vector<int32_t>* filled{};
std::vector<int32_t>* empty{};
int32_t n{};
std::vector<int32_t>* dynamic{};

// """Tests single-element list repeat with repeat_range codegen."""
//
// # Single element repeat - list
// zeros: list[int32] = [0] * 5
// print(len(zeros))
// print(zeros[0])
// print(zeros[4])
//
// # Single element repeat - list (via constructor)
// filled: list[int32] = [42] * 10
// print(len(filled))
// print(filled[0])
// print(filled[9])
//
// # Zero count repeat - produces empty list
// empty: list[int32] = [99] * 0
// print(len(empty))
//
// # Variable count
// n: int32 = 3
// dynamic: list[int32] = [7] * n
// print(len(dynamic))
// print(dynamic[0])
// print(dynamic[2])
void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    static std::vector<int32_t> __global_slot_1 = ::tpy::from_range<std::vector<int32_t>>(::tpy::repeat_range<int32_t>(5, {0}));
    zeros = &__global_slot_1;
    std::cout << ::tpy::__len__((*zeros)) << "\n" << ::tpy::check_signals;
    std::cout << ::tpy::__getitem__((*zeros), 0) << "\n" << ::tpy::check_signals;
    std::cout << ::tpy::__getitem__((*zeros), 4) << "\n" << ::tpy::check_signals;
    static std::vector<int32_t> __global_slot_2 = ::tpy::from_range<std::vector<int32_t>>(::tpy::repeat_range<int32_t>(10, {42}));
    filled = &__global_slot_2;
    std::cout << ::tpy::__len__((*filled)) << "\n" << ::tpy::check_signals;
    std::cout << ::tpy::__getitem__((*filled), 0) << "\n" << ::tpy::check_signals;
    std::cout << ::tpy::__getitem__((*filled), 9) << "\n" << ::tpy::check_signals;
    static std::vector<int32_t> __global_slot_3 = ::tpy::from_range<std::vector<int32_t>>(::tpy::repeat_range<int32_t>(0, {99}));
    empty = &__global_slot_3;
    std::cout << ::tpy::__len__((*empty)) << "\n" << ::tpy::check_signals;
    n = 3;
    static std::vector<int32_t> __global_slot_4 = ::tpy::from_range<std::vector<int32_t>>(::tpy::repeat_range<int32_t>(n, {7}));
    dynamic = &__global_slot_4;
    std::cout << ::tpy::__len__((*dynamic)) << "\n" << ::tpy::check_signals;
    std::cout << ::tpy::__getitem__((*dynamic), 0) << "\n" << ::tpy::check_signals;
    std::cout << ::tpy::__getitem__((*dynamic), 2) << "\n" << ::tpy::check_signals;
}

} // namespace tpyapp::main

int __tpy_main(int argc, char* argv[]) {
    ::tpy::init_sys_argv(argc, argv);
    ::tpyapp::main::__tpy_init();
    return 0;
}

int main(int argc, char* argv[]) {
    ::tpy::process_startup();
    return __tpy_main(argc, argv);
}
