// Generated by TurboPython Compiler
#pragma once

#include <tpy/tpy.hpp>
#include "tpystd/tpy/_types.hpp"
#include "tpystd/typing/_typing.hpp"

namespace tpyapp::bases {

struct Counter;
struct Tag;

inline constexpr std::string_view __name__ = "bases";

// class Counter:
struct Counter {
    // value: int32
    int32_t value;

    static constexpr std::string_view __tpy_class_name__ = "bases.Counter";
};

inline std::ostream& operator<<(std::ostream& os, const Counter& obj) {
    ::tpy::print_object_default(os, "Counter", obj);
    return os;
}

// class Tag:
struct Tag {
    // value: str
    std::string value;

    static constexpr std::string_view __tpy_class_name__ = "bases.Tag";
};

inline std::ostream& operator<<(std::ostream& os, const Tag& obj) {
    ::tpy::print_object_default(os, "Tag", obj);
    return os;
}

void __tpy_init();
} // namespace tpyapp::bases
