// Generated by TurboPython Compiler
#include "config.hpp"

namespace tpy_user::config {

tpy::Global<std::string_view> __name__;
// 3: MAX_VALUE: Int32 = Int32(100)
tpy::Global<int32_t> MAX_VALUE;

// 5: def get_max() -> Int32:
int32_t get_max() {
  // 6:     return MAX_VALUE
  return MAX_VALUE;
}

void __tpy_init() {
  __name__ = "config";
  // 3: MAX_VALUE: Int32 = Int32(100)
  MAX_VALUE = 100;
}

} // namespace tpy_user::config
