// Generated by TurboPython Compiler
#pragma once

#include <tpy/tpy.hpp>
#include "tpystd/builtins.hpp"
#include "tpystd/tpy.hpp"
#include "tpystd/typing.hpp"

namespace tpyapp::main {

struct E;
struct Data;

inline constexpr std::string_view __name__ = "__main__";

std::expected<Data, E> make_data(const ::tpy::BigInt& v);
std::expected<::tpy::BigInt, E> get_value(const ::tpy::BigInt& v);
void main();

// class E(Exception, ControlFlow):
struct E : ::tpy::Exception {

};

inline std::ostream& operator<<(std::ostream& os, const E& obj) {
    os << "E("
       << ")";
    return os;
}

// @nocopy
// class Data:
struct Data {
    // value: int
    ::tpy::BigInt value;

    // def __init__(self, v: int):
    Data() = default;
    explicit Data(const ::tpy::BigInt& v) : value(v) {}
    // non-copyable (@nocopy)
    Data(const Data&) = delete;
    Data& operator=(const Data&) = delete;
    Data(Data&&) = default;
    Data& operator=(Data&&) = default;
};

inline std::ostream& operator<<(std::ostream& os, const Data& obj) {
    os << "Data("
       << "value=" << obj.value
       << ")";
    return os;
}

void __tpy_init();
} // namespace tpyapp::main
