// Generated by TurboPython Compiler
#pragma once

#include <tpy/tpy.hpp>
#include "tpystd/tpy/_types.hpp"
#include "tpystd/typing/_typing.hpp"
#include "pkg_v.hpp"

namespace tpyapp::main {

struct Holder;

inline constexpr std::string_view __name__ = "__main__";

using ::tpyapp::pkg_v::V;

bool is_null(const ::tpyapp::pkg_v::V& v);
::tpyapp::pkg_v::V wrap(const ::tpyapp::pkg_v::V& v);
void main();

// class Holder:
struct Holder {
    // # Recursive alias used as a record field type.
    // value: V
    ::tpyapp::pkg_v::V value;

    // def __init__(self, value: Own[V]) -> None:
    explicit Holder(::tpyapp::pkg_v::V&& value) : value(std::move(value)) {}
};

inline std::ostream& operator<<(std::ostream& os, const Holder& obj) {
    ::tpy::print_object_default(os, "Holder", obj);
    return os;
}

void __tpy_init();
} // namespace tpyapp::main
