// Generated by TurboPython Compiler
#include "main.hpp"

namespace tpyapp::main {


// # Test str methods: strip, replace, find, startswith, upper, lower, count, is*
// def test_strip() -> None:
//     print("strip:", "  hello  ".strip())
//     print("lstrip:", "  hello  ".lstrip())
//     print("rstrip:", "  hello  ".rstrip())
//     print("strip tabs:", "\t hi \n".strip())
void test_strip() {
    std::cout << "strip:" << " " << ::tpy::str_strip("  hello  ") << "\n";
    std::cout << "lstrip:" << " " << ::tpy::str_lstrip("  hello  ") << "\n";
    std::cout << "rstrip:" << " " << ::tpy::str_rstrip("  hello  ") << "\n";
    std::cout << "strip tabs:" << " " << ::tpy::str_strip("\t hi \n") << "\n";
}

// def test_replace() -> None:
//     print("replace:", "aabaa".replace("a", "x"))
//     print("replace once:", "hello world".replace("o", "0"))
void test_replace() {
    std::cout << "replace:" << " " << ::tpy::str_replace("aabaa", "a", "x") << "\n";
    std::cout << "replace once:" << " " << ::tpy::str_replace("hello world", "o", "0") << "\n";
}

// def test_find() -> None:
//     print("find:", "hello".find("ll"))
//     print("find miss:", "hello".find("xyz"))
//     print("rfind:", "abcabc".rfind("abc"))
//     print("rfind miss:", "hello".rfind("xyz"))
void test_find() {
    std::cout << "find:" << " " << ::tpy::str_find("hello", "ll") << "\n";
    std::cout << "find miss:" << " " << ::tpy::str_find("hello", "xyz") << "\n";
    std::cout << "rfind:" << " " << ::tpy::str_rfind("abcabc", "abc") << "\n";
    std::cout << "rfind miss:" << " " << ::tpy::str_rfind("hello", "xyz") << "\n";
}

// def test_index() -> None:
//     print("index:", "hello".index("ell"))
void test_index() {
    std::cout << "index:" << " " << ::tpy::str_index("hello", "ell") << "\n";
}

// def test_startswith_endswith() -> None:
//     s = "hello world"
//     print("startswith:", s.startswith("hello"))
//     print("startswith miss:", s.startswith("world"))
//     print("endswith:", s.endswith("world"))
//     print("endswith miss:", s.endswith("hello"))
//     print("empty prefix:", s.startswith(""))
//     print("empty suffix:", s.endswith(""))
void test_startswith_endswith() {
    std::string_view s = "hello world";
    std::cout << "startswith:" << " " << ::tpy::print_bool(::tpy::str_startswith(s, "hello")) << "\n";
    std::cout << "startswith miss:" << " " << ::tpy::print_bool(::tpy::str_startswith(s, "world")) << "\n";
    std::cout << "endswith:" << " " << ::tpy::print_bool(::tpy::str_endswith(s, "world")) << "\n";
    std::cout << "endswith miss:" << " " << ::tpy::print_bool(::tpy::str_endswith(s, "hello")) << "\n";
    std::cout << "empty prefix:" << " " << ::tpy::print_bool(::tpy::str_startswith(s, "")) << "\n";
    std::cout << "empty suffix:" << " " << ::tpy::print_bool(::tpy::str_endswith(s, "")) << "\n";
}

// def test_upper_lower() -> None:
//     print("upper:", "Hello World 123".upper())
//     print("lower:", "Hello World 123".lower())
//     print("upper empty:", "".upper())
//     print("lower empty:", "".lower())
void test_upper_lower() {
    std::cout << "upper:" << " " << ::tpy::str_upper("Hello World 123") << "\n";
    std::cout << "lower:" << " " << ::tpy::str_lower("Hello World 123") << "\n";
    std::cout << "upper empty:" << " " << ::tpy::str_upper("") << "\n";
    std::cout << "lower empty:" << " " << ::tpy::str_lower("") << "\n";
}

// def test_count() -> None:
//     print("count:", "banana".count("an"))
//     print("count miss:", "hello".count("xyz"))
//     print("count single:", "aaa".count("a"))
void test_count() {
    std::cout << "count:" << " " << ::tpy::str_count("banana", "an") << "\n";
    std::cout << "count miss:" << " " << ::tpy::str_count("hello", "xyz") << "\n";
    std::cout << "count single:" << " " << ::tpy::str_count("aaa", "a") << "\n";
}

// def test_is_methods() -> None:
//     print("isdigit 123:", "123".isdigit())
//     print("isdigit abc:", "abc".isdigit())
//     print("isdigit empty:", "".isdigit())
//     print("isalpha abc:", "abc".isalpha())
//     print("isalpha 123:", "123".isalpha())
//     print("isalpha empty:", "".isalpha())
//     print("isalnum a1:", "abc123".isalnum())
//     print("isalnum !:", "abc!".isalnum())
//     print("isalnum empty:", "".isalnum())
//     print("isspace:", "  \t\n".isspace())
//     print("isspace no:", "  a  ".isspace())
//     print("isspace empty:", "".isspace())
void test_is_methods() {
    std::cout << "isdigit 123:" << " " << ::tpy::print_bool(::tpy::str_isdigit("123")) << "\n";
    std::cout << "isdigit abc:" << " " << ::tpy::print_bool(::tpy::str_isdigit("abc")) << "\n";
    std::cout << "isdigit empty:" << " " << ::tpy::print_bool(::tpy::str_isdigit("")) << "\n";
    std::cout << "isalpha abc:" << " " << ::tpy::print_bool(::tpy::str_isalpha("abc")) << "\n";
    std::cout << "isalpha 123:" << " " << ::tpy::print_bool(::tpy::str_isalpha("123")) << "\n";
    std::cout << "isalpha empty:" << " " << ::tpy::print_bool(::tpy::str_isalpha("")) << "\n";
    std::cout << "isalnum a1:" << " " << ::tpy::print_bool(::tpy::str_isalnum("abc123")) << "\n";
    std::cout << "isalnum !:" << " " << ::tpy::print_bool(::tpy::str_isalnum("abc!")) << "\n";
    std::cout << "isalnum empty:" << " " << ::tpy::print_bool(::tpy::str_isalnum("")) << "\n";
    std::cout << "isspace:" << " " << ::tpy::print_bool(::tpy::str_isspace("  \t\n")) << "\n";
    std::cout << "isspace no:" << " " << ::tpy::print_bool(::tpy::str_isspace("  a  ")) << "\n";
    std::cout << "isspace empty:" << " " << ::tpy::print_bool(::tpy::str_isspace("")) << "\n";
}

// def test_isupper_islower() -> None:
//     print("isupper ABC:", "ABC".isupper())
//     print("isupper abc:", "abc".isupper())
//     print("isupper ABC123:", "ABC123".isupper())
//     print("isupper 123:", "123".isupper())
//     print("isupper empty:", "".isupper())
//     print("islower abc:", "abc".islower())
//     print("islower ABC:", "ABC".islower())
//     print("islower abc123:", "abc123".islower())
//     print("islower 123:", "123".islower())
//     print("islower empty:", "".islower())
void test_isupper_islower() {
    std::cout << "isupper ABC:" << " " << ::tpy::print_bool(::tpy::str_isupper("ABC")) << "\n";
    std::cout << "isupper abc:" << " " << ::tpy::print_bool(::tpy::str_isupper("abc")) << "\n";
    std::cout << "isupper ABC123:" << " " << ::tpy::print_bool(::tpy::str_isupper("ABC123")) << "\n";
    std::cout << "isupper 123:" << " " << ::tpy::print_bool(::tpy::str_isupper("123")) << "\n";
    std::cout << "isupper empty:" << " " << ::tpy::print_bool(::tpy::str_isupper("")) << "\n";
    std::cout << "islower abc:" << " " << ::tpy::print_bool(::tpy::str_islower("abc")) << "\n";
    std::cout << "islower ABC:" << " " << ::tpy::print_bool(::tpy::str_islower("ABC")) << "\n";
    std::cout << "islower abc123:" << " " << ::tpy::print_bool(::tpy::str_islower("abc123")) << "\n";
    std::cout << "islower 123:" << " " << ::tpy::print_bool(::tpy::str_islower("123")) << "\n";
    std::cout << "islower empty:" << " " << ::tpy::print_bool(::tpy::str_islower("")) << "\n";
}

// def test_capitalize_title_swapcase() -> None:
//     print("capitalize:", "hello world".capitalize())
//     print("capitalize upper:", "HELLO".capitalize())
//     print("capitalize empty:", "".capitalize())
//     print("title:", "hello world foo".title())
//     print("title mixed:", "they're bill's".title())
//     print("swapcase:", "Hello World".swapcase())
//     print("swapcase empty:", "".swapcase())
void test_capitalize_title_swapcase() {
    std::cout << "capitalize:" << " " << ::tpy::str_capitalize("hello world") << "\n";
    std::cout << "capitalize upper:" << " " << ::tpy::str_capitalize("HELLO") << "\n";
    std::cout << "capitalize empty:" << " " << ::tpy::str_capitalize("") << "\n";
    std::cout << "title:" << " " << ::tpy::str_title("hello world foo") << "\n";
    std::cout << "title mixed:" << " " << ::tpy::str_title("they're bill's") << "\n";
    std::cout << "swapcase:" << " " << ::tpy::str_swapcase("Hello World") << "\n";
    std::cout << "swapcase empty:" << " " << ::tpy::str_swapcase("") << "\n";
}

// def test_removeprefix_removesuffix() -> None:
//     print("removeprefix:", "TestCase".removeprefix("Test"))
//     print("removeprefix miss:", "TestCase".removeprefix("Foo"))
//     print("removesuffix:", "TestCase".removesuffix("Case"))
//     print("removesuffix miss:", "TestCase".removesuffix("Foo"))
//     print("removesuffix empty:", "hello".removesuffix(""))
void test_removeprefix_removesuffix() {
    std::cout << "removeprefix:" << " " << ::tpy::str_removeprefix("TestCase", "Test") << "\n";
    std::cout << "removeprefix miss:" << " " << ::tpy::str_removeprefix("TestCase", "Foo") << "\n";
    std::cout << "removesuffix:" << " " << ::tpy::str_removesuffix("TestCase", "Case") << "\n";
    std::cout << "removesuffix miss:" << " " << ::tpy::str_removesuffix("TestCase", "Foo") << "\n";
    std::cout << "removesuffix empty:" << " " << ::tpy::str_removesuffix("hello", "") << "\n";
}

// def test_rindex() -> None:
//     print("rindex:", "abcabc".rindex("abc"))
void test_rindex() {
    std::cout << "rindex:" << " " << ::tpy::str_rindex("abcabc", "abc") << "\n";
}

// def test_splitlines() -> None:
//     lines = "one\ntwo\nthree".splitlines()
//     print("splitlines:", len(lines), lines[0], lines[1], lines[2])
//     lines2 = "a\r\nb\nc".splitlines()
//     print("splitlines crlf:", len(lines2), lines2[0], lines2[1], lines2[2])
void test_splitlines() {
    std::vector<std::string> lines = ::tpy::str_splitlines("one\ntwo\nthree");
    std::cout << "splitlines:" << " " << ::tpy::__len__(lines) << " " << ::tpy::__getitem__(lines, 0) << " " << ::tpy::__getitem__(lines, 1) << " " << ::tpy::__getitem__(lines, 2) << "\n";
    std::vector<std::string> lines2 = ::tpy::str_splitlines("a\r\nb\nc");
    std::cout << "splitlines crlf:" << " " << ::tpy::__len__(lines2) << " " << ::tpy::__getitem__(lines2, 0) << " " << ::tpy::__getitem__(lines2, 1) << " " << ::tpy::__getitem__(lines2, 2) << "\n";
}

// def test_chaining() -> None:
//     result = "  Hello, World!  ".strip().lower().replace("world", "python")
//     print("chain:", result)
void test_chaining() {
    std::string result = ::tpy::str_replace(::tpy::str_lower(::tpy::str_strip("  Hello, World!  ")), "world", "python");
    std::cout << "chain:" << " " << result << "\n";
}

// test_strip()
// test_replace()
// test_find()
// test_index()
// test_startswith_endswith()
// test_upper_lower()
// test_count()
// test_is_methods()
// test_isupper_islower()
// test_capitalize_title_swapcase()
// test_removeprefix_removesuffix()
// test_rindex()
// test_splitlines()
// test_chaining()
void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    test_strip();
    test_replace();
    test_find();
    test_index();
    test_startswith_endswith();
    test_upper_lower();
    test_count();
    test_is_methods();
    test_isupper_islower();
    test_capitalize_title_swapcase();
    test_removeprefix_removesuffix();
    test_rindex();
    test_splitlines();
    test_chaining();
}

} // namespace tpyapp::main

int __tpy_main(int argc, char* argv[]) {
    ::tpy::init_sys_argv(argc, argv);
    ::tpyapp::main::__tpy_init();
    return 0;
}

int main(int argc, char* argv[]) {
    ::tpy::process_startup();
    return __tpy_main(argc, argv);
}
