// Generated by TurboPython Compiler
#pragma once

#include <tpy/tpy.hpp>
#include "tpy.hpp"
#include "typing.hpp"

namespace tpy_user::main {

struct Config;

inline constexpr std::string_view __name__ = "__main__";

void show_guarded(const Config& cfg);
void show_truthy(const Config& cfg);
void main();

// class Config:
struct Config {
    // port: Optional[Int32]
    std::optional<int32_t> port;
    // name: Optional[str]
    std::optional<std::string> name;
    // flag: Optional[bool]
    std::optional<bool> flag;
    // ratio: Optional[float]
    std::optional<double> ratio;

    // def __init__(self, port: Optional[Int32], name: Optional[str],
    Config() = default;
    explicit Config(std::optional<int32_t> port, std::optional<std::string_view> name, std::optional<bool> flag, std::optional<double> ratio) : port(port), name(name ? std::make_optional(std::string(*name)) : std::nullopt), flag(flag), ratio(ratio) {}
};

inline std::ostream& operator<<(std::ostream& os, const Config& obj) {
    os << "Config("
       << "port=" << ::tpy::print_optional_val(obj.port)
       << ", "
       << "name=" << (obj.name.has_value() ? std::string("'") + std::string(obj.name.value()) + "'" : std::string("None"))
       << ", "
       << "flag=" << ::tpy::print_optional_val<::tpy::print_bool, bool>(obj.flag)
       << ", "
       << "ratio=" << ::tpy::print_optional_val<::tpy::print_float, double>(obj.ratio)
       << ")";
    return os;
}

void __tpy_init();
} // namespace tpy_user::main
