// Generated by TurboPython Compiler
#include "main.hpp"

namespace tpy_user::main {

std::string_view __name__;

// 7: def main() -> None:
void main() {
  // 8:     p: Point = Point()
  Point p = Point();
  // 9:     p.x = 1
  p.x = 1;
  // 10:     p.y = 2
  p.y = 2;
  // 11:     items: list[Point] = []
  std::vector<Point> items = std::vector<Point>{};
  // 14:     items.append(p)           # tpyc: warning(/copies Point into owned storage/)
  items.push_back(p);
  // 15:     items[0] = p              # tpyc: warning(/copies Point into container/)
  tpy::set_item(items, 0, p);
  // 16:     items.insert(0, p)        # tpyc: warning(/copies Point into owned storage/)
  tpy::list_insert(items, 0, p);
  // 19:     items.append(copy(p))     # tpyc: ok
  items.push_back(p);
  // 20:     items[0] = copy(p)        # tpyc: ok
  tpy::set_item(items, 0, p);
  // 21:     items.insert(0, copy(p))  # tpyc: ok
  tpy::list_insert(items, 0, p);
  // 24:     items.append(Point())     # tpyc: ok
  items.push_back(Point());
  // 25:     items[0] = Point()        # tpyc: ok
  tpy::set_item(items, 0, Point());
  // 28:     nums: list[Int32] = []
  std::vector<int32_t> nums = std::vector<int32_t>{};
  // 29:     x: Int32 = 42
  int32_t x = 42;
  // 30:     nums.append(x)            # tpyc: ok
  nums.push_back(x);
  // 31:     nums[0] = x               # tpyc: ok
  tpy::set_item(nums, 0, x);
  // 33:     print(len(items))
  std::cout << tpy::__len__(items) << "\n";
}

void __tpy_init() {
  static bool initialized = false;
  if (initialized) return;
  initialized = true;

  __name__ = "__main__";
  // 35: main()
  main();
}

} // namespace tpy_user::main

int main(int argc, char* argv[]) {
  tpy::init_sys_argv(argc, argv);
  tpy_user::main::__tpy_init();
  return 0;
}
