// Generated by TurboPython Compiler
#pragma once

#include <tpy/tpy.hpp>
#include "tpystd/tpy/_types.hpp"
#include "tpystd/typing/_typing.hpp"

namespace tpyapp::main {

struct Rec;
struct W;
struct ListTaker;
struct DictTaker;
struct SetTaker;
struct RecListTaker;
struct BufTaker;

inline constexpr std::string_view __name__ = "__main__";

// def fill(xs: list[int32]) -> None:
void fill(std::vector<int32_t>& xs);
// def main() -> None:
void main();

// class Rec:
struct Rec {
    // x: int32
    int32_t x;

    // def __init__(self, x: int32) -> None:
    Rec() = default;
    explicit Rec(int32_t x);
    static constexpr std::string_view __tpy_class_name__ = "__main__.Rec";
};

inline std::ostream& operator<<(std::ostream& os, const Rec& obj) {
    ::tpy::print_object_default(os, "Rec", obj);
    return os;
}

// class W:
struct W {
    // items: list[int32]
    std::vector<int32_t> items;
    // counts: dict[str, int32]
    ::tpy::ordered_map<std::string, int32_t> counts;
    // tags: set[int32]
    ::tpy::ordered_set<int32_t> tags;
    // recs: list[Rec]
    std::vector<Rec> recs;
    // buf: bytearray
    ::tpy::ByteArray buf;

    // def __init__(self) -> None:
    W();
    static constexpr std::string_view __tpy_class_name__ = "__main__.W";
};

inline std::ostream& operator<<(std::ostream& os, const W& obj) {
    ::tpy::print_object_default(os, "W", obj);
    return os;
}

// class ListTaker:
struct ListTaker {
    // n: int32
    int32_t n;

    // def __init__(self, xs: list[int32]) -> None:
    ListTaker() = default;
    explicit ListTaker(std::vector<int32_t>& xs);
    static constexpr std::string_view __tpy_class_name__ = "__main__.ListTaker";
};

inline std::ostream& operator<<(std::ostream& os, const ListTaker& obj) {
    ::tpy::print_object_default(os, "ListTaker", obj);
    return os;
}

// class DictTaker:
struct DictTaker {
    // n: int32
    int32_t n;

    // def __init__(self, d: dict[str, int32]) -> None:
    DictTaker() = default;
    explicit DictTaker(::tpy::ordered_map<std::string, int32_t>& d);
    static constexpr std::string_view __tpy_class_name__ = "__main__.DictTaker";
};

inline std::ostream& operator<<(std::ostream& os, const DictTaker& obj) {
    ::tpy::print_object_default(os, "DictTaker", obj);
    return os;
}

// class SetTaker:
struct SetTaker {
    // n: int32
    int32_t n;

    // def __init__(self, s: set[int32]) -> None:
    SetTaker() = default;
    explicit SetTaker(::tpy::ordered_set<int32_t>& s);
    static constexpr std::string_view __tpy_class_name__ = "__main__.SetTaker";
};

inline std::ostream& operator<<(std::ostream& os, const SetTaker& obj) {
    ::tpy::print_object_default(os, "SetTaker", obj);
    return os;
}

// class RecListTaker:
struct RecListTaker {
    // n: int32
    int32_t n;

    // def __init__(self, rs: list[Rec]) -> None:
    RecListTaker() = default;
    explicit RecListTaker(std::vector<Rec>& rs);
    static constexpr std::string_view __tpy_class_name__ = "__main__.RecListTaker";
};

inline std::ostream& operator<<(std::ostream& os, const RecListTaker& obj) {
    ::tpy::print_object_default(os, "RecListTaker", obj);
    return os;
}

// class BufTaker:
struct BufTaker {
    // n: int32
    int32_t n;

    // def __init__(self, b: bytearray) -> None:
    BufTaker() = default;
    explicit BufTaker(::tpy::ByteArray& b);
    static constexpr std::string_view __tpy_class_name__ = "__main__.BufTaker";
};

inline std::ostream& operator<<(std::ostream& os, const BufTaker& obj) {
    ::tpy::print_object_default(os, "BufTaker", obj);
    return os;
}


// def __init__(self, x: int32) -> None:
//     self.x = x
inline Rec::Rec(int32_t x) : x(x) {}

// def __init__(self) -> None:
//     self.items = [1]
//     self.counts = {"a": 1}
//     self.tags = {1}
//     self.recs = [Rec(1)]
//     self.buf = bytearray(b"a")
inline W::W() : items(std::vector<int32_t>{1}), counts(::tpy::ordered_map<std::string, int32_t>({{"a", 1}})), tags(::tpy::ordered_set<int32_t>({1})), recs(std::vector<Rec>{Rec(1)}), buf(::tpy::ByteArray(::tpy::bytes_literal("a", 1))) {}

// def __init__(self, xs: list[int32]) -> None:
//     xs.append(9)  # tpyc: ok
//     self.n = len(xs)
inline ListTaker::ListTaker(std::vector<int32_t>& xs) {
    xs.push_back(9);
    this->n = ::tpy::__len__(xs);
}

// def __init__(self, d: dict[str, int32]) -> None:
//     d["b"] = 2
//     self.n = len(d)
inline DictTaker::DictTaker(::tpy::ordered_map<std::string, int32_t>& d) {
    ::tpy::__setitem__(d, "b", 2);
    this->n = ::tpy::__len__(d);
}

// def __init__(self, s: set[int32]) -> None:
//     s.add(2)
//     self.n = len(s)
inline SetTaker::SetTaker(::tpy::ordered_set<int32_t>& s) {
    s.insert(2);
    this->n = ::tpy::__len__(s);
}

// def __init__(self, rs: list[Rec]) -> None:
//     rs.append(Rec(2))
//     self.n = len(rs)
inline RecListTaker::RecListTaker(std::vector<Rec>& rs) {
    rs.push_back(Rec(2));
    this->n = ::tpy::__len__(rs);
}

// def __init__(self, b: bytearray) -> None:
//     b.append(98)
//     self.n = len(b)
inline BufTaker::BufTaker(::tpy::ByteArray& b) {
    b.push_back(98);
    this->n = ::tpy::__len__(b);
}
void __tpy_init();
} // namespace tpyapp::main
