// Generated by TurboPython Compiler
#pragma once

#include <tpy/tpy.hpp>
#include "tpystd/tpy/_types.hpp"
#include "tpystd/typing/_typing.hpp"
#include "tones.hpp"

namespace tpyapp::palette {

using ::tpyapp::tones::Shade;

inline constexpr std::string_view __name__ = "palette";

void __tpy_init();
} // namespace tpyapp::palette
