// Generated by TurboPython Compiler
#include "main.hpp"

namespace tpyapp::main {


// def consume(h: Own[Handle]) -> None:
void consume(Handle&& h) {
    // print("use", h.id)
    std::cout << "use" << " " << h.id << "\n";
}

// def main():
void main() {
    // h = Handle(1)
    Handle h = Handle(1);
    // consume(h)
    consume(std::move(h));
    // print("---")
    std::cout << "---" << "\n";
    // consume(Handle(2))
    consume(Handle(2));
    // print("done")
    std::cout << "done" << "\n";
}

void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    // main()
    main();
}

} // namespace tpyapp::main

int __tpy_main(int argc, char* argv[]) {
    ::tpy::init_sys_argv(argc, argv);
    tpyapp::main::__tpy_init();
    return 0;
}

int main(int argc, char* argv[]) {
    std::set_terminate(&::tpy::tpy_terminate_handler);
    return __tpy_main(argc, argv);
}
