// Generated by TurboPython Compiler
#include "main.hpp"

namespace tpyapp::main {


// def main() -> None:
void main() {
    // r: Rc[Pet] = Rc.new(Parrot("Polly"))
    ::tpystd::tplib::rc::Rc<Pet> r = Rc<Pet>::new_<Parrot>(Parrot("Polly"));
    // print(r.get().name())
    std::cout << r.get().name() << "\n";
}

void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    // from tplib import Rc
    ::tpystd::tplib::__tpy_init();
    // main()
    main();
}

} // namespace tpyapp::main

int __tpy_main(int argc, char* argv[]) {
    ::tpy::init_sys_argv(argc, argv);
    ::tpyapp::main::__tpy_init();
    return 0;
}

int main(int argc, char* argv[]) {
    ::tpy::process_startup();
    return __tpy_main(argc, argv);
}
