// Generated by TurboPython Compiler
#pragma once

#include <tpy/tpy.hpp>

namespace tpy_user::main {

// @dynamic
// class Pet(Protocol):
template<typename T>
concept __Pet_Concept__ = requires(T& t) {
    { t.name() } -> std::convertible_to<std::string>;
};

struct Pet {
    virtual std::string name() = 0;
    virtual ~Pet() = default;
};

} // namespace tpy_user::main

template<tpy_user::main::__Pet_Concept__ T>
struct tpy::Adapter<tpy_user::main::Pet, T> : tpy_user::main::Pet {
    T inner;
    template<typename... Args>
    Adapter(Args&&... args) : inner(std::forward<Args>(args)...) {}
    std::string name() override { return inner.name(); }
};

template<tpy_user::main::__Pet_Concept__ T>
struct tpy::RefAdapter<tpy_user::main::Pet, T> : tpy_user::main::Pet {
    T& inner;
    RefAdapter(T& ref) : inner(ref) {}
    std::string name() override { return inner.name(); }
};

namespace tpy_user::main {

struct Dog;
struct Cat;

inline constexpr std::string_view __name__ = "__main__";

void greet(Pet& pet);
void main();

// class Dog(Pet):
struct Dog : Pet {


    //     def name(self) -> str:
    std::string name() override {
        //         return "Rex"
        return "Rex";
    }
};

inline std::ostream& operator<<(std::ostream& os, const Dog& obj) {
    os << "Dog("
       << ")";
    return os;
}

// class Cat:
struct Cat {


    //     def name(self) -> str:
    std::string name() const {
        //         return "Whiskers"
        return "Whiskers";
    }
};

inline std::ostream& operator<<(std::ostream& os, const Cat& obj) {
    os << "Cat("
       << ")";
    return os;
}

void __tpy_init();
} // namespace tpy_user::main
