// Generated by TurboPython Compiler
#include "main.hpp"

namespace tpyapp::main {


// def main():
//     # @nocopy via record method at last use
//     holder = Holder()
//     holder.h = Handle()
//     h1 = Handle()
//     h1.fd = 10
//     holder.take(h1)  # tpyc: ok
//     print(holder.h.fd)
//
//     # @nocopy via generic ctor at last use
//     h2 = Handle()
//     h2.fd = 20
//     gh = GenericHolder[Handle](h2)  # tpyc: ok
//     print(gh.item.fd)
//
//     # @nocopy via generic method at last use
//     h3 = Handle()
//     h3.fd = 30
//     gh.replace(h3)  # tpyc: ok
//     print(gh.item.fd)
void main() {
    Holder holder = Holder();
    holder.h = Handle();
    Handle h1 = Handle();
    h1.fd = 10;
    holder.take(std::move(h1));
    std::cout << holder.h.fd << "\n";
    Handle h2 = Handle();
    h2.fd = 20;
    GenericHolder<Handle> gh = GenericHolder<Handle>(std::move(h2));
    std::cout << gh.item.fd << "\n";
    Handle h3 = Handle();
    h3.fd = 30;
    gh.replace(std::move(h3));
    std::cout << gh.item.fd << "\n";
}

// main()
void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    main();
}

} // namespace tpyapp::main

int __tpy_main(int argc, char* argv[]) {
    ::tpy::init_sys_argv(argc, argv);
    ::tpyapp::main::__tpy_init();
    return 0;
}

int main(int argc, char* argv[]) {
    ::tpy::process_startup();
    return __tpy_main(argc, argv);
}
