// Generated by TurboPython Compiler
#include "itersrc.hpp"
#include "itersrc_inl.hpp"

namespace tpyapp::itersrc {



// def walk() -> Iterator[int32]:
__gen_walk walk() {
    return __gen_walk();
}

void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

}

} // namespace tpyapp::itersrc
