// Generated by TurboPython Compiler
#pragma once

#include <tpy/tpy.hpp>
#include "tpystd/builtins.hpp"
#include "tpystd/tpy.hpp"
#include "tpystd/typing.hpp"
#include "tpystd/tplib.hpp"
#include "tpystd/tplib/json.hpp"
#include "tpystd/tplib/json/parser.hpp"
#include "tpystd/tplib/json/writer.hpp"

namespace tpyapp::main {

enum class Color : int32_t {
    Red = 0,
};

} // namespace tpyapp::main

template<>
struct tpy::EnumUtil<tpyapp::main::Color> {
    static std::string_view name(tpyapp::main::Color e);
    static const std::array<tpyapp::main::Color, 1> members;
    static tpyapp::main::Color from_value(int32_t v);
    static tpyapp::main::Color from_name(std::string_view s);
    static std::optional<tpyapp::main::Color> try_parse(std::string_view s);
};

namespace tpyapp::main {

inline std::ostream& operator<<(std::ostream& __os, Color __e) {
    return __os << "Color." << ::tpy::EnumUtil<Color>::name(__e);
}

struct Item;

inline constexpr std::string_view __name__ = "__main__";

void main();

// @model
// class Item:
struct Item {
    // name: str
    std::string name;
    // color: Color
    Color color;

    Item() = default;
    explicit Item(std::string_view name, Color color) : name(name), color(color) {}

    bool __eq__(const Item& other) const {
        return ((this->name == other.name) && (this->color == other.color));
    }

    static std::expected<Item, ::tpystd::tplib::json::parser::JsonError> __json_decode__(::tpystd::tplib::json::parser::JsonReader& __reader) {
        {
            auto __try_tmp_1 = __reader.read_object_start();
            if (!__try_tmp_1.has_value()) return ::tpy::make_unexpected(__try_tmp_1.error());
        }
        std::string name = "";
        std::optional<Color> color = std::nullopt;
        while (__reader.has_next()) {
            std::string_view __key;
            {
                auto __try_tmp_2 = __reader.read_key_raw();
                if (!__try_tmp_2.has_value()) return ::tpy::make_unexpected(__try_tmp_2.error());
                __key = ::tpy::unwrap_ref(*__try_tmp_2);
            }
            auto& __match_subject = __key;
            if (__match_subject == "name") {
                std::string __name_1;
                {
                    auto __try_tmp_3 = __reader.read_str();
                    if (!__try_tmp_3.has_value()) return ::tpy::make_unexpected(__try_tmp_3.error());
                    __name_1 = ::tpy::unwrap_ref(*__try_tmp_3);
                }
                name = __name_1;
            } else if (__match_subject == "color") {
                std::string __estr_3;
                {
                    auto __try_tmp_4 = __reader.read_str();
                    if (!__try_tmp_4.has_value()) return ::tpy::make_unexpected(__try_tmp_4.error());
                    __estr_3 = ::tpy::unwrap_ref(*__try_tmp_4);
                }
                std::optional<Color> __parsed_4 = ::tpy::EnumUtil<Color>::try_parse(__estr_3);
                if ((!__parsed_4.has_value())) {
                    return ::tpy::make_unexpected(::tpystd::tplib::json::parser::JsonError("invalid enum value for 'Color'"));
                }
                Color __color_2 = (*__parsed_4);
                color = __color_2;
            } else {
                {
                    auto __try_tmp_5 = __reader.skip_value();
                    if (!__try_tmp_5.has_value()) return ::tpy::make_unexpected(__try_tmp_5.error());
                }
            }
        }
        {
            auto __try_tmp_6 = __reader.read_object_end();
            if (!__try_tmp_6.has_value()) return ::tpy::make_unexpected(__try_tmp_6.error());
        }
        if ((!color.has_value())) {
            return ::tpy::make_unexpected(::tpystd::tplib::json::parser::JsonError("missing required field 'color'"));
        }
        return Item(name, (*color));
    }

    static Item from_json(std::string_view __s) {
        ::tpystd::tplib::json::parser::JsonReader __reader = ::tpystd::tplib::json::parser::JsonReader(__s);
        std::optional<Item> __result = std::nullopt;
        {
            std::optional<::tpystd::tplib::json::parser::JsonError> __err_opt_7;
            {
                auto __try_tmp_8 = Item::__json_decode__(__reader);
                if (!__try_tmp_8.has_value()) { __err_opt_7 = std::move(__try_tmp_8.error()); goto __except_7; }
                __result = ::tpy::unwrap_ref(*__try_tmp_8);
            }
            goto __after_try_7;
            // except tplib.json.parser.JsonError:
            __except_7:;
            {
                auto& __e = *__err_opt_7;
                ::tpy::tpy_panic(__e.message);
            }
            __after_try_7:;
        }
        if (!((__result.has_value()))) ::tpy::tpy_panic("json: unreachable");
        return (*__result);
    }

    static std::expected<Item, ::tpystd::tplib::json::parser::JsonError> try_from_json(std::string_view __s) {
        ::tpystd::tplib::json::parser::JsonReader __reader = ::tpystd::tplib::json::parser::JsonReader(__s);
        return Item::__json_decode__(__reader);
    }

    void __json_encode__(::tpystd::tplib::json::writer::JsonWriter& __writer) const {
        __writer.object_start();
        __writer.key("name");
        __writer.write_str(this->name);
        __writer.key("color");
        __writer.write_str(::tpy::EnumUtil<Color>::name(this->color));
        __writer.object_end();
    }

    std::string to_json(int32_t indent = 0) const {
        ::tpystd::tplib::json::writer::JsonWriter __writer = ::tpystd::tplib::json::writer::JsonWriter(indent);
        __json_encode__(__writer);
        return __writer.finish();
    }

    friend bool operator==(const Item& lhs, const Item& other) {
        return lhs.__eq__(other);
    }

    std::string __repr__() const {
        std::ostringstream __os;
        __os << "Item("
           << "name=" << "'" << this->name << "'"
           << ", "
           << "color=" << this->color
           << ")";
        return __os.str();
    }
};

inline std::ostream& operator<<(std::ostream& os, const Item& obj) {
    os << obj.__repr__();
    return os;
}

void __tpy_init();
} // namespace tpyapp::main
