# tpy: cpp_namespace("tpystd::typing")
from tpy import Int32
from .._bootstrap._decorators import readonly
from .._bootstrap._extern import builtin_type, builtin_decorator


@builtin_type("typing.Protocol")
class Protocol: ...

@builtin_type("typing.Self")
class Self: ...

@builtin_type("typing.Optional")
class Optional: ...

@builtin_type("typing.Final")
class Final: ...

@builtin_type("typing.Callable")
class Callable: ...

@builtin_type("typing.Literal")
class Literal: ...

@builtin_type("typing.TypedDict")
class TypedDict: ...

@builtin_type("typing.Unpack")
class Unpack: ...

@builtin_decorator("typing.overload")
def overload(): ...

@builtin_decorator("typing.override")
def override(): ...


class Sized(Protocol):
    @readonly
    def __len__(self) -> Int32: ...


class Sequence[T](Protocol):
    @readonly
    def __len__(self) -> Int32: ...
    @readonly
    def __getitem__(self, index: Int32) -> T: ...


class MutableSequence[T](Protocol):
    @readonly
    def __len__(self) -> Int32: ...
    def __getitem__(self, index: Int32) -> T: ...
    def __setitem__(self, index: Int32, value: T) -> None: ...


class Iterator[T](Protocol):
    def __next__(self) -> T: ...
    def __iter__(self) -> Self: ...


class Iterable[T](Protocol):
    def __iter__(self) -> Iterator[T]: ...
