// Generated by TurboPython Compiler
#include "main.hpp"

namespace tpyapp::main {


// def maybe_neg_one(do_raise: bool) -> int:
//     with Suppressor():
//         if do_raise:
//             raise ValueError("boom")
//         return 100
//     return -1
::tpy::BigInt maybe_neg_one(bool do_raise) {
    auto __ctx_1 = Suppressor();
    __ctx_1.__enter__();
    bool __fin_ran_1 = false;
    try {
        if (do_raise) {
            throw ::tpy::ValueError("boom");
        }
        ::tpy::BigInt __tpy_ret_0 = ::tpy::BigInt(100);
        __fin_ran_1 = true;
        __ctx_1.__exit__({}, nullptr, {});
        return __tpy_ret_0;
    } catch (::tpy::BaseException& __exc_1) {
        if (__fin_ran_1) throw;
        if (!__ctx_1.__exit__({}, &__exc_1, {})) throw;
    } catch (...) {
        if (__fin_ran_1) throw;
        __ctx_1.__exit__({}, nullptr, {});
        throw;
    }
    return ::tpy::BigInt(-1);
}

// def main() -> None:
//     print(maybe_neg_one(False))   # 100 -- body returns 100 through finally chain
//     print(maybe_neg_one(True))    # -1  -- CM suppresses, trailing return fires
void main() {
    std::cout << ::tpyapp::main::maybe_neg_one(false) << "\n" << ::tpy::check_signals;
    std::cout << ::tpyapp::main::maybe_neg_one(true) << "\n" << ::tpy::check_signals;
}

// main()
void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    ::tpyapp::main::main();
}

} // namespace tpyapp::main

int __tpy_main(int argc, char* argv[]) {
    ::tpy::init_sys_argv(argc, argv);
    ::tpyapp::main::__tpy_init();
    return 0;
}

int main(int argc, char* argv[]) {
    return ::tpy::run_main(argc, argv, &__tpy_main);
}
