// Generated by TurboPython Compiler
#pragma once

#include <tpy/tpy.hpp>
#include "tpystd/tpy/_types.hpp"
#include "tpystd/typing/_typing.hpp"
#include "mathlib.hpp"
#include "mathlib/funcs.hpp"

namespace tpyapp::main {

extern "C" int32_t abs(int32_t x);
extern "C" int32_t tpy_clock();

inline constexpr std::string_view __name__ = "__main__";

extern "C" void app_init();

void __tpy_init();
} // namespace tpyapp::main
