// Generated by TurboPython Compiler
#pragma once

#include <tpy/tpy.hpp>
#include "tpystd/tpy/_types.hpp"
#include "tpystd/typing/_typing.hpp"

namespace tpyapp::main {

struct Thrower;
struct Suppressor;

inline constexpr std::string_view __name__ = "__main__";

// def ret_out() -> int:
::tpy::BigInt ret_out();
// def brk_out() -> None:
void brk_out();
// def cont_out() -> None:
void cont_out();
// def ret_out_suppressing() -> int:
::tpy::BigInt ret_out_suppressing();
// def main() -> None:
void main();

// # Regression: an __exit__ that RAISES must run exactly once when control
// # leaves the with body via return / break. Sibling of with_exit_raises_once
// # (which covers the fall-through path): there the copy is moved outside the
// # try, here the inline exit-site copy is guarded instead, since a `with` can
// # be left from arbitrarily many points inside its body.
// class Thrower:
struct Thrower {


    // def __enter__(self) -> int:
    ::tpy::BigInt __enter__() const;

    // def __exit__(self, et, ev, tb) -> None:
    void __exit__(std::monostate et, const ::tpy::BaseException* ev, std::monostate tb) const;
    static constexpr std::string_view __tpy_class_name__ = "__main__.Thrower";
};

inline std::ostream& operator<<(std::ostream& os, const Thrower& obj) {
    ::tpy::print_object_default(os, "Thrower", obj);
    return os;
}

// class Suppressor:
struct Suppressor {


    // def __enter__(self) -> int:
    ::tpy::BigInt __enter__() const;

    // def __exit__(self, et, ev, tb) -> bool:
    bool __exit__(std::monostate et, const ::tpy::BaseException* ev, std::monostate tb) const;
    static constexpr std::string_view __tpy_class_name__ = "__main__.Suppressor";
};

inline std::ostream& operator<<(std::ostream& os, const Suppressor& obj) {
    ::tpy::print_object_default(os, "Suppressor", obj);
    return os;
}


// def __enter__(self) -> int:
//     return 1
inline ::tpy::BigInt Thrower::__enter__() const {
    return ::tpy::BigInt(1);
}

// def __exit__(self, et, ev, tb) -> None:
//     print("exit ran")
//     raise RuntimeError("from exit")
inline void Thrower::__exit__(std::monostate et, const ::tpy::BaseException* ev, std::monostate tb) const {
    std::cout << "exit ran" << "\n";
    throw ::tpy::RuntimeError("from exit");
}

// def __enter__(self) -> int:
//     return 1
inline ::tpy::BigInt Suppressor::__enter__() const {
    return ::tpy::BigInt(1);
}

// def __exit__(self, et, ev, tb) -> bool:
//     print("exit suppress")
//     return True
inline bool Suppressor::__exit__(std::monostate et, const ::tpy::BaseException* ev, std::monostate tb) const {
    std::cout << "exit suppress" << "\n";
    return true;
}
void __tpy_init();
} // namespace tpyapp::main
