// Generated by TurboPython Compiler
#include "main.hpp"

namespace tpyapp::main {


// def ret(h: Holder) -> Box:
//     b = h.box
//     return b
Box& ret(Holder& h) {
    Box& b = h.box;
    return b;
}

// def main() -> None:
//     h = Holder(Box(5))
//     b = ret(h)
//     b.val = 99
//     print(h.box.val)
void main() {
    Holder h = Holder(Box(5));
    Box& b = ::tpyapp::main::ret(h);
    b.val = 99;
    std::cout << h.box.val << "\n" << ::tpy::check_signals;
}

// main()
void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    ::tpyapp::main::main();
}

} // namespace tpyapp::main

int __tpy_main(int argc, char* argv[]) {
    ::tpy::init_sys_argv(argc, argv);
    ::tpyapp::main::__tpy_init();
    return 0;
}

int main(int argc, char* argv[]) {
    return ::tpy::run_main(argc, argv, &__tpy_main);
}
