// Generated by TurboPython Compiler
#include "main.hpp"

namespace tpyapp::main {


// def test_branch(flag: bool) -> None:
//     w = Wrapper(42)
//     if flag:
//         result = w.take()
//         print(result)
//     else:
//         print(w.get())
void test_branch(bool flag) {
    Wrapper w = Wrapper(::tpy::BigInt(42));
    if (flag) {
        ::tpy::BigInt result = std::move(w).take();
        std::cout << result << "\n";
    } else {
        std::cout << w.get() << "\n";
    }
}

// test_branch(True)
// test_branch(False)
void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    test_branch(true);
    test_branch(false);
}

} // namespace tpyapp::main

int __tpy_main(int argc, char* argv[]) {
    ::tpy::init_sys_argv(argc, argv);
    ::tpyapp::main::__tpy_init();
    return 0;
}

int main(int argc, char* argv[]) {
    ::tpy::process_startup();
    return __tpy_main(argc, argv);
}
