// Generated by TurboPython Compiler
#include "main.hpp"

namespace tpyapp::main {


// def main() -> None:
void main() {
    // r = MyRange(1, 6)
    MyRange r = MyRange(1, 6);
    // s = Summer(r)
    Summer<MyRange> s = Summer<MyRange>(r);
    // print(s.total())
    std::cout << s.total() << "\n";
}

void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    // main()
    main();
}

} // namespace tpyapp::main

int main(int argc, char* argv[]) {
    ::tpy::init_sys_argv(argc, argv);
    tpyapp::main::__tpy_init();
    return 0;
}
