// Generated by TurboPython Compiler
#include "main.hpp"

namespace tpyapp::main {


// def main() -> None:
//     cfg: dict[str, Any] = {
//         "host": "localhost",
//         "port": 8080,
//     }
//     host: str = cfg["host"]
//     port: int = cfg["port"]
//     print(host)
//     print(port)
void main() {
    ::tpy::ordered_map<std::string, ::tpy::Any> cfg = ::tpy::ordered_map<std::string, ::tpy::Any>({{"host", ::tpy::make_any(std::string("localhost"))}, {"port", ::tpy::make_any(::tpy::BigInt(8080))}});
    std::string host = ::tpy::any_cast_or_panic<std::string>(::tpy::__getitem__(cfg, "host"));
    ::tpy::BigInt port = ::tpy::any_cast_or_panic<::tpy::BigInt>(::tpy::__getitem__(cfg, "port"));
    std::cout << host << "\n";
    std::cout << port << "\n";
}

// main()
void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    main();
}

} // namespace tpyapp::main

int __tpy_main(int argc, char* argv[]) {
    ::tpy::init_sys_argv(argc, argv);
    ::tpyapp::main::__tpy_init();
    return 0;
}

int main(int argc, char* argv[]) {
    ::tpy::process_startup();
    return __tpy_main(argc, argv);
}
