// Generated by TurboPython Compiler
#include "main.hpp"

namespace tpyapp::main {


// def main() -> None:
//     w = Wrapper[int32](int32(5))
//     print(w.is_less(1, 2))
//     print(w.is_less(10, 3))
void main() {
    Wrapper<int32_t> w = Wrapper<int32_t>(5);
    std::cout << ::tpy::print_bool(w.is_less<int32_t>(1, 2)) << "\n";
    std::cout << ::tpy::print_bool(w.is_less<int32_t>(10, 3)) << "\n";
}

// main()
void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    ::tpyapp::main::main();
}

} // namespace tpyapp::main

int __tpy_main(int argc, char* argv[]) {
    ::tpy::init_sys_argv(argc, argv);
    ::tpyapp::main::__tpy_init();
    return 0;
}

int main(int argc, char* argv[]) {
    ::tpy::process_startup();
    return __tpy_main(argc, argv);
}
