// Generated by TurboPython Compiler
#pragma once

#include <tpy/tpy.hpp>
#include "tpystd/tpy/_types.hpp"
#include "tpystd/typing/_typing.hpp"

namespace tpyapp::main {

struct Key;

inline constexpr std::string_view __name__ = "__main__";

void main();

// class Key:
struct Key {
    // val: int
    ::tpy::BigInt val;

    // def __init__(self, v: int) -> None:
    Key() = default;
    explicit Key(const ::tpy::BigInt& v);

    // def __hash__(self) -> int:
    ::tpy::BigInt __hash__() const;

    // def __eq__(self, other: Key) -> bool:
    bool __eq__(const Key& other) const;

    friend bool operator==(const Key& lhs, const Key& other) {
        return lhs.__eq__(other);
    }
    static constexpr std::string_view __tpy_class_name__ = "__main__.Key";
};

inline std::ostream& operator<<(std::ostream& os, const Key& obj) {
    ::tpy::print_object_default(os, "Key", obj);
    return os;
}
} // namespace tpyapp::main

template<> struct std::hash<::tpyapp::main::Key> {
    size_t operator()(const ::tpyapp::main::Key& val) const noexcept {
        return static_cast<size_t>(::tpy::__hash__(val));
    }
};

namespace tpyapp::main {



// def __init__(self, v: int) -> None:
inline Key::Key(const ::tpy::BigInt& v) : val(v) {}

// def __hash__(self) -> int:
inline ::tpy::BigInt Key::__hash__() const {
    // return self.val
    return this->val;
}

// def __eq__(self, other: Key) -> bool:
inline bool Key::__eq__(const Key& other) const {
    // return self.val == other.val
    return (this->val == other.val);
}
void __tpy_init();
} // namespace tpyapp::main
