// Generated by TurboPython Compiler
#include "main.hpp"
#include "tpystd/io_inl.hpp"
#include "main_inl.hpp"
#include "tpystd/os_inl.hpp"

namespace tpyapp::main {

int32_t g_limit{};

// def holder_writes(s: Optional[str], text: str, n: int32,
//                   pairs: list[tuple[int, str]]) -> None:
//     # local holder: a free function writing fields of a local instance.
//     h = Box(0)
//     h.tag = s  # tpyc: ok
//     h.either = text  # tpyc: ok
//     h.pair = pairs[0]  # tpyc: ok
//     xs = [n, 4]
//     xs.append(5)
//     h.xs = xs  # tpyc: ok
//     h.xs.append(6)
//     # local holder: a whole-Optional container element.
//     wides: list[Optional[int64]] = [77]
//     h.n64 = wides[0]  # tpyc: ok
//     h.show("holder.writes")
//     # local holder: a constructor whose argument hoists a temp.
//     k = Keep()
//     k.flat = Flat([bytes([i]) for i in range(4)])  # tpyc: ok
//     print("holder.ctor_arg_temp", k.flat.n)
void holder_writes(std::optional<std::string_view> s, std::string_view text, int32_t n, const std::vector<std::tuple<::tpy::BigInt, std::string>>& pairs) {
    Box h = Box(0);
    h.tag = s ? std::make_optional(std::string(*s)) : std::nullopt;
    h.either = std::string(text);
    h.pair = ::tpy::__getitem__(pairs, 0);
    std::vector<int32_t> xs = {n, 4};
    xs.push_back(5);
    h.xs = std::move(xs);
    h.xs.push_back(6);
    std::vector<std::optional<int64_t>> wides = {77};
    h.n64 = ::tpy::__getitem__(wides, 0);
    h.show("holder.writes");
    Keep k = Keep();
    std::vector<::tpy::Bytes> __tmp_1 = ({
        std::vector<::tpy::Bytes> __result;
        const int32_t __stop_0 = 4;
        if (__stop_0 > 0) __result.reserve(static_cast<size_t>(__stop_0));
        for (int32_t i = 0; i < __stop_0; ++i) {
            __result.push_back(::tpy::bytes_from_int_iterable(std::array<int32_t, 1>{i}));
        }
        std::move(__result);
    });
    k.flat = Flat(__tmp_1);
    std::cout << "holder.ctor_arg_temp" << " " << k.flat.n << "\n";
}

// def make_buf(n: int32) -> Own[bytearray]:
//     return bytearray(n)
::tpy::ByteArray make_buf(int32_t n) {
    return ::tpy::bytearray_from_size(n);
}

// def make_list(n: int32) -> Own[list[int32]]:
//     return [n, n + 1]
std::vector<int32_t> make_list(int32_t n) {
    return {n, (::tpy::add_check<int32_t>(n, 1))};
}

// def make_res(v: int32) -> Own[Res]:
//     return Res(v)
Res make_res(int32_t v) {
    return Res(v);
}

// def show_cb(n: int32) -> None:
//     print("ctor.callback", n)
void show_cb(int32_t n) {
    std::cout << "ctor.callback" << " " << n << "\n";
}

// def pick(a: int32) -> int32:
//     print("ctor.pick", a)
//     return a
int32_t pick(int32_t a) {
    std::cout << "ctor.pick" << " " << a << "\n";
    return a;
}

// def view_of_borrow() -> None:
//     # A view of a field read through a borrow-returning call lives as long
//     # as the receiver.
//     h = Holds()
//     v: StrView = h.peek().name  # tpyc: ok
//     print("local.view_of_borrow", v)
void view_of_borrow() {
    Holds h = Holds();
    std::string_view v = h.peek().name;
    std::cout << "local.view_of_borrow" << " " << v << "\n";
}

// def nested_writes(p: Own[str], t: tuple[int, int32] | None,
//                   n: int | None) -> None:
//     # nested def: a captured Own param written to a field is never moved --
//     # the closure may run again.
//     h = Slot()
//     v = Vals()
//
//     def inner() -> None:
//         h.x = p  # tpyc: warning(/copies str into field/)
//         # ... nor a captured by-value param.
//         v.t = t if t is not None else (0, 0)  # tpyc: ok
//         v.o = n  # tpyc: ok
//     inner()
//     inner()
//     print("nested.captured", len(h.x), len(p), v.t, v.o, t, n)
void nested_writes(std::string p, std::optional<std::tuple<::tpy::BigInt, int32_t>> t, std::optional<::tpy::BigInt> n) {
    Slot h = Slot();
    Vals v = Vals();
    auto inner = [&h, &n, &p, &t, &v]() {
        h.x = p;
        v.t = (((t.has_value())) ? ((*t)) : (std::tuple<::tpy::BigInt, int32_t>{::tpy::BigInt(0), 0}));
        v.o = n;
    };
    inner();
    inner();
    std::cout << "nested.captured" << " " << ::tpy::__len__(h.x) << " " << ::tpy::__len__(p) << " " << ::tpy::TuplePrinter(v.t) << " " << ::tpy::print_optional_val(v.o) << " " << ::tpy::print_optional_val<::tpy::TuplePrinter<::tpy::BigInt, int32_t>, std::tuple<::tpy::BigInt, int32_t>>(t) << " " << ::tpy::print_optional_val(n) << "\n";
}

// def call_lambda(f: Callable[[], int32]) -> int32:
//     return f()
int32_t call_lambda(const std::function<int32_t()>& f) {
    return f();
}

// def lambda_reads() -> None:
//     # A lambda built after the call still reads `xs`, so the call copies
//     # it instead of moving it.
//     xs = [1, 2, 3]
//     k = Sink()
//     n = k.put(xs)  # tpyc: warning(/copies list\[int32\] into owned storage/)
//     print("lambda.live", n, call_lambda(lambda: len(xs)))
void lambda_reads() {
    std::vector<int32_t> xs = {1, 2, 3};
    Sink k = Sink();
    std::vector<int32_t> __tmp_1 = xs;
    int32_t n = k.put(std::move(__tmp_1));
    std::cout << "lambda.live" << " " << n << " " << ::tpyapp::main::call_lambda([xs]() -> int32_t { return ::tpy::__len__(xs); }) << "\n";
}

// def ctor_writes() -> None:
//     s = Src(show_cb, P(3))
//     built = Built(4, s, 1, "abcd", P(8), True)
//     # The Own param's field is its own storage.
//     built.other.v = built.other.v + 1
//     built.show()
//     closed = Closed(Pt(2), 6, 0, "tt", b"bb", False)
//     closed.show()
//     d = Derived("a string long enough to leave the small buffer")
//     print("ctor.base", d.a == d.b, len(d.a), d.c, d.d)
//     r = Reads()
//     print("ctor.base_reads", r.a, r.b)
//     bo = BasedOrder(7)
//     print("ctor.based_order", bo.a, bo.b.v, bo.r.val)
//     vs = ViewSlots("vs")
//     vs.set(3)
//     print("view_slots", vs.o is None)
//     view_of_borrow()
void ctor_writes() {
    Src s = Src(show_cb, P(3));
    Built built = Built(4, s, ::tpy::make_any(::tpy::BigInt(1)), "abcd", P(8), true);
    built.other.v = (::tpy::add_check<int32_t>(built.other.v, 1));
    built.show();
    Closed closed = Closed(Pt(2), 6, 0, "tt", ::tpy::bytes_literal("bb", 2), false);
    closed.show();
    Derived d = Derived("a string long enough to leave the small buffer");
    std::cout << "ctor.base" << " " << ::tpy::print_bool((d.a == d.b)) << " " << ::tpy::__len__(d.a) << " " << d.c << " " << d.d << "\n";
    Reads r = Reads();
    std::cout << "ctor.base_reads" << " " << r.a << " " << r.b << "\n";
    BasedOrder bo = BasedOrder(7);
    std::cout << "ctor.based_order" << " " << bo.a << " " << bo.b.v << " " << bo.r.val << "\n";
    ViewSlots vs = ViewSlots("vs");
    vs.set(3);
    std::cout << "view_slots" << " " << ::tpy::print_bool((!vs.o.has_value())) << "\n";
    ::tpyapp::main::view_of_borrow();
}

// async def main_coro(b: Box) -> None:
//     await b.async_writes("async", "tx", 3)  # -> S_RESUME_0
::tpystd::tpy::Poll<::std::monostate> __coro_main_coro::__poll__(::tpystd::coro::Waker waker) {
    while (true) switch (__state) {
    case S_INITIAL: {  // entry
        __state = S_DONE;  // until a yield sets where to resume
        __coro_arg_0 = "async";
        __sub_0.emplace(b, __coro_arg_0, "tx", 3);
        __state = S_RESUME_0;
        continue;
    }
    case S_RESUME_0: {  // after: await b.async_writes("async", "tx", 3)
        auto __r0 = ::tpy::poll_with_cancel(__sub_0, __cancel_pending, waker);
        if (__r0.is_pending()) return ::tpystd::tpy::Poll<::std::monostate>::pending();
        (void)std::move(__r0).value();
        __sub_0.reset();
        __state = S_DONE;
        return ::tpystd::tpy::Poll<::std::monostate>::ready(::std::monostate{});
    }
    case S_DONE: ::tpy::tpy_panic("poll after Ready");
    }
    __builtin_unreachable();
}


// async def main_coro(b: Box) -> None:
__coro_main_coro main_coro(Box& b) {
    return __coro_main_coro(b);
}

// def main() -> None:
//     b = Box("init")
//     b.show("start")
//     b.method_writes("s", b"b", "text", 42, 5000000000, [(1, "one")],
//                     [P(5)], Inner("in"), True)
//     b.method_writes(None, None, "abc", 7, 1, [(2, "two")], [P(6)],
//                     Inner(None), False)
//     for k in b.gen_writes("gen", "gt", 8):
//         print("gen.yield", k)
//     asyncio.run(main_coro(b))
//     holder_writes("hold", "ht", 9, [(3, "three")])
//     k = Keep()
//     k.load(b"src")
//     vals = Vals()
//     vals.keep((10**20, 7), 10**21, "kept string long enough to heap")
//     nested_writes("a captured string long enough to heap", (10**20, 2),
//                   10**30)
//     lambda_reads()
//     ctor_writes()
void main() {
    ::tpy::Union<int32_t, std::string> __tmp_1 = "init";
    Box b = Box(__tmp_1);
    b.show("start");
    std::vector<P> __tmp_2 = {P(5)};
    b.method_writes("s", ::tpy::bytes_literal_owned("b", 1), "text", 42, static_cast<int64_t>(5000000000), {std::tuple<::tpy::BigInt, std::string>{::tpy::BigInt(1), "one"}}, __tmp_2, Inner("in"), true);
    std::vector<P> __tmp_3 = {P(6)};
    b.method_writes(std::nullopt, std::nullopt, "abc", 7, 1, {std::tuple<::tpy::BigInt, std::string>{::tpy::BigInt(2), "two"}}, __tmp_3, Inner(std::nullopt), false);
    {
        std::string __tmp_4 = "gen";
        auto __src_0 = b.gen_writes(__tmp_4, "gt", 8);
        auto&& __itr_0 = ::tpy::__iter__(__src_0);
        for (;;) {
            auto __r_1 = __itr_0.__next__();
            if (!__r_1.has_value()) break;
            int32_t k = ::tpy::unwrap_ref(*__r_1);
            std::cout << "gen.yield" << " " << k << "\n";
        }
    }
    ::tpystd::asyncio::run<std::monostate>(::tpy::make_adapter<::tpystd::coro::Cancellable<std::monostate>>(::tpyapp::main::main_coro(b)));
    std::vector<std::tuple<::tpy::BigInt, std::string>> __tmp_5 = {std::tuple<::tpy::BigInt, std::string>{::tpy::BigInt(3), "three"}};
    ::tpyapp::main::holder_writes("hold", "ht", 9, __tmp_5);
    Keep __slot_1 = Keep();
    Keep* k = &__slot_1;
    k->load(::tpy::bytes_literal("src", 3));
    Vals vals = Vals();
    vals.keep(std::tuple<::tpy::BigInt, int32_t>{((::tpy::BigInt(10)).pow(::tpy::BigInt(20))), 7}, ((::tpy::BigInt(10)).pow(::tpy::BigInt(21))), "kept string long enough to heap");
    ::tpyapp::main::nested_writes("a captured string long enough to heap", std::tuple<::tpy::BigInt, int32_t>{((::tpy::BigInt(10)).pow(::tpy::BigInt(20))), 2}, ((::tpy::BigInt(10)).pow(::tpy::BigInt(30))));
    ::tpyapp::main::lambda_reads();
    ::tpyapp::main::ctor_writes();
}


// async def async_writes(self, s: Optional[str], text: str,
//                        n: int32) -> None:
//     # async method: the same writes across a suspension.
//     await asyncio.sleep(0)                                          # -> S_RESUME_0
//     self.tag = s  # tpyc: ok
//     self.either = str(n)  # tpyc: ok
//     await asyncio.sleep(0)                                          # -> S_RESUME_1
//     self.pair = (n, text)  # tpyc: ok
//     self.show("async.writes")
//     # async method: a frame-local list moves in at its last use; a
//     # frame-local str read after the write stays intact.
//     ys = [n, 40]
//     ys.append(41)
//     label = text + "?"
//     self.xs = ys  # tpyc: ok
//     self.tag = label  # tpyc: ok
//     await asyncio.sleep(0)                                          # -> S_RESUME_2
//     self.xs.append(42)
//     print("async.frame_locals", self.xs, self.tag, label)
::tpystd::tpy::Poll<::std::monostate> __coro_Box_async_writes::__poll__(::tpystd::coro::Waker waker) {
    while (true) switch (__state) {
    case S_INITIAL: {  // entry
        __state = S_DONE;  // until a yield sets where to resume
        __sub_0.emplace(std::move(::tpystd::asyncio::sleep(static_cast<double>(0))));
        __state = S_RESUME_0;
        continue;
    }
    case S_RESUME_0: {  // after: await asyncio.sleep(0)
        auto __r0 = ::tpy::poll_with_cancel(__sub_0, __cancel_pending, waker);
        if (__r0.is_pending()) return ::tpystd::tpy::Poll<::std::monostate>::pending();
        (void)std::move(__r0).value();
        __sub_0.reset();
        __self.tag = s ? std::make_optional(std::string(*s)) : std::nullopt;
        __self.either = ::tpy::fixed_to_str<int32_t>(n);
        __sub_1.emplace(std::move(::tpystd::asyncio::sleep(static_cast<double>(0))));
        __state = S_RESUME_1;
        continue;
    }
    case S_RESUME_1: {  // after: await asyncio.sleep(0)
        auto __r1 = ::tpy::poll_with_cancel(__sub_1, __cancel_pending, waker);
        if (__r1.is_pending()) return ::tpystd::tpy::Poll<::std::monostate>::pending();
        (void)std::move(__r1).value();
        __sub_1.reset();
        __self.pair = std::tuple<::tpy::BigInt, std::string>{n, std::string(text)};
        __self.show("async.writes");
        ys.emplace(std::vector<int32_t>{n, 40});
        (*ys).push_back(41);
        label = (::tpy::str_concat(text, "?"));
        __self.xs = std::move((*ys));
        __self.tag = label;
        __sub_2.emplace(std::move(::tpystd::asyncio::sleep(static_cast<double>(0))));
        __state = S_RESUME_2;
        continue;
    }
    case S_RESUME_2: {  // after: await asyncio.sleep(0)
        auto __r2 = ::tpy::poll_with_cancel(__sub_2, __cancel_pending, waker);
        if (__r2.is_pending()) return ::tpystd::tpy::Poll<::std::monostate>::pending();
        (void)std::move(__r2).value();
        __sub_2.reset();
        __self.xs.push_back(42);
        std::cout << "async.frame_locals" << " " << ::tpy::ListPrinter(__self.xs) << " " << ::tpy::print_optional_val(__self.tag) << " " << label << "\n";
        __state = S_DONE;
        return ::tpystd::tpy::Poll<::std::monostate>::ready(::std::monostate{});
    }
    case S_DONE: ::tpy::tpy_panic("poll after Ready");
    }
    __builtin_unreachable();
}



// def __init__(self, e: int32 | str) -> None:
//     self.tag = None
//     self.raw = None
//     self.either = e
//     self.pair = (0, "")
//     self.xs = []
//     self.p = P(0)
//     self.op = None
//     self.n64 = None
Box::Box(const ::tpy::Union<int32_t, std::string>& e)
    : tag(std::nullopt),
      raw(std::nullopt),
      either(e),
      pair(std::tuple<::tpy::BigInt, std::string>{::tpy::BigInt(0), ""}),
      xs(std::vector<int32_t>{}),
      p(P(0)),
      op(std::nullopt),
      n64(std::nullopt) {}

// def method_writes(self, s: Optional[str], b: Optional[bytes], text: str,
//                   n: int32, wide: int64, pairs: list[tuple[int, str]],
//                   ps: list[P], inner: Inner, flag: bool) -> None:
//     # method: an `Optional[str]` / `Optional[bytes]` param lands through
//     # the view->owned shim; str / bytes values through their owned twin.
//     self.tag = s  # tpyc: ok
//     self.raw = b  # tpyc: ok
//     self.show("method.opt_params")
//     self.tag = text + "!"  # tpyc: ok
//     self.raw = b"xy"  # tpyc: ok
//     self.show("method.opt_fresh")
//     self.tag = text[1:3]  # tpyc: ok
//     self.tag = inner.tag  # tpyc: ok
//     self.show("method.opt_view_field")
//     # method: a value union takes a literal, a view member, a conversion.
//     self.either = 7  # tpyc: ok
//     self.show("method.union_literal")
//     self.either = text  # tpyc: ok
//     self.show("method.union_view")
//     self.either = str(n)  # tpyc: ok
//     self.show("method.union_conv")
//     # method: a value tuple from a container element; an Optional
//     # int64 from a fixed-width value.
//     self.pair = pairs[0]  # tpyc: ok
//     self.n64 = wide  # tpyc: ok
//     self.show("method.tuple_int64")
//     # method: a fresh list and a fresh select of records own their
//     # storage -- mutating the field reaches nothing else.
//     self.xs = [n] + [2]  # tpyc: ok
//     self.xs.append(9)
//     self.p = P(1) if flag else P(2)  # tpyc: ok
//     self.p.v = self.p.v + 10
//     # method: an explicit copy of an element into an Optional record
//     # slot; the source element is mutated after the write.
//     self.op = copy(ps[0])  # tpyc: ok
//     ps[0].v = 99
//     self.show("method.ref_fresh")
//     op = self.op
//     if op is not None:
//         print("method.op_copy", op.v, ps[0].v)
void Box::method_writes(std::optional<std::string_view> s, std::optional<::tpy::BytesView> b, std::string_view text, int32_t n, int64_t wide, const std::vector<std::tuple<::tpy::BigInt, std::string>>& pairs, std::vector<P>& ps, const Inner& inner, bool flag) {
    this->tag = s ? std::make_optional(std::string(*s)) : std::nullopt;
    this->raw = b ? std::make_optional(::tpy::Bytes(*b)) : std::nullopt;
    this->show("method.opt_params");
    this->tag = (::tpy::str_concat(text, "!"));
    this->raw = ::tpy::bytes_literal_owned("xy", 2);
    this->show("method.opt_fresh");
    this->tag = std::string(::tpy::str_slice(text, ::tpy::BasicSlice{1, 3}));
    this->tag = inner.tag;
    this->show("method.opt_view_field");
    this->either = 7;
    this->show("method.union_literal");
    this->either = std::string(text);
    this->show("method.union_view");
    this->either = ::tpy::fixed_to_str<int32_t>(n);
    this->show("method.union_conv");
    this->pair = ::tpy::__getitem__(pairs, 0);
    this->n64 = wide;
    this->show("method.tuple_int64");
    this->xs = (::tpy::list_concat(std::vector<int32_t>{n}, std::vector<int32_t>{2}));
    this->xs.push_back(9);
    this->p = ((flag) ? (P(1)) : (P(2)));
    this->p.v = (::tpy::add_check<int32_t>(this->p.v, 10));
    this->op = P(::tpy::__getitem__(ps, 0));
    ::tpy::__getitem__(ps, 0).v = 99;
    this->show("method.ref_fresh");
    P* op = ::tpy::optional_to_ptr(this->op);
    if ((op != nullptr)) {
        std::cout << "method.op_copy" << " " << op->v << " " << ::tpy::__getitem__(ps, 0).v << "\n";
    }
}

// def __init__(self, n: int32, s: Src, p: Any, text: str,
//              own: Own[P], flag: bool) -> None:
//     # ctor: free calls returning an owned reference value.
//     self.buf = make_buf(n)  # tpyc: ok
//     self.xs = make_list(n)  # tpyc: ok
//     # ctor: an explicit copy of a borrow-returning call.
//     self.cp = copy(s.peek())  # tpyc: ok
//     # ctor: a callable read off another record's field.
//     self.cb = s.cb  # tpyc: ok
//     self.n = n
//     # ctor: a lambda that captures no `self`.
//     self.action = lambda: print("ctor.lambda", n)  # tpyc: ok
//     # ctor: an already-Any source.
//     self.payload = p  # tpyc: ok
//     # ctor: an explicit copy of a str view into an owned str.
//     self.name = copy(text)  # tpyc: ok
//     # ctor: a view field from a slice of a view param.
//     self.lab = text[1:3]  # tpyc: ok
//     # ctor: copy() of an Own param in a tuple, then its last use moves
//     # it into another field.
//     self.pair = (1, copy(own))  # tpyc: ok
//     self.other = own  # tpyc: ok
//     # ctor: global reads, bare and inside an expression.
//     self.lim = g_limit  # tpyc: ok
//     self.lim2 = g_limit + 1  # tpyc: ok
//     # ctor: a non-default-constructible field from a conditional of
//     # owned calls.
//     self.res = make_res(1) if flag else make_res(2)  # tpyc: ok
//     # ctor: a source that needs a statement temporary is assigned in
//     # the body instead.
//     self.flat = Flat([bytes([i]) for i in range(3)])  # tpyc: ok
//     k = n * 2
//     # ctor: a source reading a body local is assigned in the body.
//     self.late = k  # tpyc: ok
Built::Built(int32_t n, Src& s, ::tpy::Any p, std::string_view text, P&& own, bool flag)
    : buf(::tpyapp::main::make_buf(n)),
      xs(::tpyapp::main::make_list(n)),
      cp(s.peek()),
      cb(s.cb),
      n(n),
      action([n]() { std::cout << "ctor.lambda" << " " << n << "\n"; }),
      payload(p),
      name(text),
      lab(::tpy::str_slice(text, ::tpy::BasicSlice{1, 3})),
      pair(::tpy::tuple_to_storage<std::tuple<int32_t, P>>(std::tuple<int32_t, P>{1, P(own)})),
      other(std::move(own)),
      lim(g_limit),
      lim2((::tpy::add_check<int32_t>(g_limit, 1))),
      res(((flag) ? (::tpyapp::main::make_res(1)) : (::tpyapp::main::make_res(2)))) {
    std::vector<::tpy::Bytes> __tmp_1 = ({
        std::vector<::tpy::Bytes> __result;
        const int32_t __stop_0 = 3;
        if (__stop_0 > 0) __result.reserve(static_cast<size_t>(__stop_0));
        for (int32_t i = 0; i < __stop_0; ++i) {
            __result.push_back(::tpy::bytes_from_int_iterable(std::array<int32_t, 1>{i}));
        }
        std::move(__result);
    });
    this->flat = Flat(__tmp_1);
    int32_t k = (::tpy::mul_check<int32_t>(n, 2));
    this->late = k;
}

// def __init__(self, pt: Pt | None, k: int32, a: int32, t: str,
//              tb: bytes, c: bool) -> None:
//     # ctor: a ValueType record in an Optional field, from its param.
//     self.pt = pt  # tpyc: ok
//     # ctor: a ValueType constructor call into a value-union field.
//     self.u = Pt(k)  # tpyc: ok
//     # ctor: a tuple literal into an Optional value-tuple field.
//     self.r = (1.5, 3)  # tpyc: ok
//     # ctor: an `or` whose left operand is held once in a temporary --
//     # the init becomes a body assignment.
//     self.v = pick(a) or pick(1)  # tpyc: ok
//     # ctor: str / bytes params and a bytes literal / select into
//     # Optional str / bytes fields.
//     self.s = t  # tpyc: ok
//     self.bs = tb  # tpyc: ok
//     self.b2 = b"z"  # tpyc: ok
//     self.b3 = b"z" if c else None  # tpyc: ok
Closed::Closed(std::optional<Pt> pt, int32_t k, int32_t a, std::string_view t, ::tpy::BytesView tb, bool c)
    : pt(pt),
      u(Pt(k)),
      r(std::tuple<double, int32_t>{1.5, 3}) {
    auto&& __tmp_1 = ::tpyapp::main::pick(a);
    this->v = (__tmp_1 ? __tmp_1 : ::tpyapp::main::pick(1));
    this->s = std::string(t);
    this->bs = ::tpy::Bytes(tb);
    this->b2 = ::tpy::bytes_literal_owned("z", 1);
    this->b3 = ((c) ? (std::optional<::tpy::Bytes>(::tpy::bytes_literal_owned("z", 1))) : (std::optional<::tpy::Bytes>(std::nullopt)));
}
// # A field write takes every source its slot's value form admits, at every
// # position (warned copies live in records/field_admission_warned).
// import asyncio
//
// g_limit: int32 = 5
//
// main()
void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    ::tpystd::asyncio::__tpy_init();
    g_limit = 5;
    ::tpyapp::main::main();
}

} // namespace tpyapp::main

int __tpy_main(int argc, char* argv[]) {
    ::tpy::init_sys_argv(argc, argv);
    ::tpyapp::main::__tpy_init();
    return 0;
}

int main(int argc, char* argv[]) {
    ::tpy::process_startup();
    return __tpy_main(argc, argv);
}
