// Generated by TurboPython Compiler
#pragma once

#include <tpy/tpy.hpp>
#include "tpystd/tpy/_types.hpp"
#include "tpystd/typing/_typing.hpp"

namespace tpyapp::main {

struct Rec;

inline constexpr std::string_view __name__ = "__main__";

// def main() -> None:
void main();

// class Rec:
struct Rec {
    // self.n = n
    int32_t n;

    // def __init__(self, n: int32) -> None:
    Rec() = default;
    explicit Rec(int32_t n);
    static constexpr std::string_view __tpy_class_name__ = "__main__.Rec";
};

inline std::ostream& operator<<(std::ostream& os, const Rec& obj) {
    ::tpy::print_object_default(os, "Rec", obj);
    return os;
}


// def __init__(self, n: int32) -> None:
//     self.n = n
inline Rec::Rec(int32_t n) : n(n) {}
void __tpy_init();
} // namespace tpyapp::main
