// Generated by TurboPython Compiler
#include "main.hpp"

namespace tpyapp::main {


// def main() -> None:
//     t: Tree[int] = [1, [2, 3], 4]
//     print(leaf_count(t))
//     leaf: Tree[int] = 7
//     print(leaf_count(leaf))
void main() {
    ::tpyapp::treelib::Tree<::tpy::BigInt> t = std::vector<::tpyapp::treelib::Tree<::tpy::BigInt>>{1, std::vector<::tpyapp::treelib::Tree<::tpy::BigInt>>{2, 3}, 4};
    std::cout << ::tpyapp::treelib::leaf_count<::tpy::BigInt>(t) << "\n" << ::tpy::check_signals;
    ::tpyapp::treelib::Tree<::tpy::BigInt> leaf = 7;
    std::cout << ::tpyapp::treelib::leaf_count<::tpy::BigInt>(leaf) << "\n" << ::tpy::check_signals;
}

// # A generic recursive alias (and a traversal over it) defined in treelib,
// # used from main: the wrapper template is emitted in the defining module's
// # header and instantiated cross-module. Construct a value here and dispatch
// # through the imported function.
// from treelib import Tree, leaf_count
//
// main()
void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    ::tpyapp::treelib::__tpy_init();
    ::tpyapp::main::main();
}

} // namespace tpyapp::main

int __tpy_main(int argc, char* argv[]) {
    ::tpy::init_sys_argv(argc, argv);
    ::tpyapp::main::__tpy_init();
    return 0;
}

int main(int argc, char* argv[]) {
    ::tpy::process_startup();
    return __tpy_main(argc, argv);
}
