// Generated by TurboPython Compiler
#include "main.hpp"

namespace tpyapp::main {


// def main() -> None:
//     with Suppress():
//         raise FileNotFoundError("missing.txt")
//     print("after FNFE")
//
//     with Suppress():
//         raise OSError("io")
//     print("after OS")
//
//     try:
//         with Suppress():
//             raise RuntimeError("re")
//     except RuntimeError as e:
//         print("propagated RE: " + str(e))
void main() {
    auto __ctx_1 = Suppress();
    __ctx_1.__enter__();
    try {
        throw ::tpy::FileNotFoundError("missing.txt");
    } catch (::tpy::BaseException& __exc_1) {
        if (!__ctx_1.__exit__({}, &__exc_1, {})) throw;
    } catch (...) {
        __ctx_1.__exit__({}, nullptr, {});
        throw;
    }
    std::cout << "after FNFE" << "\n" << ::tpy::check_signals;
    auto __ctx_2 = Suppress();
    __ctx_2.__enter__();
    try {
        ::tpy::OSError("io").__raise__();
    } catch (::tpy::BaseException& __exc_2) {
        if (!__ctx_2.__exit__({}, &__exc_2, {})) throw;
    } catch (...) {
        __ctx_2.__exit__({}, nullptr, {});
        throw;
    }
    std::cout << "after OS" << "\n" << ::tpy::check_signals;
    {
        try {
            auto __ctx_3 = Suppress();
            __ctx_3.__enter__();
            try {
                throw ::tpy::RuntimeError("re");
            } catch (::tpy::BaseException& __exc_3) {
                if (!__ctx_3.__exit__({}, &__exc_3, {})) throw;
            } catch (...) {
                __ctx_3.__exit__({}, nullptr, {});
                throw;
            }
        } catch (const ::tpy::RuntimeError& e) {
            std::cout << (::tpy::str_concat("propagated RE: ", std::string(::tpy::__str__(e)))) << "\n" << ::tpy::check_signals;
        }
    }
}


// def __exit__(self, exc_type, exc_val, exc_tb) -> bool:
//     if exc_val is None:
//         return False
//     # Deep-chain dispatch: FileNotFoundError sits three levels under
//     # BaseException. Hits before the broader OSError arm.
//     if isinstance(exc_val, FileNotFoundError):  # tpyc: ok
//         print("FNFE: " + str(exc_val))
//         return True
//     if isinstance(exc_val, OSError):  # tpyc: ok
//         print("OS: " + str(exc_val))
//         return True
//     # Root-class isinstance: same as `is not None` for Optional[BaseException],
//     # but pins the codegen of dynamic_cast against the root type.
//     if isinstance(exc_val, BaseException):  # tpyc: ok
//         print("BASE: " + str(exc_val))
//         return False  # propagate
//     return False
bool Suppress::__exit__(std::monostate exc_type, const ::tpy::BaseException* exc_val, std::monostate exc_tb) const {
    if ((exc_val == nullptr)) {
        return false;
    }
    if (const ::tpy::FileNotFoundError* __exc_val_ptr = dynamic_cast<const ::tpy::FileNotFoundError*>(exc_val); (__exc_val_ptr != nullptr)) {
        std::cout << (::tpy::str_concat("FNFE: ", std::string(::tpy::__str__((*__exc_val_ptr))))) << "\n" << ::tpy::check_signals;
        return true;
    }
    if (const ::tpy::OSError* __exc_val_ptr = dynamic_cast<const ::tpy::OSError*>(exc_val); (__exc_val_ptr != nullptr)) {
        std::cout << (::tpy::str_concat("OS: ", std::string(::tpy::__str__((*__exc_val_ptr))))) << "\n" << ::tpy::check_signals;
        return true;
    }
    if ((dynamic_cast<const ::tpy::BaseException*>(exc_val) != nullptr)) {
        std::cout << (::tpy::str_concat("BASE: ", std::string(::tpy::__str__((*exc_val))))) << "\n" << ::tpy::check_signals;
        return false;
    }
    return false;
}
// main()
void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    ::tpyapp::main::main();
}

} // namespace tpyapp::main

int __tpy_main(int argc, char* argv[]) {
    ::tpy::init_sys_argv(argc, argv);
    ::tpyapp::main::__tpy_init();
    return 0;
}

int main(int argc, char* argv[]) {
    return ::tpy::run_main(argc, argv, &__tpy_main);
}
