// Generated by TurboPython Compiler
#pragma once

#include "main.hpp"

namespace tpyapp::main {

// # generator body: the closure runs between the narrowing and the read
// def gen_capture() -> Iterator[int]:
//     t = N()
//
//     def wipe() -> None:
//         t.v = None
//
//     if t.v is not None:
//         wipe()
//         y = t.v  # tpyc: type(/None/)
//         print("gen_capture:", y)
//         yield 0                        # -> S_RESUME_0
inline std::expected<::tpy::BigInt, ::tpy::StopIteration> __gen_gen_capture::__next__() {
    while (true) switch (__state) {
    case S_INITIAL: {  // entry
        __state = S_DONE;  // until a yield sets where to resume
        t.emplace(N());
        // def wipe: frame member
        if (((*t).v.has_value())) {
            wipe();
            y = (*t).v;
            std::cout << "gen_capture:" << " " << ::tpy::print_optional_val(y) << "\n" << ::tpy::check_signals;
            __state = S_RESUME_0;
            return ::tpy::BigInt(0);
        } else {
            __state = S_JOIN_0;
            continue;
        }
    }
    case S_RESUME_0:  // after: yield 0
    case S_JOIN_0: {
        __state = S_DONE;
        return ::tpy::make_unexpected(::tpy::StopIteration{});
    }
    case S_DONE: return ::tpy::make_unexpected(::tpy::StopIteration{});
    }
    __builtin_unreachable();
}

} // namespace tpyapp::main
