// Generated by TurboPython Compiler
#include "main.hpp"

namespace tpyapp::main {


// @error_return(AttributeError)
// def fetch(b: Bag, name: str) -> str:
std::expected<std::string, ::tpy::AttributeError> fetch(Bag& b, std::string_view name) {
    // if name == "host":
    if ((name == "host")) {
        // return b.host       # auto-propagate path: dunder returns OK
        return ({ auto __er_1 = b.__getattr__("host"); if (!__er_1.has_value()) return ::tpy::make_unexpected(__er_1.error()); ::tpy::unwrap_ref_move(*__er_1); });
    }
    // return b.missing        # auto-propagate path: dunder raises -> caller returns unexpected
    return ({ auto __er_2 = b.__getattr__("missing"); if (!__er_2.has_value()) return ::tpy::make_unexpected(__er_2.error()); ::tpy::unwrap_ref_move(*__er_2); });
}

// def main() -> None:
void main() {
    // b = Bag()
    Bag b = Bag();
    // try:
    {
        std::optional<::tpy::AttributeError> __err_opt_3;
        // print(fetch(b, "host"))
        std::cout << ({ auto __er_4 = fetch(b, "host"); if (!__er_4.has_value()) { __err_opt_3 = std::move(__er_4.error()); goto __except_3; } ::tpy::unwrap_ref_move(*__er_4); }) << "\n";
        // print(fetch(b, "missing"))
        std::cout << ({ auto __er_5 = fetch(b, "missing"); if (!__er_5.has_value()) { __err_opt_3 = std::move(__er_5.error()); goto __except_3; } ::tpy::unwrap_ref_move(*__er_5); }) << "\n";
        goto __after_try_3;
        // except AttributeError:
        __except_3:;
        {
            auto& e = *__err_opt_3;
            // print("caught:", str(e))
            std::cout << "caught:" << " " << std::string(::tpy::__str__(e)) << "\n";
        }
        __after_try_3:;
    }
}

void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    // main()
    main();
}

} // namespace tpyapp::main

int __tpy_main(int argc, char* argv[]) {
    ::tpy::init_sys_argv(argc, argv);
    ::tpyapp::main::__tpy_init();
    return 0;
}

int main(int argc, char* argv[]) {
    std::set_terminate(&::tpy::tpy_terminate_handler);
    return __tpy_main(argc, argv);
}
