// Generated by TurboPython Compiler
#include "main.hpp"

namespace tpyapp::main {


// def main() -> None:
void main() {
    // h = Holder()
    Holder h = Holder();
    // print(h.scan_dict())
    std::cout << h.scan_dict() << "\n";
    // print(h.sum_list())
    std::cout << h.sum_list() << "\n";
    // print(h.sum_set())
    std::cout << h.sum_set() << "\n";
    // print(h.count_str())
    std::cout << h.count_str() << "\n";
}

void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    // main()
    main();
}

} // namespace tpyapp::main

int __tpy_main(int argc, char* argv[]) {
    ::tpy::init_sys_argv(argc, argv);
    ::tpyapp::main::__tpy_init();
    return 0;
}

int main(int argc, char* argv[]) {
    ::tpy::process_startup();
    return __tpy_main(argc, argv);
}
