// Generated by TurboPython Compiler
#include "main.hpp"

namespace tpy_user::main {


// 18: def maybe_val(x: Optional[Int32]) -> Optional[Int32]:
std::optional<int32_t> maybe_val(std::optional<int32_t> x) {
    // 19:     return x
    return x;
}

// 21: def main():
void main() {
    // 22:     # Generic Optional with value type
    // 23:     c = Container[Int32](Int32(42))
    int32_t __tmp_1 = 42;
    Container<int32_t> c = Container<int32_t>(&(__tmp_1));
    // 24:     v = c.get()
    int32_t* v = c.get();
    // 25:     if v is not None:
    if ((v != nullptr)) {
        // 26:         print("got:", v)
        std::cout << "got:" << " " << tpy::print_optional(v) << "\n";
    // 27:     else:
    } else {
        // 28:         print("got: None")
        std::cout << "got: None" << "\n";
    }
    // 30:     c.set(None)
    c.set(nullptr);
    // 31:     v2 = c.get()
    int32_t* v2 = c.get();
    // 32:     if v2 is not None:
    if ((v2 != nullptr)) {
        // 33:         print("after set:", v2)
        std::cout << "after set:" << " " << tpy::print_optional(v2) << "\n";
    // 34:     else:
    } else {
        // 35:         print("after set: None")
        std::cout << "after set: None" << "\n";
    }
    // 37:     c.set(Int32(99))
    int32_t __tmp_2 = 99;
    c.set(&(__tmp_2));
    // 38:     v3 = c.get()
    int32_t* v3 = c.get();
    // 39:     if v3 is not None:
    if ((v3 != nullptr)) {
        // 40:         print("restored:", v3)
        std::cout << "restored:" << " " << tpy::print_optional(v3) << "\n";
    }
    // 42:     # None-initialized container
    // 43:     c2 = Container[Int32](None)
    Container<int32_t> c2 = Container<int32_t>(nullptr);
    // 44:     v4 = c2.get()
    int32_t* v4 = c2.get();
    // 45:     if v4 is None:
    if ((v4 == nullptr)) {
        // 46:         print("none init: ok")
        std::cout << "none init: ok" << "\n";
    }
    // 48:     # Optional[T] from typing (equivalent to T | None)
    // 49:     r = maybe_val(Int32(7))
    std::optional<int32_t> r = maybe_val(7);
    // 50:     if r is not None:
    if ((r.has_value())) {
        // 51:         print("maybe:", r)
        std::cout << "maybe:" << " " << tpy::print_optional_val(r) << "\n";
    }
    // 53:     r2 = maybe_val(None)
    std::optional<int32_t> r2 = maybe_val(std::nullopt);
    // 54:     if r2 is None:
    if ((!r2.has_value())) {
        // 55:         print("maybe None: ok")
        std::cout << "maybe None: ok" << "\n";
    }
    // 57:     print("done")
    std::cout << "done" << "\n";
}

void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    // 59: main()
    main();
}

} // namespace tpy_user::main

int main(int argc, char* argv[]) {
    tpy::init_sys_argv(argc, argv);
    tpy_user::main::__tpy_init();
    return 0;
}
