// Generated by TurboPython Compiler
#include "main.hpp"

namespace tpyapp::main {


// def push(xs: list[int32], v: int32) -> None:
//     xs.append(v)
void push(std::vector<int32_t>& xs, int32_t v) {
    xs.push_back(v);
}

// def read_elements(g: dict[str, list[int32]], m: list[list[int32]]) -> int32:
//     # The value-position element reads themselves -- kept in their own body so
//     # this half actually ROUTES through the element gate arm (main() below
//     # carries positions that still reject, which would fall the whole body
//     # back and leave the arm unexercised at exec).
//     print(len(g["a"]))
//     print(g["a"])
//     row = g["a"]
//     row.append(99)
//     g["a"].append(4)
//     return len(g["a"]) + len(m[1])
int32_t read_elements(::tpy::ordered_map<std::string, std::vector<int32_t>>& g, const std::vector<std::vector<int32_t>>& m) {
    std::cout << ::tpy::__len__(::tpy::__getitem__(g, "a")) << "\n";
    std::cout << ::tpy::ListPrinter(::tpy::__getitem__(g, "a")) << "\n";
    std::vector<int32_t>& row = ::tpy::__getitem__(g, "a");
    row.push_back(99);
    ::tpy::__getitem__(g, "a").push_back(4);
    return (::tpy::add_check<int32_t>(::tpy::__len__(::tpy::__getitem__(g, "a")), ::tpy::__len__(::tpy::__getitem__(m, 1))));
}

// def main() -> None:
//     a: list[int32] = [1, 2]
//     b: list[int32] = [3]
//     g: dict[str, list[int32]] = {}
//     g["a"] = a
//     g["b"] = b
//
//     # A bound local aliases the dict's storage -- the mutation is observable
//     # through the dict, not just through the local.
//     r0: list[int32] = [1]
//     r1: list[int32] = [2, 3]
//     m: list[list[int32]] = [r0, r1]
//     print(read_elements(g, m))
//
//     # Same through a callee taking the element directly.
//     push(g["b"], 7)
//     print(g["b"])
//
//     # Read positions that never had a per-sink row of their own.
//     total = 0
//     for v in g["a"]:
//         total += v
//     print(total)
//
//     m[1].append(4)
//     print(len(m[1]))
//     print(m[1])
void main() {
    std::vector<int32_t> a = {1, 2};
    std::vector<int32_t> b = {3};
    ::tpy::ordered_map<std::string, std::vector<int32_t>> g = ::tpy::ordered_map<std::string, std::vector<int32_t>>();
    ::tpy::__setitem__(g, "a", std::move(a));
    ::tpy::__setitem__(g, "b", std::move(b));
    std::vector<int32_t> r0 = {1};
    std::vector<int32_t> r1 = {2, 3};
    std::vector<std::vector<int32_t>> m = ::tpy::make_vector<std::vector<int32_t>>(std::move(r0), std::move(r1));
    std::cout << read_elements(g, m) << "\n";
    push(::tpy::__getitem__(g, "b"), 7);
    std::cout << ::tpy::ListPrinter(::tpy::__getitem__(g, "b")) << "\n";
    int32_t total = 0;
    auto& __obj_0 = ::tpy::__getitem__(g, "a");
    auto __beg_0 = __obj_0.begin();
    auto __end_0 = __obj_0.end();
    for (; __beg_0 != __end_0; ++__beg_0) {
        int32_t v = *__beg_0;
        total = ::tpy::add_check<int32_t>(total, v);
    }
    std::cout << total << "\n";
    ::tpy::__getitem__(m, 1).push_back(4);
    std::cout << ::tpy::__len__(::tpy::__getitem__(m, 1)) << "\n";
    std::cout << ::tpy::ListPrinter(::tpy::__getitem__(m, 1)) << "\n";
}

// main()
void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    main();
}

} // namespace tpyapp::main

int __tpy_main(int argc, char* argv[]) {
    ::tpy::init_sys_argv(argc, argv);
    ::tpyapp::main::__tpy_init();
    return 0;
}

int main(int argc, char* argv[]) {
    ::tpy::process_startup();
    return __tpy_main(argc, argv);
}
