// Generated by TurboPython Compiler
#pragma once

#include <tpy/tpy.hpp>
#include "tpystd/tpy/_types.hpp"
#include "tpystd/typing/_typing.hpp"

namespace tpyapp::main {

struct Point;

extern Point* q;
inline constexpr std::string_view __name__ = "__main__";

// def get_x(p: Point | None) -> int32:
int32_t get_x(const Point* p);
// def get_mag(p: Point | None) -> int32:
int32_t get_mag(Point* p);

// class Point:
struct Point {
    // x: int32
    int32_t x;

    // def __init__(self, x: int32):
    Point() = default;
    explicit Point(int32_t x);

    // def mag(self) -> int32:
    int32_t mag() const;
    static constexpr std::string_view __tpy_class_name__ = "__main__.Point";
};

inline std::ostream& operator<<(std::ostream& os, const Point& obj) {
    ::tpy::print_object_default(os, "Point", obj);
    return os;
}


// def __init__(self, x: int32):
//     self.x = x
inline Point::Point(int32_t x) : x(x) {}

// def mag(self) -> int32:
//     return self.x
inline int32_t Point::mag() const {
    return this->x;
}
void __tpy_init();
} // namespace tpyapp::main
