"""Frontend plugin IR.

Plain-dataclass intermediate representation that frontend plugins emit and
lowering converts into a `TpyModule`. See `docs/FRONTEND_PLUGIN_DESIGN.md`
for the design contract.

M1 scope: only the nodes needed to express a Pascal "Hello, World!"
program end-to-end. Additional nodes land milestone-by-milestone.
"""

from .nodes import (
    API_VERSION,
    Assign,
    Attr,
    BinOp,
    BinOpKind,
    BoolLit,
    Call,
    CallableType,
    CmpOpKind,
    Compare,
    Enum,
    EnumValue,
    Expr,
    ExprStmt,
    Field,
    FloatLit,
    ForEach,
    ForRange,
    FrontendDirectives,
    FrontendModule,
    FromImport,
    Function,
    If,
    Import,
    ImportDecl,
    ImportName,
    IntLit,
    IntTypeArg,
    ListLit,
    Loc,
    Match,
    MatchCase,
    MatchClass,
    MatchPattern,
    MatchValue,
    MatchWildcard,
    Name,
    NamedType,
    NoneLit,
    Param,
    PointerType,
    Raise,
    RangeDir,
    Record,
    RepeatUntil,
    Return,
    SetLit,
    StarImport,
    Stmt,
    StrLit,
    Subscript,
    TypeArg,
    TypeExpr,
    TypeTypeArg,
    UnaryOp,
    UnaryOpKind,
    UnionType,
    VarDecl,
    While,
)
from .lower import LoweredFrontend, lower_module

__all__ = [
    "API_VERSION",
    "Assign",
    "Attr",
    "BinOp",
    "BinOpKind",
    "BoolLit",
    "Call",
    "CallableType",
    "CmpOpKind",
    "Compare",
    "Enum",
    "EnumValue",
    "Expr",
    "ExprStmt",
    "Field",
    "FloatLit",
    "ForEach",
    "ForRange",
    "FrontendDirectives",
    "FrontendModule",
    "FromImport",
    "Function",
    "If",
    "Import",
    "ImportDecl",
    "ImportName",
    "IntLit",
    "IntTypeArg",
    "ListLit",
    "Loc",
    "LoweredFrontend",
    "Match",
    "MatchCase",
    "MatchClass",
    "MatchPattern",
    "MatchValue",
    "MatchWildcard",
    "Name",
    "NamedType",
    "NoneLit",
    "Param",
    "PointerType",
    "Raise",
    "RangeDir",
    "Record",
    "RepeatUntil",
    "Return",
    "SetLit",
    "StarImport",
    "Stmt",
    "StrLit",
    "Subscript",
    "TypeArg",
    "TypeExpr",
    "TypeTypeArg",
    "UnaryOp",
    "UnaryOpKind",
    "UnionType",
    "VarDecl",
    "While",
    "lower_module",
]
