// Generated by TurboPython Compiler
#include "main.hpp"

namespace tpyapp::main {


// def first(rows: list[Payload]) -> Payload:
//     return rows[0]
Payload& first(std::vector<Payload>& rows) {
    return ::tpy::__getitem__(rows, 0);
}

// def take(rows: list[Payload]) -> Own[Payload]:
//     # `first(rows)` hands back `Payload&`; filling the owning slot from it is
//     # the copy the warning declares.
//     return first(rows)  # tpyc: warning(/copies Payload into owned storage/)
Payload take(std::vector<Payload>& rows) {
    return first(rows);
}

// def take_copy(rows: list[Payload]) -> Own[Payload]:
//     return copy(first(rows))  # tpyc: ok
Payload take_copy(std::vector<Payload>& rows) {
    return Payload(first(rows));
}

// def main() -> None:
//     rows = [Payload(1)]
//     print(take(rows).n, take_copy(rows).n, rows[0].n)
void main() {
    std::vector<Payload> rows = {Payload(1)};
    std::cout << take(rows).n << " " << take_copy(rows).n << " " << ::tpy::__getitem__(rows, 0).n << "\n";
}

// main()
void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    main();
}

} // namespace tpyapp::main

int __tpy_main(int argc, char* argv[]) {
    ::tpy::init_sys_argv(argc, argv);
    ::tpyapp::main::__tpy_init();
    return 0;
}

int main(int argc, char* argv[]) {
    ::tpy::process_startup();
    return __tpy_main(argc, argv);
}
