// Generated by TurboPython Compiler
#pragma once

#include <tpy/tpy.hpp>
#include "tpystd/tpy/_types.hpp"
#include "tpystd/typing/_typing.hpp"

namespace tpyapp::main {

struct Snap;
struct Holder;

inline constexpr std::string_view __name__ = "__main__";

struct __gen_drain;

// def use(s: Snap) -> None:
void use(const Snap& s);
// def use_annotated(s: Snap) -> None:
void use_annotated(const Snap& s);
// def drain(s: Snap) -> Iterator[int32]:
__gen_drain drain(const Snap& s);
// def use_view(h: Holder) -> None:
void use_view(const Holder& h);
// def main() -> None:
void main();

// class Snap:
struct Snap {
    // _items: list[int32]
    std::vector<int32_t> _items;

    // def __init__(self) -> None:
    Snap();

    // @property
    // def snapshot(self) -> Own[list[int32]]:
    std::vector<int32_t> snapshot() const;

    // def widen(self) -> int32:
    int32_t widen();
    static constexpr std::string_view __tpy_class_name__ = "__main__.Snap";
};

inline std::ostream& operator<<(std::ostream& os, const Snap& obj) {
    ::tpy::print_object_default(os, "Snap", obj);
    return os;
}

// class Holder:
struct Holder {
    // label: str
    std::string label;

    // def __init__(self) -> None:
    Holder();

    // @property
    // def view(self) -> StrView:
    std::string_view view() const;
    static constexpr std::string_view __tpy_class_name__ = "__main__.Holder";
};

inline std::ostream& operator<<(std::ostream& os, const Holder& obj) {
    ::tpy::print_object_default(os, "Holder", obj);
    return os;
}

// def drain(s: Snap) -> Iterator[int32]:
struct __gen_drain : public ::tpy::next_iter_mixin<__gen_drain, int32_t> {
    int32_t __state;
    const Snap& s;
    ::tpy::frame_slot<std::vector<int32_t>> snap;
    int32_t x;
    ::tpy::frame_slot<::tpy::begin_iter_t<std::vector<int32_t>>> __for_it_0;
    ::tpy::frame_slot<::tpy::begin_iter_t<std::vector<int32_t>>> __for_end_0;

    enum : int32_t {
        S_INITIAL = 0,
        S_RESUME_0 = 1,
        S_JOIN_0 = 2,
        S_DONE = 3,
    };

    __gen_drain(const Snap& s)
        : __state(S_INITIAL), s(s) {}

    std::expected<int32_t, ::tpy::StopIteration> __next__();
    __gen_drain& __iter__() { return *this; }

    friend std::ostream& operator<<(std::ostream& os, const __gen_drain&) {
        return os << "<generator drain>";
    }
};


// def __init__(self) -> None:
//     self._items = [1]
inline Snap::Snap() : _items(std::vector<int32_t>{1}) {}

// @property
// def snapshot(self) -> Own[list[int32]]:
//     out: list[int32] = []
//     for x in self._items:
//         out.append(x)
//     return out
inline std::vector<int32_t> Snap::snapshot() const {
    std::vector<int32_t> out = std::vector<int32_t>{};
    auto& __obj_0 = this->_items;
    auto __beg_0 = __obj_0.begin();
    auto __end_0 = __obj_0.end();
    for (; __beg_0 != __end_0; ++__beg_0) {
        int32_t x = *__beg_0;
        out.push_back(x);
    }
    return out;
}

// # method: the same decl spelled off `self`
// def widen(self) -> int32:
//     mine = self.snapshot  # tpyc: ok
//     mine.append(9)
//     return len(mine)
inline int32_t Snap::widen() {
    std::vector<int32_t> mine = this->snapshot();
    mine.push_back(9);
    return ::tpy::__len__(mine);
}

// def __init__(self) -> None:
//     self.label = "ab"
inline Holder::Holder() : label("ab") {}

// @property
// def view(self) -> StrView:
//     return self.label
inline std::string_view Holder::view() const {
    return this->label;
}
void __tpy_init();
} // namespace tpyapp::main
