// Generated by TurboPython Compiler
#include "main.hpp"

namespace tpyapp::main {


// async def msg(tag: str) -> str:
::tpystd::tpy::Poll<std::string> __coro_msg::__poll__(::tpystd::coro::Waker waker) {
    (void)waker;
    switch (__state) {
    case S_INITIAL: {
        // print("building", tag)
        std::cout << "building" << " " << tag << "\n";
        // return tag + "!"
        __state = S_DONE;
        std::string __tpy_async_ret = (::tpy::str_concat(tag, "!"));
        return ::tpystd::tpy::Poll<std::string>::ready(std::move(__tpy_async_ret));
    }
    case S_DONE: ::tpy::tpy_panic("poll after Ready");
    }
    __builtin_unreachable();
}


// async def msg(tag: str) -> str:
__coro_msg msg(std::string_view tag) {
    return __coro_msg(tag);
}

// async def go(x: Int32) -> None:
::tpystd::tpy::Poll<::std::monostate> __coro_go::__poll__(::tpystd::coro::Waker waker) {
    while (true) switch (__state) {
    case S_INITIAL: {
        if ((!((x > 0)))) {
            __coro_arg_0 = "positive";
            // assert x > 0, await msg("positive")
            __sub_0.emplace(__coro_arg_0);
            __state = S_RESUME_0;
            continue;
        } else {
            __state = S_JOIN_0;
            continue;
        }
    }
    case S_RESUME_0: {
        auto __r0 = ::tpy::poll_with_cancel(__sub_0, __cancel_pending, waker);
        if (__r0.is_pending()) return ::tpystd::tpy::Poll<::std::monostate>::pending();
        __await_lift_0 = std::move(__r0).value();
        __sub_0.reset();
        // assert x > 0, await msg("positive")
        ::tpy::raise_assertion_error(__await_lift_0);
        __state = S_JOIN_0;
        continue;
    }
    case S_JOIN_0: {
        // print("passed", x)
        std::cout << "passed" << " " << x << "\n";
        __state = S_DONE;
        return ::tpystd::tpy::Poll<::std::monostate>::ready(::std::monostate{});
    }
    case S_DONE: ::tpy::tpy_panic("poll after Ready");
    }
    __builtin_unreachable();
}


// async def go(x: Int32) -> None:
__coro_go go(int32_t x) {
    return __coro_go(x);
}

// async def main_coro() -> None:
::tpystd::tpy::Poll<::std::monostate> __coro_main_coro::__poll__(::tpystd::coro::Waker waker) {
    while (true) switch (__state) {
    case S_INITIAL: {
        // await go(2)
        __sub_0.emplace(2);
        __state = S_RESUME_0;
        continue;
    }
    case S_RESUME_0: {
        auto __r0 = ::tpy::poll_with_cancel(__sub_0, __cancel_pending, waker);
        if (__r0.is_pending()) return ::tpystd::tpy::Poll<::std::monostate>::pending();
        (void)std::move(__r0).value();
        __sub_0.reset();
        __state = S_JOIN_1;
        continue;
    }
    case S_RESUME_1: {
        try {
            auto __r1 = ::tpy::poll_with_cancel(__sub_1, __cancel_pending, waker);
            if (__r1.is_pending()) return ::tpystd::tpy::Poll<::std::monostate>::pending();
            (void)std::move(__r1).value();
            __sub_1.reset();
            __state = S_JOIN_0;
            continue;
        } catch (const ::tpy::AssertionError& e) {
            __sub_1.reset();
            // print("caught", e)
            std::cout << "caught" << " " << e << "\n";
            __state = S_JOIN_0;
            continue;
        } catch (...) {
            __sub_1.reset();
            throw;
        }
    }
    case S_JOIN_0: {
        __state = S_DONE;
        return ::tpystd::tpy::Poll<::std::monostate>::ready(::std::monostate{});
    }
    case S_JOIN_1: {
        // await go(0)
        __sub_1.emplace(0);
        __state = S_RESUME_1;
        continue;
    }
    case S_DONE: ::tpy::tpy_panic("poll after Ready");
    }
    __builtin_unreachable();
}


// async def main_coro() -> None:
__coro_main_coro main_coro() {
    return __coro_main_coro();
}

void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    // # An awaiting assert message is evaluated only on failure (CPython);
    // # the passing path must not run its side effects.
    // import asyncio
    ::tpystd::asyncio::__tpy_init();
    // asyncio.run(main_coro())
    ::tpystd::asyncio::run<std::monostate>(::tpy::make_adapter<::tpystd::coro::Cancellable<std::monostate>>(main_coro()));
}

} // namespace tpyapp::main

int __tpy_main(int argc, char* argv[]) {
    ::tpy::init_sys_argv(argc, argv);
    ::tpyapp::main::__tpy_init();
    return 0;
}

int main(int argc, char* argv[]) {
    ::tpy::process_startup();
    return __tpy_main(argc, argv);
}
