// Generated by TurboPython Compiler
#include "main.hpp"

namespace tpy_user::main {


// def main() -> None:
void main() {
    // pet: Pet = Dog()
    Dog __slot_1{Dog()};
    Pet* pet = &__slot_1;
    // print(pet.make_noise())
    std::cout << pet->make_noise() << "\n";
}

void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

    // main()
    main();
}

} // namespace tpy_user::main

int main(int argc, char* argv[]) {
    ::tpy::init_sys_argv(argc, argv);
    tpy_user::main::__tpy_init();
    return 0;
}
