// Generated by TurboPython Compiler
#pragma once

#include <tpy/tpy.hpp>
#include "tpystd/tpy/_types.hpp"
#include "tpystd/typing/_typing.hpp"

namespace tpyapp::main {

struct __tpy_builder_argparse_args_1;

inline constexpr std::string_view __name__ = "__main__";

int32_t main();
__tpy_builder_argparse_args_1 __tpy_builder_argparse_parse_1(const std::vector<std::string>& argv);

// p.parse_args(["unexpected"])
struct __tpy_builder_argparse_args_1 {

    // p.parse_args(["unexpected"])
    __tpy_builder_argparse_args_1() {}
};

inline std::ostream& operator<<(std::ostream& os, const __tpy_builder_argparse_args_1& obj) {
    ::tpy::print_object_default(os, "__tpy_builder_argparse_args_1", obj);
    return os;
}

void __tpy_init();
} // namespace tpyapp::main
