// Generated by TurboPython Compiler
#pragma once

#include <tpy/tpy.hpp>
#include "tpystd/tpy/_types.hpp"
#include "tpystd/typing/_typing.hpp"

namespace tpyapp::main {

// class Counted(Protocol):
template<typename T>
concept Counted = requires(T& t) {
    { t.value() } -> std::convertible_to<int32_t>;
};

struct Token;
template<Counted T> struct Holder;

inline constexpr std::string_view __name__ = "__main__";

void main();

// @nocopy
// class Token(Counted):
struct Token {
    // n: int32
    int32_t n;

    // def __init__(self, n: int32) -> None:
    Token() = default;
    explicit Token(int32_t n);
    // non-copyable (@nocopy)
    Token(const Token&) = delete;
    Token& operator=(const Token&) = delete;
    Token(Token&&) = default;
    Token& operator=(Token&&) = default;

    // def value(self) -> int32:
    int32_t value() const;
    static constexpr std::string_view __tpy_class_name__ = "__main__.Token";
};

inline std::ostream& operator<<(std::ostream& os, const Token& obj) {
    ::tpy::print_object_default(os, "Token", obj);
    return os;
}

// @nocopy
// class Holder[T: Counted]:
template<Counted T>
struct Holder {
    // item: T
    T item;

    // def __init__(self, item: Send[Own[T]]) -> None:
    Holder() = default;
    explicit Holder(::tpy::own_param_t<T> item) : item(std::move(item)) {}
    // non-copyable (@nocopy)
    Holder(const Holder&) = delete;
    Holder& operator=(const Holder&) = delete;
    Holder(Holder&&) = default;
    Holder& operator=(Holder&&) = default;

    // def value(self) -> int32:
    int32_t value() {
        // return self.item.value()
        return this->item.value();
    }
    static constexpr std::string_view __tpy_class_name__ = "__main__.Holder";
};

template<typename T>
inline std::ostream& operator<<(std::ostream& os, const Holder<T>& obj) {
    ::tpy::print_object_default(os, "Holder", obj);
    return os;
}


// def __init__(self, n: int32) -> None:
inline Token::Token(int32_t n) : n(n) {}

// def value(self) -> int32:
inline int32_t Token::value() const {
    // return self.n
    return this->n;
}
void __tpy_init();
} // namespace tpyapp::main
