// Generated by TurboPython Compiler
#include "main.hpp"

namespace tpyapp::main {


// def pick(flag: bool, a: int32 | None, b: int32 | None) -> int32:
//     if flag:
//         assert a is not None
//     else:
//         assert b is not None
//     return a + 1  # tpyc: warning(/Potential None access/)
int32_t pick(bool flag, std::optional<int32_t> a, std::optional<int32_t> b) {
    if (flag) {
        if (!((a.has_value()))) ::tpy::raise_assertion_error();
    } else {
        if (!((b.has_value()))) ::tpy::raise_assertion_error();
    }
    return (::tpy::add_check<int32_t>(::tpy::deref_optional_check(a), 1));
}

void __tpy_init() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;

}

} // namespace tpyapp::main

int __tpy_main(int argc, char* argv[]) {
    ::tpy::init_sys_argv(argc, argv);
    ::tpyapp::main::__tpy_init();
    return 0;
}

int main(int argc, char* argv[]) {
    return ::tpy::run_main(argc, argv, &__tpy_main);
}
