// Generated by TurboPython Compiler
#pragma once

#include <tpy/tpy.hpp>
#include "tpystd/tpy/_types.hpp"
#include "tpystd/typing/_typing.hpp"

namespace tpyapp::main {

struct Dog;
struct Cat;
struct Zoo;

inline constexpr std::string_view __name__ = "__main__";

void main();

// @dataclass
// class Dog:
struct Dog {
    // name: str
    std::string name;

    Dog() = default;
    explicit Dog(std::string_view name) : name(name) {}

    bool __eq__(const Dog& other) const {
        return (this->name == other.name);
    }

    std::string __repr__() const {
        return std::format("Dog(name={})", ::tpy::__repr__(this->name));
    }

    friend bool operator==(const Dog& lhs, const Dog& other) {
        return lhs.__eq__(other);
    }
};

inline std::ostream& operator<<(std::ostream& os, const Dog& obj) {
    os << obj.__repr__();
    return os;
}

// @dataclass
// class Cat:
struct Cat {
    // name: str
    std::string name;

    Cat() = default;
    explicit Cat(std::string_view name) : name(name) {}

    bool __eq__(const Cat& other) const {
        return (this->name == other.name);
    }

    std::string __repr__() const {
        return std::format("Cat(name={})", ::tpy::__repr__(this->name));
    }

    friend bool operator==(const Cat& lhs, const Cat& other) {
        return lhs.__eq__(other);
    }
};

inline std::ostream& operator<<(std::ostream& os, const Cat& obj) {
    os << obj.__repr__();
    return os;
}

// class Zoo:
struct Zoo {
    // pet: Dog | Cat
    std::variant<Cat, Dog> pet;
    // tag: str
    std::string tag;

    // def __init__(self, pet: Dog | Cat, tag: str) -> None:
    explicit Zoo(const std::variant<Cat*, Dog*> pet, std::string_view tag) : pet(::tpy::to_value_variant<std::variant<Cat, Dog>>(pet)), tag(tag) {}
};

inline std::ostream& operator<<(std::ostream& os, const Zoo& obj) {
    ::tpy::print_object_default(os, "Zoo", obj);
    return os;
}

void __tpy_init();
} // namespace tpyapp::main
