// Generated by TurboPython Compiler
#pragma once

#include <tpy/tpy.hpp>
#include "tpystd/builtins.hpp"
#include "tpystd/tpy.hpp"
#include "tpystd/typing.hpp"

namespace tpyapp::main {

struct HeapVal;

inline constexpr std::string_view __name__ = "__main__";

void main();

// class HeapVal:
struct HeapVal {
    // _ptr: Ptr[Int32]
    int32_t* _ptr;
    bool __tpy_owned_ = true;

    // def __init__(self, value: Int32):
    HeapVal() = default;
    explicit HeapVal(int32_t value) : _ptr(static_cast<int32_t*>(::operator new(sizeof(int32_t), std::align_val_t(alignof(int32_t))))) {
        // print("init", value)
        std::cout << "init" << " " << value << "\n";
        // unsafe_init(self._ptr, value)
        ::new(static_cast<void*>(this->_ptr)) int32_t(std::move(value));
    }
    HeapVal(const HeapVal&) = delete;
    HeapVal& operator=(const HeapVal&) = delete;
    HeapVal(HeapVal&& other) noexcept : _ptr(std::move(other._ptr)) {
        other.__tpy_owned_ = false;
    }
    HeapVal& operator=(HeapVal&& other) noexcept {
        if (this != &other) {
            this->~HeapVal();
            new (this) HeapVal(std::move(other));
        }
        return *this;
    }
    // def __del__(self):

    ~HeapVal() {
        if (!__tpy_owned_) return;
        // print("del")
        std::cout << "del" << "\n";
        // unsafe_drop(self._ptr)
        ::tpy::destroy_at(this->_ptr);
        // unsafe_free(self._ptr)
        ::operator delete(this->_ptr, std::align_val_t(alignof(int32_t)));
    }

    // def take(self: Own[Self]) -> Int32:
    int32_t take() && {
        this->__tpy_owned_ = false;
        // print("take")
        std::cout << "take" << "\n";
        // val: Int32 = unsafe_move_out(self._ptr)
        int32_t val = std::move(*this->_ptr);
        // unsafe_free(self._ptr)
        ::operator delete(this->_ptr, std::align_val_t(alignof(int32_t)));
        // return val
        return val;
    }
};

inline std::ostream& operator<<(std::ostream& os, const HeapVal& obj) {
    os << "HeapVal("
       << "_ptr=" << obj._ptr
       << ")";
    return os;
}

void __tpy_init();
} // namespace tpyapp::main
